- authenticate/circuit/breaker.go
- authenticate/middleware_test.go
- authenticate/providers/singleflight_middleware.go
- docs/guide/readme.md
- env.example
- go.mod
- go.sum
- internal/aead/aead.go
- internal/sessions/cookie_store.go
- internal/sessions/session_state.go
Adds the ability to proxy HTTP endpoints. Would close #11 . Tested with the following route.
```bash
export ROUTES='https://nossl.corp.beyondperimeter.com=http://neverssl.com'
```
> proxy : add HTTP endpoint support

- Dockerfile
Change the Docker container to copy the pomerium binary instead of the base binaries from the Golang base container. Also makes the pomerium binary be run as the default command. This splits this functionality off from #9
> Fix dockerfile, add CMD

- .gitignore
- README.md
- docker-compose.yml
- docs/guide/identity-providers.md
- docs/guide/readme.md
> deployment : add docker support, docker-compose example file, quickstart

- authenticate/authenticate.go
- authenticate/handlers.go
This PR adds a SKIP_PROVIDER_BUTTON environment variable that skips the Pomerium sign-in page and redirects the user directly to the OAuth provider (Google, Okta, etc) if the user is not yet authenticated with that provider. It replicates the functionality of "-skip-provider-button" flag from https://github.com/bitly/oauth2_proxy. It also acts as an implementation of https://github.com/buzzfeed/sso/issues/132. My organization does use this feature in our current oauth2_proxy deployments, so it would be nice to have it here.
Internally, the implementation is hacky; if the flag is set while in SignIn(), it will call a separate helper whose only job is to extract the auth redirect URL from the authenticator instance, which proceeds to validate it as if it were user input. (The normal code …
> authenticate: skip provider login screen

- authenticate/authenticate.go
- authenticate/handlers.go
Fixes #24 , was a small typo in error check that always failed when redirect button was enabled.
> authenticate: fixes incorrect error check

- helm/.helmignore
- helm/Chart.yaml
- helm/README.md
- helm/templates/_helpers.tpl
- helm/templates/deployment.yaml
- helm/templates/ingress.yaml
- helm/templates/secret.yaml
- helm/templates/service.yaml
- helm/values.yaml
This PR adds Helm charts for deploying pomerium. This PR is paired with #9 for setting modes.
Open issues:
* Client secret, client ID, cookie secret, shared secret, and TLS cert/key are stored in K8s secrets, but the contents are still visible with helm get manifest. There should be an option to allow someone to provision the secrets outside of the chart.
* The README.md file is a stub, and needs proper documentation for both authenticator and proxy deployment.
* Maybe more sensible defaults in values.yaml should be provided.
* The default image location is dependent on #7. This is overridable in values.yaml.
> Add helm charts

- authenticate/authenticate.go
- authenticate/handlers.go
- internal/httputil/errors.go
- internal/templates/templates.go
- proxy/handlers.go
- proxy/handlers_test.go
- proxy/proxy.go
proxy: use internal/httputil for error handling
- General formatting and comment cleanup.
- Inject pomerium version at compile time via template package.
> proxy: use internal/httputil for error handling

- cmd/pomerium/main.go
Re-adding the hostless /ping for the authenticate service. Without these 4 lines, Pomerium fails to stay running when using the helm chart that's checked into the repo; the Kubernetes liveness/readiness probes don't see the pod as successfully running, and Kubernetes goes into an endless restart loop.
I have tried the following:
* Adding `httpHeaders: {name: "Host", value: "insert_redirect_uri_hostname_here"}` to both probes to try to force it to recognize. Pomerium fails to stay running.
* Removing the probes from the deployment definition. Pomerium successfully stays running and responds correctly. Thus it's certain that it's one of the probes failing.
* Modifying the code here to log the request.host golang reports. It reports "10.x.x.x:443". (Actual pod internal IP address for the …
> cmd/pomerium : restore /ping without hostname

- docs/.vuepress/config.js
- docs/docs/examples/kubernetes/authenticate.deploy.yml
- docs/docs/examples/kubernetes/proxy.deploy.yml
- internal/middleware/middleware.go
- internal/middleware/middleware_test.go
- proxy/handlers.go
- proxy/handlers_test.go
proxy: add unit tests
- Fixed pomerium.io site description
- Updated kubernetes examples to use the latest docker images.
- Use cryputil hash function for proxy hmac.
- Add unit tests for proxy handlers.
**Checklist**:
> proxy: add unit tests

- docs/docs/examples/kubernetes/proxy.deploy.yml
As you can see below an error occurs when you have the port. There is another option for port which screws it up.
```
189a15d0e56","error":"rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: address pomerium-authenticate-service.pomerium.svc.cluster.local:443:443: too many colons in address\"","time":"2019-02-14T16:27:07Z","message":"proxy: error redeeming authorization code"}
```
**Checklist**:
> docs: remove port from internal service url

- docs/docs/examples/docker/gitlab.docker-compose.yml
- docs/docs/examples/docker/nginx.docker-compose.yml
- docs/docs/examples/kubernetes/proxy.deploy.yml
- proxy/authenticator/authenticator.go
- proxy/authenticator/grpc.go
- proxy/authenticator/grpc_test.go
- proxy/proxy.go
This PR fixes the misspelling of overide with a single "r" to override through the codebase, in variable names, comments, and docs.
**Checklist**:
> all: fix misspelling of override

- proxy/authenticator/grpc.go
- proxy/authenticator/grpc_test.go
Fixes a bug where authenticator checks if the authenticate service's target connection string includes a port value (e.g. has a colon). Previously implementation did the reverse (does a colon string ever contain the connection string) and would never fire. 
See: 
- #47   
**Checklist**:
> proxy/authenticator: fix check to ensure port assigned

- helm/templates/deployment.yaml
- helm/templates/secret.yaml
- helm/values.yaml
- proxy/authenticator/authenticator.go
- proxy/authenticator/grpc.go
- proxy/proxy.go
This PR adds support for a certificate authority for the proxy to allow connections to the authenticate server when using your own certificate authority.
An unfortunate result of the conversion to using gRPC on the backend is that since AWS Application Load Balancer's [only talk HTTP/1.1](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#listener-configuration]) from the LB to the application (they can terminate HTTP/2.0 from the client), gRPC is unable to traverse through the load balancer. This forces us to use an internal authenticator URL to talk from the proxy to the authenticator. However, this also means that we can no longer rely on the publicly signed certificates provided by AWS's certificate manager that the ALB uses. Since my …
> proxy: support certificate authority to verify server

- internal/identity/google.go
Closes #67 
In the future, it makes sense to extend policy, group, and authorize to support  the more secure groupd_id and user_id.
**Checklist**:
Thanks to @victornoel for reporting the issue.
> internal/identity: use email for gsuite group identifier

- CHANGELOG.md
- cmd/pomerium/main.go
- cmd/pomerium/options.go
- docs/docs/config-reference.md
- internal/log/log.go
- internal/log/log_test.go
- POMERIUM_DEBUG no longer sets log level.
- LOG_LEVEL now responsible for setting global log level.
Fixes #70 
Thank you @victornoel for reporting the issue.
**Checklist**:
> internal/log: fix setting log level

- docs/.vuepress/config.js
- docs/guide/helm.md
- helm/Chart.yaml
- helm/OWNERS
- helm/README.md
- helm/templates/NOTES.txt
- helm/templates/_helpers.tpl
- helm/templates/authenticate-deployment.yaml
- helm/templates/authenticate-service.yaml
- helm/templates/authorize-deployment.yaml
- helm/templates/authorize-service.yaml
- helm/templates/configmap.yaml
- helm/templates/ingress.yaml
- helm/templates/proxy-deployment.yaml
- helm/templates/proxy-service.yaml
- helm/templates/secret.yaml
- helm/templates/tls-secrets.yaml
- helm/values.yaml
- scripts/helm_gke.sh
- adds quick-start documentation for using helm
- update helm deployment charts to match outstanding official charts repo.
Closes #22 
See.
- https://github.com/helm/charts/pull/12415
- #64 
**Checklist**:
> deployment: update helm and add quick-start docs

- internal/identity/google.go
Fixes Issue #80 
Google only provide refresh_token on the first authorization from the user. If user clears cookies, re-authorization will not bring back refresh_token. A work around to this is to add prompt=consent to the OAuth redirect URL and will always return a refresh_token.
**Checklist**:
> Force requesting refresh_token from Google

- internal/identity/google.go
Fixes a bug where caused by setting both `prompt=consent` and `approval_prompt=force`. Though approval_prompt seems to be legacy it is still in the [oauth2 source code](https://github.com/golang/oauth2/blob/9f3314589c9a9136388751d9adae6b0ed400978a/oauth2.go#L120). 
See: 
- https://github.com/googleapis/oauth2client/issues/453
- #81 
- #80 
**Checklist**:
> internal/identity: google cannot have both approval_prompt and prompt

- .github/PULL_REQUEST_TEMPLATE
- CHANGELOG.md
- authenticate/authenticate.go
- authenticate/authenticate_test.go
- authenticate/handlers.go
- authenticate/handlers_test.go
- cmd/pomerium/main.go
- docs/docs/config-reference.md
- docs/docs/examples/docker/basic.docker-compose.yml
- docs/docs/examples/docker/nginx.docker-compose.yml
- docs/docs/examples/kubernetes/authenticate.deploy.yml
- docs/docs/examples/kubernetes/ingress.nginx.yml
- docs/docs/examples/kubernetes/ingress.yml
- docs/docs/examples/kubernetes/proxy.deploy.yml
- docs/docs/identity-providers.md
- docs/guide/synology.md
- env.example
- internal/middleware/middleware.go
- internal/middleware/middleware_test.go
- policy.example.yaml
- scripts/helm_gke.sh
- Removed `PROXY_ROOT_DOMAIN` config option which is now inferred from `AUTHENTICATE_SERVICE_URL`. Only callback requests originating from a URL on the same sub-domain are permitted. 
- Removed `REDIRECT_URL` config option which is now inferred from `AUTHENTICATE_SERVICE_URL` (e.g. `https://$AUTHENTICATE_SERVICE_URL/oauth2/callback`).
See:
- #71 
**Checklist**:
> authenticate: infer settings from authenticate url

- cmd/pomerium/main.go
Flags should be parsed so we can output version to command line without processing any other fields. 
**Checklist**:
> bug: version should be processed before other flags

- Dockerfile
- Makefile
Replaces the current alpine based Dockerfile with [distroless](https://github.com/GoogleContainerTools/distroless). Improvements include:
- Minimal surface area, ideal for static builds like pomerium.
- Includes `ca-certificates`
- Includes`nsswitch`
Closes #97 .
**See also**
- [best practices for building containers](https://cloud.google.com/solutions/best-practices-for-building-containers#use_the_smallest_base_image_possible)
- [Life of a happy developer in a container world by David Gageot
](https://www.youtube.com/watch?v=lviLZFciDv4)
- [Distroless Docker: Containerizing Apps, not VMs](https://www.youtube.com/watch?v=lviLZFciDv4)
**Checklist**:
Test image is available on dockerhub as `pomerium/pomerium:distroless`
/cc @yegle @eriksw
> deployment: use distroless builds

- .dockerignore
- Dockerfile.arm32v6
- Dockerfile.arm32v7
I was hoping to be able to do this without adding a bunch of dockerfiles per architecture but it looks like Docker hub does not currently support passing `ARG`s in with their automated builds. 
Closes #95.
See:
- https://github.com/docker/hub-feedback/issues/508
**Checklist**:
\cc @fightforlife
> deployment: add docker images for arm

- internal/middleware/middleware.go
- internal/middleware/middleware_test.go
- internal/policy/policy.go
- policy.example.yaml
- proxy/handlers.go
- proxy/handlers_test.go
- proxy/proxy.go
- proxy/proxy_test.go
Fixes  #78
Add a route-level setting (`false` by default) to allow unauthenticated OPTIONS requests for CORS. See #78 for more information.
**Checklist**:
> add cors_allow_preflight option to a route's policy

- cmd/pomerium/main.go
- internal/urlutil/url.go
- internal/urlutil/url_test.go
Go strips the port from the host only when it is trying to locate a http handler. It does not strip the port when the user adds a handler for a host that includes a port number. As a result, trying to add handlers for hosts that include the port no longer works. To fix a bug where authenticate handler's were not being found, we explicitly strip the auth host handler of any port.
Closes #104 
See also:
- https://github.com/golang/go/issues/23351
- https://github.com/golang/go/pull/31832
**Checklist**:
> cmd/pomerium: strip port from authentication handler

- cmd/pomerium/main.go
- cmd/pomerium/options.go
- docs/reference/readme.md
- internal/urlutil/url.go
This would make the HTTP redirect server default to off and also allows for the port to be configured.
Closes #103.
```bash
#policy.yaml
export HTTP_REDIRECT_ADDR=":http"
```
`http http://external-httpbin.corp.beyondperimeter.com/ping`
```bash
HTTP/1.1 301 Moved Permanently
Connection: close
Content-Length: 89
Content-Type: text/html; charset=utf-8
Date: Fri, 03 May 2019 23:45:43 GMT
Location: https://external-httpbin.corp.beyondperimeter.com/ping
<a href="https://external-httpbin.corp.beyondperimeter.com/ping">Moved Permanently</a>.
```
See also:
- #92 
**Checklist**:
/cc @yegle @haozhou
> proxy: make http redirect server configurable

- authenticate/handlers.go
- authorize/gprc.go
- cmd/pomerium/main.go
- cmd/pomerium/main_test.go
- cmd/pomerium/options.go
- proxy/handlers.go
- proxy/handlers_test.go
- proxy/proxy.go
- proxy/proxy_test.go
These changes abstract the shared middleware to the global serve mux. Headers, request id, loggers, and health checks (ping) middleware are now applied on all routes including 4xx and 5xx responses. 
See
- #116 
**Checklist**:
/cc @yegle
> cmd/pomerium: wrap global mux with standard middleware

- authenticate/handlers.go
- cmd/pomerium/options.go
- docs/docs/certificates.md
These changes fixes a regression in #117 where content `Content-Security-Policy` and `Referrer-Policy` were incorrectly being applied to upstream routes in addition to authenticate handlers. These changes apply those headers **only** to authenticate's endpoints.
Closes #119 
Example
```bash
curl -I https://httpbin.corp.beyondperimeter.com/
HTTP/2 302
content-type: text/html; charset=utf-8
request-id: bb049b04-2718-9233-6e30-d0c1ac552580
set-cookie: _pomerium_proxy=; Path=/; Domain=httpbin.corp.beyondperimeter.com; Expires=Wed, 15 May 2019 04:14:14 GMT; HttpOnly; Secure
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
```
```bash
curl -I …
```
> authenticate: remove CSP / referrer policy headers from other handlers

- Dockerfile
Fixes:
```
==> build
==> fmt
==> lint
/bin/sh: 1: golint: not found
```
**Checklist**:
> docker: add missing golint command

- authenticate/handlers.go
Reasonably lazy PR to add some more info on which particular param is invalid - trying to troubleshoot my setup and struggling.  
**Checklist**:
- [👎] updated docs
- [🤠] unit tests added
- [🤡] related issues referenced
- [💯] ready for review
> authenticate: add more verbose errors to authenticate handler

- authenticate/authenticate.go
- authenticate/authenticate_test.go
- authenticate/handlers.go
- authenticate/handlers_test.go
- internal/config/options.go
- internal/httputil/errors.go
- internal/sessions/cookie_store.go
- internal/sessions/cookie_store_test.go
- proxy/handlers.go
- proxy/handlers_test.go
- proxy/proxy.go
- proxy/proxy_test.go
- internal/sessions: session state is domain scoped
- internal/sessions: infer csrf cookie, route scoped
- proxy & authenticate: use shared cookie name
- proxy & authenticate: prevent resaving unchanged session
- proxy & authenticate: redirect instead of error for no session on login
- internal/config: merge cookies
- proxy: remove favicon specific route
tl;dr -- This fixes the annoying behavior of logging {in/out} from one route and not having that change be reflected in another route. 
Fixes #128 
**Checklist**:
> internal/sessions: make user state domain scoped

- docs/reference/readme.md
- internal/policy/policy.go
- policy.example.yaml
- proxy/handlers.go
- proxy/handlers_test.go
- proxy/proxy_test.go
Fixes #129
- Implemented a new access control option that allows public, unauthenticated access to specific targets.
- Added bypass check to `Proxy::shouldSkipAuthentication`
- Ensured all unit tests pass in `proxy/`
- Ran the following manual integration test
```yaml
- from: hello1.homelab.tejunareddy.com
to: http://localhost:8081
allowed_users:
- tejunareddy@gmail.com
- from: hello2.homelab.tejunareddy.com
to: http://localhost:8082
allowed_users:
- not_a_user@yahoo.com
- from: hello3.homelab.tejunareddy.com
to: http://localhost:8083
allow_public_unauthenticated_access: true
```
1. Sign out of pomerium with `/.pomerium/signout`
2. Ensure 200 OK for hello3.homelab.tejunareddy.com, but 403 Forbidden for hello1 and hello2.
3. Sign into tejunareddy@gmail.com
4. Ensure 400 OK for hello3 and …
> proxy: support for public unauthenticated routes

- Dockerfile
- Dockerfile.arm32v6
- Dockerfile.arm32v7
- Dockerfile.arm64v8
- authorize/authorize_test.go
- docs/docs/examples.md
- docs/docs/examples/docker/basic.docker-compose.yml
- docs/docs/examples/docker/nginx.docker-compose.yml
- docs/guide/readme.md
- scripts/kubernetes_gke.sh
Part of #115
- Existing env-only users should be unaffected.  
- Adds a default yaml location for users to mount a config over 
- Moves the config option to CMD so that pomerium args can be specified at runtime when desired 
- Example use case is if someone wanted to pass their config as toml or json for some reason
```shell
08:23 $ docker run -it pomerium -help
Usage of /bin/pomerium:
-config string
Specify configuration file location
-version
prints the version
```
- I slurped in a test coverage fix that took my last PR down 0.1% and was annoying me 😄 
**Checklist**:
> deployment: expose config file interface in docker images

- docs/docs/examples/docker/basic.docker-compose.yml
- docs/docs/examples/docker/nginx.docker-compose.yml
- docs/guide/readme.md
- docs/reference/readme.md
- scripts/kubernetes_gke.sh
- s/config-policy-only.yaml /config.example.policy.only/
- Removed `POLICY_FILE` references 
Closes #140 
**Checklist**:
> docs: fix example policy name typo

- cmd/pomerium/main.go
- internal/httputil/errors.go
- internal/log/middleware.go
- internal/log/middleware_test.go
- internal/log/wrap_writer.go
- internal/log/wrap_writer_test.go
- internal/templates/templates.go
Adds request id to error pages. Rearranged some of the log-related middleware to be part of the more logically coherent package. 
Partially resolves #138 
**Checklist**:
/cc @yegle
> internal/httputil: add request id to error page

- authenticate/authenticate.go
- authenticate/authenticate_test.go
Fixes an issue where `AuthenticateURL` validation check would fail because the setting is empty, but not nil. 
Closes #148 
**Checklist**:
> authenticate: catch missing required setting

- docs/.vuepress/config.js
- docs/docs/upgrading.md
Just a simple upgrade guide roughly inspired after [HashiCorp's vault](https://github.com/hashicorp/vault/tree/master/website/source/docs/upgrading). WIP while I backfill changes but wanted to make format public. 
**Checklist**:
\cc @travisgroth
> docs: add upgrade guide

- CHANGELOG.md
- docs/docs/upgrading.md
- docs/reference/readme.md
- go.mod
- go.sum
- internal/config/options.go
- internal/config/options_test.go
- proxy/proxy.go
These changes standardize the way url config options are handled in pomerium. Namely:
- Standard lib's url.Parse is pretty lenient about what it accepts so I wrapped it to check for some basic attributes like host and scheme.
- I fixed what I think was a broken unit test. 
- Added a dependency called `go-cmp` which is an absolute delight to unit test with as comparing and checking deep structs. 
Fixes #153 
**Checklist**:
/cc @travisgroth @victornoel
> internal/config: change internal-authenticate-addr to url

- docs/reference/readme.md
- internal/config/options.go
- internal/log/middleware.go
- proxy/handlers.go
- proxy/handlers_test.go
- proxy/proxy.go
Fixes #77 
Allows proxy to handle websocket connections. 
- Fix hardcoded HTTP protocol version. Hardcoded to HTTP2, which does not support websockets (at least not well)
- Prevent websocket connections from being proxied through a `timeoutHandler`, as websockets are long-lived connections and should not have timeouts enforced on them.
- Added configuration variable to opt-in to websocket support.
This is an opt-in feature because it can be potentially abused (see discussion in this PR). By opting-in, the user acknowledges this risk.
**Checklist**:
> Enable websocket support

- authenticate/handlers.go
- go.mod
- go.sum
- internal/middleware/middleware.go
- internal/middleware/middleware_test.go
Refactor `ValidateRedirectURI` to check if two urls are coming from the same top level domain vs matching for exact subdomain and depth. 
Fixes #152 
See: 
- [Why it's trickier than it sounds](https://godoc.org/golang.org/x/net/publicsuffix#EffectiveTLDPlusOne)
**Checklist**:
> internal/middleware: validate TLD plus one

- docs/.vuepress/config.js
- docs/docs/examples.md
- docs/docs/examples/config/config.example.env
- docs/docs/examples/config/config.example.yaml
- docs/docs/examples/config/config.minimal.env
- docs/docs/examples/config/config.minimal.yaml
- docs/docs/examples/config/policy.example.yaml
- docs/docs/examples/docker/basic.docker-compose.yml
- docs/docs/examples/docker/nginx.docker-compose.yml
- docs/docs/examples/kubernetes/authenticate.deploy.yml
- docs/docs/identity-providers.md
- docs/docs/readme.md
- docs/guide/binary.md
- docs/guide/helm.md
- docs/guide/kubernetes.md
- docs/guide/readme.md
- docs/guide/synology.md
- docs/reference/readme.md
- scripts/helm_gke.sh
- scripts/kubernetes_gke.sh
- Use wildcard certificate domain path from docs.
-  Generate secret keys on the fly for config.example.env
- Prefer as minimal (comment out) configuration as possible to get examples working. 
-  Change examples to show env-var best practices around secret. e.g. secrets should come from env vars, and other configurations can come from config file.
Part of #145 
Fixes #156 
**Checklist**:
> docs: update quickstart and examples

- authenticate/handlers.go
- authenticate/handlers_test.go
- internal/config/options.go
- internal/httputil/errors.go
- internal/middleware/middleware.go
- internal/middleware/middleware_test.go
- internal/templates/templates.go
- proxy/handlers.go
- proxy/handlers_test.go
The existing implementation used a ErrorResponse method to propogate
and create http error messages. Since we added functionality to
troubleshoot, signout, and do other tasks following an http error
it's useful to use Error struct in place of method arguments.
This fixes #157 where a troubleshooting links were appearing on pages
that it didn't make sense on (e.g. pages without valid sessions).
**Checklist**:
> internal/httputil: use error structs for http errors

- proxy/proxy.go
Previously, internal service url was being passed as it's full string representation, however
the grpc client expects a hostname:port pair. 
Thank you @victornoel for reporting the issue.
> proxy: fix authenticate internal service url

- .travis.yml
Make CI runs faster
**Checklist**:
> Add build cache to hopefully speed up travis

- cmd/pomerium/main.go
- docs/reference/readme.md
The following changes adds logging of pomerium's version on startup.
Fixes #161 
/cc @victornoel
**Checklist**:
> cmd/pomerium: add version and options dump

- .travis.yml
Try to get first test runs to be faster
**Checklist**:
> Faster initial test runs

- authenticate/authenticate.go
- authenticate/authenticate_test.go
- authorize/authorize.go
- authorize/authorize_test.go
- cmd/pomerium/main.go
- cmd/pomerium/main_test.go
- internal/config/options.go
- internal/config/options_test.go
- proxy/handlers.go
- proxy/handlers_test.go
- proxy/proxy.go
- proxy/proxy_test.go
> Change Options from pointers to values

- README.md
These changes adds a slack badge to the main repo's readme.
Also, changes the logo to be the long, wide version. 
See
- #155 
**Checklist**:
> docs: add slack link to readme

- internal/log/middleware.go
- internal/middleware/responsewriter/wrap_writer.go
- internal/middleware/responsewriter/wrap_writer_test.go
Preliminary work for #35.
Move the wrapped ResponseWriter to middleware so we can leverage it elsewhere.
**Checklist**:
> Relocate wrapped ResponseWriter to middleware

- cmd/pomerium/main.go
- internal/metrics/exporter.go
- internal/metrics/exporter_test.go
- internal/metrics/middleware.go
- internal/metrics/middleware_test.go
- proxy/handlers.go
internal/metrics: simplified struct definition with fmt -s.
internal/metrics: added full path to package name.
See:
- #184 
**Checklist**:
/cc @travisgroth
> internal/logs: make non error conditions less scary in logs

- CHANGELOG.md
- authorize/authorize.go
- authorize/authorize_test.go
- authorize/identity.go
- authorize/identity_test.go
- docs/reference/readme.md
- proxy/handlers_test.go
- proxy/proxy.go
- proxy/proxy_test.go
Closes #190 
**Checklist**:
When you have no policies, it will look like this in the logs:
```
{"level":"warn","time":"2019-07-02T06:27:49-04:00","message":"authorize: loaded configuration with no policies specified"}
{"level":"info","policy-count":0,"time":"2019-07-02T06:27:49-04:00","message":"authorize: updated policies"}
{"level":"warn","time":"2019-07-02T06:27:49-04:00","message":"proxy: loaded configuration with no policies specified"}
{"level":"info","policy-count":0,"time":"2019-07-02T06:27:49-04:00","message":"proxy: updated policies"}
```
Normal output:
```
{"level":"info","policy-count":1,"time":"2019-07-01T22:25:27-04:00","message":"authorize: updated policies"}
{"level":"info","policy-count":1,"time":"2019-07-01T22:25:27-04:00","message":"proxy: updated policies"}
```
Will …
> Allow empty policies at startup

- CHANGELOG.md
- authenticate/handlers.go
- docs/docs/identity-providers.md
- internal/identity/microsoft.go
Fixes #192 
@desimone I'm not seeing any place to insert some easy unit test fixes so maybe we should creat an issue for better testing around the identity providers in general.  
**Checklist**:
> internal/identity: fix azure group lookup

- CHANGELOG.md
- authenticate/handlers.go
- internal/sessions/session_state.go
- internal/sessions/session_state_test.go
If a session is too large to set (browser dictated), pomerium will no longer fail silently but instead raise both a log and error message. 
**Context**
- #211 
**Checklist**:
/cc @travisgroth
> internal/sessions: error if session too large

- CHANGELOG.md
- authenticate/authenticate.go
- internal/sessions/cookie_store.go
- internal/sessions/cookie_store_test.go
These changes allow a users to manually set the scope of pomerium's session cookie via the setting `CookieDomain`. This setting is useful for users that must support pomerium services served from different subdomain, and thus need to scope sessions  at a higher level.
For example, if you had the following configuration.
```yaml
authenticate_service_url: https://authenticate.corp.beyondperimeter.com
authorize_service_url: https://authorize.corp.beyondperimeter.com
cookie_domain: "corp.beyondperimeter.com"
policy:
- from: httpbin.aws.corp.beyondperimeter.com
to: http://localhost:1111
- from: httpbin.gke.corp.beyondperimeter.com
to: http://localhost:2222
```
Fixes #181 
Fixes #197 
**Additional Context**
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
- …
> internal/sessions: support custom session domain

- CHANGELOG.md
- Dockerfile
- Makefile
Working release checklist in #214 
I don't think the lint command belongs in the docker file for release; we aren't using it in the container.
I think the error reported in #121 should be fixed as part of the Makefile, if anywhere.  I can add that to this PR if that sounds right.
**Checklist**:
> Make dockerfiles consistent between archs

- internal/cryptutil/encrypt.go
- internal/cryptutil/encrypt_test.go
- internal/cryptutil/marshal.go
- internal/cryptutil/marshal_test.go
- internal/cryptutil/sign_test.go
It's an edge-case where if an empty public key was passed into `DecodePublicKey` a panic could be caused. 
**Checklist**:
> internal/cryptutil: fixed potential panic on nil pubkey block

- CHANGELOG.md
- internal/httputil/https.go
Prefer [curve](https://wiki.mozilla.org/Security/Server_Side_TLS) X25519 to P256 for TLS connections. 
Closes #233 
**Checklist**:
> internal/httputil: prefer X25519 over P256

- Makefile
Until we have a better mechanism for determining if a build has unexpected files.
See:
- https://github.com/pomerium/pomerium/pull/172#issue-285418664
- https://github.com/pomerium/pomerium/issues/171
- https://github.com/pomerium/pomerium/issues/192#issuecomment-511651501
**Checklist**:
> deployment: fix 'dirty' build tag

- cmd/pomerium/main.go
- internal/metrics/helpers_test.go
- internal/metrics/info.go
- internal/metrics/info_test.go
Fixes issue with some checksums being larger than int64
```{"level":"warn","error":"strconv.ParseInt: parsing \"0xd18a518ef7190001\": value out of range","time":"2019-07-22T08:52:08-04:00","message":"Could not parse config checksum into integer"}```
**Checklist**:
> Fix checksum integer overflow in metrics

- CHANGELOG.md
- internal/cryptutil/encrypt.go
- internal/cryptutil/marshal.go
- internal/cryptutil/mock_cipher_test.go
- internal/cryptutil/sign.go
- Fixed a potential race condition where a signer could concurrently mutate a request signer. 
- Add unit tests for mock cipher 🙄 
- Fix up package messages for cryptutil package. 
```
==================
WARNING: DATA RACE
Write at 0x00c000382480 by goroutine 48:
github.com/pomerium/pomerium/internal/cryptutil.(*ES256Signer).SignJWT()
/Users/bdd/pomerium/internal/cryptutil/sign.go:80 +0x52
github.com/pomerium/pomerium/internal/middleware.SignRequest.func1.1()
/Users/bdd/pomerium/internal/middleware/reverse_proxy.go:17 +0x30b
net/http.HandlerFunc.ServeHTTP()
/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1995 +0x51
github.com/pomerium/pomerium/internal/middleware.StripPomeriumCookie.func1.1()
/Users/bdd/pomerium/internal/middleware/reverse_proxy.go:45 +0x6d9 …
```
> cryptutil: fix potential race with signer

- cmd/pomerium/main.go
When running in authenticate or authorize mode, Pomerium would try to defer close a  nil- instance of proxy.  
Fixes #242 . Thank you @unsubtleguy
**Checklist**:
> cmd/pomerium: fix close on nil proxy clients

- Makefile
- authenticate/authenticate.go
- authenticate/authenticate_test.go
- cmd/pomerium/main_test.go
- internal/config/options.go
- internal/config/options_test.go
- internal/identity/providers.go
- proxy/proxy.go
- proxy/proxy_test.go
Fixes regression in redirect URL being passed by reference to identity from authenticate.
See:
- https://github.com/pomerium/pomerium/pull/202/files#diff-54dcb0c4d47e021d5e418c259fbb6669R73
- https://github.com/travisgroth/pomerium/blob/29eee409ef9307c253124108fda0808219762293/authenticate/authenticate.go#L78-L79
**Checklist**:
> authenticate: copy redirect url by value

- internal/identity/microsoft.go
This change fixes an issue that for every login with the Azure AD identity provider the permission consent screen is shown.
With this change you still get a prompt for which account to use (like it is for the Google identity provider).
**Checklist**:
> Don't force consent screen for every Azure AD login

- docs/docs/CHANGELOG.md
- docs/docs/reference/reference.md
- internal/config/options.go
- internal/config/options_test.go
- proxy/clients/clients.go
- proxy/clients/clients_test.go
- proxy/proxy.go
1. Enable WaitForReady to allow background retries through transient failures
1. Expose a configurable timeout for backend requests to Authorize and Authenticate
1. Enable DNS round_robin load balancing to Authorize and Authenticate services by default
This should mitigate the issue in #69 by hiding upstream restarts behind (1) + (2)
**Checklist**:
> GRPC Reliability Improvements

- cmd/pomerium/main_test.go
- docs/docs/CHANGELOG.md
- docs/docs/reference/reference.md
- internal/config/options.go
- internal/httputil/options.go
Go 1.12.8 changed the way url parse handles service named ports. To be on the safe side, these changes make ports explicit. 
See: 
- https://github.com/golang/go/commit/3226f2d492963d361af9dfc6714ef141ba606713#diff-6f43cc724ae52e4acba8855ce391e144
- https://golang.org/src/net/lookup.go
**Checklist**:
> config: remove references to named ports

- internal/middleware/reverse_proxy.go
- internal/middleware/reverse_proxy_test.go
This PR improves StripPomeriumCookie in two ways:
1. Strip cookies with `_pomerium` prefix (like `_pomerium_csrf`)
2. Do not generate cookie header with empty parts (like `Cookie: ;;;`)
Fixes #285 
**Checklist**:
> Fix pomerium cookie stripping

- .travis.yml
- .travis/docker_build.sh
- hooks/post_checkout
- hooks/pre_build
Related: #284 
It seems like Docker Hub automated builds really don't handle ARM builds correctly.  This PR moves image testing as well as publishing into Travis.  This should set the stage for moving to multi-arch as well.
**Checklist**:
> Move docker image builds to Travis CI

- docs/docs/CHANGELOG.md
- docs/docs/reference/reference.md
- internal/config/policy.go
- internal/config/policy_test.go
- proxy/proxy.go
config: add tls_server_name option
This option is useful when your backend is an HTTPS server, has a valid certificate, but you want to communicate with it using an internal hostname (e.g. Docker container name), or even IP addresses.
**Checklist**:
> Add `tls_server_name` option to policy file.

- docs/docs/CHANGELOG.md
- internal/log/middleware.go
- internal/log/middleware_test.go
Previously, If a request went through multiple proxies, only the right-most IP address (the originating client) was logged as a forward address. In this implementation, each proxy and the originating IP are logged as an array. 
**Checklist**:
> internal/log: return full `X-Forwarded-For`

- internal/urlutil/url.go
- internal/urlutil/url_test.go
Fixes a potential data race (in tests, really) where the mockedTime struct could race.
**Checklist**:
> bug: fix potential race condition in unit test

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE
The current Issue templates are a little prickly. These might be a bit friendlier? 
**Checklist**:
> github: make issue templates less annoying

- docs/.vuepress/config.js
- docs/.vuepress/theme/components/DropdownLink.vue
- docs/.vuepress/theme/components/NavLinks.vue
- docs/docs/reference/examples/docker/basic.docker-compose.yml
- docs/docs/reference/examples/docker/nginx.docker-compose.yml
- docs/docs/reference/examples/kubernetes/pomerium-authenticate.yml
- docs/docs/reference/examples/kubernetes/pomerium-authorize.yml
- docs/docs/reference/examples/kubernetes/pomerium-proxy.yml
These changes add a version selection navbar dropdown to the top of each page.
Does not change the default deploy branch from master, but at least updates the examples to also use `master` image. Tagged releases (and versioned branches) will also match. This feels roughly the status quo of how other projects handle documentation/release versioning.  
Fixes #330 
Fixes #337 
[Live preview](https://deploy-preview-335--pomerium-docs.netlify.com)
**Checklist**:
> docs: add version dropdown

- cmd/pomerium/main.go
- internal/config/options.go
Fixes an issue where changes / hot reloads were not being registered. Not sure how to unit test this. 
```bash
2019/10/02 22:31:42 error: Config File "config" Not Found in "[]"
```
- #328 
- #332 
**Checklist**:
> internal/config: fix on config change

- authenticate/handlers.go
- docs/docs/CHANGELOG.md
- docs/docs/reference/img/auth-flow-diagram.svg
- docs/docs/reference/reference.md
- internal/config/options.go
- internal/config/policy.go
- internal/templates/templates.go
- proxy/handlers.go
- proxy/handlers_test.go
- proxy/middleware.go
- proxy/proxy.go
[diagram](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gICAgcGFydGljaXBhbnQgQ2xpZW50IGFzIEJyb3dzZXJcbiAgICBwYXJ0aWNpcGFudCBJZFAgYXMgSWRlbnRpdHkgUHJvdmlkZXJcbiAgICBDbGllbnQtPj5JbmdyZXM6IEdFVCAvYXBwXG4gICAgSW5ncmVzLT4-UG9tZXJpdW06IC92ZXJpZnkvYXBwXG4gICAgUG9tZXJpdW0tPj5Qb21lcml1bTogQXV0aGVudGljYXRlZD9cbiAgICBQb21lcml1bS0-PiBQb21lcml1bTogTm8hXG4gICAgUG9tZXJpdW0tPj5Qb21lcml1bSBBdXRoTjogIFxuICAgIFBvbWVyaXVtIEF1dGhOLT4-Q2xpZW50OiBIVFRQIDMwMSBzaWduIGluIGNhbGxiYWNrIHVybFxuICAgIENsaWVudC0-PklkUDogIFxuICAgIElkUC0-PkNsaWVudDogIFxuICAgIENsaWVudC0-PlBvbWVyaXVtIEF1dGhOOiBIVFRQIDMwMTogT2F1dGgyIGNhbGxiYWNrIGVuZHBvaW50XG4gICAgUG9tZXJpdW0gQXV0aE4tPj4gQ2xpZW50OiBTYXZlIHNlc3Npb25cbiAgICBDbGllbnQtPj4gSW5ncmVzOiBIVFRQIDMwMSBhcHBcbiAgICBJbmdyZXMtPj4gUG9tZXJpdW06IC92ZXJ …
> proxy: support external access control request handling (forward auth)

- proxy/proxy.go
Fixes a regression which came about as part of the gorilla mux switchover. Before this fix, 404's would just return the status code in text form. Now, they return a custom 404 page like before. 
Fixes #345
Thanks again to @cmmichael  for reporting. 
**Checklist**:
> proxy: use custom 404 handler

- proxy/proxy.go
Fixes an "off-by-one" route issue where the dashboard required a slash. Not adding a changelog item because this was caught before release. 
Fixes #344 
**Checklist**:
> proxy: fix dashboard path prefix

- go.mod
- go.sum
Fixes an issue where proxy would fail to find routes if they contained ports. 
Fixes #352 
**Checklist**:
> proxy: fix routes with non-standard ports

- internal/sessions/cookie_store.go
- internal/sessions/cookie_store_test.go
- internal/sessions/header_store.go
- internal/sessions/middleware.go
- internal/sessions/middleware_test.go
- internal/sessions/query_store.go
- internal/sessions/store.go
- internal/sessions/util.go
- internal/sessions/util_test.go
- proxy/handlers.go
- proxy/handlers_test.go
- proxy/middleware.go
- proxy/proxy.go
These changes standardize how session loading is done for session cookie, auth bearer token, and query params. Each implements a common interface that returns a user's session state. 
- Bearer token previously combined with session cookie.
- rearranged cookie-store to put exported methods above unexported
- added header store that implements session loader interface
- added query param store that implements session loader interface
- #281 (possibly solving a large portion of it)
**Checklist**:
> internal/sessions: separate query params, auth-header, and cookie stores

- internal/config/options.go
- internal/httputil/server.go
Authorize, even in standalone mode will start a HTTP server in addition to the gRPC server. By default, both gRPC and HTTP will try to claim the default port `443`. The following code will anticipate that default, and use and warn the user, and use a alternative port (`:5443`) for the HTTP server. 
A similar method is used when all-in-one mode is used, and gRPC communicates over localhost. 
* #350 
**Checklist**:
> authorize: change http addr if conflict

- docs/.vuepress/config.js
- docs/docs/reference/examples/docker/basic.docker-compose.yml
- docs/docs/reference/examples/docker/nginx.docker-compose.yml
- docs/docs/reference/examples/kubernetes/pomerium-authenticate.yml
- docs/docs/reference/examples/kubernetes/pomerium-authorize.yml
- docs/docs/reference/examples/kubernetes/pomerium-proxy.yml
Kicks off a new release cycle. Resets docs to use master branch for docs and docker images. 
#350 
**Checklist**:
> docs: use master for docs again

- docs/docs/CHANGELOG.md
- docs/docs/reference/reference.md
- docs/docs/upgrading.md
- proxy/handlers.go
- proxy/handlers_test.go
Fixes an issue where requests handled by forward-auth would not be redirected back to the underlying route after successful authentication and authorization. 
Nota bene, this does create a breaking change. Previously, routes were verified by taking the downstream applications hostname in the form of a path `(e.g. ${fwdauth}/.pomerium/verify/httpbin.some.example`) variable. The new method for verifying a route using forward authentication is to pass the entire requested url in the form of a query string `(e.g. ${fwdauth}/.pomerium/verify?url=https://httpbin.some.example)` where the routed domain is the value of the `uri` key.
For example, in nginx this would look like:
```diff
-    nginx.ingress.kubernetes.io/auth-url: https://fwdauth.corp.example.com/.pomerium/verify/httpbin.corp.example.c …
```
> bug: fix forward-auth redirect & add Kubernetes recipe example

- docs/docs/CHANGELOG.md
- docs/docs/reference/reference.md
- docs/docs/upgrading.md
- proxy/handlers.go
- proxy/handlers_test.go
- proxy/middleware.go
- proxy/proxy.go
This PR changes the way forward-authentication works in several respects: 
1) Forward-authentication handlers are not registered as part of the dashboard router registration process (this had the weird side effect of making it so that you could do forward-auth validation against _any_ proxied route at `${route}/.pomerium/verify`
1) Verification will now occur on at the _root_ of the forward authentication host handler. I think this is easier to read / work with. 
1) Verification and signing endpoints are now two distinct endpoints (more along the lines of what Nginx asks for). One handler that simply verifies (returns `200` or `401`) the request, and another which again verifies the request, but will return a `302` redirect to complete the authentication process. In practice, `sign-in` is …
> proxy: strip added params from verify callback

- authenticate/handlers.go
Fixes an issue where callback url path was not being set for programmatic sign-ins.
**Checklist**:
> bug: fix bad callback url for programmatic

- internal/templates/templates.go
Previously, audiences (which can usually be quite long) was hard truncated to avoid breaking the surrounding CSS box, which was a bit of a hack and there was no way to see the true underlying value.
These changes instead use `css` to hide any overflow with an ellipsis, and the full value is still viewable via a tooltip (see below).  These changes also apply that overflow strategy to any other field. 
Fixes #385 
**Checklist**:
> internal/templates: properly truncate fields

- authenticate/handlers.go
- authenticate/handlers_test.go
- go.mod
- go.sum
- internal/httputil/constants.go
- internal/httputil/errors.go
- internal/httputil/handlers.go
- internal/httputil/handlers_test.go
- internal/middleware/middleware.go
- proxy/handlers.go
- proxy/middleware.go
In the event of an authentication error, the proxy service now checks incoming requests to see if they contain the `X-Requested-With` header (which is typically, but not always, a XHR request) and will  return a direct error instead of redirecting to the identity provider. 
Also,  a request header `x-pomerium-intercepted-response: true` was added to indicate to any client application when a given response was created by pomerium itself, and not the downstream application. 
See the below links for why it's rather difficult to detect whether a request is a an ajax/xhr request. 
These changes also ensure that the authenticate service (in particular, the sign_in endpoint) properly handles preflight checks which are typically made when a `302` redirect is sent to reauthenticate a user. For …
> authenticate: handle XHR redirect flow

- .golangci.yml
- Makefile
- proxy/handlers.go
Significant speed improvements in latest version of `golangci-lint`. Was hitting issues cutting local builds with deadlines.
- https://github.com/golangci/golangci-lint/issues/685#issuecomment-541886167
**Checklist**:
> lint: bump golangci-lint 1.21.0

- authenticate/authenticate.go
- authenticate/handlers.go
- internal/sessions/state.go
- internal/sessions/state_test.go
- proxy/middleware.go
`XHR` thy name is pain.
These changes make pomerium tokens match the expiry of access token from the identity provider. 
Though not a solution to the following issues to ( #409, #390) , does alleviate some of the frequency. 
**Checklist**:
> authenticate: session expiry now matches identity provider's

- docs/docs/background.md
Adjusted some things I noticed while reading the background.
Note that I'm dutch and not a native English speaker.
> docs(background): improved sentence flow and other stuff

- docs/configuration/readme.md
Adds documentation for the cookie options already present in options.go. I've added them as a subsection under shared settings, because they're used by both authenticate and proxy (but not authorize).
**Checklist**:
- [n/a] add related issues
- [n/a] updated unit tests
- [n/a] updated UPGRADING.md
> docs: add cookie settings

- docs/configuration/readme.md
Fixes error in nginx forward auth example.
YAML formatting also slightly updated.
**Checklist**:
> docs: Fix typo in forward auth nginx example

- docs/configuration/readme.md
The config vars for cookie domain are incorrect.
**Checklist**:
> docs: fix cookie_domain

- internal/cryptutil/hmac.go
These changes makes the HMAC period used five minutes. This period matches the expiry used by urlutils SignedURL. 
Fixes #473 
**Checklist**:
> internal/cryptutil: standardize leeway to 5 mins

- proxy/proxy.go
Bring policy set_request_headers ahead of handling AllowPublicUnauthenticatedAccess to avoiding set_request_headers was bypassed when AllowPublicUnauthenticatedAccess enabled.
Fixes #477 
**Checklist**:
> proxy: move set request headers before handle allow public access

- go.mod
- go.sum
Avoid regression in grpc's DNS update method [introduced](https://github.com/grpc/grpc-go/pull/3165) in v1.26.  The regression causes pomerium to miss changes to `cache` and `authorize` service endpoints during normal operations. 
**Checklist**:
> Roll back grpc to v1.25.1

- cmd/pomerium/main.go
- config/options.go
- config/options_test.go
- docs/configuration/readme.md
- internal/grpc/server.go
- internal/grpc/server_test.go
As of v0.26, go-grpc no longer polls DNS regularly for endpoint updates.  Discovery is only performed when a client detects a state change.  This is triggered during error conditions, but routine scaling operations in an otherwise functioning environment may leave endpoints underutilized.  To ensure we occasionally re-discover endpoints even when no connection errors have been encountered, the recommended pattern is to set server side options which gracefully terminate client connections at regular intervals.
This PR sets a reasonable default (5m) for this occasional termination and allows users to configure it further for their environments if needed.
Reference documentation - https://godoc.org/google.golang.org/grpc/keepalive#ServerParameters
https://github.com/grpc/grpc-go/pull/3165 …
> config: Expose and set default GRPC Server Keepalive Parameters

- cmd/pomerium/main.go
- go.sum
- internal/grpc/client.go
- internal/grpc/server.go
- internal/telemetry/metrics/grpc.go
- internal/telemetry/metrics/http.go
The correct Pomerium service name is no longer showing in grpc server metrics.  Instead we see the service value from the caller.  This is due to `Insert` rather than `Upsert` being used.  
Additionally, the GRPC client and server setup methods are not setting the right service name after an earlier refactor.
This PR addresses both.
**Checklist**:
> Ensure correct service name on GRPC related metrics

- .travis.yml
Prevent tip failures from marking build as failed.  We are presumably overwriting the first `matrix` section with the second one and losing the tip settings.
**Checklist**:
> ci: Consolidate matrix build parameters

- authorize/authorize.go
- config/options.go
- config/options_test.go
- internal/telemetry/metrics/info.go
- internal/telemetry/metrics/info_test.go
- proxy/proxy.go
Return uint64 from Options.Checksum to reduce type conversions and other complexity.
config: Change Options.Checksum return signature
config: Ensure metrics are updated with correct checksum
authorize: Match new Checksum return type
telemetry/metrics: remove unused field in `SetConfigInfo`
proxy: log checksum changes
Fixes #449 
**Checklist**:
> config: Remove superfluous Options.Checksum type conversions

- go.mod
- go.sum
- internal/kv/redis/redis.go
Use go mod version of redis v7.
- #508 
**Checklist**:
> dependency: use go mod redis

- authenticate/authenticate.go
Make sure the `IDP_PROVIDER` environment variable is populated and spew out a useful error message.
**Checklist**:
> Make IDP_PROVIDER env var mandatory

- docs/configuration/readme.md
- internal/kv/autocache/autocache.go
- internal/kv/bolt/bolt.go
- internal/kv/redis/redis.go
- internal/telemetry/metrics/info.go
- internal/telemetry/metrics/kv.go
- internal/telemetry/metrics/kv_test.go
- internal/telemetry/metrics/registry.go
Add metrics around the various storage mechanisms for the cache service.
Detail:
- Refactor telemetry/metrics to move `registry` into a new file
- Add generic derived metric creation functions to `registry`
- Add BoltDB metrics
- Add Autocache client/server RPC metrics
- Add Groupcache storage metrics
- Add Redis metrics
Closes #462 
**Checklist**:
> Add storage metrics

- cmd/pomerium-cli/cli.go
- go.mod
- go.sum
This adds a command line interface to generates pomerium service accounts using the same shared key as your proxy service. 
NOTA BENE: These personas will be valid until the expiry (defaults to one hour) or the shared key is changed. 
Fixes #492 
**Checklist**:
> cmd:  add cli to generate  service accounts

- docs/docs/identity-providers/gitlab.md
- internal/identity/gitlab.go
Based on our discussion in the [dev](https://pomerium-io.slack.com/archives/CUTRU68LA/p1584430862014100) slack channel, the unique identifier for a GitLab's group is changed from name to full_path.
An improvement on this PR [#518](https://github.com/pomerium/pomerium/pull/518).
**Checklist**:
> gitlab/identity: change group unique identifier to ID

- proxy/forward_auth.go
This changeset removes an extraneous unmarshalling of the user session (which is checked by the authorize function). 
**Checklist**:
> proxy: remove extra session unmarshalling

- config/options.go
- docs/configuration/readme.md
- docs/docs/upgrading.md
- proxy/middleware.go
- proxy/middleware_test.go
- proxy/proxy.go
Introduce configuration to add arbitrary JWT claims as headers in proxied requests.
Closes #585 
**Checklist**:
> Add configurable JWT claim headers

- .github/goreleaser.yaml
- .github/workflows/docker-master.yaml
- .github/workflows/release.yaml
- Dockerfile
Update docker image publishing to:
- publish a `master` image on pushes to master
- use alpine for `master` image to allow for easier debugging
- publish `latest` images only on when the release tag is the latest version, to skip cherry picked releases to older versions
**Checklist**:
> deployment: Improve docker mutable tag publishing

- docs/.vuepress/config.js
- docs/.vuepress/styles/palette.styl
- docs/configuration/readme.md
- docs/docs/CHANGELOG.md
- docs/docs/upgrading.md
Adds note about reverting the user/groups header. 
Fixes an style issue on the docs where the version dropdown is white text on a white background.
See preview : https://deploy-preview-601--pomerium-docs.netlify.com/
- https://github.com/pomerium/pomerium/pull/596
- https://github.com/pomerium/pomerium/pull/597
**Checklist**:
> docs: update upgrading / changelog to v0.7.2

- go.mod
- go.sum
grpc library was unintentionally moved down to a problematic version (1.27.0) in a previous change.  Restore 1.27.1 to prevent DNS issues during some operational changes.
Possibly #590 
#484
**Checklist**:
> Bump grpc up to 1.27.1

- docs/docs/identity-providers/gitlab.md
- internal/identity/gitlab.go
- remove hardcoded gitlab provider url.
- update the gitlab identity provider documentation.
Fixes #612 
**Checklist**:
> identity/gitlab: fix retrieve group error

- docs/docs/identity-providers/gitlab.md
- internal/identity/oidc/gitlab/gitlab.go
Changing the `api` scope which gives us too much than we need to `read_api`, the recent [GitLab 12.10 release](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#limiting-scopes-of-a-personal-access-token)
Reference: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/28944
Fixes #612 
**Checklist**:
> improvement: update gitlab api scope

- authenticate/handlers.go
- internal/identity/oauth/github/github.go
- fixes an issue where defer clear session would not be called
Fixes an issue where the gitlab provider would panic on startup because of a nil pointer (to an embedded struct). 
Fixes #636 
Thank you @Vad1mo for reporting this issue. 
**Checklist**:
> github: fix nil pointer error

- authenticate/handlers.go
- go.sum
- internal/sessions/state.go
- internal/sessions/state_test.go
These changes remove the unnecessary audience check when verifying authenticate's session. Previously, this check ensured that a route-scoped token had the proper audience but that is now being done by our policy engine on AuthZ. 
This fixes a bug where there would be an audience related error in deployments using non-standard port ranges (e.g. other than `443`/`80`). 
**Checklist**:
> session: remove audience check

- proxy/forward_auth.go
- proxy/middleware.go
- proxy/middleware_test.go
- proxy/proxy.go
- Stop returning signed JWT header to client during normal requests.  This reduces header size.
- Return signed JWT and any JWT claim headers on the forward auth endpoint.  This enables forward auth to be used in scenarios where downstream applications need access to JWT related information.
closes #631 
closes #532 
**Checklist**:
> Improve JWT header behavior

- .github/workflows/test.yaml
We were seeing an occasional error on `minikube start`. Maybe this will fix it.
**Checklist**:
> ci: force docker driver

- authorize/authorize.go
prevent panic in `Authorize` code when running in proxy service mode and config is reloaded at runtime
Fixes #634 
**Checklist**:
> Fix reload panic in Authorize code

- authorize/authorize.go
- docs/docs/CHANGELOG.md
Fix unexpected panic during config reload
#652 
**Checklist**:
> Backport fix for panic on reload to 0.7.x

- .github/Dockerfile-release
- .github/Dockerfile-release.arm32v6
- .github/Dockerfile-release.arm32v7
- .github/Dockerfile-release.arm64v8
- Dockerfile
- docs/configuration/examples/config/config.minimal.yaml
- docs/configuration/examples/docker/autocert.docker-compose.yml
- docs/configuration/readme.md
- docs/docs/quick-start/readme.md
- Compose example with data volume for autocert
- Update dockerfiles with a friendly default `autocert_dir`
- Document `autocert_dir` default for Docker
#644 
**Checklist**:
> deploy: autocert documentation and defaults

- integration/cors_test.go
- integration/manifests/lib/pomerium.libsonnet
This adds an integration test for the `cors_allow_preflight` option.
When enabled we expect a CORS request consisting of an `OPTIONS` method coupled with the `Origin` and `Access-Control-Request-Method` headers to succeed. Whereas when disabled, we expect pomerium to respond with a 302, because these routes require authentication.
**Checklist**:
> integration-tests: add CORS test

- .gitignore
- .pre-commit-config.yaml
This adds a `pre-commit` configuration to automatically run `make lint` and `go mod tidy` before committing. It can be enabled by running `pip install pre-commit` and `pre-commit install`, so it is strictly optional.
**Checklist**:
> pre-commit: add pre-commit configuration

- internal/controlplane/xds_routes.go
This implements the `preserve_host_header` option for policy routes.
Closes pomerium/internal#8
**Checklist**:
> proxy: implement preserve host headers for envoy

- internal/controlplane/xds.go
Ensure we listen on ipv4 and ipv6 for gRPC routing to AuthZ service.  This should be broadly compatible with single and dual stack.
**Checklist**:
> enable ipv6 grpc routing

- internal/envoy/envoy.go
Ensure we always return an error when envoy exits, so that we exit cleanly from CTRL+C, etc.
NB: I do not believe this will catch an out of band termination like sending SIGTERM to envoy.  Will follow up on that.
**Checklist**:
> Return an error regardless of envoy's exit status

- integration/internal/cluster/cluster.go
- integration/internal/cluster/setup.go
- integration/manifests/lib/pomerium.libsonnet
- integration/policy_test.go
- internal/controlplane/xds_listeners.go
During testing we discovered that browsers will coalesce http/2 connections if the IP address and TLS certificate are the same. This meant that when using a wildcard certificate with two domain names with the same IP address it was possible for requests for one to be routed to the routing table of the other. For example `a.example.com` would end up going to the Envoy filter chain for `b.example.com` because the TLS SNI handshake is only done at the beginning of the connection.
These changes add a test to ensure requests are handled properly even if the SNI and host headers are different. The fix was to add all domain routes for every virtual host.
**Checklist**:
> envoy: fix sni/hostname mismatched routing for http2 connection coalescing

- .github/workflows/test.yaml
Stop running tests on all pushes.  The current configuration generates noise from forked branches in addition to the tests run in PRs.
**Checklist**:
> ci: Only run testing on master branch pushes and pull requests

- internal/envoy/envoy.go
- internal/telemetry/metrics/providers.go
- internal/telemetry/metrics/providers_test.go
When handling a prometheus endpoint scrape, create a subrequest to envoy's prometheus endpoint and combine the data into our final response.
This will require a documentation follow up.  TBD after looking at any metric renaming we want to do.
**Checklist**:
> Proxy envoy metrics through control plane prometheus endpoint

- go.sum
- integration/manifests/lib/pomerium.libsonnet
- internal/controlplane/xds_clusters.go
This enables behind-the-ingress internal TLS verification. I also updated the tests so that authorize and cache are now both reached over HTTPS.
Ideally we'd actually test both cases, but I think that's going to require some more test refactoring.
**Checklist**:
> envoy: enable TLS verification for internal services

- internal/controlplane/xds_clusters.go
Current we are using `LOGICAL_DNS` for the DNS discovery type in envoy. After reading the documentation, `LOGICAL_DNS` is only really needed for large-scale web servers. It's unlikely the typical use case for pomerium will need this capability, so it makes more sense to use `STRICT_DNS` as the default.
`STRICT_DNS` always trusts the response from DNS as the complete list of addresses for a cluster, whereas `LOGICAL_DNS` assumes the DNS server only returns a subset of the addresses.
If this capability is needed in the future, we should add an additional policy configuration option to enable `LOGICAL_DNS`.
**Checklist**:
> envoy: switch to STRICT_DNS

- authorize/grpc.go
- integration/policy_test.go
Adds `x-pomerium-jwt-assertion`. 
See : https://www.pomerium.io/docs/reference/getting-users-identity.html#verification
**Checklist**:
> envoy: add jwt-assertion

- integration/control_plane_test.go
Adds a few endpoint integration tests to verify all the health-check endpoints are reachable.  This task was pretty much already complete unless I am missing something but it did give me the chance to try the integration tests. 
This test is a bit absurd because the cluster would fail to even fully load without these endpoints being up.
**Checklist**:
> envoy: verify helathcheck enpoints

- config/options.go
- config/options_test.go
- docs/configuration/readme.md
- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_routes.go
This PR implements timeouts for envoy from the various configuration settings. The only one that doesn't appear supported was the `timeout_read_header`, so I removed it from the documentation.
**Checklist**:
> envoy: implement various timeouts

- internal/controlplane/grpc_accesslog.go
This adds `duration` and `size` to the envoy access log. These appeared to be the only two missing fields from the original proxy access logs.
**Checklist**:
> envoy: add duration and size to access log

- proxy/forward_auth.go
- proxy/middleware.go
This change will copy any returned headers from the authorize check call to the response so that nginx will send them to the backend.
I tested this with an nginx configuration block like this (based on what I saw in the ingress-nginx template):
```
location / {
auth_request /auth;
auth_request_set    $auth_cookie $upstream_http_set_cookie;
auth_request_set $auth_header0 $upstream_http_x_pomerium_claim_email;
proxy_set_header 'x-pomerium-claim-email' $auth_header0;
auth_request_set $auth_header1 $upstream_http_x_pomerium_claim_user;
proxy_set_header 'x-pomerium-claim-user' $auth_header1;
auth_request_set $auth_header2 $upstream_http_x_pomerium_claim_groups;
proxy_set_header 'x-pomerium-claim-groups' $auth_header2;
auth_request_set $auth_header3 $upstream_http_x_pomerium_jwt_assertion; …
```
> envoy: forward claim and assertion headers

- internal/controlplane/server.go
Ensure we have the stats handler for metrics and tracing propagation on control plane.
**Checklist**:
> envoy: Add GRPC stats handler to control plane service

- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_routes.go
The virtual hosts and domains in envoy need to include port numbers in order to match urls like `http://httpdetails.localhost.pomerium.io:9000`. This should fix the configuration.
- Fixes #747 
**Checklist**:
> envoy: support ports in hosts for routing

- internal/telemetry/metrics/providers.go
The OpenCensus and Envoy prometheus implementations don't have parity for response encoding.  Remove encoding header to force a plain text response.
**Checklist**:
> envoy: Remove 'accept-encoding' header from proxied metric requests

- internal/cmd/pomerium/pomerium.go
- internal/controlplane/server.go
- internal/telemetry/doc.go
- internal/telemetry/grpc.go
- internal/telemetry/grpc_test.go
- internal/telemetry/metrics/grpc.go
- internal/telemetry/metrics/grpc_test.go
Small refactor that came about as part of other work.  The GRPC stats handlers in OpenCensus do implicit work for both metrics and tracing, so having them live in the metrics package doesn't make a lot fo sense.  
More work should be done to make similar changes for GRPC client and HTTP handlers in the future.
#752 
**Checklist**:
> telemetry: Refactor GRPC Server Handler

- internal/sessions/state.go
GitLab returns the user name in a `nickname` claim instead of `user`, so make
it available in `sessions.State`.
**Checklist**:
> sessions/state: Add nickname claim

- authenticate/authenticate_test.go
- authenticate/handlers_test.go
#436  Summary
Adds tests related to the well known endpoint, jwks.json url, and signing. 
**Checklist**:
> authenticate: add tests to signing endpoints

- go.mod
- go.sum
- internal/envoy/envoy.go
- internal/envoy/envoy_test.go
- Switch to OpenCensus tracer to utilize [trace propagation handling](https://www.envoyproxy.io/docs/envoy/v1.14.1/api-v3/config/trace/v3/trace.proto#envoy-v3-api-enum-config-trace-v3-opencensusconfig-tracecontext) (default to all now) 
- Add test around handling of traceConfig
- Ensure we don't panic when using Jaeger tracer
**Checklist**:
> envoy: Tracing config improvements

- internal/httputil/errors.go
- proxy/middleware.go
Fixes a bug and potential security issue where a user with a valid but expired session could send a request to an upstream server despite their session being expired. 
Huge thank you to @selaux for reporting this issue. 
To be cherrypicked onto v0.8 release branches, and released as v0.8.2.
**Checklist**:
> proxy: fix bug that would allow failed refresh session to continue

- internal/httputil/errors.go
- proxy/forward_auth.go
See https://github.com/pomerium/pomerium/pull/762 but for forward auth as well. 
Thanks again to @selaux for reporting the original, and potential forward auth issue. 
-  https://github.com/pomerium/pomerium/pull/762
To be cherrypicked and released as v0.8.3
**Checklist**:
> proxy/forward-auth: block expired request  prior to 302

- internal/envoy/envoy.go
Use configuration options for envoy's `--log-level` command line option rather than deriving it from the global logger's current level.  
**Checklist**:
> envoy: ensure command line args reflect the current log level

- internal/sessions/state.go
- internal/sessions/state_test.go
Most identity providers do _not_ provide a user specific claim. However, `sub` is typically what is intended to be used for this field. These changes allow operators to write user (vs email) driven authorization policy based on the core oidc `sub` claim. 
> Subject Identifier
> Locally unique and never reassigned identifier within the Issuer for the End-User, which is intended to be consumed by the Client.
https://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes
To be cherrypicked onto `v0.8.x` branch. 
**Checklist**
> state: infer user (`user`) from subject (`sub`)

- authenticate/authenticate.go
- authorize/check_response.go
- authorize/grpc.go
- cache/cache.go
- config/options.go
- go.sum
- internal/cmd/pomerium/pomerium.go
- internal/controlplane/xds_clusters.go
- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_routes.go
- proxy/proxy.go
Add a few getters to the options struct to avoid returning nil URLs. This is to fix an issue that was reported in slack.
**Checklist**:
> config: add getters for URLs to avoid nils

- authenticate/authenticate.go
- authenticate/authenticate_test.go
- authenticate/handlers_test.go
Adds a check to make sure authorize URL is set if running in split service mode for AuthN. 
**Checklist**:
> authenticate: ensure authorize url is set

- proxy/forward_auth.go
Traefik sends the URL path as an HTTP header named `x-forwarded-uri`. We weren't using it before, so only root-path route policies were working.
Fixes #763 
**Checklist**:
> forward-auth: support x-forwarded-uri

- docs/configuration/readme.md
Our docker-compose example was missing the `--entrypoints.web.forwardedheaders.insecure=true` option which is apparently required to make Traefik work. This PR updates the documentation.
Fixes #616 
**Checklist**:
> docs: update traefik example and add note about forwarded headers

- go.sum
- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
This PR disables cluster validation to fix out-of-order updates in the xDS control plane.
The order of updates is random because Go's map type doesn't guarantee order and the logic looks like this:
```go
current := srv.currentConfig.Load()
for typeURL, version := range versions {
// the versions are different, so the envoy config needs to be updated
if version != fmt.Sprint(current.version) { 
// ...
}
}
```
When envoy receives an LDS update it will check the routes against the existing clusters, so if the LDS update happens before the CDS update, the route would be to a non-existent cluster.
With this change that validation is disabled and routes will simply 404 until the cluster is added (which will be immediately afterward) This is what the documentation recommends for our use case:
> …
> xds: disable cluster validation to handle out-of-order updates

- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
This PR adds a final virtual host to the envoy config so that any requests for Pomerium routes like `/ping` will be routed to the control plane, even if they're done on an unmatched domain name. This should fix #787.
Fixes #787 
**Checklist**:
> xds: add catch-all for pomerium routes

- authenticate/authenticate.go
- authenticate/authenticate_test.go
This removes the validation check for the `AUTHORIZE_SERVICE_URL` in the authenticate service. Since the authenticate service never directly calls the authorize service, and the code was updated to make it tolerant of nil URLs in https://github.com/pomerium/pomerium/pull/777, it should be safe to run the authenticate service without an authorize url set.
- #786 
- #777 
**Checklist**:
> authenticate: remove authorize url validate check

- internal/cmd/pomerium/pomerium.go
- internal/controlplane/xds_listeners_test.go
We were closing the cache service immediately after starting it, resulting in autocache not working across machines.
**Checklist**:
> cache: fix closing too early

- authorize/check_response.go
- authorize/session.go
Was seeing this log line:
```
11:40:59       pomerium | {"level":"warn","error":"square/go-jose: compact JWS format must have three parts","time":"2020-05-27T11:40:59-06:00","message":"authorize: error generating new request headers"}
```
That made it seem like something was wrong, but really there was no session at all because the user hadn't logged in yet. 
This change should prevent that log from happening by returning an empty header set for non-logged-in users.
**Checklist**:
> authorize: reduce log noise for empty jwt

- internal/identity/oidc/oidc.go
- internal/identity/oidc/userinfo.go
- internal/identity/oidc/userinfo_test.go
AWS Cognito returns the `email_verified` fields as a string. This violates the spec, so rather than update it in the go-oidc library, we can workaround the issue by converting it into a bool before handing it back.
Fixes #775 
**Checklist**:
> authenticate: fix user-info call for AWS cognito

- authorize/authorize.go
- config/options.go
- config/trace.go
- config/trace_test.go
- docs/configuration/readme.md
- docs/docs/upgrading.md
- internal/cmd/pomerium/pomerium.go
- internal/envoy/envoy.go
- internal/envoy/envoy_test.go
- internal/telemetry/grpc.go
- internal/telemetry/util.go
- internal/telemetry/util_test.go
- proxy/proxy.go
Update `service` label in telemetry to be more consistent and useful in the face of both envoy and internal metrics
- Map `services` option into something that always contains `pomerium` for easier discovery and tracking
- Ensure usage of this service name mapping across tracing, metrics and envoy stats config
- Document envoy related changes
**Checklist**:
> telemetry: service label updates

- internal/cmd/pomerium/pomerium.go
- internal/controlplane/server.go
- internal/telemetry/grpc.go
Internal GRPC stats labels were missing / inconsistent.
**Checklist**:
> telemetry: Fix missing/incorrect grpc labels

- internal/kv/autocache/autocache.go
- internal/telemetry/http.go
Update autocache server and client to use new telemetry labels.
**Checklist**:
> telemetry: Fix autocache labels

- authenticate/handlers.go
Clears authN's session in the event that cache has been cleared and has an orphaned access token. 
**Checklist**:
> authenticate: clear session if ctx fails

- .github/Dockerfile-release
Envoy is not a static binary, so we need to switch to `gcr.io/distroless/base` for the release image.
Thanks to @Vad1mo for reporting.
**Checklist**:
> envoy: Switch to distroless/base for releases

- config/options.go
- config/options_test.go
It looks like we used to support quotes in the http redirect address. This change strips them from the options before updating the redirect server.
- #811 
**Checklist**:
> config: strip quotes from http redirect addr

- internal/controlplane/xds_cluster_test.go
- internal/controlplane/xds_clusters.go
It looks like docker-compose returns an ipv6 ip address for DNS lookups to localhost, but doesn't actually support binding it. By manually resolving `localhost` to `127.0.0.1`, we can force ipv4 for localhost connections.
I believe this would break ipv6 only networks, but I imagine that's exceedingly rare, so this should preserve non-docker-compose use cases as well.
- Fixes #811 
**Checklist**:
> xds: force ipv4 for localhost to workaround ipv6 issue in docker compose

- go.sum
- internal/controlplane/xds.go
When IPv6 is entirely disabled we aren't allowed to bind `::` and envoy fails out. This change should detect if ipv6 is disabled, and switch to `0.0.0.0` if that happens.
- #821 
**Checklist**:
> xds: use ipv4 address when ipv6 is disabled

- config/options.go
o is already a pointer to Options struct.
Trivial change.
> Remove additional indirection.

- internal/httputil/client.go
- internal/httputil/client_test.go
Currently, our IdP HTTP client does not use the standard HTTPStatsRoundTripper
and uses a requestID tripper instead.
This commit introduces a wrapper for standard http.Client, which will
compose a tripper.Chain to use both requestID tripper and telemetry
tripper.
Fixes #808
**Checklist**:
> internal/httputil: add HTTPStatsRoundTripper to DefaultClient

- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
This will only set the validation context in the XDS listeners if a `ClientCA` is used. I'm not sure how to reproduce the issue that was submitted, but maybe this will fix it.
- #852
**Checklist**:
> proxy: only set validation context if trusted_ca is used

- config/options.go
NewDefaultOptions() already set the viper field to a non-nil value.
Trivial change.
> Remove unnecessary viper.New()

- config/options.go
Backport b000930914769342880e35326254dbca9fdd2e93 from #849
> [Backport 0-9-0] Remove unnecessary viper.New() to 0-9-0

- config/options.go
Viper is trying to parse the `certificates` field in our config into Options.Certificates and resulting in a nil element.  This causes a failure to start pomerium.
**Checklist**:
> config: ensure viper ignores `certificates` config field

- internal/controlplane/xds.go
Fixes an issue where only the leaf certificate was being sent down to the browser. 
- Fixes #853
**Checklist**:
\cc @yegle
> controlplane: fix missing full cert chain

- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
Envoy defaults to its own preferred cipher suite which is [less opinionated than our previous cipher suite](https://github.com/pomerium/pomerium/blob/0-7-0/internal/httputil/server.go#L69-L76) and contains ciphers that are vulnerable to attacks like lucky13. 
- https://github.com/pomerium/pomerium/blob/0-7-0/internal/httputil/server.go#L69-L76
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto
- https://github.com/envoyproxy/envoy/issues/8848
- https://wiki.mozilla.org/Security/Server_Side_TLS
- https://github.com/pomerium/pomerium/issues/853
**Checklist**:
> controlplane: use previous preferred cipher suite

- docs/docs/CHANGELOG.md
- scripts/embed-envoy.bash
These changes increment the deployed version of envoy to 1.14.2.
- https://www.envoyproxy.io/docs/envoy/v1.14.2/intro/version_history#june-8-2020
- https://nvd.nist.gov/vuln/detail/CVE-2020-11080
**Checklist**:
> envoy: bump envoy to 1.14.2

- internal/cmd/pomerium/pomerium.go
Caught by:
```
go test -race ./internal/cmd/pomerium
```
The ctx in Run is both read (in handle signal goroutine) and write
(when passing to errgroup context in Run), causes data race.
Fixing it, by passing the ctx to goroutine via argument instead of
accessing it directly.
**Checklist**:
> internal/cmd/pomerium: fix data race in handling context

- internal/telemetry/metrics/kv_test.go
- internal/telemetry/metrics/registry.go
Document that metricRegistry is not safe for concurrently use. While at
it, remove t.Parallel() in tests which use metricRegistry, which causes
data race, caught by:
go test -race ./internal/telemetry/metrics
**Checklist**:
> internal/telemetry/metrics: document concurrently using

- config/policy.go
- config/policy_test.go
- internal/controlplane/xds.go
- internal/controlplane/xds_routes_test.go
- adds a route identifier that is derived only from routing information (source/destination/path) on a policy
- update envoy to use this new identifier for cluster names
Prevents unnecessary cluster churn when policy related settings are changed (eg, `allowed_users`).  This was causing transient route failures after policy changes when using HTTP2.  
Closes #870 
**Checklist**:
> policy: Add consistent route identifier

- config/policy.go
- config/policy_test.go
- internal/controlplane/xds.go
- internal/controlplane/xds_routes_test.go
Backport ee2170f5f5fdbb448b5200d4036dc1fd616008d9 from #905
> [Backport 0-9-0] config: add a consistent route ID

- internal/controlplane/xds_routes.go
- internal/controlplane/xds_routes_test.go
When switching to envoy, we forgot to adopt the middleware to set
response headers with options.Headers, which causes HSTS header is
missing in v0.9.0 release.
Fixes #901
**Checklist**:
> internal/controlplane: make sure options.Headers are set for response

- integration/manifests/lib/pomerium.libsonnet
After commit f62bb686d82820cc1313cfb79ec9364ccb5b368e, the default
headers, which include HSTS header will be set for response. It will
break integration test due to the interact with nginx ingress.
To fix it, set default headers without the HSTS header.
> integration: set default headers

- integration/policy_test.go
The test intends to check "X-Pomerium-Jwt-Assertion" exists in response
header and not empty, but accidently always test for non-empty string.
**Checklist**:
> integration: fix wrong jwt assertion test

- authenticate/authenticate.go
- authenticate/handlers.go
- authorize/grpc.go
Currently there's a data race between authn and authz, where authz waits for a session/user to synchronize from the data broker, and the user record is created by the identity manager. To avoid waiting for them to show up, we create the session and user in authn and change authz to use `Get` on the databroker directly. This should result in more consistent behavior.
**Checklist**:
> authenticate: create user record immediately, call "get" directly in authorize

- internal/envoy/envoy.go
- internal/envoy/envoy_test.go
The log line has a well defined structure that we can process by simple
string manipulation, instead of relying on regex.
```
name            old time/op    new time/op    delta
_handleLogs-12    17.3µs ±23%     1.1µs ±11%  -93.81%  (p=0.000 n=10+10)
name            old alloc/op   new alloc/op   delta
_handleLogs-12    20.1kB ± 0%     4.1kB ± 0%  -79.59%  (p=0.002 n=8+10)
name            old allocs/op  new allocs/op  delta
_handleLogs-12       141 ± 0%         1 ± 0%  -99.29%  (p=0.000 n=10+10)
```
**Checklist**:
> internal/envoy: improve handleLogs

- docs/docs/upgrading.md
Envoy does not support HTTP 1.0 by default, so document this breaking change in 0.9.0 and higher.
Fixes #915
**Checklist**:
> docs: document un-supported HTTP 1.0 in 0.9.0 and higher

- authorize/check_response.go
- authorize/evaluator/evaluator.go
- authorize/evaluator/evaluator_test.go
- authorize/grpc.go
- authorize/session.go
When doing databroker refactoring, all claims information were moved to
signed JWT instead of raw session JWT. But we are still looking for
claims info in raw session JWT, causes all X-Pomerium-Claim-* headers
being gone.
Fix this by looking for information from signed JWT instead.
Note that even with this fix, the X-Pomerium-Claim-Groups is still not
present, but it's another bug (see #941) and will be fixed later.
Fixes #936
**Checklist**:
> authorize: get claims from signed jwt

- integration/internal/cluster/setup.go
Most of the flaky failure due to the fact that not all pods are ready
yet. We currently check the readiness by get all deployments and
heuristic parsing the output. So let wait for another 10 seconds before
running tests.
**Checklist**:
> integration: sleep for amount of time before running tests

- authenticate/authenticate.go
- authenticate/handlers.go
- internal/directory/azure/azure.go
- internal/directory/azure/azure_test.go
- internal/directory/gitlab/gitlab.go
- internal/directory/gitlab/gitlab_test.go
- internal/directory/google/google.go
- internal/directory/okta/okta.go
- internal/directory/okta/okta_test.go
- internal/directory/onelogin/onelogin.go
- internal/directory/onelogin/onelogin_test.go
- internal/directory/provider.go
- internal/grpc/databroker/databroker.go
The way were generating user IDs for `user`/`directory` in the databroker was inconsistent. This should fix that problem.
We prefix the provider name on the user id in case someone changes providers. We don't want records to conflict.
Fixes #941 
**Checklist**:
> directory: generate user/directory.User ID in a consistent way

- authenticate/handlers.go
- cache/session.go
- internal/identity/manager/data.go
- internal/identity/manager/data_test.go
- internal/identity/manager/manager.go
If a session/user refresh fails we will now delete the session. This should handle revoked tokens. 
I made a couple other changes:
- handle zero timestamps better (apparently many providers have tokens which never expire)
- update the session with the server version on creation
- Fixes #935
**Checklist**:
> idp: delete sessions on refresh error, handle zero times in oauth/id tokens for refresh

- authenticate/handlers.go
The second err handling block is useless, remove it.
**Checklist**:
> authenticate: remove useless/duplicated code block

- go.sum
- internal/directory/github/github.go
- internal/directory/github/github_test.go
- internal/directory/provider.go
This implements a directory provider (for groups) for GitHub. The GitHub API is queried using a personal access token.
- Fixes #934
**Checklist**:
> github: implement github directory provider

- authenticate/handlers.go
- authenticate/handlers_test.go
- internal/identity/manager/manager.go
- internal/identity/manager/misc.go
After #926, we don't revoke access token before sign out anymore. It
causes sign out can not work anymore, because right after user click on
sign out button, we redirect user to idp provider authenticate page with
a valid access token, so user is logged in immediately again.
To fix it, just revoke the access token before sign out.
**Checklist**:
> authenticate: revoke current session oauth token before sign out

- internal/controlplane/xds_listeners_test.go
- internal/controlplane/xds_routes.go
- internal/controlplane/xds_routes_test.go
Previously, we serve a custom robots.txt that returns even for unauthenticated requests (crawlers).
```
User-agent: *
Disallow: /
```
This changes reintroduces that behavior. 
- #837 
**Checklist**:
> controlplane: add robots route

- integration/internal/cluster/setup.go
> Sleep longer before running integration tests

- docs/docs/identity-providers/okta.md
With the databroker changes the format of the `idp_service_account` changed for Okta. The documentation should now be updated to match.
- #933
**Checklist**:
> docs: update okta service account docs to match new format

- internal/directory/google/google.go
- internal/directory/provider.go
It looks like the docs for Google are already correct for configuring the service account. I went ahead and updated the code to use a ServiceAccount struct to match the other providers and give better error messages if `ImpersonateUser` is missing.
- #933
**Checklist**:
> directory: add service account struct and parsing method

- docs/docs/upgrading.md
Adding two sections to the upgrading docs about how service accounts are now required and that running more than one instance of the cache service is no longer supported.
- #933 
**Checklist**:
> docs: update upgrading document for breaking changes

- authenticate/authenticate.go
- authorize/authorize.go
- cache/cache.go
- internal/grpc/client.go
- internal/telemetry/grpc.go
- internal/telemetry/grpc_test.go
- proxy/proxy.go
- Refactor grpc client telemetry to be easier to consume consistently
- Update existing internal/grpc clients to pass service name correctly
- Update existing internal/grpc client to consume new telemetry DialOptions
- Update cache to consume new telemetry DialOptions
Closes #976 
**Checklist**:
> cache: add client telemetry

- docs/docs/identity-providers/gitlab.md
After 666fd6aa358ac1cfef1fb96490a3c609cce4e8e3, gitlab default scopes are now: "oidc", "api", "profile", "email". Updating document to reflect that change. 
Fixes #938
**Checklist**:
> docs/docs/identity-providers: document gitlab default scopes changed

- authenticate/handlers.go
- go.sum
- internal/sessions/state.go
The subject in the id token for Azure is not the same ID that is used for their API. They use an `OID` field for this. This change switches to using `OID` for the user id so that groups can be queried properly.
Fixes #978 
**Checklist**:
> azure: use OID for user id in session

- internal/directory/google/google.go
We need to use the user id for the directory information so that it is queried properly by the OPA policy.
**Checklist**:
> google: store directory information by user id

- authenticate/handlers.go
- authorize/grpc.go
- internal/sessions/state.go
- internal/sessions/state_test.go
"ver" field is not specified by RFC 7519, so in practice, most providers
return it as string, but okta returns it as number, which cause okta
authenticate broken.
To fix it, we handle "ver" field more generally, to allow both string and
number in json payload.
**Checklist**:
> internal/sessions: handle claims "ver" field generally

- cache/memberlist.go
`bufio.Scanner` will stop reading if a line is too long. This switches to using a `bufio.Reader` which won't do that.
**Checklist**:
> memberlist: use bufio reader instead of scanner

- cache/cache.go
- cache/memberlist.go
Have cache attempt to join the legacy memberlist cluster to check for other nodes so that it can log error messages.
There's no particularly good way to safely keep the cluster to 1 node and support general rolling restarts.
**Checklist**:
> cache: attempt to join memberlist cluster for sanity check

- internal/controlplane/xds_listeners.go
Additional changes to avoid streaming call timeouts through envoy.
- Disable idle timeout on control plane route.
- Set request timeout to `15s` for slowloris-like attack mitigation.  I believe the only time this would be problematic is if an inbound client is _sending_ lots of data in a single request to these routes.  I don't think we have anything like that now.  
**Checklist**:
> envoy: disable idle timeouts to controlplane

- docs/configuration/examples/kubernetes/istio/virtual-services.yml
It's necessary to specify the destination port for Pomerium services
The current example configuration does not work as-is. After reaching out on Slack, @bjoernw indicated that the destination port must be specified:
"there was one change that i think travis made that you now need to make sure in your virtual service where you are routing to the proxy you need to route to port 80 explicitly"
None
**Checklist**:
> Docs: Update Istio VirtualService example

- integration/manifests/lib/pomerium.libsonnet
After 1d1311a2400256d42d22a16fc02606379901058b, policy with groups rule
requires idp_service_account set.
**Checklist**:
> integration: add dummy value for idp_service_account

- authorize/evaluator/functions.go
- authorize/evaluator/functions_test.go
x509.Certificate.Verify() defaults to checking for Server usage rather than Client usage.  Set VerifyOptions to check for client usage explicitly.
**Checklist**:
> authorize/evaluator/opa: set client tls cert usage explicitly

- authorize/evaluator/opa/functions.go
- docs/docs/CHANGELOG.md
Backport e27ee4dd32591b4932e2fbbf8cb3626fec4c037b from #1026
> [Backport 0-9-0] authorize/evaluator/opa: set client tls cert usage explicitly

- cache/memberlist.go
In 35af5c0b91e1f93313a6ca67ed62cd1a72b11c5b, the check for multiple
cache servers in NotifyJoin is made to be done in a goroutine. That can
lead to a data race, because the memberlist can be changed at the time
the goroutine was run. go warns about this race when test memberlist was
run with "-race".
**Checklist**:
> cache: fix data race in NotifyJoin

- pkg/grpcutil/grpcutil.go
- pkg/grpcutil/grpcutil_test.go
These changes are for adding a session ID to gRPC calls. We can use this for authentication.
**Checklist**:
> pkg: add grpcutil package

- authorize/grpc.go
- authorize/grpc_test.go
- proxy/forward_auth.go
- proxy/middleware.go
When proxy receives forward auth request, it should forward the request
as-is to authorize for verification. Currently, it composes the check
request with actual path, then send the request to authorize service.
It makes the request works accidently, because the composed check
request will satisfy the policy un-intentionally. Example, for forward
auth request:
http://pomerium/?uri=https://httpbin.localhost.pomerium.io
the composed request will look like:
```
&envoy_service_auth_v2.AttributeContext_HttpRequest{
Method:   "GET",
Headers:  map[string]string{},
Path:     "",
Host:     "httpbin.localhost.pomerium.io",
Scheme:   "https",
}
```
This check request has at least two problems.
First, it will make authorize.handleForwardAuth always returns false,
even though this is a real forward …
> proxy: fix wrong forward auth request

- internal/controlplane/xds_routes.go
- internal/controlplane/xds_routes_test.go
When policy destination url has path, we should enable envoy prefix rewrite to make it works.
Fixes #1033
**Checklist**:
> internal/controlplane: set envoy prefix rewrite if present

- proxy/forward_auth.go
With Traefik in forward auth mode, when accessing:
https://example.com/foo
traefik will send a request like this to proxy:
https://pomerium?uri=https://example.com
The path "/foo" is passed to proxy via "X-Forwarded-Uri" instead of via
query parameters. When proxy redirects request to authenticate, it only
set the "pomerirum_redirect_url" to the value of "uri".
So after authentication success, the user will be redirected to example.com
instead of example.com/foo. If "X-Forwarded-Uri" is present, we should
add it to redirect uri, so the user will be redirected to right place.
**Checklist**:
> proxy: fix redirect url with traefik forward auth

- docs/configuration/readme.md
Due to the limitation of envoy, it can't handle rewriting of "From"
field without path to a destination with path.
Updates #880
Updates #1033
**Checklist**:
> docs/configuration: add doc for trailing slash limitation in "To" field

- proxy/forward_auth.go
- proxy/forward_auth_test.go
- proxy/middleware.go
Currently, authorize service does handle unauthenticated request in
forward auth mode, and return status 401.
But proxy has not handled the response yet, and always returns 403 for
both unauthenticated and unauthorized request. That breaks session
handling in forward auth mode. That said, if user was signed out, or for
any reason, authorize service return 401 status, proxy does not redirect
user to re-signin, but always return 403.
To fix it, proxy is changed to handle envoy check response in more
details, to distinguish between 401 and 403 status.
Thanks to @simbaja for rasing the problem and come up with original fix.
Fixes #1014
Fixes #858
**Checklist**:
> proxy: fix invalid session after logout in forward auth mode

- .github/goreleaser.yaml
- scripts/embed-envoy.bash
This uses a custom binary for arm64 since getenvoy doesn't support it yet.
**Checklist**:
> use custom binary for arm64 linux release

- authorize/check_response.go
When building the redirect parameter, `authorize` currently attempts to use the `x-forwarded-proto` header from envoy.  Unfortunately this doesn't work correctly when in insecure mode, as it seems envoy sets `x-forwarded-proto` to the scheme it received the request on.
The result is a bad redirect and/or hmac error.  Given the nature of Pomerium, the easiest thing to do here is always set scheme to `https`.  
**Checklist**:
> authorize: Force redirect scheme to https

- config/options.go
- config/options_test.go
My GO skills are non-existent but this is my stab to allow `certificates` to first try base64 decoding for the entries, and only then fallback to FS resolution.
Addresses #1054 
**Checklist**:
> #1054 - Change  config key parsing to attempt Base64 decoding first.

- internal/directory/google/google.go
For the Google directory provider, add both the immutable group ID and normal group e-mail to a user.  
Rationale - this allows the operator's discretion as to which type of group identifier to use, and restores the ability to use the previous (though imperfect) behavior.  
Closes #1079 
**Checklist**:
> internal/directory/google: return both group e-mail and id

- authorize/check_response.go
- authorize/google_cloud_serverless.go
- authorize/google_cloud_serverless_test.go
- authorize/grpc.go
- config/options.go
- config/policy.go
- go.sum
- internal/controlplane/xds_cluster_test.go
- internal/controlplane/xds_clusters.go
This PR adds google cloud serverless authentication support, primarily for cloud run. Changes:
* Two new config options: 
* `google_cloud_serverless_authentication_service_account`: used to define the service account (not currently implemented because I don't know how to create the identity token using a service account)
* `enable_google_cloud_serverless_authentication`: used to enable the authentication on a policy route
* Append the authorization header (when enabled) in the Authz OK response
* Add a GCP Identity Token Source which retrieves identity tokens using the compute metadata service and caches them
* Add an option to the xDS config to disable IPv6. During testing using IPv6 on a GCE instance to the cloudrun HTTP endpoint resulted in connection issues.
**Checklist**:
> implement google cloud serverless authentication

- internal/directory/azure/azure.go
- internal/directory/azure/azure_test.go
- internal/directory/github/github.go
- internal/directory/github/github_test.go
- internal/directory/gitlab/gitlab.go
- internal/directory/gitlab/gitlab_test.go
- internal/directory/okta/okta.go
- internal/directory/okta/okta_test.go
- internal/directory/onelogin/onelogin.go
- internal/directory/onelogin/onelogin_test.go
This PR allow both group name and group id in user's groups directory.
Fixes #1085
Updates #573 
**Checklist**:
> internal/directory: use both id and name for group

- internal/directory/google/google.go
Skip group without members, so it saves us time to handle group members,
and reduce the size of groups.
While at it, also querying API with the fields we need.
Fixes #567
**Checklist**:
> internal/directory: improve google user groups list

- .github/Dockerfile-cloudrun
- .github/goreleaser.yaml
- .github/workflows/release.yaml
Add image tailored for cloudrun deployment.
- Pushes image to public GCR
- Add GCP secrets friendly entrypoint
- Some requisite defaults set in ENV
This image will perform substitution of env vars via [vals](github.com/variantdev/vals) syntax.  For Cloud Run, the assumption is that GCP Secrets Manager will be used for sensitive parameters - `ref+gcpsecerets://myproject/mysecret[#/mykey]`
To source the config file from Secrets Manager, set `VALS_FILES=/pomerium/config.yaml:ref+gcpsecrets://myproject/pomerium-config`
Source main config from a secret called `pomerium-config` for shared secrets, source `IDP_SERVICE_ACCOUNT ` from a dedicated secret, and augment with a policy sourced locally at deploy time.
```shell
gcloud run deploy [SERVICE] \
--image …
```
> ci: Add cloudrun build

- .github/goreleaser.yaml
The go-releaser build definition needed to be update to point to the new location of `main` in `main.go`.
```
goreleaser release --rm-dist --snapshot -f .github/goreleaser.yaml
• releasing...
• loading config file       file=.github/goreleaser.yaml
• running before hooks
• running go mod download
• running make build-deps
• loading environment variables
• getting and validating git state
• releasing v0.10.0-rc1, commit ca6715d3c5c7187a260c5dead7f7e3a4112420f9
• pipe skipped              error=disabled during snapshot mode
• parsing tag
• setting defaults
• snapshotting
• github/gitlab/gitea releases
• project name
• building binaries
• creating source archive
• archives
• linux packages
• snapcraft packages
• calculating checksums
• signing artifacts
• docker images
• artifactory
• blobs …
```
> deployment: fix pomerium-cli release

- authorize/authorize.go
- authorize/evaluator/evaluator.go
- authorize/evaluator/evaluator_test.go
- authorize/evaluator/store.go
- authorize/evaluator/store_test.go
- authorize/run.go
This PR adds a new `Store` to the authorize evaluator.
This store holds the existing `admins` and `route_policies` data, but also stores the databroker data. This way the data will be available to custom rego policies.
Previously we passed this data on evaluation, but that has to go through a JSON marshal/unmarshal which is very slow. By using a Store we still go through the JSON marshal/unmarshal, but only when data is changed, not on every evaluation.
We still can't rely on this data for user/session/group evaluation, because it is eventually consistent, so we'd likely end up with an immediate rejection after a user logs in. So I didn't change that code.
**Checklist**:
> authorize: add evaluator store

- pkg/grpc/grpc.go
Previously, `go generate` would put generated protobuf files assuming $GOPATH, this change uses relative imports instead.
- https://github.com/golang/protobuf/issues/872#issuecomment-509801539
**Checklist**:
> grpc: use relative paths in codegen

- authorize/grpc.go
- authorize/grpc_test.go
- proxy/forward_auth.go
In #1030, the fix was done without aware of the context that traefik
forward auth mode did allow request without the "?uri=". Previosuly,
this is done in proxy, and by converting the forward auth request to
actual request. The fix is #1030 prevent this conversion, to makre
authorize service aware of which is forward auth request.
But that causes traefik forward auth without "?uri" stop working. Fixing
it by making the authorize service also honor the forwarded uri header,
too.
Fixes #1096
**Checklist**:
> authorize,proxy: allow traefik forward auth without uri query

- config/options.go
Update configuration defaults to use `127.0.0.1` instead of `localhost` in an attempt to avoid IPv6 issues present in some environments.  The most common problem is a mismatch between the host OS resolving `localhost` to ipv6, but a container engine not enabling ipv6.
This change should at least eliminate some errors that result in user confusion about a broken control plane or all-in-one mode.
https://github.com/pomerium/pomerium/issues/981
https://github.com/pomerium/pomerium/issues/821
https://github.com/pomerium/pomerium/issues/811
**Checklist**:
> config: Set loopback address by ipv4 IP

- config/options.go
Backport 75f2ed93eab89d50637c0e908f00caeecc4feb60 from #1116
> [Backport 0-9-0] Set loopback address by ipv4 IP

- scripts/embed-envoy.bash
Bumps envoy to 1.15.0 for v0.10.0 release of Pomerium. 
- https://github.com/tetratelabs/getenvoy/issues/94
- https://github.com/pomerium/pomerium/pull/1076
- https://github.com/pomerium/pomerium/issues/959#issuecomment-647382565
\cc @cuonglm @yegle 
**Checklist**:
> depedency: bump envoy to 1.15.0

- docs/docs/CHANGELOG.md
- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
With envoy 1.15.0 release, strip host port matching setting allows
incoming request with Host "example:443" will match again route with
domains match set to "example".
Not that this is not standard HTTP behavior, but it's more convenient
for users.
Fixes #959
**Checklist**:
> internal/controlplane: using envoy strip host port matching

- internal/databroker/server.go
- internal/databroker/server_test.go
Since when we now support other storage, not only memory storage, we
need to handle the error when we can't connect to storage.
**Checklist**:
> internal/databroker: handle new db error

- internal/controlplane/xds_clusters.go
- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
Force the envoy `ext_authz` call to use the pomerium `authorize` hostname in requests by naming the cluster accordingly.  A mismatch here can cause unintended routing issues with any upstream proxies present.
https://github.com/pomerium/pomerium/issues/983
**Checklist**:
> envoy: Set ExtAuthz Cluster name to URL Host

- internal/databroker/server.go
- internal/databroker/server_test.go
- pkg/storage/inmemory/inmemory.go
- pkg/storage/inmemory/inmemory_test.go
- pkg/storage/redis/redis.go
- pkg/storage/redis/redis_test.go
- pkg/storage/storage.go
Since when storage backend like redis can be fault in many cases, the
interface should return error for the caller to handle.
**Checklist**:
> pkg/storage: change backend interface to return error

- pkg/storage/redis/redis.go
- pkg/storage/redis/redis_test.go
So we can support multiple databroker servers, we can't do it if we
store last version inside Server struct.
**Checklist**:
> pkg/storage/redis: move last version to redis

- internal/databroker/config_source_test.go
- internal/databroker/helper_no_redis.go
- internal/databroker/helper_redis.go
- internal/databroker/server.go
- internal/databroker/server_test.go
- internal/signal/signal.go
- pkg/storage/inmemory/inmemory.go
- pkg/storage/redis/redis.go
- pkg/storage/redis/redis_test.go
- pkg/storage/storage.go
Currently, we're doing "sync" in databroker server. If we're going to
support multiple databroker servers instance, this mechanism won't work.
This commit moves the "sync" to storage backend, by adding new Sync
method. The Sync method will return a chanel for the caller. Everytime
something happens inside the storage, we notify the caller by sending a
message to the channel.
**Checklist**:
> pkg/storage: introduce storage.Backend Watch method

- docs/configuration/readme.md
- pkg/storage/redis/redis.go
It appears that `cookie_secret` is required (from what I have tested locally, also read the code and it appears that it requires a base64 valid string). It just adds required tag to this field.
Feel free to close it if I understood the code wrong and if I am doing something wrong configuring it!
**Checklist**:
> docs: Add required in cookie_secret

- docs/recipes/kubernetes.md
Add `kubectl` commands to set up the config in the kubernetes recipe.   Easier than manual changes to the kube config yaml.
**Checklist**:
> docs: Add kubectl config commands

- go.sum
- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
- internal/controlplane/xds_routes.go
Previously we fixed this issue by using `StripMatchingHostPort: true`. Unfortunately this made it so any routes which actually had ports in them (ie `example.com:9000`) longer match in envoy's routing table. This is because the routes were added explicitly with the port in the name.
This PR includes two changes:
1. We remove the `StripMatchingHostPort` option.
2. We add duplicate entries for any bare domain names, or domain names with default ports. `https://www.example.com` has an entry for `www.example.com` and `www.example.com:443`.
- https://github.com/pomerium/pomerium/issues/959
- https://github.com/pomerium/pomerium/pull/1126
**Checklist**:
> handle example.com and example.com:443

- authorize/authorize.go
- authorize/evaluator/evaluator.go
- authorize/evaluator/store.go
- authorize/grpc.go
- authorize/run.go
- internal/databroker/config_source.go
- internal/databroker/server.go
There were two issues in the code:
1. When the server version changed we properly updated the server version on the initial `GetAll` call, but we didn't update it in the `Sync` call, so we didn't detect the change. 
2. When we called `forceSync` we returned `nil` when no session was found, but this left the session state intact, and a user would see an error page instead of being redirected to the login page.
To fix these issues I made the following changes:
1. Data is now properly cleared from the databroker data map instead of relying on a lookup of the version to clear the state.
1. I removed the separate databroker data map update goroutine, and do it directly now.
1. In addition to updated the server version, we now reset the record version to the empty string. This should re-sync …
> fix databroker restart versioning, handle missing sessions

- pkg/storage/redis/redis.go
Instead, we run the loop in goroutine, and when context was done,
closing the underlying connection of PubSubConn, so the Receive will
return.
Fixes #1154
**Checklist**:
> pkg/storage/redis: do not use timeout to signal redis conn to stop

- pkg/grpcutil/grpcutil.go
- pkg/grpcutil/grpcutil_test.go
In addition to authorization via sessionids it would be nice to support authorization via JWTs - for example a service behind Pomerium that needs to use the JWT header.
**Checklist**:
> grpcutil: add functions for JWTs in gRPC metadata

- cache/cache.go
- cache/databroker.go
- internal/databroker/config.go
- internal/databroker/server.go
- pkg/cryptutil/encrypt_test.go
- pkg/storage/encrypted.go
- pkg/storage/encrypted_test.go
- pkg/storage/storage_test.go
This PR adds encryption to storage backends. This way all data stored in the databroker will be encrypted.
- Fixes https://github.com/pomerium/pomerium/issues/1158
**Checklist**:
> databroker: add encryption for records

- config/options.go
- docs/reference/readme.md
Allow users to use a single service account when using Google IDP with GCP Serverless Auth by defaulting to the `idp_service_account` credentials.
**Checklist**:
> config: default to google idp credentials for serverless

- authorize/grpc.go
- authorize/grpc_test.go
- internal/controlplane/xds_listeners.go
- internal/urlutil/url.go
After #1153, envoy can handle routes for `example.com` and `example.com:443`.
Authorize service should be updated to handle this case, too.
Fixes #959
**Checklist**:
> authorize: strip port from host header if necessary

- pkg/storage/redis/redis.go
In case of connection to backend failure, we try reconnecting with
backoff, to re-subscribe to the notification channel.
Fixes #1167
**Checklist**:
> pkg/storage/redis: handling connection to redis backend failure

- cmd/pomerium-cli/kubernetes.go
- go.mod
- go.sum
This PR fixes two issues:
1. We weren't decoding the expiry data in the JWT properly
2. We had hardcoded the token to expire after 10 seconds (presumably for testing and I forgot to change it back)
Fixes https://github.com/pomerium/pomerium/issues/1151
**Checklist**:
> pomerium-cli: fix kubernetes token caching

- .github/goreleaser.yaml
- .github/workflows/release.yaml
- add linux arm64 docker images back to the release pipeline
- remove push command from images no longer being generated
**Checklist**:
> ci: fix arm docker image releases

- .github/goreleaser.yaml
Creates a separate archive for `pomerium-cli`
```
136a310e3dec594b1a9347c0c99aa3695dae7e6bca084d426a1e5063d5e6a8bc  pomerium-linux-amd64.tar.gz
276dd322fab425b334b93ba14a62f058b8c446b1a6097af5e5f3b11123e0be90  pomerium-cli-linux-armv6.tar.gz
30bc8e948d55d03768439d75ffdbe3f6961b6d412bf3b815a01fc8a82d2fe82a  pomerium-darwin-amd64.tar.gz
86fe2bf382af35dc372b10352289aff74d7570aac6f94c5f331e0924a0c6b537  pomerium-cli-linux-arm64.tar.gz
91b87710f88566a9c0ac63cfac813eb249be429513335647bf4f7c5d21075b3d  pomerium-cli-windows-amd64.zip
9d35b9f156e908e76d8a1acb1bb080731fc54d9c9f9a4c7b50695fe770211057  pomerium-cli-freebsd-amd64.tar.gz
c4c83faca51b567a58b42221f34c968c94144ca80e67209b175cb7b3380d4670  pomerium-cli-darwin-amd64.tar.gz
e7cce543e628b9181c162c421b56bdddfe93aa5b5e4df39771bda0868b07a98e …
```
> deployment: cut separate archive for cli

- .github/goreleaser.yaml
fix goreleaser's pomerium-cli build 
**Checklist**:
> deploy: ensure pomerium-cli is built correctly

- cmd/pomerium-cli/kubernetes.go
- go.sum
This adds TLS CA options and fixes a shutdown bug on the HTTP server.
- Fixes https://github.com/pomerium/pomerium/issues/1149
- Fixes https://github.com/pomerium/pomerium/issues/1148
**Checklist**:
> pomerium-cli: kubernetes fixes

- cmd/pomerium-cli/kubernetes.go
Allow kubectl credentials provider to work in non-interactive sessions when we have credentials already.
**Checklist**:
> cmd/pomerium-cli: do not require terminal with cached creds

- authorize/evaluator/evaluator.go
I discover this while working on #1198. Currently, if the main policy is allowed, but the custom policy return `&evaluator.CustomEvaluatorResponse{Allowed:false, Denied:true, Reason:""}`, then we still allow the request, while it should be forbidden.
Test will be added in #1198
**Checklist**:
> authorize/evaluator: fix wrong custom policies decision

- proxy/proxy.go
- proxy/proxy_test.go
We've refactored our config loading and proxy.New() is now handed pre-validated policies.  I also don't think the proxy is directly handling routes anymore.
This change avoids calling Validate() a second time, as it can break mutually exclusive option checks like [this](https://github.com/pomerium/pomerium/blob/7a53e6bb42167d86f4197c51da767796c46d3345/config/policy.go#L277).  
Overall, I believe we have some dead code in the pomerium services around config handling that could probably use some cleanup.
**Checklist**:
> proxy: avoid second policy validation

- authorize/authorize.go
- authorize/authorize_test.go
Currently, when option changes, whether the option is good or bad, we
always store new policy evaluator.
When options is bad, policy evaluator will be nil. That can lead to panic
at runtime if a Check request were called after Authorize.OnConfigChange
ran with bad option.
We already have an error message if new policy evaluator fails, so we
must only update it on success only.
**Checklist**:
> authorize: store policy evaluator on success only

- authenticate/authenticate.go
- config/options.go
- proxy/proxy.go
In #1088, OptionsUpdater was removed, but current code still mention it.
This commit updates all comments which still mention about that
interface (authorize is exlcuded, and will be updated in #1206).
**Checklist**:
> all: update outdated comments about OptionsUpdater interface

- pkg/storage/inmemory/inmemory.go
- pkg/storage/redis/redis.go
- pkg/storage/storage.go
- pkg/storage/storage_test.go
So the caller can not write to the channel, and insist that the channel
is for notifying only.
**Checklist**:
> pkg/storage: make Watch returns receive only channel

- config/options.go
Storage certs are being loaded from the wrong options.
**Checklist**:
> config: fix loading storage client cert from wrong location

- docs/reference/readme.md
Makes clear it must be an EC key and also that it must be present in the authentication service, if run separately.
**Checklist**:
> Docs: Update README stating specific requirements for SIGNING_KEY

- cache/databroker_test.go
- internal/databroker/server.go
GRPC streaming is better at sending multiple smaller message instead of
a big one.
Benchmark result for sending 10k messages at once vs multiple batches,
each with 100 messages:
```
name     old time/op  new time/op  delta
Sync-12  14.5ms ± 3%  12.4ms ± 2%  -14.40%  (p=0.000 n=10+9)
```
**Checklist**:
> internal/databroker: make Sync send data in smaller batches

- docs/guides/argo.md
- docs/guides/kubernetes-dashboard.md
- examples/kubernetes/values.yaml
The examples had rootDomain, which is not used anymore, as far as I can tell. It confused me for a long time.
> remove rootDomain from examples

- internal/autocert/manager.go
If autocert failed to renew a valid cert, we should continue using that cert instead of aborting pomerium.
Fixes #1232
**Checklist**:
> internal/autocert: re-use cert if renewing failed but cert not expired

- docs/docs/identity-providers/okta.md
- go.sum
The okta service account token field should be api_key not api_token
Fixes #1249
**Checklist**:
> docs/docs: fix wrong okta service account field

- config/options.go
Warn if custom scopes set for builtin providers.
Fixes #1144
**Checklist**:
> config: warn if custom scopes set for builtin providers

- .github/workflows/test.yaml
Upgrade CI to use go1.15
**Checklist**:
> .github/workflows: upgrade to go1.15

- internal/databroker/config_source.go
- internal/databroker/config_source_test.go
I forgot that we need to validate the options after updating them to populate some of the fields. With this change we'll validate the config after we update it in the databroker, and if validation fails we'll continue to use the existing config (and log the error).
Also I noticed we weren't skipping invalid policies like our error message said we were.
**Checklist**:
> config: validate databroker settings

- internal/directory/okta/okta.go
See: https://developer.okta.com/docs/reference/api/groups/#list-groups-with-membership-updated-after-timestamp
Updates #1256
**Checklist**:
> internal/directory/okta: increase default batch size to 200

- internal/cmd/pomerium/pomerium.go
- internal/envoy/envoy.go
- internal/envoy/envoy_test.go
- internal/envoy/misc.go
This is a follow-up to #1255 . Envoy has some settings which can't be dynamically loaded, like the tracing options, and the log level. This PR changes the way the envoy process is run so that we can support restarting it. Envoy has built-in support for zero-downtime restarts, so we take advantage of those options.
An envoy process has a `base-id` that we first set dynamically with `--dynamic-base-id`. This `base-id` is written to a temporary file. On restart we use this `base-id` and also pass in an incremented `restart-epoch` counter. If `restart-epoch` is greater than 0, envoy knows to look in shared memory for the existing sockets/stats/etc and transfers the over. Any existing requests will be drained.
**Checklist**:
> envoy: add support for hot-reloading bootstrap configuration

- authenticate/authenticate.go
- authenticate/authenticate_test.go
- authorize/authorize.go
- authorize/check_response_test.go
- authorize/grpc_test.go
- authorize/session.go
- authorize/session_test.go
- config/options.go
- internal/cmd/pomerium/pomerium.go
- internal/sessions/cookie/cookie_store.go
- internal/sessions/cookie/cookie_store_test.go
- internal/sessions/cookie/middleware_test.go
- proxy/forward_auth_test.go
- proxy/handlers.go
- proxy/handlers_test.go
- proxy/proxy.go
- proxy/proxy_test.go
This PR makes the cookie options reloadable. I changed the cookie constructors so they take a getter function instead of the raw options. I also pulled out the `atomicOptions` struct into `config.AtomicOptions` and updated authenticate and proxy to use it.
- #1254 
**Checklist**:
> config: allow dynamic configuration of cookie settings

- docs/.vuepress/config.js
Fixes the sitemap to use .com hostname values, not io. 
https://github.com/algolia/docsearch-configs/pull/2289#issuecomment-673323663
**Checklist**:
> docs: use .com sitemap hostname

- authenticate/authenticate.go
- authenticate/authenticate_test.go
- authenticate/handlers.go
- authenticate/handlers_test.go
- internal/cmd/pomerium/pomerium.go
- internal/identity/mock_provider.go
- internal/identity/oauth/github/github.go
- internal/identity/oidc/azure/microsoft.go
- internal/identity/oidc/gitlab/gitlab.go
- internal/identity/oidc/google/google.go
- internal/identity/oidc/oidc.go
- internal/identity/oidc/okta/okta.go
- internal/identity/oidc/onelogin/onelogin.go
- internal/identity/providers.go
This PR makes the IDP provider settings in authenticate update whenever configuration is changed. This should allow a user to change IDP settings without restarting the process.
- #1254 
**Checklist**:
> authenticate: support reloading IDP settings

- authenticate/authenticate.go
- authenticate/handlers.go
- authenticate/handlers_test.go
- authenticate/state.go
- pkg/cryptutil/encrypt.go
This change moves most of the properties on the Authenticate struct into a seperate authenticateState struct so they can be updated whenever configuration changes.
#1254 
**Checklist**:
> authenticate: move properties to atomically updated state

- internal/directory/okta/okta.go
- internal/directory/okta/okta_test.go
This PR improves how we query okta API, by doing 2 things:
- In case rate limit reached, we honor the response header from okta, sleep until that time and performing query again.
- Using filters to query for updated groups only (both profile and membership), hence reducing number of requests we need to perform to okta API server.
Updates #1256 
**Checklist**:
> Improving okta API requests

- config/trace_test.go
- go.mod
- go.sum
Test needs to be changed to use lowercase name, as required by zipkin
JSON API v2 spec.
See: https://github.com/openzipkin/zipkin-go/pull/166
**Checklist**:
> Upgrade zipkin-go to v0.2.3

- internal/autocert/manager.go
These changes ensure that autocert is being bootstrapped with the correct cache store location. Previously, we were using NewDefaults and inadvertently setting the cert renewal thread to look in the wrong  storage location. 
Fixes #1281 
https://github.com/caddyserver/certmagic/blob/10a8b5c72339665fa9fbdb180236cd64b13337b3/certmagic.go#L423-L442
**Checklist**:
> autocert: fix  bootstrapped cache store path

- .github/workflows/test.yaml
- go.sum
- internal/directory/okta/okta.go
- internal/directory/okta/okta_test.go
Okta uses space " " instead of plus sign "+" in query filter.
See https://developer.okta.com/docs/reference/api-overview/#filtering
**Checklist**:
> internal/directory/okta: fix wrong API query filter

- integration/control_plane_test.go
- proxy/handlers.go
Validate signature middleware must be applied for the callback
sub-router, not the whole dashboard router.
Fixes #1297
**Checklist**:
> proxy: fix wrong applied middleware

- cache/cache.go
- cache/cache_test.go
- cache/databroker.go
- cache/databroker_test.go
- cache/memberlist_test.go
- go.sum
- internal/cmd/pomerium/pomerium.go
- internal/databroker/config.go
- internal/databroker/server.go
- internal/databroker/server_test.go
- internal/directory/provider.go
- internal/identity/manager/config.go
- internal/identity/manager/manager.go
- pkg/storage/inmemory/inmemory.go
- pkg/storage/redis/redis.go
- pkg/storage/storage.go
- pkg/storage/storage_test.go
This updates the cache (databroker) service to update the internal databroker server whenever configuration options change.
To implement this I added `Close` methods to `redis`/`inmemory` and re-create the databases if the options change such that a rebuild is necessary. In the case of `inmemory` this would cause all data to be erased, but for redis the switchover should be largely invisible.
Many of the databroker options aren't available in the dashboard currently but we will likely want to add them.
- #1254 
**Checklist**:
> cache: support databroker option changes

- authenticate/authenticate.go
- authenticate/handlers.go
- authenticate/handlers_test.go
- authenticate/state.go
- go.sum
This PR moves the databroker connection in authenticate to the state. This way if the connection changes it will pick up the new connection automatically.
I also added a call to `ValidateOptions` every time we rebuild the state.
- #1254 
**Checklist**:
> authenticate: move databroker connection to state

- cache/cache.go
- config/options.go
- internal/directory/azure/azure.go
- internal/directory/azure/azure_test.go
- internal/directory/provider.go
- pkg/grpc/directory/directory.go
This PR updates the Azure directory provider so that it supports deriving service account credentials from the existing configuration options. 
Fixes #1299 
**Checklist**:
> azure: support deriving credentials from client id, client secret and provider url

- authorize/grpc.go
- go.sum
Fixes #1293 
Previously, authorization decisions were not logging user and groups. 
```
{"level":"info","service":"authorize","request-id":"02fd15f5-19a0-4e2b-b580-26960ec1a079","check-request-id":"fa7b7b10-657b-4532-a95e-4d67ad576671","method":"GET","path":"/spec.json","host":"httpbin.imac.bdd.io","query":"","allow":true,"status":200,"message":"OK","user":"snip@snip.com","groups":["ssnip"],"time":"2020-08-18T21:04:15-07:00","message":"authorize check"}
```
**Checklist**:
> authorize: log users and groups

- authorize/evaluator/evaluator.go
- authorize/evaluator/evaluator_test.go
This PR adds a `jti` to the JWT payload. `jti` is the unique identifier for the JWT and we use it to represent the session ID internally. It would be nice to also pass it through so that upstream applications can retrieve the currently logged-in user's session ID to query data from the databroker.
**Checklist**:
> authorize: add jti to JWT payload

- go.mod
- go.sum
- internal/directory/okta/okta.go
- internal/directory/okta/okta_test.go
- internal/directory/provider.go
Backport 23eea09ed0be04e635a9feb0544a76ce40988db2 from #1278
Backport a4408ab6cf11e49c34b80b86b52c589a773ac653 from #1296 
Backport 598102f58709409dca2510eab3541ef8c6980c4d from #1271 
~~Backport f356ff5581ca38e97ae5f802a714290b497651a7 from #1271~~
Set a default QPS to avoid introducing new config options
> [Backport 0-10-0] internal/directory/okta: improve API requests

- cmd/pomerium-cli/cli.go
- docs/docs/topics/impersonation.md
This makes it easier to safely pass it in programmatically to a container
without cutting and pasting or putting it on the command line.
Allows the shared secret to be passed in the  POMERIUM_SHARED_KEY environment variable, in addition to as the final command line argument or via an explicit prompt.
None.
**Checklist**:
- [N/A] add related issues
- [NA] updated unit tests
- [N/A] updated UPGRADING.md
> Allow setting the shared secret via an environment variable.

- Dockerfile
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Signed-off-by: Robert <rspier@pobox.com>
Eliminates warning from apt when stdin is not a tty by using apt-get instead.
**Checklist**:
> Use apt-get instead of apt to eliminate warning.

- Dockerfile
Size increases by 22MB.  (144MB -> 167MB)
This normalizes with expectations (and instructions, see impersonation
docs) that it will be there.
Adds a make build call to the Dockerfile to build the CLI.  
(Also makes the build call for the `pomerium` binary explicit.)
Fixes #1343 
**Checklist**:
- [x ] ready for review
> Include pomerium-cli in the docker image by default.  Fixes #1343.

- internal/controlplane/http.go
- internal/controlplane/server.go
Ensure we're getting proper tracing with propagation on the control plane http endpoints.
This is arguably a bug fix, so marking it for v0.10.x.
closes #535 
**Checklist**:
> internal/controlplane: add telemetry http handler

- internal/directory/okta/okta.go
- internal/directory/okta/okta_test.go
Allow non-json encoded in okta service account value.
Fixes #1354
**Checklist**:
> internal/directory/okta: acceept non-json service account

- renovate.json
Fix renovate bot config for mod tidy.
https://docs.renovatebot.com/configuration-options/#postupdateoptions
https://docs.renovatebot.com/modules/manager/gomod/
**Checklist**:
> deps: ensure renovate runs `go mod tidy`

- docs/reference/readme.md
- internal/controlplane/xds_routes.go
- internal/controlplane/xds_routes_test.go
With this change we support using the `timeout` property on a policy with `allow_websockets`, though we still don't use the global timeout.
Closes #1327 
**Checklist**:
> proxy: support websocket timeouts

- authorize/grpc.go
- config/policy.go
- internal/controlplane/xds_listeners_test.go
- internal/controlplane/xds_routes.go
- internal/controlplane/xds_routes_test.go
For public unauthenticated routes we want `robots.txt` to be forwarded to the backend. This PR implements that change.
Closes #837 
**Checklist**:
> proxy: disable control-plane robots.txt for public unauthenticated routes

- authorize/evaluator/evaluator.go
- authorize/evaluator/evaluator_test.go
This PR updates the JWT generation code in authorize to use the impersonate email and groups session options instead of the user email and groups. (if set)
**Checklist**:
> authorize: use impersonate email/groups in JWT

- authorize/evaluator/custom.go
- internal/databroker/config_source.go
This PR adds a couple additional traces for custom rego evaluation and the databroker config source. I also fixed a bug in the order of operations when loading options from the databroker. Calling `Validate` after adding the new policies would end up replacing them with the original environment variable, so I add them after calling validate instead.
**Checklist**:
> databroker: add tracing for rego evaluation and databroker sync, fix bug in databroker config source

- .github/stale.yaml
Add first pass at automated stale issue closure.  Intentionally very conservative.  Key aspects:
- 30 day count down with 7 day grace period
- Explicitly ignore labels that indicate activity on Pomerium's side (thinking, accepted)
- Explicitly ignore issues that are assigned
- Only evaluate `WaitingForInfo` / `ChangesRequested` labels
- Low rate limit to start, in case of any unexpected behavior
**Checklist**:
> ci: add stale issue automation

- docs/reference/readme.md
- go.mod
- go.sum
- internal/directory/okta/okta.go
- internal/directory/provider.go
We did honor the rate limit header from okta, so don't bother to add our
rate limiter there.
**Checklist**:
> internal/directory/okta: remove rate limiter

- .github/ISSUE_TEMPLATE/bug_report.md
- internal/controlplane/grpc_accesslog.go
- internal/controlplane/http.go
- internal/middleware/middleware.go
- internal/middleware/middleware_test.go
These changes make health check endpoints default to `debug` log level. These changes also remove the pomerium version from the healthcheck endpoint `ping`. 
Fixes #776 
Fixes https://github.com/pomerium/internal/issues/147
**Checklist**:
> {proxy/controlplane}: make health checks debug level

- internal/envoy/envoy.go
Prevent two "cold" start issues by ensuring we always start from a `0` epoch.
After previous start:
`{"service":"envoy","name":"envoy","time":"2020-09-08T21:59:24Z","message":"previous envoy process is still initializing"}`
After a previous start, but the shared memory segment is missing:
`{"service":"envoy","name":"envoy","time":"2020-09-08T19:40:18Z","message":"[2020-09-08 19:40:18.453][1832][critical][assert] panic: cannot open shared memory region /envoy_shared_memory_356280060 check user permissions. Error: No such file or directory"}`
**Checklist**:
> internal/envoy: start epoch from 0

- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
We were improperly adding domain names with their ports in the `server_names` TLS field:
```
"filter_chain_match": {
"server_names": [
"b.localhost.pomerium.io:8843"
]
},
```
It should've been:
```
"filter_chain_match": {
"server_names": [
"b.localhost.pomerium.io"
]
},
```
The later route matchers will handle the ports.
Fixes #1150 
**Checklist**:
> proxy: for filter matches only include bare domain name

- internal/controlplane/xds_cluster_test.go
- internal/controlplane/xds_clusters.go
These changes add support for connecting to upstreams which use P-384 and P-512 EC curves. 
- https://github.com/envoyproxy/envoy/issues/10855
**Checklist**:
> controlplane: support P-384 / P-512 EC curves

- internal/directory/azure/azure.go
- internal/directory/azure/azure_test.go
- internal/directory/azure/group.go
- internal/directory/azure/group_test.go
With Azure active directory a group may contain other groups. For example, group 1 may contain group 2, and group 2 may contain user 1, therefore user 1 is a member of group 2 and group 1. These changes implement that behavior.
I pulled out the code to do that into a `groupLookup` type which implements the recursion using a stack and also should prevent cycles.
Fixes #1397 
**Checklist**:
> azure: add support for nested groups

- internal/autocert/manager.go
- internal/autocert/manager_test.go
We were adding the config headers for normal envoy responses, but not for the redirect handler. This PR adds those headers for redirects to HTTPS as well as for the autocert responses.
- for #1413 
**Checklist**:
> redirect-server: add config headers to responses

- internal/directory/okta/okta.go
- internal/directory/okta/okta_test.go
We rely on a local cache of groups to improve the efficiency of the Okta API. Unfortunately we were never removing groups from this cache, so if a group was deleted we would still query for its members and that call would fail.
This PR adds a check for a 404 on the members call and if received deletes the local group and ignores the error.
Fixes #1414 
**Checklist**:
> okta: handle deleted groups

- examples/traefik/config.yaml
- examples/traefik/docker-compose.yaml
Update traefik middleware to use X-Pomerium-Claim-* instead of X-Pomerium-Authenticated-*
fixes #1421
**Checklist**:
> fix(examples): Use X-Pomerium-Claim headers

- internal/controlplane/xds_cluster_test.go
- internal/controlplane/xds_clusters.go
Fixes a typo in https://github.com/pomerium/pomerium/pull/1409. P-512 != P-521.
```json
{
"level": "error",
"error": "Error adding/updating cluster(s) policy-3816db18ba3f8895: Failed to initialize ECDH curves X25519:P-256:P-512",
"code": 13,
"details": null,
"time": "2020-09-17T21:58:40-07:00",
"message": "error applying configuration"
}
```
- https://github.com/pomerium/pomerium/pull/1409
**Checklist**:
> controplane: remove p-521 EC

- docs/.vuepress/config.js
- docs/guides/traefik-ingress.md
- examples/traefik-ingress/README.md
- examples/traefik-ingress/add_repos.sh
- examples/traefik-ingress/crds/middleware.yaml
- examples/traefik-ingress/install.sh
- examples/traefik-ingress/values/hello.yaml
- examples/traefik-ingress/values/pomerium.yaml
- examples/traefik-ingress/values/traefik.yaml
Add a full traefik example with forward auth on kubernetes.
**Checklist**:
> docs: Add Traefik + Kubernetes example

- .github/workflows/release.yaml
Our release action is using an old version of go. 
**Checklist**:
> deployment: bump release go to v1.15.x

- internal/frontend/assets/html/error.go.html
- internal/httputil/errors.go
In previous versions of Pomerium (pre v0.9.0), a users were presented with an error page with a "retry url" link.  That link was populated from the value of the `pomerium_redirect_uri` query param. 
Under certain conditions, this queryparam could be misused to create a crafted retry URL link which in turn could then be used to trick a user to visiting a malicious site.
These changes remove the "retry url" functionality out of an abundance of caution. 
- https://github.com/pomerium/internal/issues/160
**Checklist**:
> httputil: remove retry button

- proxy/handlers.go
- proxy/handlers_test.go
- proxy/middleware.go
This adds a new `/.pomerium/jwt` endpoint to query for the JWT assertion header value. To implement this we call the authz check method which fills in the header.
- #1369 
**Checklist**:
> proxy: add support for /.pomerium/jwt

- internal/databroker/server.go
- pkg/storage/redis/redis.go
- pkg/storage/redis/redis_test.go
Keyspace event notifications are problematic for some redis implementations, and setting config isn't ideal. This swaps them out for pubsub commands.
- #1448 
**Checklist**:
> redis: use pubsub instead of keyspace events

- internal/identity/manager/manager.go
I found this bug when working on the incremental azure directory sync. We were only resetting the next check time if we were due to refresh the directory users and groups.
In practice this meant if no one had logged in yet the 2nd (3rd, 4th, etc) directory sync wouldn't happen, because the `nextTime` would not have been changed.
We now always set the `nextTime` to the `directoryNextRefresh` if it's before `nextTime`.
**Checklist**:
> identity manager: fix directory sync timing

- internal/httputil/server.go
- internal/httputil/server_test.go
This PR changes our `HTTP -> HTTPS` redirect code to preserve the URL path and query string.
- Fixes #1449 
**Checklist**:
> proxy: preserve path and query string for http->https redirect

- config/policy.go
- docs/reference/readme.md
- go.mod
- go.sum
- internal/controlplane/xds_routes.go
- internal/controlplane/xds_routes_test.go
This PR adds new policy config options for customizing host header rewriting. I basically copied the available options in envoy: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html#config-route-v3-routeaction.
I updated the readme with an explanation of the value:
- `yaml`/`json` settings: `host_rewrite`, `host_rewrite_header`, `host_path_regex_rewrite_pattern`, `host_path_regex_rewrite_substitution`
- Type: `string`
- Optional
- Example: `host_rewrite: "example.com"`
The `host` header can be customized via 3 mutually exclusive options:
1. `host_rewrite` which will rewrite the host to a new literal value.
2. `host_rewrite_header` which will rewrite the host to match an incoming header value.
3. `host_path_regex_rewrite_pattern`, …
> config: add support for host header rewriting

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/envs/nginx.yaml
- .devcontainer/envs/traefik.yaml
- .devcontainer/readme.md
- .gitignore
- .vscode/launch.json
- examples/nginx/auth.conf
- examples/nginx/docker-compose.yaml
- examples/nginx/ext_authz.conf
- examples/nginx/httpbin.conf
- examples/nginx/pomerium.conf
- examples/nginx/proxy.conf
Adds remote container development configurations for VS code. These are most useful for step-debugging / developing against other fronting proxies / forward-auth configurations. 
It's related to all my issues. All of them. 
- https://github.com/pomerium/pomerium/pull/1447
- https://github.com/pomerium/pomerium/pull/1415
- #1313 
**Checklist**:
> dev: add remote container debug configs

- .github/goreleaser.yaml
- docs/docs/installation.md
- ospkg/conf/config.yaml
- ospkg/pomerium.service
- ospkg/postinstall.sh
- ospkg/preinstall.sh
Adds some basic packages.
- run as non-root / unprivileged port
- includes base config file
- pre-configures autocert directory default
Artifact list on snapshot:
```
pomerium-cli_v0.10.0+next-1_aarch64.rpm
pomerium-cli_v0.10.0+next-1_amd64.deb
pomerium-cli_v0.10.0+next-1_arm.deb
pomerium-cli_v0.10.0+next-1_arm.rpm
pomerium-cli_v0.10.0+next-1_arm64.deb
pomerium-cli_v0.10.0+next-1_armhf.deb
pomerium-cli_v0.10.0+next-1_armhf.rpm
pomerium-cli_v0.10.0+next-1_x86_64.rpm
pomerium-v0.10.0+next-1.aarch64.rpm
pomerium-v0.10.0+next-1.x86_64.rpm
pomerium_v0.10.0+next-1_amd64.deb
pomerium_v0.10.0+next-1_arm64.deb
```
The 'v' doesn't show up in formal releases.
**Checklist**:
> deployment: Generate deb and rpm packages

- proxy/forward_auth.go
When using Pomerium forward auth with nginx, after authentication succeeded it will always redirect to domain root.
This is due to a codepath that is intended for reading Traefik original URL always hit when Traefik's header is missing.
**Checklist**:
> proxy/forward_auth: don't reset forward auth path if X-Forwarded-Uri is not set

- .github/goreleaser.yaml
Fix systemd unit file missing from os packages
**Checklist**:
> ci: ensure systemd unit file is in packages

- go.mod
- go.sum
Pins the version of `/x/sys` to fix an issue with darwin builds and dockertest. 
- https://github.com/pomerium/pomerium/pull/1484 (example)
- https://github.com/ory/dockertest/issues/212#issuecomment-685167115
**Checklist**:
> deployment: pin /x/sys to fix dockertest

- integration/control_plane_test.go
- internal/controlplane/xds_listeners_test.go
- internal/controlplane/xds_routes.go
- internal/controlplane/xds_routes_test.go
This puts the `/.pomerium/admin` endpoint behind authz so only admins have access.
**Checklist**:
> authenticate: protect /.pomerium/admin endpoint

- authenticate/state.go
- authorize/state.go
- cache/cache.go
- cmd/pomerium-cli/cli.go
- integration/control_plane_test.go
- internal/databroker/config_source.go
- internal/telemetry/grpc.go
- internal/telemetry/grpc_test.go
- internal/telemetry/requestid/grpc_client.go
- pkg/grpc/client.go
- pkg/grpcutil/options.go
This adds authentication to the databroker so that a JWT signed by the shared key is required to call methods.
- Fixes #1501 
**Checklist**:
> databroker: require JWT for access

- internal/controlplane/http.go
These endpoints help to debug problems with memory leaks or performance. They will be exposed on the control plane HTTP server, which has a dynamic port. To use this with the pprof tool you'd execute something like:
```bash
go tool pprof 'http://localhost:33125/debug/pprof/heap?gc
```
The dynamic port can be found in the logs:
```json
{"level":"info","port":"33125","time":"2020-10-09T17:57:01Z","message":"HTTP server started"}
```
- #1496 
**Checklist**:
> debug: add pprof endpoints

- .github/workflows/docker-master.yaml
- .vscode/launch.json
- DEBUG.MD
- Dockerfile.debug
- Makefile
- scripts/debug-entrypoint.sh
Provide a build configuration and container suitable for remote debugging.
- Add `make build-debug` command for a debuggable binary
- Add `Dockerfile.debug` and entrypoint for an appropriately configured debug container
- Add `DEBUG.md` for a brief overview of what's in place and how to use it
- Add publishing step for debug image
- Also serves as initial testing of new buildx commands.  Stepping stone to trying out multi-arch.
**Checklist**:
> deplyoment: add debug build / container / docs

- internal/autocert/manager.go
- internal/autocert/manager_test.go
This PR updates the autocert code to periodically check if certificates need to be renewed. Once renewed the XDS config will be updated and envoy should start serving new certificates.
I also added a test to this code by mocking out an ACME api. It doesn't remotely implement the actual protocol, but its enough to verify the certs are getting renewed.
- #1490 
**Checklist**:
> autocert: support certificate renewal

- authenticate/handlers.go
- authenticate/handlers_test.go
- authenticate/state.go
- internal/httputil/errors.go
- internal/httputil/handlers.go
- internal/httputil/handlers_test.go
- internal/urlutil/query_params.go
Small improvements to authenticate that I noticed while making unrelated changes. 
- Generate shared cipher on startup, not per request.
- Use a render json helper.
- Remove unused API path declarations.
- Remove unused queryparam store. 
- No specific issues but the cipher could be a performance (entropy exhaustion?) under stress.
**Checklist**:
> authenticate: remove unused paths, generate cipher at startup, remove qp store

- scripts/embed-envoy.bash
Updates envoy to [v0.16.0](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.16.0) .
I don't see any breaking changes in the changelog or in my light manual testing however please do double check :)
Notable enhancements for us...
- build: enable building envoy arm64 images by buildx tool in x86 CI platform
- ext_authz filter: added support for emitting dynamic metadata for both HTTP and network filters. The emitted dynamic metadata is set by dynamic metadata field in a returned CheckResponse.
- ext_authz filter: added stat_prefix as an optional additional prefix for the statistics emitted from ext_authz HTTP filter.
- ext_authz filter: added support for letting the authorization server instruct Envoy to remove headers from the original request by setting the new field …
> chore(deps): upgrade envoy to v0.16.0

- cache/cache.go
- cache/databroker.go
- cache/databroker_test.go
- pkg/grpcutil/options.go
- pkg/grpcutil/options_test.go
Although we were using an interceptor to enforce the shared key on the databroker it was only being attached to the internal gRPC server, not the control plane gRPC server. This change makes the call to require the signed JWT explicit in the databroker server implementation so that it works for either gRPC server.
**Checklist**:
> fix databroker requiring signed jwt

- docs/reference/readme.md
> [Backport 0-10-0] Remove typo on remove_request_headers docs

- internal/directory/github/github.go
- internal/directory/github/github_test.go
Current code expects gitHub graphql API returns int for id, but actually it is base64 string value.
This fixes the JSON definition and parsing team ID.
Fixes #1554
**Checklist**:
> github: fix retrieving team id with graphql API (#1554)

- config/http.go
- config/http_test.go
- internal/cmd/pomerium/pomerium.go
- pkg/cryptutil/tls.go
- pkg/grpc/client.go
This sets the default HTTP transport to support the `CA` and `CAFile` defined in the config options. This should allow support for custom certs with any OIDC or directory provider.
Closes #1570 
**Checklist**:
> use custom default http transport

- proxy/forward_auth.go
When Pomerium is used in forward-auth configuration, fronting proxies rely on any forwarded headers to be set as response headers. These changes copy _all_ the request headers and writes them as response headers. 
Tested against traefik. 
```yaml
version: "3"
services:
traefik:
image: traefik:v2.3
command:
- "--accesslog=true"
- "--api.insecure=true"
- "--entrypoints.web.address=:80"
- "--entrypoints.websecure.address=:443"
- "--entryPoints.websecure.forwardedHeaders.insecure"
- "--providers.docker.exposedbydefault=false"
- "--providers.docker=true"
ports:
- "80:80"
- "443:443"
- "8080:8080"
volumes:
- /var/run/docker.sock:/var/run/docker.sock
httpbin:
image: kennethreitz/httpbin:latest
labels:
- "traefik.http.middlewares.pomerium.forwardauth.authResponseHeaders=X-Pomerium-Claim-Email,X-Po …
```
> proxy/forward_auth: copy response headers as request headers

- docs/docs/quick-start/kubernetes.md
Fixed the 'cd' command which currently tries to change to a directory which doesn't exist.
> Fix command in Kubernetes Quick start docs

- .devcontainer/envs/nginx.yaml
- authorize/grpc.go
- examples/nginx/httpbin.conf
- examples/nginx/proxy.conf
- proxy/forward_auth.go
Fixes a bug where pomerium would not properly handle special characters. 
- https://github.com/pomerium/pomerium/pull/1563
- Fixes https://github.com/pomerium/pomerium/issues/1559
**Checklist**:
>  forward-auth: fix special character support for nginx 

- cache/cache.go
- go.sum
- internal/controlplane/server.go
- pkg/grpcutil/version.go
This adds version information to the gRPC headers. Clients can retrieve these headers to know which version of Pomerium they're communicating with. (primarily useful for the databroker)
**Checklist**:
> attach version to gRPC server metadata

- pkg/storage/redis/redis.go
Set `MaxIdle` to a non-zero value, preventing aggressive connection termination.
Closes #1600 
https://github.com/gomodule/redigo/issues/534
**Checklist**:
> pkg/storage/redis: Prevent connection churn

- .github/goreleaser.yaml
Update snapshot name template to contain version and commit reference.  
- snapshot names can now be tied to commit history
- multiple snapshots can be made after a release and still be differentiated
- package filenames no longer contain leading `v`
Before:
```bash
• linux packages
• creating                  file=dist/pomerium_v0.11.0-rc1+next-1_amd64.deb
• creating                  file=dist/pomerium-v0.11.0-rc1+next-1.x86_64.rpm
• creating                  file=dist/pomerium_v0.11.0-rc1+next-1_arm64.deb
• creating                  file=dist/pomerium-v0.11.0-rc1+next-1.aarch64.rpm
• creating                  file=dist/pomerium-cli_v0.11.0-rc1+next-1_amd64.deb
• creating                  file=dist/pomerium-cli_v0.11.0-rc1+next-1_x86_64.rpm
• creating …
```
> ci: improve release snapshot name template

- pkg/cryptutil/encrypt.go
- pkg/cryptutil/encrypt_test.go
We've had a few issues where folks running in all-in-one mode with persistent databroker backends would get an error 
```
{"level":"fatal","error":"failed to initialize directory groups: error getting all directory groups: rpc error: code = Unknown desc = chacha20poly1305: message authentication failed","time":"2020-11-22T02:52:09Z","message":"cmd/pomerium"}
```
Which could be a bit more clear. What's going on is that while we try to be helpful and auto-generate the `shared_secret` value in all-in-one mode which is used to encrypt data at rest in the databroker, if shared_secret is not explicitly set, you can end up with decryption errors because the shared key is getting rotated every restart. 
These changes should at least make the decryption error a bit more obvious as to what's going …
> cryptutil: more explicit decryption error

- authorize/authorize.go
- authorize/evaluator/evaluator.go
- authorize/run.go
- internal/cmd/pomerium/pomerium.go
This updates the authorize service so that we can wait until the initial sync is complete before starting the listener in the control plane. Assuming there's a health check on the service, and there's more than one authorize service, this should provide a more consistent experience when restarting the service.
Fixes #1620 
**Checklist**:
> wait for initial sync to complete before starting control plane

- internal/cmd/pomerium/pomerium.go
The ordering on the config source initialization made it so that any databroker config options would not be picked up by the autocert settings. Notably `http_redirect_addr` wasn't being changed. Changing the order so that the databroker is built first fixes the problem.
**Checklist**:
> fix ordering of autocert config source

- pkg/storage/inmemory/inmemory.go
- pkg/storage/inmemory/inmemory_test.go
If `Delete` was called twice for the same record id, and then `ClearDeleted` was called, it would result in a panic because the record would not be found during the second deletion. This PR fixes the issue by using protobuf get methods which are nil-safe. I also added a test which reproduced the original issue.
Fixes #1622 
**Checklist**:
> fix panic when deleting a record twice from the inmemory data store

- internal/identity/oidc/azure/microsoft.go
Microsoft Azure is not OIDC spec compliant and returns an invalid `issuer` claim when the "default" / "common" endpoint is used which would allow both public (any microsoft managed account) or private active directory instance to authenticate.
For example, see the "issuer" on azure's default oidc  well known endpoint.  
https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
```diff
{
+   "issuer":"https://login.microsoftonline.com/{tenantid}/v2.0",
}
```
Since `{tenantid}` is obviously not valid, the provider fails to register and we handle the edge-case where the provider issuer value will not match JWK token's issuer values. 
- Fixes #1605
- https://github.com/MicrosoftDocs/azure-docs/issues/38427#issuecommen …
> microsoft: add support for common endpoint

- authorize/evaluator/evaluator.go
Currently the Azure provider doesn't have email in the user object. However it does have it in the directory user object. This change makes it so that the JWT will contain the directory user email if it is provided.
We likely need to investigate Azure specifically to see if we can also get the email via the User object, but I think this change is helpful.
**Checklist**:
> use the directory email when provided for the jwt

- internal/cmd/pomerium/pomerium.go
- pkg/storage/inmemory/inmemory.go
Because of the way we were building the config it was possible for the config to be updated before we had finished initializing the services. As a result we were using an older config and not detecting the change.
This PR makes it so that we always use the latest config in those places.
I think it may still be racy in a few places, so we should probably change the design slightly. A new design might be:
1. Remove the `OnConfigChange(li)` method on the `ConfigSource` interface, so that's no longer possible to add a listener after construction.
2. Update all the config sources so that they take in a list of listeners. (some already do) Add these immediately so we're guaranteed not to fire a change event before the listener is attached.
3. Update all the config source listeners …
> fix config race

- .github/goreleaser.yaml
Correct the rpm file name for pomerium-cli
n/a
**Checklist**:
> ci: fix pomerium-cli rpm name

- .github/goreleaser.yaml
> [Backport 0-11-0] ci: fix pomerium-cli rpm name

- docs/.vuepress/config.js
Update docs to include v0.11 in the version menu
n/a
**Checklist**:
> docs: add v0.11 link to version menu

- docs/reference/readme.md
- docs/reference/settings.yaml
Add documentation around `allowed_idp_claims`
https://github.com/pomerium/pomerium/pull/1542
**Checklist**:
> docs: add allowed_idp_claims docs

- cmd/pomerium-cli/kubernetes.go
- go.sum
- internal/databroker/server.go
- pkg/cryptutil/tls.go
We have a `GetCertPool` method in `cryptuil` which we weren't using in the databroker. This method has better error checking, so I switched the databroker to use it. I also changed some of the error messages to make it clear that the data needs to be PEM-encoded.
Fixes #1606 
**Checklist**:
> improve ca cert error message, use GetCertPool for databroker storage

- docs/reference/readme.md
- docs/reference/settings.yaml
The phrase `see policy` was somewhat confusing. This PR changes the language to be more clear.
**Checklist**:
> remove "see policy" phrase in settings docs

- .github/goreleaser.yaml
- .github/workflows/release.yaml
- Fix `pomerium-cli` rpm name (for real this time)
- Update `latest` docker image tag creation for multi-arch manifests
#1661 
#1643 
**Checklist**:
> deployment: Fix docker and rpm workflows

- go.sum
- internal/directory/provider.go
Support `allowed_groups` in a policy with self host Gitlab provider. 
**Checklist**:
> internal/directory: use gitlab provider url option

- docs/reference/readme.md
- docs/reference/settings.yaml
- examples/config/config.example.yaml
- examples/config/config.minimal.yaml
- examples/config/policy.example.yaml
- examples/kubernetes/kubernetes-config.yaml
- examples/kubernetes/values.yaml
- examples/nginx/config.yaml
- examples/nginx/docker-compose.yaml
- examples/nginx/httpbin.conf
- examples/nginx/proxy.conf
- examples/traefik/config.yaml
Fixes the nginx example which assumed support for a third party module. Also, renamed the example domains to use the `*.localhost.pomerium.io` which points back to localhost and is consistent with our other examples. 
Fixes #1690 
**Checklist**:
> docs: fix nginx config

- config/options.go
Get rid of `omitempty` when ignoring fields with `yaml:"-"`.  It causes duplicate errors with yaml.Marshal:
`Duplicated key '-'`
https://github.com/pomerium/pomerium-operator/pull/96
https://github.com/go-yaml/yaml/issues/667
**Checklist**:
> config: fix ignored yaml fields

- cmd/pomerium-cli/tcp.go
- go.mod
- go.sum
- internal/authclient/authclient.go
- internal/authclient/authclient_test.go
- internal/authclient/config.go
- internal/cliutil/clitutil.go
- internal/cliutil/jwtcache.go
- internal/cliutil/jwtcache_test.go
- internal/tcptunnel/config.go
- internal/tcptunnel/tcptunnel.go
- internal/tcptunnel/tcptunnel_test.go
This PR adds support for a new `pomerium-cli` command to establish a TCP tunnel via HTTP Connect. Changes:
1. New `tcp` sub-command
2. Using `base36` for file names in a cache directory (was afraid hex might have filenames that were too long, but also wanted to avoid case sensitivity)
3. Add `authclient` package that makes a generic version of our kubernetes browser login flow. A subsequent PR will update the kubernetes command.
4. Add a `cliutil` package that has a cache for storing JWTs.
5. Add a `tcptunnel` package that contains the TCP tunneling code.
The TCP tunnel can either start a local TCP listener, or be called with a Reader+Writer. (the latter is used for stdin/stdout support) When a connection is established an HTTP CONNECT request is made to the server with an authorization …
> TCP client command

- go.sum
- internal/controlplane/xds_routes.go
- internal/controlplane/xds_routes_test.go
Similar to websockets support, we should default to no timeout for established TCP connections.
#1695 
**Checklist**:
> internal/controlplane: 0s default timeout for tcp routes

- cmd/pomerium-cli/kubernetes.go
- cmd/pomerium-cli/main.go
- cmd/pomerium-cli/tcp.go
- go.sum
As part of the TCP tunnel command we added a new `authclient` package. This PR refactors the existing `k8s` command to use that package instead of its own implementation.
**Checklist**:
> k8s cmd: use authclient package

- cmd/pomerium-cli/kubernetes.go
- cmd/pomerium-cli/main.go
- cmd/pomerium-cli/tcp.go
Updates the TCP command to support the same TLS flags as the kubernetes command. Also refactors the kubernetes command so they use the same code path.
**Checklist**:
> add TLS flags for TCP tunnel

- internal/authclient/authclient.go
- internal/tcptunnel/tcptunnel.go
- internal/tcptunnel/tcptunnel_test.go
When using `authclient` with a URL like `https://example.com:443`, the generated URL would contain the port in the redirect_uri. Somewhere along the redirect chain this port would be stripped, and you'd end up going to `https://example.com`, but the HMAC would be invalid because it was generated with the port in place.
This PR changes the code to strip `:443` and `:80` from the URL to open in the browser.
**Checklist**:
> remove :443 or :80 from proxy URLs in authclient

- internal/controlplane/xds_cluster_test.go
- internal/controlplane/xds_clusters.go
- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
Reverts pomerium/pomerium#1734
Apparently these settings don't work even though its what the documentation said and they worked locally for me.
> Revert "set recommended defaults"

- pkg/grpc/session/session.go
- pkg/grpc/user/user.go
When we wrap gRPC errors with `fmt.Errorf` the corresponding gRPC error code is lost. I believe the correct way to add info to a gRPC error is.
```go
status.Errorf(status.Code(err), "msg: %w", err)
```
In this case the added message wasn't very helpful anyway.
(we have code that ignores `NotFound` errors, but since those aren't preserved we're not handling errors properly from the databroker)
**Checklist**:
> fix error wrapping

- config/options.go
- config/trace.go
- config/trace_test.go
- docs/reference/readme.md
- docs/reference/settings.yaml
- go.mod
- go.sum
- internal/envoy/envoy.go
- internal/telemetry/trace/trace.go
This PR adds support for a new Datadog tracing provider in addition to the existing jaeger and zipkin exporters.
**Checklist**:
> telemetry: add support for datadog tracing

- internal/controlplane/xds_routes.go
- internal/controlplane/xds_routes_test.go
Envoy has an idle stream timeout which defaults to 5 minutes if not set. This change sets it to 0 (thus disabling idle timeouts) for TCP or websocket routes.
The upstream timeout is an independent setting and still available via config options.
Before:
After: (was open indefinitely, I manually closed it)
Fixes #1740 
**Checklist**:
> tcp: prevent idle stream timeouts for TCP and Websocket routes

- scripts/embed-envoy.bash
Bumps envoy to 1.16.2. 
- https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.16.2
**Checklist**:
> depedency: update envoy to 1.16.2

- authenticate/handlers_test.go
- authenticate/state.go
- authorize/check_response_test.go
- authorize/grpc_test.go
- authorize/session_test.go
- authorize/state.go
- cmd/pomerium-cli/cli.go
- internal/encoding/jws/jws.go
- internal/sessions/middleware_test.go
- internal/sessions/mock/mock_store.go
- proxy/forward_auth_test.go
- proxy/state.go
Currently to create a new signer we pass in an issuer. Turns out we don't use the issuer for signing.
**Checklist**:
> jws: remove issuer

- .github/workflows/release.yaml
Remove deprecated `set-env` command from build process.
n/a
**Checklist**:
> ci: fix deprecated command in latestTag step

- internal/autocert/manager.go
- internal/cmd/pomerium/pomerium.go
- internal/log/log.go
Ensure we're logging acme challenge errors.  Right now we log the failure but not the reason.  Here's an example with this PR:
```
{"level":"error","time":"2021-01-11T15:53:28-05:00","logger":"acme_client","msg":"challenge failed","service":"autocert","identifier":"authenticate.localhost.pomerium.io","challenge_type":"http-01","status_code":400,"problem_type":"urn:ietf:params:acme:error:dns","error":"No valid IP addresses found for authenticate.localhost.pomerium.io"}
```
- internal/autocert: configure logger for acme client
- internal/autocert: don't change certmagic package defaults
- cmd/pomerium: initialize logging before autocert starts
- internal/log: ensure zap logger level matches zerolog level
Closes #1749 
**Checklist**:
> autocert: improve logging

- internal/directory/google/google.go
- internal/directory/google/google_test.go
Google users don't always have a name. This PR fixes a panic when this happens.
Fixes #1770 
**Checklist**:
> google: fix nil name

- config/options.go
- docs/reference/readme.md
- docs/reference/settings.yaml
- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
This PR adds a new config option for requiring incoming HTTP requests to use the [HAProxy proxy protocol](https://www.haproxy.org/download/1.9/doc/proxy-protocol.txt) (either version 1 or version 2).
**Checklist**:
> add support for proxy protocol on HTTP listener

- go.mod
- go.sum
- internal/identity/oidc/azure/microsoft.go
- internal/identity/oidc/gitlab/gitlab.go
- internal/identity/oidc/google/google.go
- internal/identity/oidc/oidc.go
- internal/identity/oidc/onelogin/onelogin.go
- internal/identity/oidc/userinfo.go
- internal/identity/oidc/userinfo_test.go
Bumps `go-oidc` to v3.  
- https://github.com/coreos/go-oidc/releases/tag/v3.0.0
**Checklist**:
> chore(deps): update oidc to v3

- internal/cmd/pomerium/pomerium.go
Autocert appends certificates to the options config. Those are erased before Validate is called again to avoid increasing the list every time.
Fixes #1792
**Checklist**:
> move file change detection before autocert

- config/constants.go
- config/custom.go
- config/custom_test.go
- config/options.go
- config/policy.go
- docs/reference/readme.md
- docs/reference/settings.yaml
- internal/controlplane/xds_cluster_test.go
- internal/controlplane/xds_clusters.go
Envoy health check configuration option. 
Protobuf config support is ejected into a separate ticket to directly import all Envoy .proto structures. 
https://github.com/pomerium/internal/issues/246
https://github.com/pomerium/internal/issues/264
**Checklist**:
> upstream health check config

- config/options.go
- config/options_test.go
When users configure a persistent databroker storage layer, we should ensure they have a shared key configured to prevent unexpected errors on restart.
fixes #1795
**Checklist**:
> config: require shared key if using redis backed databroker

- config/constants.go
- config/custom.go
- config/options.go
- config/policy.go
- docs/docs/topics/load_balancing.md
- docs/reference/readme.md
- docs/reference/settings.yaml
- internal/cmd/pomerium/pomerium.go
- internal/controlplane/constants.go
- internal/controlplane/server.go
- internal/controlplane/xds.go
- internal/controlplane/xds_cluster_test.go
- internal/controlplane/xds_clusters.go
all options from https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto should be available part of `policy` spec.
**Checklist**:
Pomerium `config.proto` will be handled as part of separate PR to import Envoy's proto specs explicitly.
> expose all envoy cluster options in policy

- internal/controlplane/xds_cluster_test.go
- internal/controlplane/xds_clusters.go
Currently we turn on the STATIC dns family if there is an IP address in the destination endpoint. This changes that behavior so we only enable STATIC dns when *all* endpoints are IP addresses.
> controlplane: only enable STATIC dns when all adresses are IP addresses

- authorize/authorize.go
- authorize/evaluator/evaluator.go
- authorize/grpc.go
- config/options.go
- internal/autocert/manager.go
- internal/controlplane/xds_clusters.go
- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_routes.go
- internal/databroker/config_source.go
- internal/databroker/config_source_test.go
- proxy/proxy.go
The `Policies` slice is erased any time `Validate` is called. Because of this the policies added by the databroker were being inadvertently removed upstream.
This change adds another field called `AdditionalPolicies` to avoid this. I briefly looked into solving this by adding a new field to `config.Config` but it involved changing hundreds of files and I wasn't confident I could make those changes safely.
> config: fix databroker policies

- authenticate/handlers.go
- internal/identity/mock_provider.go
- internal/identity/oauth/github/github.go
- internal/identity/oidc/azure/microsoft.go
- internal/identity/oidc/config.go
- internal/identity/oidc/oidc.go
- internal/identity/providers.go
This PR delays the construction of the OIDC provider so that it can be done only when its used the first time. This will then surface any errors at the point of evaluation. For example in authenticate a user would see a 500 error like:
```
Internal Server Error: identity/oidc: could not connect to oidc: Get "http://keycloak.local/.well-known/openid-configuration": dial tcp: lookup keycloak.local: no such host
```
That error should go away the first time the IDP provider is available.
Fixes #1780
**Checklist**:
> authenticate: delay evaluation of OIDC provider

- pkg/grpc/grpc.go
go:generate doesn't like using double quotes like this.
> fix go:generate for envoy config

- .golangci.yml
- authorize/check_response.go
- authorize/check_response_test.go
- authorize/grpc.go
- config/options.go
- config/options_test.go
- databroker/cache.go
- internal/cmd/pomerium/pomerium.go
- internal/controlplane/xds_clusters.go
- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
- internal/controlplane/xds_routes.go
Update the config `Get...URL()` methods to return errors. This will be required when we support multiple endpoints.
Also fix a bunch of lint issues I inadvertently introduced. I didn't know the:
```
if x, err := ...; err != nil {
return nil, err
} else {
// do something with x
}
```
Pattern was disallowed by linting. Unfortunately this:
```
x, err := ...
if err != nil {
return nil, err
}
// do something with x
```
Is not identical to the original code, it introduces a new variable at a different scope, which can cause issues when we re-use variable names.
#1718
> config: return errors on invalid URLs, fix linting

- .github/workflows/docker-master.yaml
- Makefile
Update makefile and checkout build steps to capture a meaningful version in builds off master.
fixes #1748 
fixes #1747
> ci: fix version metadata in non-releases

- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
In https://github.com/pomerium/pomerium/pull/1835 I accidentally ended up requiring client certificates for any route Pomerium handled. Although this doesn't break anything, since it still allows access even if you don't provide one, it's pretty annoying to have to pick one.
This PR updates the validation context so that it's only added if we are using `ClientCA` or `TLSDownstreamClientCA` for a particular domain.
Fixes #1843
> xds: fix always requiring client certificates

- docs/docs/identity-providers/gitlab.md
Updates GitLab provider docs to reference self-hosted GitLab and provide additional clarity on required scopes.
**Checklist**:
> Update GitLab provider docs

- .github/goreleaser.yaml
Set maintainer field to prevent errors on debian systems.
fixes #1838
> deployment: set maintainer field in packages

- config/config_source.go
Add a mutex to the static config source to fix a data race in the tests.
> config: fix data race

- .github/workflows/backport.yaml
- Allow backports from forks by using the new [`pull_request_target`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) trigger.
- Update title template to look like original PR for a consistent changelog
n/a
> ci: enable backporting from forks

- Makefile
Try to remove some automatically generated code from the way codecov calculates metrics.
n/a
> remove generated code from code coverage metrics

- internal/controlplane/xds_cluster_test.go
- internal/controlplane/xds_clusters.go
- internal/controlplane/xds_routes.go
- internal/controlplane/xds_routes_test.go
- make sure envoy cluster names are unique
- keep cluster metrics name w/o prefix for now, subject to change after https://github.com/pomerium/pomerium-console/issues/645 
Fixes https://github.com/pomerium/internal/issues/290
> unique envoy cluster ids

- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
- internal/controlplane/xds_routes.go
- internal/controlplane/xds_routes_test.go
These changes add the response headers to add to the route virtual host. 
- Fixes #1860
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-virtualhost
> controlplane: add global headers to virtualhost

- pkg/storage/redis/redis.go
- pkg/storage/redis/redis_test.go
The redis implementation of the databroker is not currently incrementing the record version when a record is deleted. Because the version doesn't change, the record change isn't detected by sync and consumers will only pick up the change on restart.
> redis: fix deletion versioning

- config/config_source.go
Support dynamic reloading of the certificate file list in `certs`.
Tweaking docs regarding hot reloading in a follow up.
#1775
> config: add CertificateFiles to FileWatcherSource list

- authorize/grpc.go
- go.sum
- internal/controlplane/grpc_accesslog.go
Remove the query string from the logs. Envoy adds them to `path` which is confusing. I don't think they're really needed in the logs, so this removes them.
> logs: strip query string

- internal/identity/oidc/onelogin/onelogin.go
The newer v2 OneLogin OIDC Connect API no longer supports `offline_access`:
> Version 2.0 only.
> When this scope is supplied with Password Grant a refresh_token allowing offline access will be returned.
> Using this scope with Implicit or Authorization Code flow will cause an error.
This PR updates our onelogin code to remove offline access for the v2 URL.
- #1885
> onelogin: fix default scopes for v2

- .github/workflows/docker-master.yaml
- .github/workflows/release.yaml
Pin the release testing environment to the latest version release rather than master to ensure compatibility.
n/a
> ci: deploy latest release to test environment

- docs/docs/upgrading.md
Update the upgrading guide to explicitly mention client side service accounts.
> docs: add breaking sa changes in v0.13

- docs/docs/topics/programmatic-access.md
The progammatic login docs said to pass `redirect_uri` but the actual expected query param is `pomerium_redirect_uri`.
Fixes #1877
> docs: fix query param name

- internal/directory/google/google.go
The endpoint URL for google changed when we upgraded to the latest version of the library, but we didn't update the default URL, so it was querying the wrong endpoint.
Fixes #1926
> google: fix default provider URL

- config/policy.go
- config/policy_test.go
When parsing config from protobuf, we are requiring `to` to contain destinations even when there is a redirect configured.
n/a
> config: fix redirect routes from protobuf

- config/metrics.go
- internal/httputil/handlers.go
- internal/middleware/middleware.go
- internal/middleware/middleware_test.go
- Equalize the the length of the inputs to avoid timing attack
- Move the basic auth handler into the middleware package
- Add more tests
- Fixes #1933 
- Related to #1917
> middleware: basic auth equalize lengths of input

- Makefile
- internal/autocert/manager_test.go
This test would fluctuate on test coverage because the ticker didn't always fire before completing. By making the ticker fire faster, it should always happen at least once before the test loop finishes.
> autocert: remove non-determinism

- config/metrics.go
- internal/telemetry/metrics/helpers_test.go
- internal/telemetry/metrics/info.go
- internal/telemetry/metrics/info_test.go
- internal/telemetry/metrics/registry.go
- pkg/metrics/constants.go
- add hostname
- move metrics and labels into separate public package to refer to from console
> use build_info as liveness gauge metric

- .github/workflows/test.yaml
Caches the binaries used to make the build including opa, mispell, etc. 
- #1938
> ci: cache build and test binaries

- proxy/handlers.go
- proxy/proxy.go
- proxy/state.go
Due to the addition of a CSRF check we can no longer sign out directly from the proxy, so I updated the handler to redirect to the dashboard, which has a logout button.
> proxy: redirect to dashboard for logout

- config/constants.go
- config/options.go
- config/options_test.go
So we can use these policy hooks in other projects to fill config options.
> config: expose viper policy hooks

- cmd/pomerium/main.go
Right now we hit a `Fatal()` log statement for any error reason at exit, including context cancellation resulting from various OS signals.  This results in a non-zero exit code even when the termination was requested gracefully.
This PR checks if the underlying error is a `context.Canceled` and will exit normally in that case.  This should cover most normal shutdowns such as SIGTERM.
Fixes #1935
> cmd/pomerium: exit 0 for normal shutdown

- authenticate/authenticate.go
- authorize/authorize.go
- config/config.go
- config/config_source.go
- config/options.go
- internal/databroker/config_source.go
- internal/telemetry/metrics/info.go
- internal/telemetry/metrics/info_test.go
- internal/telemetry/metrics/registry.go
- pkg/metrics/constants.go
- proxy/proxy.go
Add a log entry whenever the config changes. We have separate checksums for different config sources: `local` and `databroker`.
> config: log config source changes

- go.mod
- internal/envoy/envoy.go
- internal/telemetry/metrics/processes.go
- internal/telemetry/metrics/processes_test.go
Add a process collector to collect process metrics for envoy. This is based on the process collector in prometheus but compatible with our opencensus config.
> telemetry: add process collector for envoy

- config/policy.go
- docs/reference/readme.md
- docs/reference/settings.yaml
- go.mod
- go.sum
- internal/controlplane/luascripts/rewrite-headers.lua
- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
- internal/controlplane/xds_lua.go
- internal/controlplane/xds_lua_test.go
- internal/controlplane/xds_routes.go
- internal/controlplane/xds_routes_test.go
Add a new `rewrite_response_headers` option which allows users to modify response headers before they are returned to the user. Similar to http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect.
Only prefix matching is supported via lua. There's work being done in envoy to support regex and other matchers natively.
I also added a unit test for the lua code using a pure-go lua implementation to simulate a call from envoy.
> config: add rewrite_response_headers option

- internal/directory/ping/api.go
- internal/directory/ping/config.go
- internal/directory/ping/provider.go
- internal/directory/ping/provider_test.go
- internal/directory/provider.go
- internal/identity/oidc/ping/ping.go
- internal/identity/providers.go
Implement an identity and directory provider for Ping One. Configuration is:
```yaml
idp_provider: "ping"
idp_provider_url: "https://auth.pingone.com/ENDPOINT_ID/as"
idp_client_id: "OIDC_CLIENT_ID"
idp_client_secret: "OIDC_CLIENT_SECRET"
idp_service_account: |
{
"client_id": "WORKER_CLIENT_ID",
"client_secret": "WORKER_CLIENT_SECRET"
}
```
(service account can also be a base64 encoded json object)
I will update the documentation in a separate PR.
- #1971
> ping: identity and directory providers

- internal/identity/oidc/userinfo.go
- internal/identity/oidc/userinfo_test.go
Some providers (ping) return a `mail` claim instead of `email`. This change will copy the claim into `email` if there's nothing there and `mail` looks like an email address.
> identity: infer email from mail claim

- authorize/evaluator/opa/policy/authz.rego
- authorize/evaluator/opa_test.go
Lower the JWT expiration to 5 minutes past the current time.
> authorize: set JWT to expire after 5 minutes

- internal/telemetry/metrics/processes.go
[`CPUTime()`](https://pkg.go.dev/github.com/prometheus/procfs@v0.2.0#ProcStat.CPUTime) is already a SUM
> Fix process cpu usage metric

- docs/reference/readme.md
- docs/reference/settings.yaml
- go.mod
- go.sum
- internal/testutil/redis.go
- pkg/storage/redis/client.go
- pkg/storage/redis/client_test.go
- pkg/storage/redis/redis.go
- pkg/storage/redis/redis_test.go
Adds support for redis cluster URLs. Redis cluster doesn't seem to support transactions across multiple nodes, so we have to ensure all keys are stored in the same slot.
> redis: add redis cluster support

- authorize/check_response.go
- authorize/check_response_test.go
- authorize/grpc.go
- authorize/grpc_test.go
- authorize/session_test.go
- go.mod
- go.sum
- internal/cmd/pomerium/pomerium.go
- internal/controlplane/grpc_accesslog.go
- internal/controlplane/xds.go
- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
- internal/controlplane/xds_tracing.go
- internal/envoy/envoy.go
- internal/envoy/envoy_test.go
- scripts/get-envoy.bash
Upgrade envoy to v1.17.1. The `v2` API is deprecated, so we switch the authorize service to the v3 API as well as several typed configs. Tracing also had to move to the control plane instead of the bootstrap.
> envoy: upgrade to v1.17.1

- internal/envoy/embed.go
- internal/envoy/envoy.go
We should be able to have tighter permissions on the embedded envoy binary and config file. This changes them from `755` to `700`.
> envoy: restrict permissions on embedded envoy binary

- authenticate/authenticate.go
- authenticate/authenticate_test.go
- authenticate/handlers.go
- authenticate/handlers_test.go
- authenticate/state.go
- authorize/authorize.go
- authorize/authorize_test.go
- authorize/check_response_test.go
- authorize/evaluator/evaluator.go
- authorize/evaluator/evaluator_test.go
- authorize/grpc.go
- authorize/grpc_test.go
- config/options.go
- config/options_test.go
- internal/autocert/manager.go
- internal/controlplane/xds_listeners.go
- internal/controlplane/xds_listeners_test.go
- internal/controlplane/xds_routes.go
- internal/controlplane/xds_routes_test.go
- proxy/handlers.go
- proxy/proxy.go
- proxy/proxy_test.go
- proxy/state.go
As part of removing side-effects from config option validation, this PR uses `Get...` methods for `AuthenticateURL`, `SignOutURL` and `ForwardAuthURL`.
> config: use getters for authenticate, signout and forward auth urls

- authorize/evaluator/opa/policy/authz.rego
Signed-off-by: Nandor Kracser <bonifaido@gmail.com>
A lot of OIDC providers offer the de-facto "groups" claim, which lists a user's existing group memberships. These are (incomplete list):
- [OneLogin](https://developers.onelogin.com/openid-connect/scopes)
- [Dex](https://dexidp.io/docs/custom-scopes-claims-clients/#scopes)
- [okta](https://developer.okta.com/docs/guides/customize-tokens-groups-claim/add-groups-claim-org-as/)
- [Auth0](https://auth0.com/docs/extensions/authorization-extension?_ga=2.80662615.1996932338.1615212854-499469682.1614950441)
This way group information can be sent back to the backend service via `X-Pomerium-Claim-Groups`, grabbing the `groups` claim from the ID token.
A documentation update would be needed if this is accepted, but first I wanted to make sure this …
> oidc: use groups claim from ID token if present

- internal/autocert/manager.go
- internal/telemetry/metrics/autocert.go
- internal/telemetry/metrics/registry.go
- pkg/metrics/constants.go
Add additional metrics for autocert to track the number of renewals, the total number of autocert certificates and the next expiration.
Fixes #1825
> autocert: add metrics for renewal count, total and next expiration

- pkg/cryptutil/dek.go
- pkg/cryptutil/dek_test.go
- pkg/cryptutil/kek.go
- pkg/cryptutil/kek_test.go
Add `KeyEncryptionKey` and `DataEncryptionKey` for performing envelope encryption.
> cryptutil: add envelope encryption w/key encryption key and data encryption key

- pkg/protoutil/transform.go
- pkg/protoutil/transform_test.go
Add a new `Transform` function to protoutil. This takes in a protobuf message and recursively calls a transformation value on each (basic) value. This could be used to encrypt every string in a protobuf message.
> protoutil: add generic transformer

- config/options.go
- config/validate.go
- internal/controlplane/xds_listeners.go
- internal/registry/constants.go
- internal/registry/reporter.go
- internal/registry/reporter_test.go
`metrics_address` logic [was previously altered](https://github.com/pomerium/pomerium/pull/1939/files#diff-22920b1b96bb2c68825bb4d927afa5c33804be1939b99d76476e5e307ea669eeR49-R51) to only allow IP addresses.
This field is also used by metrics reporter, that previously relied on a hostname to determine the metrics scraping address it can advertise via service registry. 
There's no uniform way for an application to know its DNS hostname, which is why it has to be supplied externally.
> support host:port in metrics_address

- config/options.go
I set `use_proxy_protocol` to be true in my yaml config. Envoy didn't use proxy protocol albeit. Both the documents and https://github.com/pomerium/pomerium/pull/1777 hint the name should be use_proxy_protocol.
> change require_proxy_protocol to use_proxy_protocol

- pkg/storage/redis/redis_test.go
There are issues running REDIS cluster tests on MacOS. This PR restricts these tests to just Linux.
> skip REDIS cluster test if GOOS != linux

- internal/directory/provider.go
The document about how to set gitlab.com as a idp provider https://www.pomerium.com/docs/identity-providers/gitlab.html#gitlab-com didn't mention we need to specify `idp_provider_url: "https://gitlab.com/"` in the config file.
I only set `id_provider`, `idp_client_id`, `idp_client_secret` and `idp_service_account` as in the document. I was baffled  by the error 
```
8:54PM WRN failed to refresh directory users and groups error="gitlab: error querying groups: Get \"/api/v4/groups\": unsupported protocol scheme \"\"" service=identity_manager
```
This error is due to pomerium actually tried to request url `/api/v4/groups` instead of `https://gitlab.com/api/v4/groups`. I think it is more reasonable to set a default endpoint `https://gitlab.com/` for gitlab.
> add default gitlab url

- authenticate/handlers.go
- authenticate/handlers_test.go
- authenticate/middleware.go
- internal/frontend/assets/html/userInfo.html
- proxy/handlers.go
- proxy/state.go
Ensure redirect parameter signatures are validated for `/.pomerium/*` routes.
#2046 
Fixes https://github.com/pomerium/pomerium/security/advisories/GHSA-fv82-r8qv-ch4v
> authenticate: validate signature on /.pomerium, /.pomerium/sign_in and /.pomerium/sign_out

- authenticate/handlers.go
- proxy/handlers.go
Remove the default redirect to `/` when logging out from the proxy. We already have code in authenticate to show a `OK: user logged out` message. 
Also fix an issue where the logout button was pointing to the authenticate root path instead of `/.pomerium/sign_out`.
> authenticate: fix default sign out url

- docs/docs/community/readme.md
It seems like Slack now supports nearly-never expiring invite URLs, which is a better option than slack-in or slackin-extended.
https://github.com/pomerium/pomerium/issues/2014
> docs: update community slack link

- databroker/databroker.go
- internal/databroker/config.go
- pkg/storage/inmemory/stream.go
- pkg/storage/redis/stream.go
Updating the installation id was causing the in-memory databroker store to get recreated. This would then close the backend, but corresponding streams weren't being closed. This change fixes it so they're closed explicitly for both the in-memory and redis (which was less prone to the issue because it also periodically polls). I also removed the installation id from the databroker server config, because we actually only use it in the telemetry package, so there's no need to use it directly.
> databroker: remove unused installation id, close streams when backend is closed

- config/crypt.go
- pkg/cryptutil/kek.go
- pkg/cryptutil/kek_test.go
- pkg/cryptutil/x509.go
- pkg/cryptutil/x509_test.go
Several changes:
1. Generate the key encryption key (KEK) id using the public KEK bytes instead of the private KEK bytes. This way given a public KEK, you can know the key id without needing the private KEK.
2. Add support for marshaling private KEKs via `MarshalPKCS8PrivateKey` similar to ed25519 keys, but with a different algorithm id.
3. Add support for marshaling public KEKs via `MarshalPKIXPublicKey` similar to ed25519 keys, but with a differnet algorithm id.
This should be interoperable with the standard format used by `openssl genpkey` and allows us to store KEKs in a predictable way.
> cryptutil: always use kek public id, add x509 support

- .vscode/launch.json
- authorize/sync.go
- internal/databroker/config_source.go
- internal/identity/manager/sync.go
- internal/telemetry/metrics/const.go
- internal/telemetry/metrics/info.go
- internal/telemetry/metrics/info_test.go
- internal/telemetry/metrics/registry.go
- pkg/grpc/databroker/syncer.go
- pkg/grpc/databroker/syncer_test.go
- pkg/metrics/constants.go
adds two new metrics: 
- `pomerium_config_db_errors{config_id="dashboard"}` - amount of errors, including routes skipped while parsing this config 
- `pomerium_config_db_version{config_id="dashboard"}` - current databroker version that was applied
https://github.com/pomerium/pomerium-console/issues/708
> config related metrics

- authenticate/handlers.go
- authenticate/handlers_test.go
- authenticate/middleware.go
- authorize/check_response.go
- internal/httputil/reproxy/reproxy.go
- internal/middleware/middleware.go
- internal/middleware/middleware_test.go
- internal/urlutil/signed.go
- internal/urlutil/signed_test.go
- pkg/cryptutil/hmac.go
- pkg/cryptutil/hmac_test.go
- proxy/state.go
Update the HMAC methods in cryptutil to takes `[]byte` instead of `string`. Also update the signed URL to take in `[]byte`.
> cryptutil: use bytes for hmac

- internal/directory/auth0/auth0.go
- internal/directory/auth0/auth0_test.go
- internal/directory/azure/azure.go
- internal/directory/azure/azure_test.go
- internal/directory/azure/delta.go
- internal/directory/github/github.go
- internal/directory/github/github_test.go
- internal/directory/gitlab/gitlab.go
- internal/directory/gitlab/gitlab_test.go
- internal/directory/google/google.go
- internal/directory/google/google_test.go
- internal/directory/okta/okta.go
- internal/directory/okta/okta_test.go
- internal/directory/onelogin/onelogin.go
- internal/directory/onelogin/onelogin_test.go
- internal/sessions/state.go
- pkg/grpc/databroker/databroker.go
- pkg/storage/redis/redis.go
Remove the provider name from the user id. For example `okta/12345` will now be `12345`.
This was originally added to perhaps support multiple providers, but ended up causing more problems than it was worth. We can solve multiple providers in a different way (if we ever pursue it).
I also updated the key in redis so all users will have to login again and get the new ids.
Fixes #2025
> directory: remove provider from user id

- authenticate/handlers.go
- authenticate/middleware.go
- authenticate/state.go
- authorize/check_response.go
- authorize/state.go
- internal/middleware/middleware.go
- proxy/state.go
We've been using the `SharedKey` directly from the options, which means we were actually HMACing with the base64 string, not the bytes themselves. This change fixes that.
> crypto: use actual bytes of shared secret, not the base64 encoded representation

- config/http.go
- config/http_test.go
This newer option was forgotten when we implemented the policy transport. It will now use the `tls_custom_ca` when set in the options.
There's also `tls_downstream_client_ca`, but that should still be handled by envoy.
- #2076
> config: use tls_custom_ca from policy when available

- pkg/storage/encrypted.go
- pkg/storage/encrypted_test.go
Fixes version and modified fields not propagating back when encrypted storage is used, that lead to zero version returned in record of GRPC `databroker.Put` call. 
This is a quick fix, probably a better approach would be to alter databroker API so that it would not mutate input arguments and rather return a changed record.
> propagate changes back from encrypted backend

- config/envoyconfig/bootstrap.go
- config/envoyconfig/bootstrap_test.go
- config/envoyconfig/envoyconfig.go
- internal/cmd/pomerium/pomerium.go
- internal/controlplane/server.go
- internal/controlplane/xds.go
- internal/envoy/envoy.go
- internal/envoy/envoy_test.go
- internal/testutil/testutil.go
Move bootstrap configuration stored in the internal `envoy` package to the public `envoyconfig` package. It makes more sense to be here and will make constructing a complete, non-xds bootstrap config easier.
> envoyconfig: move most bootstrap config to shared package

- config/options.go
Removes a legacy mutation on the `address` parameter which breaks GRPC TLS lookup.  See #2091 for additional context.
Closes #2091
> config: don't change address value on databroker or authorize

- scripts/embed-envoy.bash
- Upgrade envoy to v1.16.3
- Tweak embed script to source from our own binary repo
NB: OSX build/test will fail due to getenvoy not having darwin `v1.16.3` yet.
n/a
> deps: upgrade envoy to 1.16.3

- authorize/evaluator/opa/policy/authz.rego
- authorize/evaluator/opa_test.go
At some point we lost the ability to pass arbitrary IDP claims as headers or in the attestation header. This re-adds them.
The `base_jwt_claims` will take precedence.
- #1588
> authorize: support arbitrary jwt claims

- .github/workflows/release.yaml
- docs/docs/installation.md
- Remove bintray publishing due to upcoming deprecation
- Publish RPM and DEB packages to cloudsmith repo
- Add basic docs on using the OS package repos
n/a
> deployment: Publish OS packages to cloudsmith

- .github/goreleaser.yaml
- scripts/get-envoy.bash
- Refactor goreleaser hooks for split get/embed scripts
- Update `get-envoy` script to pull from our binary source
- Update `get-envoy` script to accept an optional target directory env var
https://github.com/pomerium/pomerium/pull/1908
> deployment: update get-envoy script and release hooks

- internal/tcptunnel/tcptunnel.go
Remove tun.cfg.dstHost from jwtCacheKey. 
Users that uses an `--pomerium-url` does only need one browser popup per auth cycle (default 14 hours)
This is handy when running an Ansible playbook or similar tools which makes you to connect to multiple hosts and now get one browser popup per server per auth cycle.
Mor information can be found in the related issue.
Implements #2100
> Drop tun.cfg.dstHost from jwtCacheKey

- authenticate/authenticate.go
- authenticate/authenticate_test.go
- authenticate/state.go
- authorize/authorize.go
- authorize/evaluator/evaluator.go
- authorize/state.go
- config/envoyconfig/listeners.go
- config/options.go
- config/options_test.go
- databroker/cache.go
- databroker/databroker.go
- internal/autocert/manager.go
- internal/databroker/config.go
- internal/databroker/config_source.go
- internal/httputil/reproxy/reproxy.go
- internal/registry/reporter.go
- proxy/proxy.go
- proxy/proxy_test.go
- proxy/state.go
Removes the remaining validate side effects for options:
- defaulting shared key in `all` mode
- defaulting gRPC addr in `all` mode
- enabling insecure gRPC in `all` mode
- returning an empty map if `disable` is set in the `SetResponseHeaders`
- use the IDP service account for google cloud serverless
- returning 1 for QPS if < 1
> config: remove validate side effects

- authorize/check_response.go
We started requiring this URL to be signed with https://github.com/pomerium/pomerium/pull/2048. Unfortunately we didn't update the "session details" link when you get a 403 error.
Fixes #2117
> authorize: fix unsigned URL

- authorize/evaluator/evaluator.go
- authorize/evaluator/opa/policy/authz.rego
- authorize/evaluator/opa_test.go
With the way this rego was written if there were no entries in the main policy `allowed_x` lists, we wouldn't actually concatenate the sub policy lists. By using a generator on the main array we should always default to at least an empty array which allows the sub policies to be handled properly. I added a test to make sure this works now.
> authorize: fix empty sub policy arrays

- config/envoyconfig/listeners.go
- config/envoyconfig/listeners_test.go
- internal/controlplane/xdsmgr/xdsmgr.go
It appears that envoy doesn't allow you to update a listener address via LDS, so instead we'll name the ingress with a hash of the address. The `xdsmgr` will then remove the previous one and add the new one, thus allowing us to change the metrics address at runtime.
> envoyconfig: fix metrics ingress listener name

- scripts/get-envoy.bash
Currently envoy is re-downloaded on every `make build`, this changes it to use whatever was previously cached.
> use cached envoy

- config/http.go
- config/http_test.go
- internal/httputil/headers.go
- internal/httputil/reproxy/reproxy.go
`kubectl` uses SPDY for `exec`. When proxying through the control plane we end up using HTTP/2, and the proxy rejects the `Upgrade` header, because SPDY can't be used with HTTP/2 (error is [here](https://github.com/golang/net/blob/0fccb6fa2b5ce302a9da5afc2513d351bd175889/http2/server.go#L2953)). This PR disables support for HTTP/2 in the control plane reverse proxy if SPDY is being used.
This should fix `kubectl exec`:
```bash
† kubectl --context=via-pomerium exec busybox1 -i -t -- /bin/sh
/ # echo hi
hi
/ # 
```
Fixes #2126
> httputil: fix SPDY support with reverse proxy

- authorize/log.go
This removes the duplicate `message` key in the authorize access logs. Message is both the default key for zero log, and was being used to set the reply message. This makes that explicit.
> authorize: audit log had duplicate "message" key

- pkg/grpc/client.go
Allow custom options to `NewGRPCClientConn`.
> let pass custom dial opts

- authorize/check_response.go
- authorize/check_response_test.go
- authorize/grpc.go
- internal/frontend/assets/html/error.go.html
- internal/httputil/errors.go
- internal/httputil/handlers.go
- internal/httputil/httputil.go
This PR adds the request id to all debugable error pages, and  makes sure that both go and envoy based control planes are leveraging the same http error template code. 
control plane: add request id to all error pages
- use a single http error handler for both envoy and go control plane
- add http lib style status text for our custom statuses.
Closes https://github.com/pomerium/pomerium-console/issues/424
> control plane: add request id to all error pages

- authorize/authorize.go
- authorize/evaluator/store.go
- authorize/grpc.go
- authorize/sync.go
- pkg/grpc/databroker/syncer.go
It looks like the way we're doing locking with the OPA evaluator store is causing deadlocks. I misunderstood how the `RWMutex` works, and it turns out it can't reliably be used recursively:
> If a goroutine holds a RWMutex for reading and another goroutine might
> call Lock, no goroutine should expect to be able to acquire a read lock
> until the initial read lock is released. In particular, this prohibits
> recursive read locking. This is to ensure that the lock eventually becomes
> available; a blocked Lock call excludes new readers from acquiring the
> lock.
I believe the deadlock happens like this:
1. We perform an evaluation which takes a read-only transaction to the store `RLock`
2. During sync we update a record `Lock`
3. During policy evaluation we attempt to retrieve a record …
> authorize: refactor store locking

- Dockerfile.debug
Currently the debug image is missing some glibc packages and executing envoy will error out with a misleading message.  This adds the missing packages.
n/a
> deployment: update alpine debug image dependencies

- docs/docs/topics/programmatic-access.md
In programmatic access, we support an alternate format for software which requires authorization headers to be `Bearer` type.  Update the docs to mention this.
n/a
> docs: mention alternative bearer token header format

- internal/envoy/embed.go
- internal/envoy/envoy.go
We currently optimize for startup time and attempt to cache the envoy binary once we've extracted it on a system.  This creates starting security conditions that are hard to validate even with checksumming of the binary and atomic creation.
Changes:
- switch to a randomized subdirectory created on-demand, to help ensure we are running the same binary we checksum
- clean the entire base directory before extraction, so that we don't consume additional disk space every time we start on a system
- always extract a fresh copy of envoy
https://github.com/pomerium/pomerium/pull/1908
> internal/envoy: always extract envoy

- docs/reference/readme.md
- docs/reference/settings.yaml
Add an info block recommending setting these headers. It's not safe for us to choose a default value for them.
> docs: add info note to set_response_headers

- docs/reference/readme.md
- docs/reference/settings.yaml
Provides an example of how to generate a signing key and links to the script to generate other algorithm types. 
Fixes #2080
> docs: add inline instructions to generate signing-key

- Makefile
It looks like our metadata ldflags were getting overridden during `make build`, resulting in `v0.0.0` for the version in non-release builds.
n/a
> deployment: fix empty version on master builds

- config/envoyconfig/clusters.go
- config/envoyconfig/clusters_test.go
- docs/docs/community/security.md
Pomerium 0.13 used Envoy v1.16's pretty liberal upstream cipher suite. Envoy 1.17 changed that cipher suite to be essentially TLS 1.13. This reverts that change.
Fixes #2195
> proxy / controplane: use old upstream cipher suite

- config/envoyconfig/clusters.go
- internal/controlplane/server.go
- pkg/grpc/health.go
Previously if multiple authorize endpoints are defined and one of them is down, it would continue receive traffic based on default round-robin request load balancing policy, that would result 1/n % of HTTP requests to fail. 
This PR adds GRPC health check for `pomerium-authorize` GRPC cluster, that ensures reachability, and outlier detection that ensures authorize endpoint would be ejected if misconfigured. 
Fixes https://github.com/pomerium/internal/issues/399
> authorize: grpc health check

- authenticate/state.go
- internal/sessions/cookie/cookie_store.go
- proxy/state.go
Reverts pomerium/pomerium#2159
In certain situations, when Pomerium is paired with additional single-sign-on (SSO) systems (e.g. SAML) which perform a `POST` following authentication, the `_pomerium` session could would not be set, and would result in an erroneous / blocking redirect flow loop.
We should allow user's to set their desired `SameSite` value as an option, and default to None.
```
Q: What is the Lax + POST mitigation?
This is a specific exception made to account for existing cookie usage on some Single Sign-On implementations where a CSRF token is expected on a cross-site POST request. This is purely a temporary solution and will be removed in the future. It does not add any new behavior, but instead is just not applying the new SameSite=Lax default in certain scenarios. …
```
> Revert "authenticate,proxy: add same site lax to cookies"

- pkg/policy/criteria/domains.go
- pkg/policy/criteria/emails.go
- pkg/policy/criteria/groups.go
- pkg/policy/criteria/users.go
- pkg/policy/generator/conditionals.go
- pkg/policy/generator/generator.go
- pkg/policy/generator/generator_test.go
- pkg/policy/parser/json.go
- pkg/policy/policy.go
- pkg/policy/rules/rules.go
Several changes for the Pomerium Policy Language:
1. Bubble up the values from rules to `and`, `or`, `not` and then to `allow` and `deny`. This is necessary because `deny` returns an HTTP status code and message.
2. Fix several rules where we were using `=` but should've used `==`
3. Combine all the `allow` or `deny` rules into a complete definition using else blocks
4. Fix the databroker helpers so that they don't allow null values. We were doing this in authz but it didn't get ported over. Also use `=` instead of `:=`.
5. There was a bug in the `user` rule. It should be `user.id` not `user_id`.
6. Sort the rules and assign them locations so we get deterministic ordering of rules in the formatted output.
> PPL: bubble up values, bug fixes

- config/policy.go
- config/policy_ppl.go
- config/policy_ppl_test.go
Add a new `ToPPL` function to config policies to convert a policy to the Pomerium Policy Language. This is an intermediate step necessary to convert the policy to rego.
This PPL script should implement all of the functionality related to policy enforcement currently in `authz.rego` (but not the header generation which will be handled by a separate rego script)
> ppl: convert config policy to ppl

- config/envoyconfig/http_connection_manager.go
- config/envoyconfig/listeners.go
- config/envoyconfig/listeners_test.go
If envoy fails to match a request to a route it responds with a "local" reply. This PR adds a local reply configuration to add our global response headers to this reply.
Fixes #2110
> envoy: add global response headers to local replies

- docs/.vuepress/config.js
- docs/.vuepress/public/_redirects
- docs/guides/code-server.md
Updates documentation to use the correct name for code-server
Fixes #2222
> fix(docs): use correct name for code-server

- docs/docs/architecture.md
The was the only image on this page that was also a link to the image, which failed with a 404 (which is the default Nginx 404 page, BTW).
> docs: rm broken link

- authorize/evaluator/custom.go
- authorize/evaluator/custom_test.go
- authorize/evaluator/evaluator.go
Fix a panic in custom rego. If a different package name was used the result set was empty which cause an out of bounds panic.
> authorize: fix custom rego panic

- docs/.vuepress/public/_redirects
Adds a redirect to an old reference page currently referenced on the helm chart. 
https://github.com/pomerium/pomerium-helm/blob/master/charts/pomerium/values.yaml
> docs: update _redirects

- go.mod
- go.sum
- internal/envoy/envoy.go
- internal/envoy/envoy_darwin.go
- internal/envoy/envoy_linux.go
- internal/envoy/envoy_notlinux.go
- internal/envoy/envoy_other.go
If envoy exits unexpectedly, we should use `log.Fatal` to exit as well. This PR also fixes a bug with hot-restart. The `restart-epoch` was supposed to start at 1 for the first restart, not 0.
Fixes https://github.com/pomerium/internal/issues/414
> envoy: exit if envoy exits

- config/policy_ppl.go
- config/policy_ppl_test.go
The way we were generating the PPL for allowed claims was wrong. It was supposed to use the `SubPath` for each key (ie `claims/family_name`), and the value was supposed to be each element of the array (so `[Smith,Jones]` creates two separate claims rules.
Fixes #2241
> policy: fix allowed idp claims PPL generation

- config/envoyconfig/clusters.go
- config/envoyconfig/clusters_test.go
- config/envoyconfig/envoyconfig.go
- docs/docs/upgrading.md
Fallback to the custom ca defined in the global options when no policy ca is defined. 
There's a non-trivial chance this may break existing users, since previously we only validated internal connections between pomerium services using this certificate authority, and now we will be validating all upstream services.
Fixes https://github.com/pomerium/internal/issues/417
> envoyconfig: fallback to global custom ca when no policy ca is defined

- Makefile
- go.mod
- go.sum
- internal/envoy/envoy.go
The darwin/arm64 build was failing with:
```bash
../../../../pkg/mod/github.com/shirou/gopsutil@v0.0.0-20190731134726-d80c43f9c984/process/process_darwin.go:595:34: undefined: KinfoProc
```
This should fix the issue by using the `v3` API and removing `getenvoy` (which is no longer used?).
> darwin: use gopsutil v3 to fix arm issue

- .github/goreleaser.yaml
- internal/envoy/envoy.go
- scripts/get-envoy.bash
We don't currently have a build of envoy for darwin/arm64 (ie m1), but we can run the x86 build using rosetta. This updates the envoy script and run command.
> darwin: use x86 envoy build for arm64

- config/options.go
The `SharedKey` field has struct tags that are `shared_secret` which can result in confusing error messages to users.
`SharedKey` == `shared_secret`
https://github.com/pomerium/pomerium/blob/ca5c78587efc5de3f593b5a32971ed8efa1a96e6/config/options.go#L73-L76
- https://github.com/pomerium/pomerium/pull/2109
> options: s/shared-key/shared secret

- config/options.go
- docs/docs/topics/load-balancing.md
- docs/reference/readme.md
- docs/reference/settings.yaml
Warn if some config keys cannot be recognized.
Also fixes few typos in the docs. 
Fixes https://github.com/pomerium/internal/issues/358 https://github.com/pomerium/internal/issues/413
> config: warn about unrecognized keys 

- authorize/evaluator/evaluator.go
- authorize/evaluator/evaluator_test.go
- config/envoyconfig/routes.go
- internal/httputil/headers.go
If an incoming request contains X-Pomerium-Jwt-Assertion and does not contain X-Pomerium-Jwt-Assertion-For, copy X-Pomerium-Jwt-Assertion into X-Pomerium-Jwt-Assertion-For when proxying to the upstream.
Implements https://github.com/pomerium/internal/issues/410
> authorize: preserve original context

- internal/envoy/envoy.go
- internal/envoy/envoy_darwin.go
- internal/envoy/envoy_linux.go
- internal/envoy/envoy_other.go
- internal/envoy/misc.go
Disable envoy hot-reload for MacOS, because it doesn't appear to work. Instead we kill the previous process and start a brand new.
Also change the fatal "error retrieving subprocess status" to an error. For some reason on MacOS this will sometimes return "signal: killed". My search on google didn't turn up anything. 
Fixes https://github.com/pomerium/internal/issues/424
Fixes https://github.com/pomerium/pomerium/issues/2212
> envoy: disable hot-reload for macos

- authorize/evaluator/headers_evaluator_test.go
- authorize/evaluator/opa/policy/headers.rego
round timestamp for 'exp' and 'iat' claim that some SDKs expect to be whole unix seconds.
#2248
> authorize: round timestamp

- config/trace.go
- internal/envoy/envoy_linux.go
- internal/telemetry/trace/datadog.go
- internal/telemetry/trace/jaeger.go
- internal/telemetry/trace/trace.go
- internal/telemetry/trace/trace_test.go
- internal/telemetry/trace/zipkin.go
The zipkin trace exporter also started an HTTP reporter that needs to be terminated when a different trace provider is dynamically configured. This updates the code to better handle changes.
I also updated the envoy restart so that we more aggressively drain and terminate the original process. During hot-reload the old envoy process will continue to send tracing information to the previous zipkin URL, but once the new one takes over the new URL should be used.
I also updated the logging provider for zipkin so logs are JSON formatted.
Fixes https://github.com/pomerium/pomerium-console/issues/1265
> tracing: support dynamic reloading, more aggressive envoy restart

- authorize/check_response.go
- authorize/check_response_test.go
- authorize/grpc.go
- authorize/grpc_test.go
- go.mod
- go.sum
Currently when a user is not logged in and they don't have access to a route, we redirect the user through the Login flow. Unfortunately this causes issues for single page applications, because usually the request that will result in the redirect is done via AJAX or Fetch, and Javascript can't handle the HTML redirect.
This PR changes the behavior slightly so we only do the redirect if a request for an HTML page is made. Other types of requests receive a 401 instead, which applications can detect and handle appropriately. (For example Grafana reloads the page and sends the user through the Login flow again)
Fixes #2176
> authorize: only redirect for HTML pages

- config/envoyconfig/bootstrap.go
- config/envoyconfig/bootstrap_test.go
- config/envoyconfig/clusters.go
- config/envoyconfig/listeners.go
- config/envoyconfig/tracing.go
- config/envoyconfig/tracing_test.go
- internal/envoy/envoy.go
The Zipkin OpenCensus tracer is deprecated in envoy. We can use the native zipkin tracer instead. Also move tracing configuration to the dynamic config instead of the bootstrap config.
Fixes https://github.com/pomerium/internal/issues/411
> envoyconfig: use zipkin tracer

- authorize/check_response.go
The grpc-web library uses its own content-types instead of application/json. This PR adds them to the list of acceptable media types so that they will be handled like JSON.
> authorize: handle grpc-web content types like json

- authorize/evaluator/opa/policy/headers.rego
- config/envoyconfig/routes.go
- config/envoyconfig/routes_test.go
If no value was defined for a given claim it would be possible for an incoming request to set a value and have it still go through. This makes it so we always set a header even if there is no value, thus overwriting the original request header.
The reason why we only check `PassIdentityHeaders` and don't remove the headers there is that the remove header code is called *after* the extauthz code, which means it removes the headers we added with rego.
Fixes https://github.com/pomerium/internal/issues/423
Fixes https://github.com/pomerium/internal/issues/422
> envoy: always set jwt claim headers even if no value is available

- internal/contextkeys/contextkeys.go
- internal/controlplane/xdsmgr/xdsmgr.go
- pkg/grpc/databroker/syncer.go
There was an issue that could result in context being tagged with a wrong version. 
Related to https://github.com/pomerium/pomerium-console/issues/1269
> databroker: only tag contexts used for UpdateRecords

- config/envoyconfig/listeners.go
- config/envoyconfig/listeners_test.go
The `codecType` option needs to match `alpnProtocols`. Because they didn't match the browser was making an HTTP/2 request to a server that only accepted HTTP/1 (or vice-versa).
Fixes #2271
> envoy: fix usage of codec_type with alpn

- internal/autocert/manager.go
- internal/autocert/manager_test.go
- internal/autocert/ocsp.go
- internal/autocert/ocsp_test.go
Certificates with OCSP must-staple will become invalid and cause connection handshake failures unless an up to date OCSP response is stapled to it. 
Fixes #1946 https://github.com/pomerium/internal/issues/440
> ocsp: reload on response changes

- .gitignore
- Makefile
- cmd/pomerium-cli/version.go
- cmd/pomerium/main.go
- databroker/cache.go
- internal/cmd/pomerium/pomerium.go
- internal/controlplane/server.go
- internal/envoy/embed.go
- internal/envoy/envoy.go
- internal/envoy/files/files.go
- internal/telemetry/metrics/info_test.go
- internal/telemetry/metrics/registry.go
- pkg/grpcutil/version.go
- pkg/metrics/constants.go
- scripts/get-envoy.bash
* Update the get-envoy script to save the sha256 sum and version to a `files` directory where they can be embedded and read at runtime. 
* Update the CLI so the version command prints the envoy version.
* Update metrics to include the envoy version.
Fixes #2201
> envoy: add full version

- internal/directory/azure/api.go
- internal/directory/azure/azure.go
- internal/directory/azure/azure_test.go
- internal/directory/azure/delta.go
Currently we only make one call to the azure `transitiveMembersOf` endpoint, but if there are more than 100 groups for a single user, only a subset of them will be set. This PR updates the call to support paging so that we should get all the groups.
I tested this change by manually adding `$top=1` to the API request and saw a request in the logs for each group. Another way to test would be to add more than 100 groups to a user in azure.
Fixes #2299
> directory/azure: add paging support to user group members call

- config/certs.go
- config/certs_test.go
- config/options.go
- internal/databroker/config_source.go
- pkg/cryptutil/certificates.go
Reject certs coming from databroker config if they conflict with local. 
Implements https://github.com/pomerium/internal/issues/449
> certs: reject certs from databroker if they conflict with local

- pkg/policy/generator/conditionals.go
- pkg/policy/generator/generator.go
- pkg/policy/generator/generator_test.go
Due to the way rego works the `not` and `nor` rules weren't working. This PR updates them to use set comprehensions so that they always evaluate to `true` or `false` and are never undefined.
This behavior is described here: https://www.openpolicyagent.org/docs/latest/policy-language/#universal-quantification-for-all which is where they also recommend using comprehensions as an alternative solution.
- https://github.com/pomerium/pomerium-console/issues/1446
> ppl: fix not/nor rules

- internal/envoy/envoy.go
There's been instances on developer machines where envoy is detected as dead by gopsutil, but is actually still running.  `IsRunning()` uses information from `CreateTime()` to determine if the same process is running, so this PR adds context from `CreateTime()` when `IsRunning()` returns false.
n/a
> internal/envoy: add debugging information if envoy is no longer running

- authorize/check_response.go
According to https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/doc/PROTOCOL-HTTP2.md
> If Content-Type does not begin with “application/grpc”, gRPC servers SHOULD respond with HTTP status of 415 (Unsupported Media Type). 
which hints that content-type should always be present for gRPC requests. 
Fixes https://github.com/pomerium/internal/issues/446
> authorize: do not send redirects to gRPC 

- pkg/storage/inmemory/backend_test.go
- pkg/storage/inmemory/stream.go
Coverage for this package was non-deterministic because the various select blocks pseudo-randomly choose when multiple options can proceed. I updated the code to try each possibility in order so that they always come out the same way. I also added some tests for the various ways a stream can be closed.
Fixes https://github.com/pomerium/internal/issues/456
> storage/inmemory: add tests for close behavior

- authorize/evaluator/policy_evaluator.go
- authorize/evaluator/policy_evaluator_test.go
- pkg/policy/generator/generator_test.go
PPL rules generally create simple boolean values. For example `user: x` returns true if the user is `x`. Historically our policy rego script used an array with `[status, reason]` for the deny block. This PR updates the policy evaluator so that it supports either. If the deny block returns true it will set `[403,""]`.
Fixes https://github.com/pomerium/pomerium-console/issues/1473
> authorize: support boolean deny results

- internal/registry/redis/lua/registry.lua
- internal/registry/redis/redis.go
The `Publish` function was being called any time `List` was called even if there were no changes. Since `List` can sometimes trigger a change (if something has expired), we can't really do the change detection outside of the lua function itself. This PR moves the `Publish` call to the lua function, where it is conditionally executed if something changes.
This should improve `Watch`, which was likely stuck in an infinite change loop.
Fixes https://github.com/pomerium/internal/issues/455
> registry/redis: call publish from within lua function

- config/envoyconfig/routes.go
- config/envoyconfig/routes_test.go
- config/policy.go
1. Fix timeout propagation in protobuf
2. Add `allowWebsockets` to `timeout` and `idleTimeout` tests
> fix: timeout in protobuf

- config/envoyconfig/bootstrap.go
- config/envoyconfig/bootstrap_test.go
- internal/envoy/envoy.go
Add a bootstrap layered runtime configuration to suppress an envoy warning.
Fixes https://github.com/pomerium/internal/issues/453
> envoyconfig: add bootstrap layered runtime configuration

- docs/docs/topics/certificates.md
Current instructions:
```
$ go get -u github.com/FiloSottile/mkcert
go get: github.com/FiloSottile/mkcert@v1.4.1 updating to
github.com/FiloSottile/mkcert@v1.4.3: parsing go.mod:
module declares its path as: filippo.io/mkcert
but was required as: github.com/FiloSottile/mkcert
```
Updated:
```
$ go get -u filippo.io/mkcert
go: downloading filippo.io/mkcert v1.4.3
...
```
- NA reference any related issues
- NA updated unit tests
> Update installation source for mkcert

- internal/authclient/authclient.go
The existing implementation of pomerium-cli does not respect the http proxy env vars so here we add the default http.Transport behavior back with [ProxyFromEnvironment](https://golang.org/pkg/net/http/#ProxyFromEnvironment).
> cli: use proxy from environment

- config/envoyconfig/filemgr/filemgr.go
Only delete cached files. Ignore noisy error.
Fixes https://github.com/pomerium/internal/issues/451
> envoyconfig: only delete cached files, ignore noisy error

- internal/envoy/envoy.go
Only check for pid with monitor. Ignore creation time.
Fixes https://github.com/pomerium/internal/issues/424
> envoy: only check for pid with monitor

- config/envoyconfig/tracing.go
Default zipkin path to / when empty
- https://github.com/pomerium/pomerium-console/issues/1483
> envoyconfig: default zipkin path to / when empty

- config/policy.go
Add a warning about using `http` source URLs.
Fixes https://github.com/pomerium/internal/issues/458
- [] add appropriate tag (`improvement` / `bug` / etc)
> config: add warning about http URLs

- authorize/grpc.go
The envoy `CheckRequest` HTTP path comes in encoded:
> path (string) 
> The request target, as it appears in the first line of the HTTP request. This includes the URL path and query-string. No decoding is performed.
So we need to store it as the `RawPath` instead of the `Path`.
Fixes https://github.com/pomerium/internal/issues/468
> authorize: decode CheckRequest path for redirect

- authorize/grpc.go
Currently if a policy evaluation results in a deny, we always deny, even if a user isn't logged in. This PR updates the code to treat denies like `!allow`. 
- https://github.com/pomerium/pomerium-console/issues/1577
> authorize: allow redirects on deny

- .github/workflows/backport.yaml
Change the credentials we use for our backport action.  This should allow tests to automatically run when it creates PRs.
https://github.com/tibdex/backport/issues/61
> ci: use github app for backport credentials

- .golangci.yml
- internal/directory/azure/delta.go
Apparently `golint` is deprecated, so use `revive` instead.
- https://github.com/pomerium/internal/issues/469
> ci: use revive instead of golint

- internal/envoy/embed.go
- internal/envoy/envoy.go
Only allow embedded envoy unless `OverrideEnvoyPath` is set.
Fixes https://github.com/pomerium/internal/issues/436
> envoy: only allow embedding

- internal/envoy/envoy.go
- internal/telemetry/grpc.go
- internal/telemetry/grpc_test.go
Envoy sometimes sends gRPC requests with `b3` tags instead of `grpc-trace-bin`. This PR updates the code to support either.
Fixes #2372
> telemetry: support b3 headers on gRPC server calls

- config/custom.go
- internal/urlutil/url.go
- internal/urlutil/url_test.go
Improve parse error message for URLs with port in path.
- https://github.com/pomerium/pomerium-console/issues/1590
> urlutil: improve error message for urls with port in path

- authorize/evaluator/policy_evaluator.go
Use cryptutil's `Hash` the scripts to be consistent. 
This should be pretty darn fast, but would probably be fine to use something like `xxhash` via `cryptuil.MustHash` if it adds up. 
- #2383
> evaluator: use `cryptutil.Hash` for script spans

- internal/databroker/server.go
- internal/directory/azure/azure.go
- internal/directory/github/github.go
- internal/directory/gitlab/gitlab.go
- internal/directory/google/google.go
- internal/directory/okta/okta.go
- internal/directory/onelogin/onelogin.go
- internal/directory/ping/config.go
- internal/httputil/client.go
- internal/httputil/client_test.go
- internal/identity/oauth/github/github.go
- internal/identity/oidc/oidc.go
- pkg/grpc/databroker/leaser.go
Add a new logging http transport that the directory providers can use.
Fixes #2382
> directory: add logging http client to help with debugging outbound http requests

- internal/directory/google/google.go
Using `WithHTTPClient` with the google SDK results in the `oauth2` transport no longer being used. I couldn't find any other way to hook up to this reliably without duplicating all of the code in `admin.NewService`, so I just removed it entirely.
- Fixes #2389
> google: remove WithHTTPClient

- SECURITY.md
- docs/docs/community/security.md
Symlink the security policy in our docs so that Github recognizes it.
> symlink security policy to root of project

- config/envoyconfig/clusters.go
- config/envoyconfig/clusters_test.go
- config/envoyconfig/protocols.go
I guess you can't use http/2 with websockets because they use the same header field. This PR updates the envoy config to explicitly disable http/2 when using web sockets.
- #2388
> disable http/2 for websockets

- config/constants.go
- config/custom.go
- config/custom_test.go
- config/options.go
- config/policy.go
- config/policy_ppl.go
- config/policy_ppl_test.go
- internal/httputil/reproxy/reproxy.go
Add support for embedded PPL policy. Also add an additional `policy` field in the config: `routes`.
Fixes https://github.com/pomerium/internal/issues/480
> config: add support for embedded PPL policy

- docs/reference/readme.md
- docs/reference/settings.yaml
Add warning that only secure schemes are supported for security reasons (otherwise credentials / cookies could be easily MITM'd). 
https://pomerium-io.slack.com/archives/CK92MUAES/p1627615869000100?thread_ts=1627567572.143500&cid=CK92MUAES
> docs: only secure schemes are supported

- authorize/evaluator/headers_evaluator_test.go
- authorize/evaluator/opa/policy/headers.rego
Add a new `sid` claim to the assertion JWT. This can be used by applications to determine the session of the user. It's different from the `jti` in that the `sid` is always set to the input session id, regardless of impersonation.
- https://github.com/pomerium/pomerium-console/issues/1770
> authorize: add sid to JWT claims

- pkg/storage/redis/redis_test.go
I'm hoping this PR fixes our test flakiness with redis.
Move the context timeout to inside the redis cluster start so if we have to pull the docker image down it doesn't count to the timeout. Also increase it a bit.
Fixes #2424
> redis: increase timeout on test

- README.md
- docs/docs/readme.md
Clarify that device state is really device identity via client certificates for the moment. Proper device state context coming in future integrations. 
- Fixes #2283 
- Related #1835 
- https://github.com/pomerium/pomerium/pull/2280#issuecomment-858283296
> docs: clarify device identity, not state via client certs

- docs/docs/upgrading.md
- docs/reference/readme.md
- docs/reference/settings.yaml
- pkg/cryptutil/jose.go
- pkg/cryptutil/jose_test.go
- scripts/generate_self_signed_signing_key.sh
Remove support for ed25519 signing keys.
- Fixes https://github.com/pomerium/internal/issues/491
- https://www.openpolicyagent.org/docs/latest/policy-reference/#token-signing
- https://pomerium-com.slack.com/archives/C012D1Q96TX/p1628031934062500
- https://github.com/pomerium/pomerium/issues/1626
- https://pomerium-io.slack.com/archives/CK92MUAES/p1606498282249300
- https://github.com/pomerium/pomerium/pull/1631
- https://github.com/pomerium/pomerium-console/issues/434
> config: remove support for ed25519 signing keys

- docs/reference/settings.yaml
This PR clarifies the use of the `idp_service_account` value which is
not used in all cases, though the warning callout suggests it is
required in all cases.
> docs/reference: Clarify use of idp_service_account

- docs/.vuepress/config.js
Update vuepress config to default to v0.15.
n/a
> docs: update default version to v0.15

- docs/.vuepress/config.js
This brings users back to the marketing site when they click on the Pomerium logo.
> redirect logo to the marketing site

- docs/enterprise/install/helm.md
- docs/enterprise/install/quickstart.md
Updates the config for Pomerium Console in both install docs to set the `audience` key to match the domain set as `from` in the route to the console.
https://github.com/pomerium/pomerium-console/issues/1797
> specify expected audience in Console config

- pkg/storage/redis/redis_test.go
- pomerium.go
When we added `tools.go` it caused a plain `go get github.com/pomerium/pomerium` to fail because no build constraints matched. This PR adds a blank non-constrained file so that `go get` works again.
```
† go get github.com/pomerium/pomerium@36c2c9b0afe2b659df76610e3690327b3ab5067a
go: downloading github.com/pomerium/pomerium v0.15.1-0.20210806171735-36c2c9b0afe2
go get: upgraded github.com/pomerium/pomerium v0.15.1-0.20210806144600-1e03b0fac135 => v0.15.1-0.20210806171735-36c2c9b0afe2
```
This also includes changes to the redis tests (again). I realized there's a race condition between triggering `ready` and actually having started subscribing to events. So now we'll just call Put multiple times till it gets the event.
> fix go get, improve redis test

- authorize/evaluator/evaluator_test.go
- authorize/evaluator/store.go
- authorize/evaluator/store_test.go
- authorize/sync_test.go
- config/envoyconfig/tracing.go
- databroker/directory.go
- internal/controlplane/events.go
- internal/controlplane/xds.go
- internal/databroker/config_source_test.go
- internal/databroker/server_test.go
- internal/identity/manager/manager.go
- pkg/grpc/session/session.go
- pkg/grpc/user/user.go
- pkg/logutil/scrub.go
- pkg/policy/criteria/criteria_test.go
- pkg/protoutil/any.go
- pkg/protoutil/transform.go
- pkg/storage/encrypted.go
- pkg/storage/encrypted_test.go
- pkg/storage/storage_test.go
By default `anypb.New` creates Anys without using deterministic serialization. (i.e. sorted map order) This has unfortunate consequences when comparing two Anys.
This PR updates anywhere we've used `anypb.New` with `protoutil.NewAny` and turns on deterministic serialization.
> protoutil: add NewAny method for deterministic serialization

- docs/enterprise/install/helm.md
We're going to host the enterprise charts next to open source.  Updating the docs to reflect that.
n/a
> docs: update enterprise helm instructions to use main repo

- docs/enterprise/console-settings.yaml
- docs/enterprise/reference/configure.md
- docs/reference/settings.yaml
Documents Tracing Sample Rate notation in the Console, which is different from the OSS key.
Closes https://github.com/pomerium/pomerium-console/issues/1159
> Document tracing sample rate in console

- docs/enterprise/concepts.md
Adds a new section to Concepts describing how associated policies could prevent routes from being moved.
https://github.com/pomerium/pomerium-console/pull/1865
> Document moving routes

- docs/reference/readme.md
- docs/reference/settings.yaml
Envoy prevents setting certain request headers from being set directly via `set_request_header` as of v0.19. This change makes it clear the preferred mechanism for setting things like `host` or path rewrites. 
- https://pomerium-io.slack.com/archives/CK92MUAES/p1628684451019000
- https://github.com/envoyproxy/envoy/blob/0ab463fe054de02786b2de24a17206b14b12c01d/source/common/router/header_parser.cc#L45-L54
- https://github.com/envoyproxy/envoy/pull/14747
> docs: clarify  custom request header limitations

- docs/docs/install/helm.md
This fixes the command in environments like macOS where the CAROOT path includes a space.
Closes https://github.com/pomerium/docs/issues/19
-  ~updated unit tests~
-  ~updated UPGRADING.md~
> Wrap mkcert command in quotes

- docs/enterprise/reference/manage.md
- docs/guides/argo.md
- docs/reference/readme.md
- docs/reference/settings.yaml
- examples/config/config.example.yaml
- examples/config/config.minimal.yaml
- examples/config/policy.example.yaml
- examples/config/route.example.yaml
Standardizing on `user@example.com` as the example email address for configs.
- ~reference any related issues~
-  ~updated unit tests~
-  ~updated UPGRADING.md~
> docs: use generic email

- docs/.vuepress/config.js
- docs/docs/install/helm.md
- docs/docs/install/readme.md
- docs/docs/topics/certificates.md
- docs/partials/install-mkcert.md
- examples/config/config.docker.yaml
- examples/docker/basic.docker-compose.yml
- package.json
This update simplifies the quickstart process by assuming a local test environment without a TLS solution or a FQDN
Additionally, this PR expands the Docs site with the `markdown-it-includes` plugin, allowing us to single-source content we want to include in multiple pages.
-  ~reference any related issues~
- ~updated unit tests~
-  ~updated UPGRADING.md~
> Update Docker Quickstart

- internal/httputil/client.go
- internal/httputil/client_test.go
- internal/identity/oauth/github/github.go
- internal/urlutil/url.go
- internal/urlutil/url_test.go
Update the Github IDP to support a custom provider URL. It already had some support for this, but URLs that ended with `/` didn't work, and the user info was always retrieved from the Github API. It will now be retrieved from the custom provider URL if it's not the default.
The `defaultClient` in `httputil` was changed to a method so that it would pick up the default HTTP transport built in `config`. (which allows all the custom TLS settings to get picked up)
- https://github.com/pomerium/internal/issues/514
> github: support provider URL

- docs/docs/install/binary.md
Adds a step to the Binary Install doc to enable the Pomerium service to bind to port `443`
closes https://github.com/pomerium/internal/issues/464
> document binding service to 443

- .github/goreleaser.yaml
- .github/workflows/release.yaml
Add support for m1 / darwin/arm64 for the CLI. Pomerium itself is still amd64 until envoy supports m1. 
Fixes #2470
> ci: support darwn/arm64 aka m1 for cli

- authorize/authorize.go
- authorize/evaluator/google_cloud_serverless.go
- authorize/grpc.go
- authorize/sync.go
Discovered while working on integration tests, there are circumstances where forward auth with nginx can get into an infinite redirect loop. Moving the `isForwardAuth` check to after the session id check seems to fix it. It also makes more sense in term of the flow.
Basically we want to Redirect to authenticate if there's no session, but if there is a session we want to return Forbidden. In forward auth mode that means returning a `401 Unauthorized` with no session and a `403 Forbidden` when there is a session.
I also moved a noisy log and added error logging for google cloud serverless.
> fix forward-auth, logging

- authenticate/state.go
- authorize/state.go
- internal/cmd/pomerium/pomerium.go
- internal/controlplane/events.go
- internal/databroker/config_source.go
- internal/registry/reporter.go
- pkg/grpc/client.go
This PR updates the gRPC client cache so that it's not shared across services. This is so that if a service closes the connection it won't inadvertently close it for another service.
Fixes https://github.com/pomerium/internal/issues/535
> grpc: disable gRPC connection re-use across services

- config/options.go
- config/options_test.go
- docs/docs/upgrading.md
Remove the deprecated `headers` option.
Fixes https://github.com/pomerium/internal/issues/475
> config: remove headers

- internal/identity/oidc/gitlab/gitlab.go
Currently, we require a GitLab application with the `api` scope on GitLab (SAAS) to authenticate using it as an IdP. This gives the application full read/write permissions for the entire API, much more than we need.
This change restricts the scope to `email` ~and `openid`~ (already defined). Including `profile` was also discussed, ~but the values therein are already provided by `openid`~ and put back in to match OIDC spec.:
I've built and tested this locally, with no problems (other than those caused by my own stupidity :smile: ).
https://github.com/pomerium/docs/issues/25
> Remove api from GitLab defaultScope

- config/options.go
- config/options_test.go
In some cases certificates may be entirely supplied from external source, i.e. via ingress-controller. 
Allow Pomerium to start with a warning and self-signed certificate if none are supplied via local configuraiton.
Fixes https://github.com/pomerium/internal/issues/532
> allow pomerium to start without certs

- authorize/evaluator/headers_evaluator.go
- authorize/evaluator/headers_evaluator_test.go
Fix the google cloudrun header audience field. It was supposed to have `https://` in front of it. (which is confusing because our audience doesn't).
- #2454
> authorize: fix google cloudrun header audience
