config/policy_ppl_test.go, pkg/policy/criteria/users.go, pkg/policy/criteria/users_test.go
Use session.user_id instead of user.id for user criterion
- https://github.com/pomerium/pomerium-console/issues/2025
=> ppl: use session.user_id instead of user.id for user criterion

authorize/evaluator/headers_evaluator_test.go, authorize/evaluator/opa/policy/headers.rego
Instead of relying on the user record id for the `sub` and `user` JWT claims we should use the `session.user_id`.
Fixes https://github.com/pomerium/internal/issues/565
=> authorize: use session.user_id in headers

internal/identity/manager/manager.go, internal/identity/manager/manager_test.go
Implement exponential backoff for directory refresh.
Fixes #2568
=> directory: implement exponential backoff for refresh

internal/directory/google/google.go, internal/directory/provider.go
Add support for a provider URL with the google provider. This is so we can mock directory calls in integration tests. If no provider URL is supplied the current default will be used.
=> google: support provider URL

internal/autocert/manager.go
Remove a noisy error log. This error is returned for domains not managed by certmagic. It's not a real error.
It was introduced in #2286 
Fixes #2559
=> autocert: remove log

internal/frontend/assets/html/userInfo.html, internal/frontend/templates.go
Format the `exp`, `iat` and `updated_at` claims on the userinfo page.
Fixes #2578
=> userinfo: format exp, iat and updated_at

cmd/pomerium-cli/tcp.go, go.mod, go.sum
Minor adjustments to the pomerium-cli tcp command's logger format.
* Use RFC3339 timestamp
* Disable colors when not in a terminal
Will open a backport of this to v0.15 as well.
Fixes https://github.com/pomerium/internal/issues/554
=> cli: update tcp log output format

cmd/pomerium-cli/cache.go
Use the user's cache directory instead of the config directory.
Fixes https://github.com/pomerium/internal/issues/567
=> pomerium-cli: use cache dir instead of config dir

cmd/pomerium-cli/main.go, go.mod, internal/tcptunnel/config.go, internal/tcptunnel/tcptunnel_test.go
It appears that when using TLS with the tcptunnel we sometimes negotiate HTTP/2, which won't work with the CONNECT upgrade connection. These changes should make it so that we never negotiate HTTP/2 when using ALPN.
- #2590
=> tcptunnel: force the use of HTTP/1.1 during ALPN

internal/authclient/config.go
When using a TLS config in the `authclient` we need to clone it so that we don't inadvertently modify it when enabling the HTTP server. The modification can be seen here: https://cs.opensource.google/go/go/+/master:src/net/http/h2_bundle.go;l=3875?q=NextProtos&ss=go%2Fgo.
This is why HTTP/2 was getting re-enabled.
- #2590
=> authclient: clone TLS configuration to prevent overriding NextProtos

docs/.vuepress/config.js, package.json
Adds `vuepress-plugin-code-copy` ([link](https://www.npmjs.com/package/vuepress-plugin-code-copy)) to provide a one-click copy button to code snippets.
=> DOCS: Add copy button to code snippets

.github/CODEOWNERS
`packages.json` Is used by the docs site to manage vuepress and its plugins/dependencies.
https://github.com/pomerium/pomerium/pull/2603
=> Add docs team as a code owner of packages.json

cmd/pomerium-cli/kubernetes.go, cmd/pomerium-cli/main.go, cmd/pomerium-cli/tcp.go, internal/authclient/authclient.go, internal/authclient/authclient_test.go, internal/authclient/config.go, internal/tcptunnel/config.go, internal/tcptunnel/tcptunnel.go
Add support for a custom browser command and print the URL similar to how the gcloud CLI does.
Fixes https://github.com/pomerium/internal/issues/544
=> pomerium-cli: add support for a custom browser command

README.md, docs/enterprise/about.md
I updated the documentation link, deleted a superfluous word in another page.
Grammar change
=> docs: remove extra word / updated docs link

docs/.vuepress/config.js
IdP configuration need only be done once, and users are only interested in the IdP they use. Making this section collapsible frees up space on the ever-growing menu.
@desimone we discussed this before and I know you had some concerns, but the conversation is not historically accessible. Please outline any concerns on this PR.
=> DOCS: Collapse IDP Header

docs/enterprise/concepts.md, docs/enterprise/console-settings.yaml, docs/enterprise/reference/configure.md, docs/enterprise/reference/manage.md
Cross-links terms that have entries in both Enterprise Concepts and Enterprise Reference.
Last nit in https://github.com/pomerium/docs/issues/40
=> Docs: cross-reference links between concepts and reference

config/envoyconfig/clusters.go
Clearer error message for duplicate routes. 
Fixes #2655
=> config/envoyconfig: better duplicate message

.github/goreleaser.yaml
`pomerium-cli` is meant to be a user facing tool but was erroneously packaged in `/usr/sbin` on Linux, which may not be in a normal user's `$PATH`.
Relocate it to `/usr/bin` in accordance with [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard).
Fixes https://github.com/pomerium/pomerium/issues/2676
=> deployment: relocate pomerium-cli to /usr/bin

authenticate/handlers.go, internal/identity/manager/config.go, internal/identity/manager/manager.go, internal/identity/manager/manager_test.go
Currently we only update user info on login if a user record doesn't already exist. This change makes it so we always update the user info.
Fixes https://github.com/pomerium/internal/issues/618
=> authenticate: always update user record on login

docs/docs/k8s/ingress.md
Adds the `allow_spdy` annotation to the Ingress Controller doc.
Documents https://github.com/pomerium/ingress-controller/pull/83
=> Docs: Add spdy annotation

config/config_source.go, config/config_source_test.go
Update the config source to watch policy files in addition to config changes.
Fixes #2722
=> config: detect changes to the kubernetes service account token file

authenticate/handlers.go, config/envoyconfig/routes.go, config/envoyconfig/routes_test.go
Redirect the root path in authenticate to `/.pomerium/` for easier debugging.
Fixes https://github.com/pomerium/pomerium/issues/2766
=> authenticate: redirect / to /.pomerium/

docs/docs/upgrading.md, internal/identity/oidc/google/google.go, internal/identity/oidc/oidc.go
During OIDC authentication flow, Pomerium will no longer default to setting the uri param for `access_type` to `offline` which is custom and unique to google's IdP. Other identity providers should be able to depend on the `offline_access` scope for `refresh_tokens`. 
- Fixes #2773 
- https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess 
- https://developers.google.com/identity/protocols/oauth2/web-server#offline
=> identity: only assign `access_type` uri params to google.

docs/guides/kubernetes.md
Updates [Securing Kubernetes](https://pomerium.com/guides/kubernetes.html) to continue from our Helm-based install instructions, using the service account created in the chart.
Closes https://github.com/pomerium/docs/issues/7
Supersedes #2738
=> Docs: Update Securing Kubernetes Guide

docs/enterprise/api.md
Fix for broken indentation in first code block.
=> DOCS: Fix indentation in API doc

internal/controlplane/xdsmgr/xdsmgr.go
When Envoy is unable to apply a configuration it will `NACK` the request. Currently we log these as errors. This PR treats them as fatal errors.
- https://github.com/pomerium/internal/issues/632
=> envoy: treat configuration errors as fatal

config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go
Fix route-specific client certificates when using a non-standard `from` port.
Fixes https://github.com/pomerium/pomerium/issues/2794
=> envoyconfig: fix tls_downstream_client_ca for non-standard ports

internal/directory/azure/azure.go, internal/directory/github/github.go, internal/directory/gitlab/gitlab.go, internal/directory/okta/okta.go, internal/directory/onelogin/onelogin.go, internal/directory/ping/config.go, internal/httputil/client.go, internal/telemetry/http.go, internal/telemetry/metrics/const.go, internal/telemetry/metrics/http.go, internal/telemetry/metrics/http_test.go
The HTTP client we are using for communicating with the Identity Provider wasn't using a metrics-enabled RoundTripper so we are missing RED type metrics around user/directory/session requests. 
This refactors the metrics roundtripper signature to remove the deprecated `destination` label and adds metrics to the httputil logging client.  It also adds in a `name` field for passing in a name of the client consumer.
Sample of resulting metrics:
```
pomerium_http_client_request_duration_ms_bucket{host="dev-YYY.okta.com",http_method="GET",http_status="200",service="okta_idp_client",installation_id="",hostname="XXXXX",le="100"} 2
pomerium_http_client_request_duration_ms_bucket{host="dev-YYY.okta.com",http_method="GET",http_status="200",service="okta_idp_client",installation_id="",hostname="XXXXX" …
```
=> Fix IdP client metrics

internal/telemetry/grpc.go
We are missing the per-method server metrics that should come from our grpc metrics handler.  This is due to a missing context key that comes from ocgrpc's Handler; without it, the metrics are never actually recorded at the end of the RPC.
* add a call to the underlying TagRPC to get the required key set
* add a comment since it seems like an unnecessary call
Sample metric:
```
pomerium_grpc_server_request_duration_ms_count{grpc_method="Put",grpc_server_status="OK",grpc_service="databroker.DataBrokerService",service="pomerium",installation_id="",hostname="XXXX"} 6
```
https://github.com/pomerium/pomerium/pull/2376
=> internal/telemetry: fix grpc server metrics

authorize/grpc.go
Fix for an nginx infinite redirect due to always returning 401. This appears to already be fixed on master, but this section of the code has radically changed and can't be backported.
Fixes #2796
=> authorize: fix nginx infinite redirect

.gitignore, internal/envoy/envoy_darwin.go, internal/envoy/files/files_darwin_amd64.go, internal/envoy/files/files_darwin_arm64.go, scripts/get-envoy.bash
Envoy does not yet have an official release build for Apple M1, meanwhile you may install locally: 
1.  Have Xcode installed and development agreement accepted
2. `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`
3. `brew install --HEAD envoy`
After that, you should be able to build Pomerium darwin-arm64 using locally compiled envoy 1.21.0-dev.
=> dev build support for darwin-arm64 from envoy tip

.github/workflows/release.yaml
Explicitly set our release action for 1.16.12.
https://github.com/actions/setup-go/issues/129
=> deps: pin release to latest go version

internal/tests/xdserr/cmd/main.go, pkg/grpcutil/client.go
`NewGRPCClientConn` snippet exists with minor variations in core, console, ingress-controller and cli. Moving to public package so that other repos can just use it directly.
=> move NewGRPCClientConn to public package

authenticate/authenticate.go, authorize/check_response.go, pkg/webauthnutil/device_type.go, pkg/webauthnutil/device_type_test.go, pkg/webauthnutil/options_test.go
Add two new default device types: `any` and `enclave_only`. `any` is equivalent to the original `default`, `enclave_only` requires a `PLATFORM`, resident key.
- https://github.com/pomerium/internal/issues/701
=> devices: switch "default" device type to two built-in default device types

internal/frontend/assets/html/userInfo.html, internal/frontend/assets/style/main.css
Add a confirmation dialog to the delete button and fix the display of the button in firefox.
Fixes https://github.com/pomerium/internal/issues/702
Fixes https://github.com/pomerium/pomerium/issues/2837
=> dashboard: add confirmation dialog, fix button in firefox

docs/.vuepress/config.js
Update version menu for new release branch.
NB, the 0-16-0 domain will get a proper TLS cert in a day or so.
#2845
=> docs: update version menu for v0.16

docs/docs/topics/getting-users-identity.md
Signed-off-by: Sylvain Rabot <sylvain@abstraction.fr>
=> docs: fix generation of the public key

.github/workflows/release.yaml
Previously we pinned the go release to 0.16.12 to force the updated version of go. The .X branch should now be autoupdated. 
- fixes #2828
=> deps: unpin go version to 0.16.x

docs/docs/upgrading.md, docs/reference/readme.md, docs/reference/settings.yaml
- Adjusts copy in the [upgrade notes](https://github.com/pomerium/pomerium/pull/2845).
- Adjusts certificate reference content.
- Backports [IDP metrics](https://github.com/pomerium/pomerium/pull/2842) to the source reference file.
- Sorts new metrics alphabetically.
#2845
#2842 
#2830 - Needs merge to resolve broken link in Upgrading.
=> DOCS: Fixes to 16 release

docs/docs/topics/mutual-auth.md
Mutual Authentication was merged with links in headers, which breaks the VuePress ToC component.
#2820
=> DOCS: Fix ToC

.github/ISSUE_TEMPLATE/config.yml
To help push folks into the forums and slack, remove the ability to use a blank issue template.
n/a
=> disable blank github issues

authenticate/authenticate.go, authenticate/handlers.go, authenticate/handlers/device-enrolled.go, authenticate/handlers/handlers.go, authenticate/handlers/webauthn/webauthn.go, internal/frontend/assets/html/device-enrolled.go.html, internal/urlutil/proxy.go
Add a new device-enrolled page that can be shown after a device is enrolled successfully.
Fixes #2891
=> authenticate: add device-enrolled page

scripts/get-envoy.bash
Upgrade envoy from 1.19.1 to 1.20.1.
- https://github.com/pomerium/internal/issues/708
=> envoy: upgrade to 1.20.1

docs/docs/identity-providers/google.md, docs/reference/readme.md, docs/reference/settings.yaml, examples/config/config.example.env, examples/config/config.example.yaml, examples/docker/nginx.docker-compose.yml
Update documentation to remove references to `idp_provider_url` with Google OAuth, since it will break when used.  (Keep references for other providers)
Partially fixes #2866.
=> Remove references to idp_provider_url for Google.

docs/docs/topics/mutual-auth.md
Fixes references to north-south and east-west traffic, which were moved from headers to copy without correct re-adjustment.
=> Docs: Mutual Auth Hotfix

config/envoyconfig/listeners.go, config/envoyconfig/tls.go, config/envoyconfig/tls_test.go, pkg/cryptutil/certificates.go
If a TLS certificate has a must-staple extension set, envoy will reject the certificate if doesn't also have an OCSP response. This results in an invalid configuration and a fatal error in Pomerium. When Pomerium restarts it picks the certificate up again and crashes, resulting in rate-limiting from the Let's Encrypt side.
This PR adds a validation step to reject invalid certificates before we hand them to envoy. This allows us to recover if the OCSP response subsequently gets added to the certificate.
The bug can be quite difficult to reproduce: it requires a server accessible from the internet and I had to modify the code to erase the OCSP response to simulate it missing. I wasn't able to come up with a way to build a real integration test, but I did add a unit test.
Fixes #2852
=> envoy: check certificates for must-staple flag and drop them if they are missing the response

docs/guides/argo.md
minot fix: link to argo workflows in the Pomerium guide to [secure Argo.](https://www.pomerium.com/guides/argo.html)
=> docs: fix argo link

authorize/check_response.go, authorize/grpc.go, pkg/policy/criteria/device.go, pkg/policy/criteria/device_test.go
For device handling we rely on `Reasons` returned by PPL. There are two device-specific reasons: `device-unauthenticated` and `device-unauthorized`. The first triggers the device registration/authentication flow. The second results in a special access denied error.
Currently we are only checking these reasons when they are returned by an `allow` block and not a `deny` block. This means that if you were to use a `device` criterion in a `deny` block the user would only ever see forbidden.
This PR updates the code so that both the "Not Allowed" and "Denied" conditions are handled in similar ways so that the user will go through the device authentication flow before (possibly) seeing a forbidden error.
The other issue is that we were still using `default` as the default device type from …
=> handle device states in deny block, fix default device type

.github/Dockerfile-release, .github/goreleaser.yaml, Dockerfile
It seems like we're using the wrong env var to detect the target platform when building the image from master.  We should be using `TARGETARCH` rather than `ARCH` per [the docs](https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope).
- Update the top level `Dockerfile` to use the correct variable name
- Update our release pipeline and `Dockerfile` to use the same variable name for consistency
- Set target platform explicitly in goreleaser config
#2896
=> deployment: fix distroless base arch

authenticate/handlers/webauthn/webauthn.go, pkg/webauthnutil/device_type.go, pkg/webauthnutil/device_type_test.go
Treat undefined device types as any.
Fixes https://github.com/pomerium/internal/issues/731
=> devices: treat undefined device types as any

authenticate/handlers.go
Add the callback endpoint from the proxy service to authenticate. This is needed when we redirect to `/.pomerium/callback` directly in the authenticate service (which happens when registering devices directly from the .pomerium endpoint).
Fixes #2920
=> authenticate: add callback endpoint

authenticate/handlers.go, authenticate/handlers/webauthn/webauthn.go
After deleting a device we need to redirect to an absolute URL otherwise we get a 500 error.
Fixes https://github.com/pomerium/internal/issues/732
=> webauthn: use absolute URL for delete redirect

authenticate/handlers.go, authenticate/handlers/webauthn/webauthn.go, config/envoyconfig/listeners.go, config/options.go, config/options_test.go
When redirecting to a Pomerium domain from authenticate we typically use the `/.pomerium/callback` handler so that we can update the cookie for that route. However if we have a non-Pomerium redirect URI, that domain won't have that path, so we should just redirect without modifying it.
The `GetAllRouteableHTTPDomains` function basically already existed in the envoy config subpackage, so I pulled it so that webauthn could use it.
Fixes https://github.com/pomerium/pomerium-console/issues/2262
=> authenticate: support webauthn redirects to non-pomerium domains

internal/frontend/assets/html/userInfo.html
Signed-off-by: Sylvain Rabot <sylvain@abstraction.fr>
=> Remove spurious </ul> tags

pkg/grpc/device/device.go, pkg/grpc/device/device_test.go
Device credentials contain three properties intended for debugging, but not essential for functionality:
```proto
message WebAuthn {
// ...
// the options that were used to do initial registration
bytes register_options = 3;
// the response returned from initial registration
bytes register_response = 4;
// subsequent authenticate responses
repeated bytes authenticate_response = 5;
// ...
}
```
Sometimes these properties can be quite large, which can cause issues when attempting to store them in a database or send them over the wire via gRPC. This PR adds code to shrink credentials by removing data until the entire payload is less than 256KB.
Fixes https://github.com/pomerium/pomerium-console/issues/2288
=> devices: shrink credentials by removing unnecessary data

databroker/directory.go, internal/directory/directoryerrors/errors.go, internal/directory/google/google.go, internal/directory/google/google_test.go, internal/directory/provider.go
Google groups can contain user members which aren't members of the Group's organization. Currently when this happens we don't create `directory.User` records for these members. This PR updates the code to create `directory.User` records, which in turn makes it possible to support group permission checks for user that aren't also a member of the organization.
For example, previously if we had data like this:
```yaml
organization:
users:
- email: user1@inside.test
- email: user2@inside.test
groups:
- email: group1@inside.test
members:
- user1@inside.test
- user2@inside.test
- user3@outside.test
```
And a policy that required membership in the `group1@inside.test` group, `user3@outside.test` would still not have access to the route, even though they were a member of that group. With this PR …
=> google: support groups for users outside of the organization

Dockerfile.debug
It looks like alpine dropped the expired DST cert so we don't need to remove it anymore.  This only impacts the debug image.
https://github.com/pomerium/pomerium/issues/2653
=> deployment: remove DST cert workaround from debug image

docs/reference/readme.md, docs/reference/settings.yaml
Small clarification on the reference section for `idp_provider_url`. Defines how we use "base path" to determine the path to a discovery document.
=> DOCS: Clarify base path for idp_provider_url

.github/goreleaser.yaml
Explicitly enable buildx in goreleaser to prevent build failures.
https://github.com/pomerium/ingress-controller/pull/127
https://github.com/pomerium/cli/pull/31
https://github.com/pomerium/pomerium/pull/2925
=> deployment: enable goreleaser buildx

config/options_test.go, config/policy.go, config/policy_test.go, internal/urlutil/url.go
The regular expression route matching should only be matching the path part of the URL. It should also always match a full string and not a partial submatch. This PR fixes both issues.
Fixes #2952
=> config: fix policy matching for regular expressions

authenticate/authenticate.go, authenticate/handlers.go, authenticate/url.go, authenticate/url_test.go
When we redirect to the `/.pomerium` endpoint we include a `?pomerium_redirect_url` parameter on the query string. This is HMAC'd and expires after a few minutes, which means if you refresh the page you sometimes get an error. This PR updates the code so that if we see the redirect url on the userinfo page we save it to a cookie and strip it from the query string.
Fixes #2967
=> authenticate: fix expiring user info endpoint

internal/directory/auth0/auth0.go, internal/directory/auth0/auth0_test.go
Add an optional explicit `domain` property to the service account configuration for auth0. This is necessary when a custom domain is used for login, but the management api is still configured with the `*.auth0.com` domain.
Fixes #2978
=> auth0: support explicit domains in the service account

examples/nginx/config.yaml, examples/nginx/docker-compose.yaml, examples/nginx/verify.conf
I noticed the current example assumes `verify` uses port 80 but it uses 8000.
=> Update nginx example with verify port

.github/Dockerfile-release-nonroot, .github/goreleaser.yaml, .github/workflows/release.yaml, docs/docs/releases.md
Adds a set of `nonroot` images for releases.  These run under the `nonroot` user from the upstream distroless images.  
- In some environments these could be used as drop-in replacements to increase security.  
- In others, additional capabilities can be set or an alternate listener port can be selected.
closes https://github.com/pomerium/pomerium/issues/835
=> deployment: add `nonroot` release docker images

go.mod, go.sum, internal/controlplane/http.go
Add compression middleware to our control plane HTTP stack. This can significantly reduce the size of assets like javascript and css files.
- https://github.com/pomerium/internal/issues/759
=> controlplane: add compression middleware

.github/Dockerfile-release
In our release dockerfile, we use a file glob to copy the `pomerium` and (in previous releases) `pomerium-cli` binary.  However, it appears that `COPY` command is in a context where already built RPMs might be present and can include them into the image.
Since we no longer build the `pomerium-cli` binary in this repo, there's no need for the wildcard at all and this PR makes the desired artifacts explicit.
Originally found and fixed in https://github.com/pomerium/pomerium/pull/3001 on master.
=> deployment: only include pomerium binary

docs/.vuepress/theme/components/PageEdit.vue, docs/.vuepress/theme/styles/wrapper.styl
This PR overrides the PageEdit component from the default theme, so that we can add in our license disclaimer.
Input welcome on how to best style the changes.
Resolves https://github.com/pomerium/docs/issues/59
=> Docs: Add License Notice

Makefile
We appear to be hitting timeouts while installing the new MUI dependencies in our edge docker image.  This is likely only a problem on GH actions runners due to contention and other limitations.
This adds a 30s timeout to the yarn install step in the makefile, which seems to be mitigating the problem.
n/a
=> deps: increase yarn network timeout

.github/workflows/test.yaml, Makefile
Increase yarn network timeout further.  We're experiencing slow installs during the arm64 image build because it runs under qemu.
#3018 
https://github.com/nodejs/docker-node/issues/1335
=> ci: increase yarn timeout more

docs/enterprise/reference/configure.md, docs/reference/readme.md, docs/reference/settings.yaml
These changes better differentiate which settings affect upstream and downstream CAs
https://github.com/pomerium/pomerium-console/pull/2327 is dependent on this PR and its subsequent backport.
=> DOCS: update CA-related reference copy

.github/goreleaser.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml, Dockerfile.debug, Makefile
We need to run new commands with `yarn` to build the updated user info endpoint UI.  This PR adds the appropriate steps to release and debug builds.
https://github.com/pomerium/pomerium/pull/3004
=> ci: add mui build to release steps

.github/workflows/release.yaml
Remove the explicit specification of `master` branch in our demo environment deployment
n/a
=> ci: use default branch name for helmfile repo

docs/enterprise/console-settings.yaml, docs/enterprise/reference/manage.md
Updates Console docs for the device enrollment redirect URL as optional. 
Dependent on https://github.com/pomerium/pomerium-console/pull/2330. Currently it appears this should not be backported.
=> Docs: Mark redirect URL as optional

config/http_test.go
I think the upstream certificate changed for the `httptest` package, so our tests started failing. This PR changes the way we get the locally used certificate so that it comes directly from the server, which should be more resilient.
- #3055
=> config: fix httptest local certificate

docs/docs/tcp/git.md, docs/docs/topics/device-identity.md, docs/enterprise/console-settings.yaml, docs/enterprise/reference/manage.md, docs/guides/code-server.md, docs/partials/client-cert-alt-port.md
- Removes an unused partial, so it's no longer in our sitemap.
- Updates several links that used `.html` instead of `.md`, or were otherwise erroneous.
- Adds spaces to links using footer references with a `:` after, so the link checker no longer flags them as false positives.
Fixes https://github.com/pomerium/docs/issues/66
=> DOCS: Various Link Fixes

docs/enterprise/console-settings.yaml
Proof-of-concept solution for https://github.com/pomerium/pomerium-console/issues/2375 - I add a key with an appropriate "View Docs" link. If the key is there, "View Docs" points to the value. If not, use existing logic.
This also allows us to link to docs other than the source material generating the tooltip, which improves the user experience by bringing them to relevant new information instead of the same content in a different place.
https://github.com/pomerium/pomerium-console/issues/2375
=> Docs: Add 'more' key for 'View Docs' value

internal/directory/azure/api.go, internal/directory/azure/azure_test.go
Users that are created in active directory that have not been granted access to Microsoft Exchange do not have an email address however the upn claim is present in the JWT. Currently, the email is transformed incorrectly as it assumes all users without an email are guest accounts, which isn't always the case. Instead we should check if the user is an internal or external user and only apply the transformation on external (guest) users.
=> Extract email for active directory users that don't have access to exchange

internal/log/log.go, pkg/storage/encrypted.go, pkg/storage/encrypted_test.go
Currently when decrypting records in the databroker we modify the type URL to match the record type. It is sometimes useful to store records with a different type URL from the type URL used to represent the data itself. This PR updates the decryption code to preserve the type URL on the record.
Also we weren't using the context when logging errors.
https://github.com/pomerium/internal/issues/799
=> databroker: use contextual logging for errors, use original record type for encryption

docs/.vuepress/config.js
Add 0-17-0 to vuepress menu and set default text to v0.17.
N/A
=> docs: v0.17 release vuepress config

authorize/evaluator/evaluator.go, authorize/evaluator/evaluator_test.go, authorize/grpc.go, authorize/grpc_test.go, authorize/log.go
Add the source IP address so it can be used for rego evaluation.
- https://github.com/pomerium/internal/issues/799
=> authorize: add request IP to rego evaluation

docs/.vuepress/config.js
Adds a template file used to create TCP route examples to the exclusion list for the sitemap.
Coverage issue warnings from Google.
=> Docs: exclude template from sitemap

pkg/protoutil/struct.go, pkg/protoutil/struct_test.go
One easy way to support converting any protobuf message into a `structpb.Struct` is to run it through `protojson.Marshal`/`protojson.Unmarshal`. This PR adds code to `ToStruct` to handle protobuf messages..
- https://github.com/pomerium/internal/issues/799
=> protoutil: add support for converting arbitrary protobuf messages into structs

docs/docs/k8s/ingress.md
Documents the order in which routes are applied when using the Ingress Controller.
Documents https://github.com/pomerium/ingress-controller/pull/145
=> Docs: Ingress routing order

docs/docs/k8s/helm.md, docs/guides/upstream-mtls.md
hello.localhost.pomerium.com has no dns record associated with it so won't work without hacking `/etc/hosts`
The walkthrough also issues certificates to `*.localhost.pomerium.io`
=> Correct domain name

docs/enterprise/concepts.md, docs/enterprise/console-settings.yaml, docs/enterprise/reference/configure.md
Documents that managers in different Namespaces can create alternate routes to the same service. Includes possible solutions.
Also adds some form to the "Configure" section of Enterprise Reference docs.
Fixes https://github.com/pomerium/pomerium-console/issues/1637
=> DOCS: Document duplicate routes in Console

docs/docs/architecture.md, docs/reference/readme.md, docs/reference/settings.yaml
Adds clarification on how config files/environment variables are set when using Pomerium in all-in-one versus split service modes.
Resolves #3095
=> Clarify configuration between modes

docs/docs/tcp/git.md, docs/docs/tcp/mysql.md, docs/docs/tcp/rdp.md, docs/docs/tcp/redis.md, docs/docs/tcp/service-template.md, docs/docs/tcp/ssh.md
Added a note to existing TCP example pages. It specifies that we assume an existing TCP route and links to the related documentation.
=> DOCS: Note assumed TCP route on all examples

docs/enterprise/console-settings.yaml, docs/enterprise/reference/manage.md
Documents the main routes page of the Enterprise Console in the Enterprise Reference documentation.
Fixes https://github.com/pomerium/pomerium-console/issues/2191
=> DOCS: Expand Enterprise Route Reference

docs/enterprise/metrics.md
Updates the Enterprise docs' explanation of the `metrics_address` key.
Note: We discussed using FQDN, but I opted for local DNS based on the warning in the `metrics_address` reference copy.
Fixes https://github.com/pomerium/docs/issues/29
=> Docs: Update metrics address copy

docs/docs/k8s/helm.md
The namespace for pomerium is not created during the walkthrough so running the command to create the tls secret fails.
``` bash
% kubectl create secret tls pomerium-tls-ca --namespace=pomerium \
--cert="$(mkcert -CAROOT)/rootCA.pem" --key="$(mkcert -CAROOT)/rootCA-key.pem"
error: failed to create secret namespaces "pomerium" not found
```
This PR adds the creation of the namespace before running the tls secret command.
=> Add missing namespace creation for pomerium

docs/guides/local-oidc.md
See https://github.com/pomerium/pomerium/issues/2930.  I think https://github.com/pomerium/pomerium/pull/3035 was incomplete.
=> docs: update default verify port to 8000

internal/directory/azure/azure.go, internal/directory/azure/azure_test.go, internal/directory/github/github.go, internal/directory/github/github_test.go, internal/directory/gitlab/gitlab.go, internal/directory/gitlab/gitlab_test.go, internal/directory/google/google.go, internal/directory/google/google_test.go, internal/directory/okta/okta.go, internal/directory/okta/okta_test.go, internal/directory/onelogin/onelogin.go, internal/directory/onelogin/onelogin_test.go, internal/directory/ping/config.go, internal/directory/ping/config_test.go
Add support for non-base64-encoded service accounts.
Fixes #3147
=> directory: support non-base64 encoded service accounts

ui/src/components/Avatar.tsx
We were using `.pop` which modifies the original array leading to weird behavior where the next react render would show the default avatar image instead of the profile picture. Using `[0]` instead fixes it.
Fixes #3146.
=> userinfo: fix missing profile picture

docs/docs/identity-providers/google.md, examples/config/config.docker.yaml
- Adds `config.yaml` example config
- Documents the error a user gets when the service account is not configured.
- Adds commented service account key to docker config example.
Fixes #3139
=> Docs: Google IDP without Service Account

docs/.vuepress/styles/palette.styl, docs/enterprise/pomerium-console_serve.yaml, docs/enterprise/reference/config.md, scripts/generate-console-pages.js
- Updates the Pomerium Console config values page with the latest updates from console.
- Converts the page to table format.
https://github.com/pomerium/pomerium-console/pull/2390
=> Docs: Convert Console Config to Table

docs/docs/k8s/helm.md, docs/docs/k8s/ingress.md
- First commit alphabetizes table of annotations.
- ~Second commit adds `ingress.pomerium.io/default-cert-secret` to a tooltip, pointing to the annotations documentation in the project README (staged)~.
- Third commit undoes the second, and documents defining a default cert as a Helm configuration option.
Documents https://github.com/pomerium/ingress-controller/pull/151
Blocked by https://github.com/pomerium/pomerium-helm/pull/276
=> Docs: document default cert annotation.

internal/directory/github/github_test.go, internal/directory/github/graphql.go
When a user logged in using the GitHub IDP we were overriding the groups with a single group: `[""]`. The reason this was happening was because we weren't requesting the team slug back from the GraphQL API. This code updates the GraphQL query to return the team slug and also updates the test to make sure we are querying the API properly. 
Fixes https://github.com/pomerium/pomerium/issues/3160
=> github: fix missing groups

.github/workflows/release.yaml
The `master` branch is being deprecated.
N/A
=> ci: update setup-gcloud to use v0

Dockerfile.debug
Starting in `go` 1.18, `go get` no longer works outside of a module.  This updates to the now required `go install` syntax for retrieving `dlv` in our Debug image.
n/a
=> deployment: update syntax installing `dlv` in debug image

docs/docs/readme.md, docs/enterprise/install/readme.md, docs/guides/traefik-ingress.md
- Adds enterprise demo install video to enteprise -> install index page.
- Adds intro video to main docs landing page.
- Adds `rel=0` to existing youtube embed.
=> DOCS: Add New Videos to Docs Pages

.devcontainer/Dockerfile, .github/Dockerfile-cloudrun, .github/Dockerfile-release, .github/Dockerfile-release-debug, .github/Dockerfile-release-debug-nonroot, .github/Dockerfile-release-nonroot, Dockerfile, Dockerfile.debug, examples/mutual-tls/Dockerfile, internal/testutil/testdata/Dockerfile
Pinning docker dependencies. I thought this wouldn't work because the digest manifests were platform-specific, but it turns out there's a hash of the manifest file which should work.
=> try pinning docker dependency

config/envoyconfig/clusters.go, config/envoyconfig/clusters_test.go, config/envoyconfig/tls.go, config/envoyconfig/tls_test.go, go.mod, go.sum, scripts/get-envoy.bash
Upgrade to envoy 1.21.1. `matchSubjectAltNames` was deprecated so I updated the config generation to use `matchTypedSubjectAltNames`.
Fixes https://github.com/pomerium/internal/issues/709
=> envoy: upgrade to 1.21.1

authenticate/handlers.go, authenticate/handlers/webauthn/webauthn.go, authenticate/middleware.go, internal/urlutil/url.go
The WebAuthn handler was checking the HMAC on the URL against the internal authenticate URL, but the HMAC was generated for the external authenticate URL.
Fixes https://github.com/pomerium/pomerium/issues/3191
=> authenticate: fix internal url with webauthn

docs/docs/topics/data-storage.md, docs/docs/troubleshooting.md
This adds details on how and when to execute the FLUSHALL command for the Redis storage backend.
Closes [#159](https://github.com/pomerium/pomerium/issues/3187)
=> feat(docs) Add Redis FLUSHALL doc on how and when to execute commands

config/config.go, config/config_source.go, config/envoyconfig/bootstrap_test.go, config/envoyconfig/builder.go, config/envoyconfig/clusters.go, config/envoyconfig/clusters_test.go, config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go, config/envoyconfig/routes.go, config/envoyconfig/routes_test.go, config/metrics.go, config/options.go, internal/cmd/pomerium/pomerium.go, internal/controlplane/http.go, internal/controlplane/server.go, internal/registry/reporter.go
Fix the debug and metrics endpoints so they appear on a different listener. 
Fixes https://github.com/pomerium/internal/issues/816
=> authenticate: fix debug and metrics endpoints

authorize/evaluator/headers_evaluator_test.go, authorize/evaluator/opa/policy/headers.rego
Add a name claim to the assertion JWT.
Fixes https://github.com/pomerium/pomerium/issues/3216
=> authorize: add name claim

docs/reference/readme.md, docs/reference/settings.yaml
Corrects `override_certificate_name` type to `string`
=> DOCS: Reference Hotfix

Makefile, docs/enterprise/console-settings.yaml, docs/enterprise/reference/configure.md, docs/reference/settings.yaml, scripts/generate-settings-docs.py
To make it easier for downstream consumers of the yaml reference docs, this PR automatically adds a section UUID for each block of content.  It also adds a `make gen-docs` command to help with re-running the script.
The script changes should keep the yaml consistent in future edits, but the first pass reformats things a bit.  
https://github.com/pomerium/internal/issues/806
=> docs: Add UUID to docs yaml blocks

docs/.vuepress/config.js, package.json, yarn.lock
Adds ~my~ our fork of the plugin `@limdongjin/vuepress-plugin-simple-seo`, which has some minor JS logic fixes, to the Docs site. This plugin gives us the meta tags required to generate Twitter cards.
=> DOCS: add twitter meta tags

authorize/evaluator/evaluator.go, config/http.go
Some libraries (for example OPA) expect the `http.DefaultTransport` to be a `*http.Transport`. However when we override the `DefaultTransport` we replace it with a custom `RoundTripper`, so this interface conversion can't succeed.
This PR changes `NewHTTPTransport` so that it returns a `*http.Transport`. This is done by cloning the default transport and overriding the `DialTLSContext` function to use a custom `tls.Config` when necessary. We also set `ForceAttemptHTTP2` because the default behavior when the `DialTLSContext` is overridden is to disable http/2 entirely:
> ForceAttemptHTTP2 controls whether HTTP/2 is enabled when a non-zero Dial, DialTLS, or DialContext func or TLSClientConfig is provided. By default, use of any those fields conservatively disables HTTP/2. To use a custom …
=> config: fix DefaultTransport so it is still a *http.Transport

pkg/grpc/databroker/leaser.go, pkg/grpc/databroker/leaser_test.go
Adds `databroker.NewLeasers` convenience method that runs multiple concurrent methods within a single lease.
=> add databroker multi lease handlers

config/policy_ppl_test.go, pkg/policy/rules/rules.go
Our custom `object_get` function in rego is used to handle nested path look ups for JSON objects. Currently it uses `/` to indicate we should look inside an object. This PR also adds support for `.`.
- https://github.com/pomerium/pomerium-console/issues/2501
=> ppl: support . in object_get paths

config/envoyconfig/bootstrap.go, config/envoyconfig/bootstrap_test.go, config/envoyconfig/clusters.go, config/envoyconfig/protocols.go
Envoy deprecated the original `http2ProtocolOptions`, this PR updates the bootstrap code to use the newer configuration format, which we already using for policy clusters.
Fixes #819
=> envoy: use typed extension protocol options for static bootstrap cluster

authorize/authorize.go, authorize/check_response_test.go, authorize/evaluator/evaluator.go, authorize/evaluator/evaluator_test.go, authorize/evaluator/headers_evaluator.go, authorize/evaluator/headers_evaluator_test.go, authorize/evaluator/policy_evaluator.go, authorize/evaluator/policy_evaluator_test.go, authorize/internal/store/index.go, authorize/internal/store/index_test.go, authorize/internal/store/store.go, authorize/internal/store/store_test.go, authorize/state.go, go.mod, go.sum
Add support for indexing databroker records by CIDR blocks in rego.
If a record is a struct type and contains an `$index` field with a `cidr` subfield it will be inserted into a patricia tree and can then be retrieved via an IP address that is within the block.
For example this policy:
```rego
package pomerium.policy
allow {
record := get_databroker_record("type.googleapis.com/google.protobuf.Struct", "192.168.0.7")
record.country == "US"
}
```
Will match this record:
```json
{
"$index": { "cidr": "192.168.0.0/16" },
"country": "US"
}
```
- https://github.com/pomerium/pomerium-console/issues/2522
- [] updated docs
=> authorize: add support for cidr lookups

authorize/check_response.go, internal/httputil/router.go
We need to pass the idp id for webauthn registration so the proper session gets updated. Also update the dashboard subrouter on the authenticate service so that static files don't have middleware added to them (they were redirecting to the auth flow when not logged in leading to a blank screen)
- https://github.com/pomerium/internal/issues/830
=> authorize: pass idp id for webauthn url, allow unauthenticated access to static files

docs/enterprise/api.md
Updates the `pip3` example command to use HTTPS instead of SSH, which requires a key.
Slack Discussion
=> DOCS: use https to download python api lib

pkg/storage/inmemory/backend.go, pkg/storage/inmemory/backend_test.go
The in-memory storage backend will deadlock if multiple records are updated in a single call because we call `.Lock` multiple times. This PR fixes that and adds a test so it doesn't happen again.
=> databroker: fix in-memory backend deadlock

authenticate/handlers.go, authenticate/handlers_test.go
Fix the internal service URL dashboard redirect.
- https://github.com/pomerium/internal/issues/837
=> authenticate: fix internal service URL dashboard redirect

authenticate/handlers.go, authenticate/handlers_test.go
(cherry picked from commit 464ccdf7674bdc9e191fdcd5eff9eed7359233c9)
Backport of #3305
=> authenticate: fix internal service URL dashboard redirect (#3305)

config/http.go, config/http_test.go
Fix the reproxy policy transport so that it disables the custom TLS dialer. When the custom TLS dialer is set `transport.TLSClientConfig` is ignored. 
Fixes #3321
=> httputil/reproxy: fix policy transport

docs/enterprise/console-settings.yaml, docs/enterprise/reference/manage.md
Adds a (silly) example of a policy using Rego.
- Closes https://github.com/pomerium/docs/issues/71
- Blocked until https://github.com/pomerium/pomerium/pull/3260 is pulled into a release.
=> DOCS: Add Rego Example

docs/docs/identity-providers/auth0.md
There is a typo in the Auth0 config example, misleading people to configure IDP.
Fixes #3331
=> docs: fix a typo in auth0 config example

config/envoyconfig/builder.go
Reproxy handler is set to nil during config validation in the console and ingress controller, 
that would result in SIGSEGV if `kubernetes_service_account_token` config option is set. 
as `reproxy` package is internal, a fix is to prevent a nil reproxy.
https://github.com/pomerium/ingress-controller/issues/205
=> envoyconfig: prevent nil reproxy handler

.github/workflows/needs-data.yaml
Currently, it's easy to miss issues that have been updated. This makes it so any "NeedsMoreData" labeled issue gets marked with "NeedsDiscussion" for triage. 
N/A
=> ci: use labels to alert of recently updated issues

config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go
Pomerium logs contain `request-id` fields, however it was not exposed in the actual response. 
This PR adds `x-request-id` to every response.
=> add x-request-id in responses

.github/workflows/release.yaml, .github/workflows/test.yaml, Dockerfile, Dockerfile.debug, go.mod, go.sum, pkg/storage/filter.go, pkg/storage/filter_test.go, pkg/storage/index.go, pkg/storage/index_test.go, pkg/storage/stream_filter.go, pkg/storage/stream_filter_test.go
This PR adds a `FilterExpression` type to the storage package. This type represents a query filter derived from a JSON object similar to this:
```json
{
"$and": [
{ "id": "example1" },
{ "$index": "10.0.0.1" }
]
}
```
Supported expressions are:
- `$and`: an array of sub expressions, each of which must be true for `$and` to be true
- `$or`: an array of sub expressions, at least one of which must be true for `$or` to be true
- `id`: for filtering a list of records by the record id
- `$index`: for filtering a list of records by an index value. Only CIDR indexing is currently supported.
The upgrade to 1.18 is necessary to get the new `net/netip` package, which has handy types and functions for implementing the CIDR indexing.
Fixes https://github.com/pomerium/internal/issues/855
=> storage: add filter expressions, upgrade go to 1.18.1

internal/databroker/server.go, pkg/storage/encrypted.go, pkg/storage/inmemory/backend.go, pkg/storage/inmemory/backend_test.go, pkg/storage/inmemory/stream.go, pkg/storage/redis/redis.go, pkg/storage/redis/redis_test.go, pkg/storage/redis/stream.go, pkg/storage/storage.go
Add `recordType` and `FilterExpression` to the arguments for `SyncLatest`. Also updates the in-memory and redis backends to support filtering. Filtering is implemented via a function applied to all the results.
Fixes https://github.com/pomerium/internal/issues/854
Fixes https://github.com/pomerium/internal/issues/853
=> storage: add filtering to SyncLatest

databroker/cache.go, internal/directory/provider.go, internal/identity/providers.go
Currently, IdP settings are required for Pomerium bootstrap config, and it would not 
start up without them. 
Allowing Pomerium to start without IdP configuration allows it to be later configured 
by external source, such as Ingress Controller.
Implements https://github.com/pomerium/internal/issues/862
=> do not require idp set in the bootstrap config, as it may be later configured via the databroker

pkg/storage/postgres/filter.go, pkg/storage/postgres/filter_test.go
Currently when we try to use an `$index: ...` query, we don't check the value to make sure that it's a valid CIDR before attempting to use the GIST index. This results in an error: 
```
{"level":"error","error":"rpc error: code = Unknown desc = ERROR: invalid input syntax for type inet: \"\" (SQLSTATE 22P02)","time":"2022-06-02T16:23:07Z","message":"authorize/store: error retrieving record"}
```
This PR changes the code so that we only use the CIDR index when `$index` is set to a valid IP address or prefix.
Fixes https://github.com/pomerium/internal/issues/872
=> postgres: fix CIDR query

authorize/databroker.go, pkg/storage/storage.go
We were mistakenly using the OPA storage not found error check when retrieving a session or service account. We should've been using our storage not found error check.
- https://github.com/pomerium/pomerium-console/issues/2590
=> authorize: fix not found check

internal/identity/manager/manager.go, internal/identity/manager/manager_test.go
We now support batching Puts on the databroker. This PR updates the identity manager so that it updates the directory with batches instead of 10 at a time concurrently. This dramatically improves performance for large updates.
- https://github.com/pomerium/pomerium-console/issues/2590
=> identity: batch directory updates

authorize/grpc.go
The previous version of the code would not return an error if a user record did not exist:
```go
s := a.forceSyncSession(ctx, ss.ID)
if s == nil {
return nil, nil, errors.New("session not found")
}
u := a.forceSyncUser(ctx, s.GetUserId())
return s, u, nil
```
We inadvertently made this more strict when we switched to querying for the user on-demand. This PR restores the original behavior.
A `user.User` record will not exist unless that specific user logs in via Authenticate. If a service account is created for a user, and the user itself never logs in, then only a `directory.User` record will exist.
- https://github.com/pomerium/pomerium-console/issues/2590
=> authorize: allow missing user for authorization

.github/goreleaser.yaml
Remove the ignore block from goreleaser to build for darwin/arm64.
Fixes #3414
=> goreleaser: remove ignore

authenticate/handlers/webauthn/webauthn.go, internal/httputil/httputil.go, internal/httputil/httputil_test.go
Fix the device enrollment IP address.
Fixes https://github.com/pomerium/internal/issues/858
=> device enrollment: fix ip address

pkg/storage/postgres/backend_test.go, pkg/storage/postgres/postgres.go
Record deletion was failing because we were passing an argument (`indexCIDR`) that was never used.
Fixes #3445 
Delete records in the databroker was broken. This PR fixes it.
=> postgres: fix record deletion

authenticate/authenticate.go, authenticate/identity.go, authenticate/state.go, authorize/authorize.go, authorize/check_response.go, config/config_source.go, config/identity.go, config/options.go, databroker/cache.go, proxy/proxy.go, proxy/state.go
Add support for loading values from files for these options.
- https://github.com/pomerium/pomerium/issues/3441
Users can now load these options from a file instead of an environment variable.
=> config: support files for shared_secret, client_secret, cookie_secret and signing_key

internal/urlutil/data.go, ui/embed.go
When a user receives an authorization error page we have assets on the page pointing to `/.pomerium/` URLs. When in forward-auth mode, these assets are not loaded because `/.pomerium` ends up forwarded to the application server instead of pomerium. This PR embeds all the assets as data URLs, so only a single network request is needed to show an error page.
Unfortunately this results in an uncacheable 4MB response but I don't know how else to fix forward auth.
Fixes #3459 
Fixes the display of errors when using forward auth.
=> userinfo: embed assets as data URLs for forward auth

internal/autocert/manager.go
Continue on certmagic errors instead of returning them. Returning them causes the process to crash.
Fixes https://github.com/pomerium/pomerium/issues/3371
Continue on certmagic errors instead of returning them. Returning them causes the process to crash.
=> autocert: continue on error

authorize/grpc.go, internal/urlutil/forward.go, internal/urlutil/forward_test.go
Traefik sends the path and query string for the original URL as a header named `X-Forwarded-Uri`. Previously we were setting this as the path, but we should've been parsing out the `?` and setting that as the RawQuery.
Fixes https://github.com/pomerium/pomerium/issues/3299
Fixes an escaping bug with Traefik.
=> authorize: fix x-forwarded-uri

authorize/databroker.go, authorize/grpc.go, pkg/storage/querier.go
Currently if a session is updated we may not pick up the update in the Authorize service for a number of seconds. This updates the code to invalidate the cache when a session is updated. This is signaled by a `DataBrokerRecordVersion` number stored in the session cookie. 
Fixes https://github.com/pomerium/internal/issues/830
Fix a bug with sessions.
=> authorize: fix device synchronization

config/options.go, config/options_test.go, pkg/cryptutil/certificates.go
When testing for overlapping certificates we previously only supported testing files. We now support files or base64 encoded bytes.
Fixes https://github.com/pomerium/internal/issues/915
I don't know how to explain this fix to a regular user. We fixed a bug in the internal machinations of pomerium.
=> options: fix overlapping certificate test

pkg/grpc/databroker/leaser.go
Adds `lease_name` to the databroker leaser log to differentiate between various lease holders. 
Only internal logs are affected.
=> add lease name to the log

.github/workflows/test.yaml, Makefile, databroker/cache.go, databroker/cache_test.go, internal/atomicutil/value.go, internal/testutil/redis.go, pkg/grpc/client.go, pkg/grpcutil/client.go, pkg/grpcutil/options.go, pkg/grpcutil/options_test.go, pkg/storage/postgres/backend_test.go, pkg/storage/postgres/registry_test.go, pkg/storage/redis/redis_test.go
Support rotating the shared secret in the databroker by using a function to load the current shared key from the options instead of only doing so on first boot.
Fixes https://github.com/pomerium/internal/issues/928
Support reloading more configuration options without a restart of the process.
=> databroker: support rotating shared secret

authorize/grpc.go, integration/policy_test.go, internal/telemetry/requestid/requestid.go, pkg/storage/querier.go
Add the requestid to the context in the authorize gRPC service so that the later error handler can display it.
Fixes https://github.com/pomerium/internal/issues/924
Fixes a bug preventing the display of the request id on error pages.
=> authorize: add request id to context

.github/dependabot.yaml
Add docker to the dependabot config.
=> depndabot: add docker support

authenticate/authenticate.go, authenticate/handlers_test.go, authenticate/state.go, authorize/authorize.go, authorize/check_response_test.go, authorize/grpc_test.go, authorize/state.go, config/options.go, databroker/databroker.go, databroker/databroker_test.go, internal/atomicutil/value.go, internal/atomicutil/value_test.go, internal/autocert/manager.go, internal/controlplane/events_test.go, internal/controlplane/server.go, internal/identity/manager/config.go, internal/identity/manager/manager.go, internal/identity/manager/sync.go, internal/identity/providers.go, internal/log/log.go, proxy/handlers_test.go, proxy/proxy.go, proxy/state.go
We now have an `atomicutil.Value` type which is a strongly-typed generic `atomic.Value`. This PR looks for anywhere we used `atomic.Value` and replaces it with `atomicutil.Value`. In many places we had custom types like `atomicAuthenticateState` which are now unneeded and were removed.
- https://github.com/pomerium/internal/issues/934
Not user facing
=> atomicutil: use atomicutil.Value wherever possible

.github/Dockerfile-release-debug, .github/Dockerfile-release-debug-nonroot, .github/Dockerfile-release-nonroot
Fix the docker debug images.
Fixes https://github.com/pomerium/pomerium/issues/3504
Fixes the docker containers so that they a user shell and/or are run as a nonroot user.
=> docker: fix debug images

authenticate/handlers.go, authenticate/handlers_test.go, internal/controlplane/http.go, internal/controlplane/server.go, internal/controlplane/server_test.go
Currently we expose a `/.well-known/pomerium` endpoint that returns a JSON object of well known URLs. That endpoint is only accessible from the authenticate service. This PR updates the controlplane so that that URL is now available on the proxy service as well, and so available on any endpoint being handled by Pomerium.
Fixes https://github.com/pomerium/pomerium/issues/3549
Exposes `/.well-known/pomerium` on the Pomerium proxy service.
=> controlplane: add well-known endpoint to the controlplane http handler

.github/workflows/release.yaml
Update the cloudsmith step to publish to any distro instead of just debian.
- https://github.com/pomerium/pomerium-console/issues/2716
=> publish to any-distro

authorize/check_response.go, authorize/check_response_test.go, authorize/grpc.go
Handle `user-unauthenticated` response for deny blocks.
Currently if a policy had an allow block that allowed public access and a deny block that denied a specific user, that policy would not enforce the deny rule and the user would have access. This is because it would not initiate the user authentication process. (Basically it would be treating the user as if they were not logged in)
This PR updates the code so that if `unauthenticated` appears in either the allow or the deny block user authentication will be initiated.
Fixes https://github.com/pomerium/internal/issues/963
=> authorize: handle user-unauthenticated response for deny blocks

.github/workflows/release.yaml
(cherry picked from commit bb2b114a56a03d935b217644a7f766f204570a0e)
Backport #3570
=> publish to any-distro (#3570)

config/envoyconfig/outbound.go, config/envoyconfig/outbound_test.go
Update the envoy config for outbound gRPC requests so that the authority header gets rewritten to match the cluster's destination address.
Fixes https://github.com/pomerium/pomerium/issues/3505
Fixes an issue with route matching for Istio.
=> envoyconfig: add authority header to outbound gRPC requests

authenticate/handlers.go
To give any javascript application the ability to query this endpoint, we should add CORS headers.
- https://github.com/pomerium/documentation/issues/101
=> authenticate: add CORS headers to jwks endpoint

config/config.go, config/config_source.go, config/envoyconfig/acmetlsalpn.go, config/envoyconfig/acmetlsalpn_test.go, config/envoyconfig/clusters.go, config/envoyconfig/filters.go, config/envoyconfig/listeners.go, internal/autocert/manager.go, internal/autocert/manager_test.go, pkg/cmd/pomerium/pomerium.go
Add support for the ACME TLS-ALPN challenge. This makes it so that autocert can provision certificates using the existing HTTPS listener on port 443 without requiring another HTTP server on port 80.
This is implemented by adding config to envoy that causes any requests for the application protocol `acme-tls/1` to be forwarded to a local TLS server. All other requests will be handled as before.
Fixes https://github.com/pomerium/internal/issues/710
=> autocert: add support for ACME TLS-ALPN

internal/autocert/manager_test.go
This test seems to fail in github actions sometimes. Wasn't able to reproduce locally, but hopefully this should prevent it from happening.
- https://github.com/pomerium/pomerium/pull/3590
=> autocert: fix flaky test

pkg/storage/postgres/migrate.go
Remove the not null constraint on the data column of the record changes table. I don't know why data would be null, but apparently it happens.
Fixes https://github.com/pomerium/pomerium-console/issues/2753
=> postgres: remove not null constraint on data column of record changes table

config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go, pkg/cryptutil/certificates.go, pkg/cryptutil/certificates_test.go, pkg/cryptutil/tls.go, pkg/cryptutil/tls_test.go
Currently we only add domains to the envoy config based on routes. This means if we have a route `from.example.com` and a wildcard certificate `*.example.com`, that certificate will only be served to requests from `from.example.com`. So `unknown.example.com` would end up receiving a self-signed certificate. This PR updates the code to also add the `*.example.com` as a handled domain. This domain will have no routes attached to it, but it will serve the proper certificate, so the user would no longer receive a self-signed certificate.
Unlike route matching envoy matches filter chains based on most specific to least specific. So if there is a filter chain for `*.example.com` and another one for `from.example.com`, if a request comes in for `from.example.com` it will be sent to that filter …
=> envoyconfig: add virtual host domains for certificates in addition to routes

authenticate/handlers.go, authenticate/handlers_test.go
Currently if you go to the authenticate service directly (`https://authenticate.localhost.pomerium.io`), we will create a session using an empty `IdentityProviderID`. However when you go to a route (`https://httpbin.localhost.pomerium.io`), the created session will have an `IdentityProviderID` set to an ID generated from a hash of the options. This change occurred when we introduced route-specific identity provider client ids and secrets. As a result of this behavior the sessions for `authenticate.localhost.pomerium.io` and `httpbin.localhost.pomerium.io` are not the same. So if you logout with `https://authenticate.localhost.pomerium.io/.pomerium/sign_out` it will delete the authenticate session but not the httpbin session. And if there is no authenticate session it will attempt to log …
=> authenticate: get/set identity provider id for all sessions

pkg/storage/postgres/backend_test.go, pkg/storage/postgres/postgres.go
Currently if an unknown protobuf type is stored in the database listing records will fail with an error. This PR updates the code to ignore unknown types.
- https://github.com/pomerium/internal/issues/984
=> postgres: handle unknown types

.github/workflows/backport.yaml, .github/workflows/benchmark.yaml, .github/workflows/docker-main.yaml, .github/workflows/release.yaml
Remove the `pin` comments. They were added by a tool to do the initial github action sha references, but we don't actually pin the version.
=> github-actions: remove pin comments

config/codec_type_test.go, config/envoyconfig/listeners_test.go, config/options.go
Previously we defaulted to `http1` when in all-in-one mode. This PR updates the code so that we default to `http2` instead.
The original behavior was because we did not add routes to all virtual hosts resulting in 421s when requests were coalesced on the same HTTP/2 connection. We now can handle these routes, so there's no need to return the 421s anymore.
Fixes https://github.com/pomerium/internal/issues/1010
=> config: default to http2

go.mod, go.sum, internal/chanutil/batch.go, internal/chanutil/batch_test.go, internal/chanutil/chanutil.go, internal/chanutil/merge.go, internal/chanutil/merge_test.go, internal/fileutil/watcher.go, internal/fileutil/watcher_test.go
Update `fileutil` to use `fsnotify` and a polling watcher. The `notify` package we currently use doesn't detect symlink updates.
Fixes #3610
=> fileutil: update watcher to use fsnotify and polling

.golangci.yml
Fix
```
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [linters_context] rowserrcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters_context] structcheck is disabled because of generics. You can track the evolution of the generics support by following the …
```
=> lint: remove deprecated linters

authenticate/handlers.go, authenticate/handlers_test.go, internal/controlplane/http.go, internal/controlplane/server.go, internal/controlplane/server_test.go, internal/httputil/handlers.go
The `/.well-known/pomerium/jwks.json` endpoint currently only exists within the authenticate service. This PR moves it to the control plane so its available from any pomerium service.
If no signing key is provided an empty keyset will be returned.
- https://github.com/pomerium/internal/issues/1016
=> controlplane: move jwks.json endpoint to control plane

pkg/storage/postgres/stream.go
Increase the number of records we fetch from the database for 64 to 4096. This will increase memory usage but should also increase database memory efficiency.
- https://github.com/pomerium/pomerium-console/issues/2921
=> postgres: increase record batch size

config/session.go, config/session_test.go
Service accounts are JWTs with the same format as a `sessions.State`, except they don't have an identity provider ID. This PR updates the loading code to allow empty identity provider IDs.
- https://github.com/pomerium/pomerium/pull/3707
=> config: allow blank identity providers when loading sessions for service account support

config/options.go
The unused key warning warning did not account for the change from `policy` to `routes`. 
Fixes #3506
=> fix unused key warnings in routes

authorize/authorize.go, authorize/evaluator/evaluator.go, authorize/evaluator/headers_evaluator.go, authorize/evaluator/policy_evaluator.go, internal/databroker/server.go
Do not discard context returned by `StartSpan` to properly see call hierarchy.
=> keep trace span context

authorize/databroker.go, authorize/evaluator/evaluator.go, authorize/grpc.go, authorize/internal/store/store.go
* update the `getDataBrokerUser` function to use the cacheable databroker querier.
* run the policy and header evaluators in parallel
* add tracing for the get_databroker_record rego function
- https://github.com/pomerium/internal/issues/1019
=> authorize: performance improvements

config/options.go, config/options_check.go
This PR adds log messages for configuration field checks. 
Note this PR does not analyze PPL.
https://github.com/pomerium/internal/issues/1029
=> add config option check logging

authorize/databroker.go, authorize/databroker_test.go, authorize/grpc.go
The `user.User` object was always being re-queried because we were relying on the `dataBrokerRecordVersion` which is intended for a `session.Session`. So if a `session.Session` were updated after a `user.User` we'd always end up requerying the `user.User`, because its record version number wouldn't change.
This will mean that `user.User` objects will now be cached for 60s.
- https://github.com/pomerium/internal/issues/1019#issuecomment-1304397383
=> authorize: fix user caching

config/config_source_test.go, config/envoyconfig/filemgr/filemgr_test.go, databroker/cache_test.go, internal/autocert/manager_test.go, internal/fileutil/watcher_test.go
The existing temporary directories in tests were created using `filepath.Join` and `os.MkdirAll`.
This PR replaces `filepath.Join` and `os.MkdirAll` with `t.TempDir` in tests. The directory created by `t.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir
=> test: use `T.TempDir` to create temporary test directory

authenticate/handlers.go, authenticate/handlers/userinfo.go, go.mod, go.sum, pkg/grpc/databroker/databroker.go, ui/src/components/GroupDetails.tsx, ui/src/components/UserInfoPage.tsx, ui/src/types/index.ts
Query the directory information for the user info page, but only for enterprise.
Fixes https://github.com/pomerium/internal/issues/1033
=> authenticate: update user info dashboard to show group info for enterprise

internal/httputil/handlers.go, internal/httputil/handlers_test.go
These endpoints should be accessible from any frontend Javascript application, so should have CORS headers added. They accidentally got lost in #3691.
=> controlplane: fix /.well-known/pomerium missing CORS headers

config/envoyconfig/http_connection_manager.go, config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go, config/options.go, config/options_test.go, pkg/cryptutil/tls.go
Only add the `Strict-Transport-Security` header by default when we're using a certificate we don't generate. This should prevent annoying HSTS pinning errors.
Fixes #3741
=> config: disable Strict-Transport-Security when using a self-signed certificate

authenticate/authenticate_test.go, config/envoyconfig/protocols.go, config/options.go, config/options_test.go, internal/log/warnings.go, internal/syncutil/syncutil.go, pkg/cryptutil/tls.go, proxy/proxy_test.go
Make the `cookie_secret` optional. When not set (in all-in-one mode), we will set it to the randomly generated shared key. This will mean on restart that all users will be logged out and have to re-authenticate.
Fixes #3740
=> config: generate cookie secret if not set in all-in-one mode

go.mod, go.sum, pkg/hpke/hpke.go, pkg/hpke/hpke_test.go, pkg/hpke/url.go, pkg/hpke/url_test.go
HPKE is hybrid public key encryption. This PR adds a package that can be used for sealing and opening messages using HPKE from the `github.com/cloudflare/circl` package. These functions will be used to implement asymmetric public key encryption between systems. (Currently implemented using symmetric encryption with the shared key)
- https://github.com/pomerium/internal/issues/1015
=> hpke: add hpke package

config/options.go, go.mod, go.sum, internal/controlplane/http.go, internal/controlplane/server_test.go, internal/handlers/jwks.go, internal/handlers/jwks_test.go, pkg/hpke/hpke.go, pkg/hpke/jwks.go, pkg/hpke/jwks_test.go, pkg/hpke/url.go
Add the HPKE public key to the JWKS endpoint and add code to fetch the HPKE public key from a JWKS endpoint. The format of an X25519 key is defined in [RFC8037](https://www.rfc-editor.org/rfc/rfc8037).
- https://github.com/pomerium/internal/issues/1015
=> hpke: add HPKE key to JWKS endpoint

pkg/protoutil/any.go, pkg/storage/postgres/postgres.go, pkg/storage/postgres/registry_test.go
During upgrade, if some of the protobuf fields are removed, the record would fail to be loaded. 
This PR changes the postgres storage deserialization to ignore unknown JSON fields. 
Fixes https://github.com/pomerium/ingress-controller/issues/441
=> storage: ignore removed fields when deserializing the data

.github/workflows/test.yaml
This test currently always fails and needs to be updated. We don't have an easy way of doing that, so for now disable the test so PRs don't look broken.
- https://github.com/pomerium/pomerium-console/issues/3027
=> ci: disable kubernetes integration test

internal/httputil/cookie.go, internal/httputil/cookie_test.go
Add functions for setting large cookies. They are chunked, with the initial cookie being the length of the subsequent cookie chunks.
- https://github.com/pomerium/internal/issues/1016
=> httputil: add cookie chunker

internal/urlutil/query_params.go, internal/urlutil/time.go, internal/urlutil/time_test.go
Add functions to build and validate issued and expiry timestamps in URLs.
- https://github.com/pomerium/internal/issues/1016
=> urlutil: add time validation functions

internal/httputil/errors.go, internal/httputil/errors_test.go
We shouldn't log `Found` or `OK` "errors".
Fixes #3780
=> httputil: ignore errors < 400

authenticate/handlers.go, authenticate/handlers_test.go, authenticate/identity_profile.go, authenticate/state.go, authorize/check_response.go, authorize/check_response_test.go, authorize/state.go, integration/authorization_test.go, integration/benchmark_test.go, integration/control_plane_test.go, integration/main_test.go, integration/policy_test.go, internal/handlers/sign_in.go, internal/handlers/userinfo.go, internal/sessions/state.go, internal/urlutil/query_params.go, internal/urlutil/time.go, internal/urlutil/time_test.go, pkg/hpke/jwks_test.go, proxy/handlers.go, proxy/handlers_test.go, proxy/identity_profile.go, proxy/proxy_test.go, proxy/state.go, ui/src/components/ClaimRow.tsx, ui/src/components/SessionDetails.tsx, ui/src/components/UserInfoPage.tsx, ui/src/types/index.ts
Rewrite the login flow so that it uses HPKE instead of symmetric encryption via the shared key. 
- https://github.com/pomerium/internal/issues/1016
=> authenticate: implement hpke-based login flow

config/policy_ppl_test.go, pkg/policy/criteria/pomerium_routes.go, proxy/handlers.go, proxy/handlers_test.go
Require a logged in user to return the JWT.
Fixes https://github.com/pomerium/pomerium/issues/3805
=> jwt: require logged in user to return .pomerium/jwt

pkg/derivecert/ca.go, pkg/derivecert/ca_test.go, pkg/derivecert/derivecert.go, pkg/derivecert/pem.go
Creates new certificate authority using a pre-shared key. This certificate authority is generated on the fly and would yield the same private key every time for the given PSK.
This PR creates an utility package `pkg/derivecert` that allows services that have a certain pre-shared key (i.e. Pomerium `shared_secret`) to get automatic TLS without need to share and distribute certs, and provides a better alternative to plaintext (or with disabled TLS cert chain validation) communication, but is not intended to be a replacement for proper mTLS setup.
Certs are intentionally created with very large validity, so that services that start (or restart) would be able to trust them.
=> derive CA from pre-shared key

authenticate/handlers.go, config/envoyconfig/listeners_test.go, config/envoyconfig/routes.go, config/envoyconfig/routes_test.go, config/policy_ppl_test.go, internal/handlers/webauthn/webauthn.go, pkg/policy/criteria/pomerium_routes.go, proxy/data.go
When a user tries to access `/.pomerium/webauthn` we  should make sure they have a session first. Currently they can reach this page, but then it fails when we try to query for the session in code. To kick off login, we need to enforce the required session as part of authorization policy, which means updating the pomerium routes criteria. The logic is now:
1. allow if there's a session and `/.pomerium/` is accessed
2. allow if there's not a session and `/.pomerium/` is accessed, but not `/.pomerium/jwt` or `/.pomerium/webauthn`
3. require a login if `/.pomerium` is accessed
4. fail with non-pomerium-route
- https://github.com/pomerium/pomerium-console/issues/3052
=> webauthn: require session when accessing /.pomerium/webauthn

internal/autocert/manager.go
We currently use the `atomicutil.Value` to store the acme issuer with a zero-value acme issuer. This acme issuer will panic if accessed. Instead we should store nil, which exits early:
```
func (am *ACMEIssuer) HandleHTTPChallenge(w http.ResponseWriter, r *http.Request) bool {
if am == nil {
return false
}
```
However `atomic.Value` doesn't support a nil value, so we can use `atomic.Pointer` which is a generic type that supports nil pointers.
Fixes https://github.com/pomerium/pomerium/issues/3806
=> autocert: use atomic pointer to allow nil

internal/identity/oidc/oidc.go, internal/identity/oidc/oidc_test.go
Fix token revocation. We need to initialize the provider before checking the revocation URL.
Fixes https://github.com/pomerium/pomerium/issues/3763
=> oidc: fix token revocation

authenticate/authenticate.go, authenticate/handlers.go, authenticate/handlers_test.go, authenticate/state.go
Remove the databroker dependency from the authenticate service.
Fixes https://github.com/pomerium/internal/issues/1070
=> authenticate: remove databroker dependency

ui/src/components/Header.tsx
The avatar and logout menu were missing because the authenticate dashboard no longer has a user object (instead it has a profile object)
Fixes https://github.com/pomerium/internal/issues/1067
=> dashboard: fix missing avatar and logout menu

proxy/handlers.go, proxy/handlers_test.go
Fix the sign out redirect URL. It was pointing the dashboard path, but should be pointing to the `/.pomerium/sign_out` path.
Fixes https://github.com/pomerium/internal/issues/1051
=> proxy: fix sign out redirect

.vscode/launch.json, authorize/state.go, config/config.go, config/http.go, pkg/hpke/jwks.go, proxy/state.go
When using custom CA, either supplied via `certificate_authority`/`certificate_authority_file`, or a custom certificate added to a system store, i.e. `mkcert --install`, `authz_check` and `proxy` were not able to communicate to the authenticate endpoint in order to fetch the signing public key. 
Apparently, installing a custom `TLSDialer` is not sufficient, and all requests to the authenticate endpoint would end up with 
EOF. 
This behaviour was observed for both Linux and MacOS using Go 1.19. 
This PR changes the way JWKSKeyFetcher operates, and adds an http Transport option to it, that is customized using current Config.
Related https://github.com/pomerium/internal/issues/1062
=> use tlsClientConfig instead of custom dialer

config/envoyconfig/http_connection_manager.go, config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go, config/envoyconfig/routes.go, config/options.go, config/options_test.go, internal/urlutil/url.go, internal/urlutil/url_test.go, pkg/cryptutil/tls.go, pkg/cryptutil/tls_test.go
The `buildFilterChains` method doesn't make sense anymore. We now add all virtual hosts to all filter chains.
- https://github.com/pomerium/internal/issues/1199
=> envoyconfig: clean up filter chain construction

authorize/grpc.go, config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go, config/options.go, config/policy.go, config/policy_test.go, internal/urlutil/url.go, internal/urlutil/url_test.go
Add support for an extended TCP route definition syntax. Currently we support:
```
tcp+https://redis.example.com:6379
```
This adds support for:
```
tcp+https://proxy.example.com/redis.example.com:6379
```
What this does is add a TLS server name for `proxy.example.com`, with a virtual host for `redis.example.com:6379`. This way if connections from the CLI have a custom Pomerium URL set they will be routed properly.
~~This PR also updates the code so that if you have a certificate for `*.example.com`, only one filter chain will be added for all the routes instead of `*.example.com` and `authenticate.example.com`, ...~~
Fixes https://github.com/pomerium/internal/issues/1199
=> config: add support for extended TCP route URLs

authorize/grpc.go
Currently, if ext_authz gRPC `Check()` call fails with error, the error (that would likely occur due to misconfiguration) would 
not be printed anywhere, and just the `ext_authz_error` would be present in the Envoy log. 
This PR adds logging of underlying reason along with the request-id.
=> authorize: log check() error

internal/identity/manager/manager.go, internal/identity/manager/manager_test.go
I think we were deleting a session when a user refresh failed and then immediately re-adding it. These changes remove the session from the session collection in addition to deleting it so that we don't attempt to refresh these session. 
Fixes https://github.com/pomerium/internal/issues/1207
=> identity: fix expired session deletion

config/config.go, config/config_test.go, config/envoyconfig/listeners.go, pkg/cryptutil/tls.go, pkg/cryptutil/tls_test.go
If deriving certificates is enabled, generate derived certificates instead of self-signed ones. Also add the derived CA to the certificate pool used for the JWKS key fetcher.
We will still see 500s when this option is not enabled, so it does not fix the associated issue.
- https://github.com/pomerium/internal/issues/1062
=> config: generate derived certificates instead of self-signed certificates

pkg/storage/postgres/backend_test.go, pkg/storage/postgres/postgres.go
Instead of skipping unknown records, return them with a struct any of `{"id": "ID"}`.
Previously when we skipped these records we inadvertently stopped a stream early if too many unknown records were returned, because the `stream.pending` list would be empty, so the code would think the stream was complete when in fact there were many more records available that would be returned by subsequent SQL calls.
Fixes https://github.com/pomerium/internal/issues/1207
=> postgres: return unknown records instead of skipping them

config/envoyconfig/listeners.go, config/envoyconfig/outbound.go, config/envoyconfig/outbound_test.go
Previously, we matched all services available in the internal `grpc-control-plane` cluster for the external listener.
This PR changes that by limiting the available services explicitly.
Fixes https://github.com/pomerium/internal/issues/1063
Fixes https://github.com/pomerium/internal/issues/1064
=> explicitly list gRPC services accessible via the gRPC listener

authorize/state.go, config/config.go, internal/httputil/transport.go, proxy/state.go
If we aren't using derived certificates, disable TLS verification because the resulting certificate used by the authenticate service will be self-signed.
Fixes https://github.com/pomerium/internal/issues/1062
=> config: use insecure skip verify if derived certificates are not used

scripts/get-envoy.bash
When using macos and building a docker image the linux binary won't be available because we only download the envoy binary for the current os. This updates the script to download all the binaries. Only one envoy binary is included because we use build constraints:
```go
//go:build darwin && amd64 && !embed_pomerium
```
=> scripts: update get-envoy script to download all binaries

config/options.go
Rename auto TLS option to `tls_derive` for consistency with other options prefixes and console.
=> tls_derive: rename for consistency

.gitignore
`gcloud authenticate` action creates `ghe-creds-*.json` file that need be added to exclusions for `goreleaser` to proceed.
=> add google cloud creds to ignore

authenticate/handlers.go, authenticate/identity_profile.go
When using the authenticate service, always associate the login with the identity provider id chosen by the proxy. This way the authenticate service idp credentials don't have to match the proxy idp credentials. 
Fixes https://github.com/pomerium/internal/issues/1256
=> authenticate: always trust the passed in idp

internal/identity/manager/manager.go, internal/identity/manager/manager_test.go
When the databroker is run with no authenticator, don't attempt to refresh sessions and users.
Fixes https://github.com/pomerium/internal/issues/1257
=> identity: fix nil reference error when there is no authenticator

Dockerfile.debug
Fix the docker debug image by switching to `debian` instead of `alpine`.
Fixes https://github.com/pomerium/pomerium/issues/3914
=> docker: switch to debian

config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go, config/envoyconfig/protocols.go, config/envoyconfig/protocols_test.go
By default envoy rewrites all HTTP headers to lowercase. According to the spec HTTP headers are supposed to be case-insensitive. Unfortunately some applications don't handle this properly. This change makes it so that when using HTTP/1, the case of headers will be preserved to upstream applications.
-  https://github.com/pomerium/pomerium/issues/3935
=> envoyconfig: preserve case of HTTP headers when using HTTP/1

config/envoyconfig/clusters.go, config/envoyconfig/clusters_test.go, config/envoyconfig/envoyconfig.go, config/options.go, config/validate.go
Add additional DNS lookup family options. Default to V4_PREFERRED.
Fixes https://github.com/pomerium/pomerium/issues/3954
=> config: add additional dns lookup families, default to V4_PREFERRED

databroker/cache.go
When no provider is defined there's a log message about how the databroker failed. This PR removes that message.
=> remove log message when no provider defined

internal/identity/oauth/apple/apple.go, internal/sessions/cookie/cookie_store.go
Fix the `UpdateUserInfo` call so that refreshing sessions doesn't kill the session anymore.
Fixes https://github.com/pomerium/pomerium/issues/3973
=> apple: fix userinfo

authenticate/state.go
Save the session cookie with a different name so that it doesn't collide with the proxy session cookie.
- https://github.com/pomerium/internal/issues/1278
=> authenticate: save the session cookie with a different name

authenticate/handlers.go
Typically we use SameSite=lax for the CSRF cookie. For Apple we need to use SameSite=none.
Fixes https://github.com/pomerium/pomerium/issues/3972
=> authenticate: only use csrf none for apple

pkg/webauthnutil/options.go, pkg/webauthnutil/options_test.go
Currently we return all the known device credentials when generating the request options. This filters the list of device credentials to only those for the given type.
Fixes https://github.com/pomerium/pomerium/issues/3909
=> webauthn: only return known device credentials that match the given type

authenticate/handlers.go
The `sign_out` endpoint shouldn't require a session to access.
Fixes https://github.com/pomerium/pomerium-console/issues/3103
=> authenticate: don't require a session for sign_out

config/envoyconfig/routes.go
When in split mode, authenticate service may either be exposed directly or be proxied by the `pomerium-proxy` service.
This PR changes the handlers to be installed for both `authenticate_service_url` and `authenticate_internal_service_url` virtual hosts.
Fixes https://github.com/pomerium/internal/issues/1285
=> authenticate: fix callback handler for split mode

authenticate/handlers.go
Per-route IDP credentials use a `pomerium_idp_id` query string parameter to indicate which credentials they need. The current code is not working because the `pomerium_idp_id` is inside an HPKE encrypted query string. This updates the code to decrypted the URL parameters to find it.
Fixes https://github.com/pomerium/pomerium/issues/3976
=> authenticate: fix identity provider id in encrypted query string

config/config.go, config/config_test.go, config/envoyconfig/listeners_test.go, config/envoyconfig/tls_test.go, config/options_test.go, pkg/cryptutil/certificates.go, pkg/cryptutil/tls_test.go, pkg/derivecert/ca.go
Generate certificates from the `deriveca` package instead of self-signed random ones. This will make it so that certificates are always the same for the same shared key.
Fixes https://github.com/pomerium/pomerium/issues/3985
=> cryptutil: generate certificates from deriveca

authorize/check_response.go, authorize/check_response_test.go, config/envoyconfig/routes.go, config/envoyconfig/routes_test.go, internal/urlutil/known.go, pkg/policy/criteria/pomerium_routes.go
The route `/.pomerium/webauthn`, is granted access via the special `pomerium` policy criterion. However when a policy defines a `deny` rule, that rule will take precedent over the `allow` rule. As a result, if there's a device `deny` rule on a route, it will cause an infinite redirect loop to the `/.pomerium/webauthn` path.
This PR updates the `requireWebauthnResponse` so that it always allows access to `/.pomerium/webauthn`.
Fixes https://github.com/pomerium/pomerium-console/issues/3210
=> authorize: allow access to /.pomerium/webauthn when policy denies access

authorize/check_response_test.go, config/config.go, internal/controlplane/http.go, internal/controlplane/server_test.go, internal/handlers/hpke_public_key.go, internal/handlers/hpke_public_key_test.go, internal/handlers/jwks.go, internal/handlers/jwks_test.go, internal/urlutil/known.go, pkg/hpke/hpke.go, pkg/hpke/http.go, pkg/hpke/http_test.go, proxy/proxy_test.go
Publishing the HPKE public key to the jwks endpoint caused problems. This PR moves it to a separate endpoint.
Fixes https://github.com/pomerium/pomerium/issues/4029
=> hpke: move published public keys to a new endpoint

authorize/evaluator/evaluator.go, authorize/evaluator/evaluator_test.go, authorize/evaluator/headers_evaluator.go, authorize/evaluator/headers_evaluator_test.go, authorize/evaluator/opa/policy/headers.rego, authorize/evaluator/policy_evaluator_test.go, authorize/internal/store/store.go, internal/controlplane/server_test.go, internal/handlers/well_known_pomerium.go, internal/handlers/well_known_pomerium_test.go
Move the sign out and JWKs URLs to the route. Update the issuer so that it's by the route not by authenticate.
https://github.com/pomerium/pomerium-console/issues/3222
=> authorize: move sign out and jwks urls to route, update issuer for JWT

authenticate/authenticate.go
The config was not stored on authenticate initialization, and was only applied on config change.
=> store authenticate state on creation

authenticate/config.go, authenticate/handlers.go
The user identity protobuf passed by the authenticate may need be stripped down from unnecessary information. Adds a hook to customize the behaviour. 
Related: https://github.com/pomerium/pomerium-zero/issues/35
=> authenticate: have an option to trim the contents of the callback

.github/workflows/benchmark.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml, .tool-versions, go.mod, scripts/get-envoy.bash
Upgrade go to 1.20.3. Upgrade envoy to 1.25.5.
Fixes https://github.com/pomerium/internal/issues/1335
=> dependencies: upgrade go and envoy

authorize/evaluator/evaluator.go, authorize/evaluator/headers_evaluator.go, authorize/evaluator/headers_evaluator_test.go, config/envoyconfig/listeners.go, config/envoyconfig/route_configurations.go, config/envoyconfig/route_configurations_test.go, config/envoyconfig/routes.go, config/envoyconfig/routes_test.go, config/from.go, config/from_test.go, config/policy.go, internal/autocert/manager.go
Adds support for from addresses like `https://*.example.com`.
- https://github.com/pomerium/internal/issues/1329
Adds support for `*` in from addresses that will match 0 or more characters. This can occur anywhere inside the host part of the URL.
=> config: add support for wildcard from addresses

internal/autocert/manager.go
The certmagic cache starts by using the `certmagic.Default` config, which uses a default logger, so when we set it on our `certmagic.Config` it doesn't use the right logger. This updates the code so we don't use `NewDefault` but set the cache ourselves.
Fixes https://github.com/pomerium/pomerium/issues/4133
=> autocert: fix certmagic cache logging

config/options.go, config/options_test.go, internal/autocert/manager.go
Default to `authenticate.pomerium.app` when the authenticate URL is not specified. This allows pomerium to run without needing to configure an identity provider.
Fixes https://github.com/pomerium/internal/issues/1323
=> config: default to authenticate.pomerium.app when authenticate url is not specified

authenticate/handlers.go, go.mod, internal/urlutil/known.go, internal/urlutil/known_test.go, pkg/hpke/url.go, pkg/hpke/url_test.go
Add a v2 HPKE mechanism that compresses the query string using zstd. Zstd is similar to Gzip but faster. We use the highest compression ratio. Using the Apple IDP I saw a decrease from 3k to 2k in request URL size.
The authenticate service will respond using the hpke version that was used by the client. So this should be backwards compatible with v22 clients.
- https://github.com/pomerium/pomerium-zero/issues/35
=> hpke: compress query string

config/config.go, config/config_test.go, config/envoyconfig/listeners_test.go, config/options.go
An Ingress Controller has the following runtime environment specifics: 
- port-mapped (8443:443) due to non-root container requirements,
- the authenticate service URL may not be accessible from _inside_ the cluster - one example is performing Quickstart with `https://authenticate.localhost.pomerium.io` in a popular Docker Desktop environment
The authenticate endpoint is essential as it hosts `/.well-known/pomerium/hpke-public-key` which is consumed by Proxy and Authorize components. 
In order to overcome that limitation, IC [sets](https://github.com/pomerium/ingress-controller/blob/120b0d9068947ace23bbbe2f2ba0df5341e81c76/pomerium/ctrl/bootstrap.go#L52-L65) `authenticate_internal_service_url` to `https://localhost:8443`.
There are two issues this PR addresses: 
Current implementation of …
=> fix WillHaveCertificateForServerName check to be strict match for derived cert name

pkg/envoy/envoy_darwin.go
Rename unused 'ctx' parameter to '_'.
n/a
=> fix lint warning in pkg/envoy

config/envoyconfig/http_connection_manager.go, config/envoyconfig/listeners.go, config/envoyconfig/route_configurations.go, config/envoyconfig/route_configurations_test.go, config/envoyconfig/routes.go, config/envoyconfig/routes_test.go, config/options.go, config/options_test.go
Currently we selectively remove the `Strict-Transport-Security` header for routes that use a generated certificate. This is done to help prevent the occurrence of an error page that requires users to manually type `thisisunsafe` to bypass.
We do this by searching the entire list of certificates for any that match the route. If there are none, we assume the certificate used will be a generated one and remove the `Strict-Transport-Security` header.
This PR updates the code to instead look for any certificates at all. If at least one certificate is supplied, we will assume the user would prefer to have this header added. If none are supplied, we will assume Pomerium is running in an entirely generated mode where the inclusion of this header is more annoying than helpful.
- …
=> config: simplify default set response headers

authorize/evaluator/headers_evaluator.go, authorize/evaluator/headers_evaluator_test.go
After the recent changes to internal policy evaluation, the /.pomerium/jwt endpoint was returning empty strings for the JWT `aud` and `iss` claims.
Fixes #4210
Fix an issue where the /.pomerium/jwt endpoint returned a JWT missing the audience and issuer claims.
=> authorize: populate issuer even when policy is nil

Dockerfile, Dockerfile.debug
=> dependencies: pin node to lts

config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go, integration/main_test.go, integration/policy_test.go
Currently, client certificate validation is performed within the authorize service, after user login. Instead, configure Envoy to perform certificate validation itself, at the time of the initial connection.
When a client certificate authority is configured, Envoy will reject any connection attempts that do not present a valid client certificate corresponding with a trust chain rooted at the configured certificate authority.
For end users without a client certificate configured in their browser, after this change they will see a browser default error page, rather than an HTML error page served by Pomerium.
=> configure Envoy to validate client certificates

.github/workflows/lint.yaml
Fixes failing `lint` workflow by pinning specific compatible versions.
=> ci: fix lint workflow

.github/Dockerfile-release, .github/Dockerfile-release-debug, .github/Dockerfile-release-debug-nonroot, .github/Dockerfile-release-nonroot, Dockerfile
The debian 'stable' images configure apt to install from the rolling 'stable' repository, rather than a specific Debian release. Thus even though we pin to a specific Docker image digest, the packages installed by 'apt-get' can change when a new Debian release is promoted to stable.
Instead, pin to an image where apt is configured to install from repositories for a specific Debian release (in this case, bullseye).
=> pin to a debian:latest image for casource base image

authorize/evaluator/headers_evaluator_test.go, authorize/evaluator/opa/policy/headers.rego
Rego will sometimes serialize integers to JSON with a decimal point and exponent. I don't completely understand this behavior.
Add a workaround to headers.rego to convert the JWT "iat" and "exp" timestamps to a string and back to an integer. This appears to cause Rego to serialize these values as plain integers.
Add a unit test to verify this behavior. Also add a unit test that will fail if the Rego behavior changes, making this workaround unnecessary.
Fixes #4149.
Simplify the Pomerium JWT timestamp format for better compatibility with some JWT parsing libraries.
=> add JWT timestamp formatting workaround

.github/Dockerfile-release, .github/Dockerfile-release-debug, .github/Dockerfile-release-debug-nonroot, .github/Dockerfile-release-nonroot, Dockerfile
Backport d96ca0611afbb9d1358dad35aee73e1cdcca0716 from #4250.
=> pin to a debian:latest image for casource base image (#4250)

.github/workflows/benchmark.yaml, .github/workflows/docker-main.yaml, .github/workflows/docker-version-branches.yaml, .github/workflows/lint.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml
Fix for this error:
> Restore cache failed: Dependencies file is not found in /home/runner/work/pomerium/pomerium. Supported file pattern: go.sum
Also consolidate some tasks and switch to builtin caching.
=> ci: updates

config/options_test.go, internal/identity/oidc/azure/microsoft.go, internal/identity/oidc/azure/microsoft_test.go, internal/identity/oidc/google/google.go, internal/identity/oidc/google/google_test.go
Allow users to clear the default Azure and Google auth code options, by explicitly setting an empty idp_request_params map.
To do this in a YAML config file, set:
idp_request_params: {}
This is the idea suggested in https://github.com/pomerium/pomerium/pull/4251#issuecomment-1595115320.
Allow default IdP request params to be removed, by explicitly setting an empty `id_request_params` map.
There is also a default Apple auth code option, but the behavior there is different — it's always applied, being merged with any additional `idp_request_params`: https://github.com/pomerium/pomerium/blob/1f839554c9ed0016a4168224bd850e6acf8e36ff/internal/identity/oauth/apple/apple.go#L60-L62
I'm not sure we should change the behavior there without further discussion, as that would be a breaking change.
=> Allow clearing default Azure and Google auth code options

authenticate/handlers.go, authenticate/identity_profile.go
Currently the Authenticate.storeIdentityProfile() method always emits an Error log. If there is no error from cookieChunker.SetCookie(), this results in an empty log entry:
{"level":"error","time":"2023-06-27T23:56:38Z"}
Refactor this method to instead return the error from SetCookie(), and update the calling code so that it logs a message only when this error is non-nil.
(Moving the log call to the calling method gives access to the request context, so the log entry will include the request ID and other related info.)
n/a
n/a
=> authenticate: remove extraneous error log

go.mod
Somehow we've ended up with three `require` blocks in the go.mod file.
Combine indirect dependencies into a single require block. Move all direct dependencies to the first require block.
n/a
n/a
=> organize go.mod

authorize/check_response.go, authorize/check_response_test.go, integration/policy_test.go
If an authorization policy requires a client certificate, but an incoming request does not include a valid certificate, we should serve a deny error page right away, regardless of whether the user is authenticated via the identity provider or not. Do not redirect to the identity provider login page in this case.
Update the existing integration tests accordingly.
- #4347
=> authorize: do not redirect if invalid client cert

authenticate/handlers_test.go, pkg/cryptutil/hmac_test.go
Remove fmt.Sprintf() calls where the format string contains no formatting verbs.
=> chore: unnecessary use of fmt.Sprintf

config/config.go, internal/autocert/manager.go, internal/urlutil/hostedauthenticate.go, internal/urlutil/hostedauthenticate_test.go, pkg/hpke/stub.go, pkg/hpke/stub_test.go
Fetch the HPKE public key only when configured to use the hosted authenticate service. Determine whether we are using the hosted authenticate service by comparing the resolved authenticate domain with a hard-coded list of hosted authenticate domains.
Extract this list of hosted authenticate domains to the internal/urlutil package in order to keep a single source of truth for this data.
Fixes #4354.
=> stub out HPKE public key fetch for self-hosted authenticate

config/envoyconfig/envoyconfig.go, config/log.go, config/log_level.go, config/options.go, internal/log/log.go, internal/log/log_test.go, pkg/envoy/envoy.go, pkg/envoy/misc.go
Validate the `log_level` and `proxy_log_level` options to prevent envoy crashing on invalid values.
The supported log levels are the superset of all the know log levels from our documentation, envoy and zerolog, because this option was previously unconstrained, so this should not be a breaking change.
- https://github.com/pomerium/internal/issues/1452
=> config: validate log levels

.github/workflows/docker-main.yaml
Update the 'Docker Main' GitHub Action workflow to update the deprecated ::set-output command to use the newer environment file mechanism.
#4358
=> replace docker publish action ::set-output usage

internal/autocert/certmagic_logger.go, internal/autocert/certmagic_logger_test.go, internal/autocert/manager.go
Suppress "no OCSP server specified in certificate" errors. These errors are generated in the certmagic package and logged with a zap logger, so we need to implement a custom zap core to remove them.
Fixes #4245
=> autocert: suppress OCSP stapling errors

config/envoyconfig/lua.go, config/envoyconfig/luascripts/set-client-certificate-metadata.lua
Add a new Lua filter that will store client certificate info as dynamic metadata. This will allow us to configure client certificate validation at the Envoy listener level, and then pass the results of that validation into our ExtAuthz service.
This also allows us to pass the entire client certificate chain (and not just the leaf certificate, which is how the 'include_peer_certificate' ExtAuthz setting behaves). This will allow us to add support for intermediate CA certificates supplied by the client.
However, if a client certificate does not validate successfully by Envoy, we will not store the certificate chain. (This should help guard against any possibility of making policy decisions based on unvalidated client certificate data.)
#4352
=> envoy: add a filter to store client cert info

authorize/evaluator/evaluator.go
There's a `//nolint` comment in `evaluator.New()`. Let's update the for loop variable to avoid it.
n/a
=> authorize: remove a nolint directive

config/envoyconfig/tls.go, config/envoyconfig/tls_test.go
When building an upstream validation context for a particular URL, check whether the hostname is an IP address. If so, configure the SAN match to use type IP_ADDRESS rather than DNS.
Resolves #4379.
Fix TLS certificate validation logic for routes where the `to` URL uses https with an IP address.
=> envoy: configure upstream IP SAN match as needed

authorize/evaluator/evaluator.go, authorize/evaluator/evaluator_test.go, authorize/evaluator/functions.go, authorize/evaluator/functions_test.go, authorize/grpc.go, authorize/grpc_test.go, config/envoyconfig/filters.go, config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go, config/envoyconfig/testdata/main_http_connection_manager_filter.json, internal/testutil/log.go
Configure Envoy to validate client certificates, using the union of all relevant client CA bundles (that is, a bundle of the main client CA setting together with all per-route client CAs). Pass the validation status from Envoy through to the authorize service, by configuring Envoy to use the newly-added SetClientCertificateMetadata filter, and by also adding the relevant metadata namespace to the ExtAuthz configuration.
Remove the existing 'include_peer_certificate' setting from the ExtAuthz configuration, as the metadata from the Lua filter will include the full certificate chain (when it validates successfully by Envoy).
Update policy evaluation to consider the validation status from Envoy, in addition to its own certificate chain validation. (Policy evaluation cannot rely solely on the …
=> authorize: incorporate mTLS validation from Envoy

authorize/evaluator/evaluator_test.go
In authorize_test.go, the policy 'to' URLs are numbered from 1 to 11. However, there is no number 8 (it looks like it was removed in commit c178819). Update the URLs with numbers 9 through 11 to remove this gap. Update the "any authenticated user" test case to use the corresponding AllowAnyAuthenticatedUser policy (currently this case passes because it's using the policy that allows any GET request, but it's not testing what it says it should).
n/a
=> authorize: fix policy numbers in evaluator test

authorize/check_response.go, authorize/check_response_test.go, authorize/evaluator/evaluator_test.go, authorize/evaluator/policy_evaluator_test.go, pkg/policy/criteria/criteria_test.go, pkg/policy/criteria/invalid_client_certificate.go, pkg/policy/criteria/invalid_client_certificate_test.go, pkg/policy/criteria/reasons.go
Add a new reason "client-certificate-required" that will be returned by the invalid_client_certificate criterion in the case that no client certificate was provided. Determine this using the new 'presented' field populated from the Envoy metadata.
- https://github.com/pomerium/pomerium/issues/4355
Change the "deny" reason logged by the authorize service from "invalid-client-certificate" to "client-certificate-required" in the case that a client certificate was required but no certificate was presented.
=> authorize: add "client-certificate-required" reason

authorize/log.go, authorize/log_test.go, internal/log/authorize.go
Add support for logging the id token. When this field is included in the logs the raw id token will be logged to `id-token` and the decoded claims to `id-token-claims`.
- https://github.com/pomerium/pomerium/issues/4376
=> authorize: add support for logging id token

.github/workflows/test.yaml
Remove the license check.
Fixes https://github.com/pomerium/internal/issues/1482
=> github-actions: remove license check

authorize/evaluator/evaluator.go, authorize/evaluator/evaluator_test.go, authorize/evaluator/functions.go, authorize/evaluator/functions_test.go, authorize/grpc.go, authorize/grpc_test.go, config/envoyconfig/luascripts/set-client-certificate-metadata.lua, config/envoyconfig/testdata/main_http_connection_manager_filter.json, integration/policy_test.go
Partially revert https://github.com/pomerium/pomerium/pull/4374: do not record the peerCertificateValidated() result as reported by Envoy, as this does not work correctly for resumed TLS sessions. Instead always record the certificate chain as presented by the client. Remove the corresponding ClientCertificateInfo Validated field, and update affected code accordingly.
#4396, https://github.com/pomerium/pomerium/issues/4257
=> authorize: do not rely on Envoy client cert validation

internal/autocert/certmagic_logger.go, internal/autocert/certmagic_logger_test.go
The certmagic package now exposes an `ErrNoOCSPServerSpecified` for the OCSP stapling error that we suppress. Let's check for this error using `errors.Is()` rather than performing a substring match on the error text.
Follow-up to https://github.com/pomerium/pomerium/issues/4245.
=> autocert: use new OCSP error type

internal/controlplane/grpc_accesslog.go, internal/controlplane/grpc_accesslog_test.go, internal/log/access.go
Add an `ip` address field for access logs.
- https://github.com/pomerium/pomerium/issues/4377
=> logs: add ip address to access logs

authorize/authorize.go, authorize/evaluator/config.go, authorize/evaluator/evaluator.go, authorize/evaluator/evaluator_test.go, authorize/evaluator/policy_evaluator.go, authorize/evaluator/policy_evaluator_test.go, config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go, config/mtls.go, config/mtls_test.go, pkg/grpc/config/config.pb.go, pkg/grpc/config/config.proto
Add an "enforcement" option to the new downstream mTLS configuration settings group.
When not set, or when set to "policy_default_deny", keep the current behavior of adding an invalid_client_certificate rule to all policies.
When the enforcement mode is set to just "policy", remove the default invalid_client_certificate rule that would be normally added.
When the enforcement mode is set to "reject_connection", configure the Envoy listener with the require_client_certificate setting and remove the ACCEPT_UNTRUSTED option.
Add a corresponding field to the Settings proto.
#4353 
Add an optional stricter client certificate enforcement mode: when `downstream_mtls.enforcement` is set to the value `reject_connection`, Pomerium will reject connection attempts without a trusted client certificate. …
=> config: add new mTLS enforcement setting

authorize/evaluator/evaluator.go, authorize/evaluator/headers_evaluator.go, authorize/evaluator/headers_evaluator_test.go, authorize/evaluator/opa/policy/headers.rego
Add support for a new token `$pomerium.client_cert_fingerprint` in the set_request_headers option. This token will be replaced with the SHA-256 hash of the presented leaf client certificate.
Fixes #4259.
Allow passing the client certificate fingerprint to upstream services, by adding support for the token `$pomerium.client_cert_fingerprint` in the [Set Request Headers](https://www.pomerium.com/docs/reference/routes/set-request-headers) option.
=> authorize: client cert fingerprint in set_request_headers

authorize/evaluator/functions.go, authorize/evaluator/functions_test.go, authorize/evaluator/gen-test-certs.go, authorize/evaluator/headers_evaluator_test.go
Update the isValidClientCertificate() method to consider any client-supplied intermediate certificates. Previously, in order to trust client certificates issued by an intermediate CA, users would need to include that intermediate CA's certificate directly in the client_ca setting. After this change, only the trusted root CA needs to be set: as long as the client can supply a set of certificates that chain back to this trusted root, the client's certificate will validate successfully.
This is in preparation for adding a `max_verify_depth` option, which otherwise wouldn't make sense, as the effective maximum is currently fixed at 1.
Rework the previous CRL checking logic to now consider CRLs for all issuers in the verified chains.
Fixes #4256, related to #4353.
=> authorize: allow client certificate intermediates

config/mtls.go, config/mtls_test.go, config/options_test.go
Return an error from DownstreamMTLSSettings.validate() if both CA and CAFile are populated, or if both CRL and CRLFile are populated.
https://github.com/pomerium/internal/issues/1485
Pomerium will now consider it an error if both `downstream_mtls.ca` and `downstream_mtls.ca_file` are set. Likewise, Pomerium will now consider it an error if both `downstream_mtls.crl` and `downstream_mtls.crl_file` are set.
=> config: extra CA and CRL validation

authorize/evaluator/headers_evaluator.go, authorize/evaluator/headers_evaluator_test.go, authorize/evaluator/opa/policy/headers.rego, config/policy.go
Currently Pomerium replaces dynamic `set_request_headers` tokens sequentially. As a result, if a replacement value itself contained a supported "$pomerium" token, Pomerium may treat that as another replacement, resulting in incorrect output.
This is unlikely to be a problem given the current set of dynamic tokens, but if we continue to add additional tokens, this will likely become more of a concern.
To forestall any issues, let's perform all replacements in one pass, using the `os.Expand()` method. This does require a slight change to the syntax, as tokens containing a '.' (i.e. all of them) will need to be wrapped in curly braces, like `${pomerium.id_token}`.
Resolves https://github.com/pomerium/internal/issues/1501.
=> authorize: rework token substitution in headers

config/policy.go
Log a deprecation warning for any route where `tls_downstream_client_ca` or `tls_downstream_client_ca_file` is non-empty, with a link to the reference page for this setting (the deprecation warning still needs to be added to the documentation, see https://github.com/pomerium/documentation/pull/913).
#4356 
The `tls_downstream_client_ca` and `tls_downstream_client_ca_file` route options are deprecated, and will be removed in a future Pomerium release.
=> config: deprecate tls_downstream_client_ca

internal/retry/config.go, internal/retry/error.go, internal/retry/error_test.go, internal/retry/retry.go, internal/retry/retry_test.go
Adds retry package that performs exponential backoff retry for a given function, 
while also monitoring multiple channels with possible side effect functions.
=> add retry package

config/constants.go, config/custom.go, config/options_test.go
Add a decode hook for the custom `SANMatcher` type. I had added an `UnmarshalJSON()` method for this type in 5568606f03023c1f936ed70b5a41fe3679ba6426 but I forgot that this needs a decode hook in order to be invoked.
Fixes #4463.
=> config: add decode hook for the SANMatcher type

config/envoyconfig/luascripts/set-client-certificate-metadata.lua, config/envoyconfig/testdata/main_http_connection_manager_filter.json
If Pomerium is operating in the `insecure_server` mode (e.g. if there is another reverse proxy in front of Pomerium), then the `ssl()` Lua method will return nil.
Add a check for this case to the set-client-certificate-metadata.lua script, in order to avoid an error when attempting to store the client certificate info.
Fixes #4465.
=> envoy: check for nil ssl() in client cert script

integration/policy_test.go
Add an integration test case to verify certain properties of the Pomerium attestation JWT:
- The 'iat' and 'exp' timestamps should be plain integers.
- The JWT should contain an issuer and audience claim.
- A JWT retrieved from the /.pomerium/jwt endpoint should contain all the same data as a JWT from the X-Pomerium-Jwt-Assertion header.
Integration tests for #4149 and #4210.
=> add integration test for Pomerium JWT

internal/zero/bootstrap/bootstrap.go
- try loading bootstrap config from file before initiating any network calls, to speed up start up
- have all api calls within retry.Retry loop
=> zero: rm extra call on start

pkg/storage/postgres/migrate.go
Add indexes for the postgres storage backend.
Fixes #4441
=> storage: add indexes for postgres

config/options.go, config/options_test.go
Do not allow the combination of 'cookie_same_site: none' and 'cookie_secure: false'.
Cookies with `SameSite=None` must also set the `Secure`option, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#none.
https://github.com/pomerium/pomerium/issues/4482
=> config: validate cookie_secure option

.github/workflows/release.yaml
Update the 'Release' GitHub Action workflow to replace the deprecated `::set-output` command with the newer `$GITHUB_OUTPUT` file mechanism.
- https://github.com/pomerium/internal/issues/1511
=> replace ::set-output in release action

internal/identity/manager/manager.go
When we start the identity manager any existing sessions and users will not be refreshed until after 10 minutes, unless a session or user is updated.
In practice this issue will rarely happen because sessions are updated in the access tracker, so anyone using Pomerium would trigger the identity manager loop check.
=> core/identity: fix slow restart

authenticate/handlers.go, authenticate/identity_profile.go
Validate the identity profile by checking that the oauth token is still valid and calling the user info endpoint. If the access token has been revoked that call should fail and the identity profile will be treated as if it doesn't exist. This will then trigger the re-authentication flow.
- https://github.com/pomerium/internal/issues/1527
=> core/authenticate: validate the identity profile

authorize/databroker.go, authorize/databroker_test.go, authorize/grpc.go, pkg/grpc/session/session.go, pkg/grpc/session/session_test.go, pkg/grpc/user/user.go, pkg/grpc/user/user_test.go
Add a validation check on sessions or service accounts to ensure they don't have expired tokens.
- https://github.com/pomerium/internal/issues/1527
=> core/authorize: check for expired tokens

.github/Dockerfile-release, .github/Dockerfile-release-debug, .github/Dockerfile-release-debug-nonroot, .github/Dockerfile-release-nonroot, Dockerfile
Update our Dockerfiles to debian12 distroless base images and remove the ca-certificates workaround (Debian 12 has dropped the problematic expired root certificate).
I'm not sure how to test this apart from running the actual release workflow.
Fixes https://github.com/pomerium/pomerium/issues/4254.
=> ci: remove ca-certificates workaround

.github/dependabot.yaml
Update our Dependabot configuration so that it will also update the release Dockerfiles in the /.github/ directory.
Hopefully fixes #4255.
=> dependabot: also update release Dockerfiles

internal/telemetry/metrics/providers.go
Add the error in the logs
N/A
I have those errors:
```
{"level":"error","config_file_source":"/etc/pomerium/config.yaml","bootstrap":true,"time":"2023-09-21T06:19:49Z","message":"responding to metrics request"}
{"level":"error","config_file_source":"/etc/pomerium/config.yaml","bootstrap":true,"time":"2023-09-21T06:20:04Z","message":"responding to metrics request"}
{"level":"error","config_file_source":"/etc/pomerium/config.yaml","bootstrap":true,"time":"2023-09-21T06:20:19Z","message":"responding to metrics request"}
```
=> Add metric request error in log

authenticate/handlers.go, authenticate/handlers_test.go, internal/handlers/signedout.go, internal/identity/mock_provider.go, internal/identity/oauth/apple/apple.go, internal/identity/oauth/github/github.go, internal/identity/oidc/auth0/auth0.go, internal/identity/oidc/auth0/auth0_test.go, internal/identity/oidc/cognito/cognito.go, internal/identity/oidc/cognito/cognito_test.go, internal/identity/oidc/oidc.go, internal/identity/providers.go, ui/src/App.tsx, ui/src/components/Header.tsx, ui/src/components/SignedOutPage.tsx, ui/src/types/index.ts
Refactor how IdP sign out works. Instead of a method called `LogOut` we now have a method called `GetSignOutURL` which more accurately describes what `LogOut` was supposed to do. It takes an id token hint and a URL to return to, and returns a new URL that when redirected to will sign the user out of the IdP.
The previous flow is hard to understand. Previously we would return a special error page if neither the redirect URL nor the signout redirect URL were defined. We will now unconditionally redirect, and if neither the redirect URL nor the signout redirect URL are defined, we will redirect to `https://authenticate/.pomerium/signed_out`. Regardless, if the IdP supports sign out, we will redirect there first.
Auth0 and Cognito have custom implementations of `GetSignOutURL` that follows …
=> core/authenticate: refactor idp sign out

internal/zero/bootstrap/new.go
Derive a signing key first. 
Related: https://github.com/pomerium/pomerium-zero/issues/826
=> zero: derive signing key first thing

internal/identity/oauth/apple/apple.go, internal/identity/oidc/oidc.go, internal/identity/oidc/refresh.go, internal/identity/oidc/refresh_test.go
The current session refresh loop attempts to refresh access tokens when they are due to expire in less than one minute. However, the code to perform the refresh relies on a `TokenSource` from the x/oauth2 package, which has its own internal [`expiryDelta`](https://cs.opensource.google/go/x/oauth2/+/refs/tags/v0.12.0:oauth2.go;l=299) threshold, with a default of 10 seconds. As a result, the first four or five attempts to refresh a particular access token will not actually refresh the token. The refresh will happen only when the access token is within 10 seconds of expiring.
Instead, before we obtain a new `TokenSource`, first clear any existing access token. This causes the `TokenSource` to consider the token invalid, triggering a refresh. This should give the refresh loop more control …
=> identity: override TokenSource expiry behavior

internal/identity/manager/data.go, internal/identity/manager/manager.go, internal/identity/manager/manager_test.go
The databroker identity manager is responsible for refreshing session records, to account for overall session expiration as well as OAuth2 access token expiration.
Refresh events are scheduled subject to a `coolOffDuration` (10 seconds, by default) relative to a `lastRefresh` timestamp. Currently, any update to a session record will reset the associated `lastRefresh` value and reschedule any pending refresh event for that session. If an update occurs close before a scheduled refresh event, this will push back the scheduled refresh event to 10 seconds from that time.
This means that if a session is updated frequently enough (e.g. if there is a steady stream of requests that cause constant updates via the AccessTracker), the access token may expire before a refresh ever runs.
To avoid this …
=> identity: preserve session refresh schedule

pkg/hpke/url.go, pkg/hpke/url_test.go
Based on https://pkg.go.dev/tailscale.com/smallzstd we can use a smaller window size and some options to reduce the memory usage for zstd.
Re-using the encoder and decoder appears to be supported based on the packages documentation. The defaults are not a memory leak, but they do use a lot of memory since they are optimized for large payloads. 
- https://github.com/pomerium/pomerium/issues/4652
- #4648
=> core/hpke: reduce memory usage from zstd

internal/controlplane/events_test.go, internal/controlplane/grpc_accesslog.go, internal/controlplane/server.go, internal/controlplane/xds.go
Some performance improvements. Mostly trying to utilize more cores by running more goroutines.
=> core/controlplane: apply configuration changes in a background thread

config/envoyconfig/clusters_test.go, config/envoyconfig/filemgr/filemgr.go, config/envoyconfig/filemgr/filemgr_test.go, config/envoyconfig/filemgr/name.go, config/envoyconfig/filemgr/name_test.go, config/envoyconfig/listeners_test.go
For envoy we use files as a DataSource whenever possible. When we have raw data we save it to a cache directory with a filename like `tls-crt-xxx.pem`. The hash of the filename is computed using the SHA512_256 of the bytes.
For this use case its not necessary to have a cryptographic hash. We can instead use `xxhash` which is much faster. Roughly 10x improvement:
```
// BenchmarkGetFileNameWithBytesHash-10    	   12331	     95284 ns/op	    1657 B/op	      63 allocs/op
// BenchmarkGetFileNameWithBytesHash-10    	  112304	      9472 ns/op	     112 B/op	       5 allocs/op
```
- https://github.com/pomerium/internal/issues/1573
=> core/filemgr: use xxhash instead of sha512 for filenames

internal/controlplane/xdsmgr/xdsmgr.go
Adds `type-url` to XDS logs so that it would be clearer which resource types are updated.
=> xds: add type url to log

internal/events/target.go, internal/events/target_test.go
<s>
Currently the event target pushes an operation onto a channel for each of its methods. This is then handled by a goroutine. Since each of the operations goes through a separate channel, and the channels were defined with a size of 1, it was possible for call order to behave unpredictably. For example:
```go
AddListener(li)
Dispatch(ctx, evt)
```
Could end up with the `Dispatch` occurring before `AddListener`. 
By making these channels synchronous we can avoid this behavior. Now `AddListener` will block until the goroutine picks it up, and `Dispatch` will always happen after `AddListener`.
</s>
Refactor the `events.Target` to use mutexes instead of a background goroutine.
=> core/events: fix flaky test

pkg/grpc/databroker/reconciler.go
Adds `databroker.Reconciler` that operates next to a Syncer and can bring the databroker into a desired 
target state.
=> databroker: add reconciler

authorize/access_tracker.go, authorize/grpc_test.go, internal/handlers/webauthn/webauthn.go, internal/identity/manager/manager.go, internal/identity/manager/manager_test.go, pkg/grpc/session/session.go
Update the AccessTracker, WebAuthn handlers, and identity manager refresh loop to perform their session record updates using the databroker Patch() method.
This should prevent any of these updates from conflicting.
- https://github.com/pomerium/internal/issues/1536
=> rework session updates to use new patch method

authorize/authorize.go, authorize/authorize_test.go, authorize/check_response_test.go, authorize/evaluator/config.go, authorize/evaluator/evaluator.go, authorize/evaluator/evaluator_test.go, authorize/evaluator/policy_evaluator.go, authorize/state.go
Add a parameter to evaluator.New() for the previous Evaluator (if any). If the evaluatorConfig is the same, reuse any PolicyEvaluators for policies that have not changed from the previous Evaluator.
Use the route IDs along with the policy checksums to determine whether a given policy has changed. Similarly, add a new cacheKey() method to the evaluatorConfig to compute a checksum used for determine whether the evaluatorConfig has changed. (Store this checksum on the Evaluator.)
- https://github.com/pomerium/internal/issues/1572
=> authorize: reuse policy evaluators where possible

config/envoyconfig/listeners_test.go, config/options.go, config/options_test.go
If we're using the default `authenticate.pomerium.app` authenticate URL, don't add a route to envoy.
Fixes https://github.com/pomerium/internal/issues/1416
=> core/config: remove unnecessary authenticate route

pkg/grpc/session/session_test.go
Increase unit test coverage for pkg/grpc/session/session.go.
=> session: add unit tests for gRPC wrapper methods

config/constants.go, config/custom.go, config/options_test.go
Add support for string to map conversion for config options, for example:
```
env IDP_REQUEST_PARAMS='{"x":"y"}' ...
```
Fixes https://github.com/pomerium/pomerium/issues/4343
Fixes https://github.com/pomerium/pomerium/issues/4318
=> core/config: add support for maps in environments

pkg/grpc/databroker/changeset.go, pkg/grpc/databroker/reconciler.go, pkg/grpc/databroker/recordset.go, pkg/grpc/databroker/recordset_test.go
it's not enough to compare records using `proto.Equal`, we sometimes need ignore fields such as `version`, `accessed_at`, `updated_at` as they would never be in sync between core and observer.
=> reconciler: allow custom comparison function

pkg/grpc/databroker/changeset.go
Prevents `Record.Data` being `nil` in the deleted records, by setting it to empty `protobuf.Any` of desired type.
Related: https://github.com/pomerium/pomerium/issues/4733
=> databroker: changeset: prevent nil data in the deleted records

pkg/storage/postgres/backend_test.go, pkg/storage/postgres/postgres.go
When deleting a record it's possible to set `data` to be nil. In that case the row would be removed from the `records` table, but there would be an entry in the `record_changes` table with `nil` data. The call to stream changes would then attempt to convert this row into a record and fail with an error. This PR updates the code to tolerate nil data.
Any consuming code would also need to tolerate nil data accordingly. Whether that's the case or not for all known usages is unclear.
Fixes #4733
=> core/storage: fix nil data unmarshal

config/options.go, config/options_test.go
Remove the `Strict-Transport-Security` header when staging autocert is being used.
Fixes https://github.com/pomerium/internal/issues/1577
=> core/config: disable strict-transport-security header with staging autocert

integration/tpl/files/renew-cert.go
Add a utility for updating the integration test certificates. It takes three file paths: the existing certificate, the CA certificate, and the CA key. It will update the NotBefore and NotAfter timestamps and the certificate signature, overwriting the existing certificate.
Example usage:
cd integration/tpl/files
go run renew-cert.go trusted.pem ca.pem ca-key.pem
- https://github.com/pomerium/pomerium/issues/4735
=> integration: add tool for renewing test certs

cmd/pomerium/main.go, internal/zero/cmd/command.go, internal/zero/cmd/env.go, internal/zero/cmd/env_test.go
Currently we only support enabling managed mode using the environment variable `POMERIUM_ZERO_TOKEN`. This PR also adds the ability to enable managed mode using the configuration option `pomerium_zero_token: TOKEN`. This way an existing installation of Pomerium can be converted into managed mode with minimal changes, notably to make managed mode compatible with our existing `.deb` and `.rpm` packages, which use config files by default.
- https://github.com/pomerium/pomerium-zero/issues/1081
=> core/zero: add support for managed mode from config file

internal/zero/bootstrap/bootstrap.go, internal/zero/cmd/command.go, internal/zero/controller/config.go
The /var/cache/ directory may not exist (e.g. on macOS). Instead, create a sub-directory under the path returned by [os.UserCacheDir()](https://pkg.go.dev/os#UserCacheDir) for the bootstrap config file.
- https://github.com/pomerium/internal/issues/1588
=> zero: use os.UserCacheDir for boostrap config path

internal/zero/cmd/command.go
The UserCacheDir()/pomerium is also used to cache envoy keypairs, and it would fail to create files otherwise when non-root.
```
{"level":"error","error":"mkdir /var/cache/pomerium/envoy: permission denied","message":"filemgr: error creating cache directory, falling back to inline bytes"}
```
Related: https://github.com/pomerium/pomerium/pull/4744
=> zero/core: set drwx------ for cache dir

internal/telemetry/metrics/providers.go, internal/telemetry/metrics/providers_test.go
The Pomerium metrics endpoint does not support the protobuf exposition format, and will always respond with text format metrics even if the protobuf format is requested (via the `Accept` header).
However, some of the metrics are collected by replaying the incoming request to an OpenCensus Prometheus metrics [exporter](https://pkg.go.dev/contrib.go.opencensus.io/exporter/prometheus#Exporter), which _does_ support the protobuf format.
When this exporter serves metrics in the protobuf format, Pomerium is unable to parse them, resulting in missing metrics in the response.
This change avoids this specific issue by explicitly setting the `Accept: text/plain` when replaying this request to the exporter.
- https://github.com/pomerium/pomerium/issues/4636
Fix an issue with the metrics endpoint …
=> metrics: explicitly set Accept header

go.mod, go.sum, pkg/counter/counter.go, pkg/counter/counter_test.go
Adds an utility package with linear probabilistic counter, to be used to estimate session statistics 
while only occupying a limited storage space.
Related: https://github.com/pomerium/pomerium-zero/issues/821
=> metrics: add linear probabilistic counter

pkg/storage/postgres/backend.go, pkg/storage/postgres/backend_test.go
Currently when we setup background listeners for change notifications we take a connection from the pgx pool and execute `LISTEN channel`. Once we receive a notification we then put that connection back into the pool.
This leads to two issues: (1) we have less connections available in the pool than we should and (2) connections end up queuing notifications they never consume since the connections never `UNLISTEN` the channels.
This PR updates the code to use a single connection for all `LISTEN`s and `Hijack` it from the connection pool so it doesn't interfere with other requests.
- https://github.com/pomerium/internal/issues/1613
=> core/storage: hijack connections for notification listeners

authenticate/handlers.go
The `Authenticate.getUserInfoData()` method has an error return value, but always returns `nil` for this value. Let's remove this return value from the method signature.
=> authenticate: getUserInfoData() cleanup

internal/authenticateflow/events.go, internal/authenticateflow/stateless.go
Move the Stateless.logAuthenticateEvent() method into the main stateless.go file.
(This was in events.go temporarily so that Git would track the file history as a rename from authenticate/events.go.)
=> authenticateflow: move logAuthenticateEvent

.github/dependabot.yaml
For https://github.com/pomerium/internal/issues/1594
=> core/ci: disable dependabot for npm

internal/authenticateflow/request.go, internal/authenticateflow/stateful.go, internal/authenticateflow/stateful_test.go
Add a new `Stateful` type implementing the stateful authentication flow from Pomerium v0.20 and earlier.
This consists mainly of logic from authenticate/handlers.go previous to commits 57217af and 539fd51.
One significant change is to set the default IdP ID when an IdP ID is not provided in the request URL (e.g. when signing in directly at the authenticate service domain). Otherwise, if session state is stored with an empty IdP ID, it won't be valid for any route.
=> authenticateflow: add stateful flow

pkg/storage/inmemory/backend.go, pkg/storage/storagetest/storagetest.go
The `Patch()` method was intended to skip any records that do not currently exist. However, currently [inmemory.Backend.Patch()](https://github.com/pomerium/pomerium/blob/c01d0e045d59976731c2266202e5b180bbaef445/pkg/storage/inmemory/backend.go#L256) will return `ErrNotFound` if the last record in the records slice is not found (it will ignore any other previous records that are not found).
Update the error handling logic here to be consistent with the postgres backend, and add a unit test to exercise this case.
- https://github.com/pomerium/pomerium/issues/4837
Fix a bug where the session access tracker may repeatedly try and fail to update a session that no longer exists.
=> storage/inmemory: fix Patch() error handling

authenticate/handlers.go, authenticate/handlers_test.go, authenticate/state.go, authorize/state.go, config/options.go, config/options_test.go, proxy/state.go
Update the initialization logic for the authenticate, authorize, and proxy services to automatically select between the stateful authentication flow and the stateless authentication flow, depending on whether Pomerium is configured to use the hosted authenticate service.
=> support both stateful and stateless authenticate

go.mod, go.sum, pkg/zero/cluster/generate.go
Pin openapi codegen and runtime to v1.0.0 
Related: https://github.com/pomerium/pomerium-zero/issues/1397
=> zero/openapi: pin v1.0.0 of a runtime

authenticate/config.go, authenticate/events/events.go, internal/authenticateflow/stateless.go
Commit b7896b3153 moved events.go from the 'authenticate' package to 'internal/authenticateflow' in order to avoid an import cycle. However this location is not actually suitable, as the hosted authenticate service refers to `AuthEvent` and `AuthEventFn`.
Move events.go back out from under 'internal', to a new package 'authenticate/events'. This should still avoid an import cycle between 'authenticate' and 'internal/authenticateflow', while also allowing the hosted authenticate service to use the events types.
=> move events.go out of internal/authenticateflow

integration/authentication_test.go, pkg/slices/slices.go, pkg/slices/slices_test.go
Update the authentication flow integration test to verify that the `pomerium_identity_profile` cookies are not present for the stateful authentication flow.
- https://github.com/pomerium/pomerium/issues/4627
=> integration: check for profile cookies

.github/goreleaser.yaml
In the CI job we currently tag docker images like `pomerium/pomerium:v0.24.0`. This will also tag `pomerium/pomerium:v0.24`.
Fixes https://github.com/pomerium/internal/issues/1368
=> core/ci: tag docker images with vMAJOR.MINOR

internal/zero/controller/controller.go, internal/zero/leaser/leaser.go, internal/zero/leaser/monitor.go, internal/zero/leaser/restart.go, internal/zero/leaser/restart_test.go, internal/zero/reconciler/service.go
This PR groups Zero control loop functions that should run within a lease:
1. resource bundle reconciler
2. analytics
3. telemetry reporter
Also makes sure when the lease holder is restarted, it happens with exponential backoff. 
Related: https://github.com/pomerium/internal/issues/1639
=> zero: group funcs that need run within a lease

databroker/cache.go, internal/controlplane/server.go, pkg/contextutil/contextutil.go, pkg/grpcutil/serve.go, pkg/grpcutil/serve_test.go, pkg/httputil/serve.go, pkg/httputil/serve_test.go
The current implementation of graceful stop for gRPC and HTTP doesn't work properly. It actually ends up shutting down immediately, but it was supposed to wait for 5 seconds to allow any active connections a chance to complete.
This PR adds two new `ServeWithGracefulStop` functions for gRPC and HTTP that should behave as expected.
Fixes https://github.com/pomerium/internal/issues/1599
=> core: fix graceful stop

internal/authenticateflow/stateful.go, internal/authenticateflow/stateful_test.go
The identity manager expects to be able to read session ID and user ID from any deleted databroker session records. The `session.Delete()` wrapper method is not compatible with this expectation, as it calls `Put()` with a record containing an empty session. The stateful authentication flow currently calls `session.Delete()` from its `RevokeSession()` method.
The result is that the identity manager will not correctly track sessions deleted by the the stateful authentication flow, and will still try to use them during session refresh and user info refresh.
Instead, let's change the stateful authentication flow `RevokeSession()` method to perform deletions in a way that is compatible with the current identity manager code. That is, include the existing session data in the `Put()` call to …
=> authenticateflow: change how sessions are deleted

internal/authenticateflow/stateful_test.go
Add assertions for the redirect URL in the unit test for the stateful authentication flow Callback() method. Remove a commented-out line of debug logging.
=> authenticateflow: verify redirect in Callback test

scripts/get-envoy.bash
Upgrade envoy to v1.25.10. We don't have darwin binaries for this version so only upgrade for linux.
Fixes https://github.com/pomerium/internal/issues/1551
=> core/envoy: upgrade to v1.25.10

internal/autocert/manager_test.go
Revert back to manual temporary directory creating and removal in the autocert test. Apparently sometimes a background process will continue writing files even after the test completes. `t.TempDir` causes the test to fail when this happens. Doing it manually if `RemoveAll` fails we can ignore the error.
I was not able to reproduce the flakiness despite running the test with `-count 100`, but it happened on github actions once.
Fixes https://github.com/pomerium/pomerium/issues/4757
=> core/autocert: fix flaky test

proxy/data.go, ui/src/components/SessionDetails.tsx
Currently we display an "Internal Server Error" when you visit the `/.pomerium/` page with no session. This PR changes it so instead of returning an error we render the user info page with empty session and user data and the show a warning with a link to the root of the domain.
Fixes https://github.com/pomerium/internal/issues/1578
=> core/proxy: handle missing session for user info endpoint

k8s/zero/.gitignore, k8s/zero/README.md, k8s/zero/deployment/base.yaml, k8s/zero/deployment/env.yaml, k8s/zero/deployment/image.yaml, k8s/zero/deployment/kustomization.yaml, k8s/zero/deployment/no-root.yaml, k8s/zero/deployment/ports.yaml, k8s/zero/deployment/readonly-root-fs.yaml, k8s/zero/deployment/resources.yaml, k8s/zero/deployment/volumes.yaml, k8s/zero/kustomization.yaml, k8s/zero/namespace.yaml, k8s/zero/pomerium-secret.yaml.example, k8s/zero/service/kustomization.yaml, k8s/zero/service/proxy.yaml
Creates manifests to deploy Pomerium Zero into Kubernetes cluster (see README.md)
Implements https://github.com/pomerium/pomerium-zero/issues/1479
=> zero/k8s: deployment manifests

changelogs/v0.25.0.md
Adds changelog for v0.25.0
https://github.com/pomerium/internal/issues/1616
=> changelog for v0.25

authenticate/handlers.go, authenticate/handlers_test.go
Currently most requests to the authenticate service will result in a log entry with the message "authenticate: origin blocked". This may be confusing, as the request is not in fact blocked; instead, what happens is that no special CORS headers are added to the response.
Let's reverse the logging behavior, and instead log a message only for those requests with a valid signature, where we do add CORS headers to the response.
Add a unit test case exercising the CORS middleware.
- https://github.com/pomerium/internal/issues/1631
=> authenticate: rework CORS headers log entry

.golangci.yml, config/envoyconfig/clusters.go, config/envoyconfig/clusters_test.go, config/envoyconfig/testdata/clusters.json, internal/testutil/testutil.go
In split service mode, and during periods of inactivity, the gRPC connections to the databroker may fall idle. Some network firewalls may eventually time out an idle TCP connection and even start dropping subsequent packets once connection traffic resumes. Combined with Linux default TCP retransmission settings, this could cause a broken connection to persist for over 15 minutes.
In an attempt to avoid this scenario, enable TCP keepalive for outbound gRPC connections, matching the Go standard library default settings for time & interval: 15 seconds for both. (The probe count does not appear to be set, so it will remain at the OS default.)
Add a test case exercising the `BuildClusters()` method with the default configuration options, comparing the results with a reference "golden" file in …
=> envoy: enable TCP keepalive for internal clusters

config/options.go, databroker/cache.go
If no `authenticate_service_url` is specified we switch to hosted authenticate mode. Hosted authenticate does not currently support user refresh, and user refresh is disabled if no `idp_provider` is specified. However if you specify an `idp_provider` while still using hosted authenticate, the identity manager will attempt to refresh the sessions, resulting in them being deleted after 10 minutes.
This PR changes the identity manager to only enable user refresh if both an `idp_provider` is set and hosted authenticate is not being used.
- https://github.com/pomerium/pomerium-console/issues/3975
=> core/databroker: disable identity manager user refresh when hosted authenticate is used

pkg/envoy/extract.go, pkg/envoy/extract_test.go
Clean up any existing temporary extracted envoy binaries on start.
For https://github.com/pomerium/internal/issues/1680
=> core/envoy: clean up temporary directory on start

pkg/policy/criteria/client_certificate.go, pkg/policy/criteria/client_certificate_test.go
Expand the [Certificate Matcher](https://www.pomerium.com/docs/capabilities/ppl#certificate-matcher) capabilities to support matching on DNS, email, or URI Subject Alternative Names, using the existing String Matcher conditions.
- https://github.com/pomerium/pomerium/issues/4615
Expand the [Certificate Matcher](https://www.pomerium.com/docs/capabilities/ppl#certificate-matcher) capabilities to support matching on DNS, email, or URI Subject Alternative Names.
=> policy: add client cert SAN match criteria

pkg/policy/criteria/accept_test.go, pkg/policy/criteria/claims_test.go, pkg/policy/criteria/cors_preflight_test.go, pkg/policy/criteria/criteria_test.go, pkg/policy/criteria/device_test.go, pkg/policy/criteria/domain_test.go, pkg/policy/criteria/email_test.go, pkg/policy/criteria/groups.go, pkg/policy/criteria/groups_test.go, pkg/policy/criteria/http_method_test.go, pkg/policy/criteria/http_path_test.go, pkg/policy/criteria/invalid_client_certificate_test.go, pkg/policy/criteria/reasons.go, pkg/policy/criteria/reject_test.go, pkg/policy/criteria/user_test.go
Add the `groups` criterion for PPL. It references data that is only populated from the Enterprise Console.
- https://github.com/pomerium/internal/issues/1673
=> core/ppl: add groups criterion

config/config_source.go, config/options.go, config/options_check.go, config/options_test.go
The `client_ca` and `client_ca_file` settings were deprecated in v0.23. Remove these options and add a link to the corresponding explanation on the Upgrading docs page.
- https://github.com/pomerium/pomerium/issues/4917
Remove the deprecated `client_ca` and `client_ca_file` settings.
=> config: remove deprecated client_ca option

internal/zero/bootstrap/source.go, internal/zero/bootstrap/source_test.go
For zero, if postgres configuration is set, we should be able to reset back to in-memory by sending an empty connection 
string in the bootstrap params. 
Related: https://github.com/pomerium/pomerium-zero/issues/1659
=> zero/bootstrap: reset back to inmem databroker if connection string is empty

.github/workflows/docker-version-branches.yaml
Switch to regular GitHub Actions runners in the 'Docker Release Branches' workflow, matching how the 'Docker Main' workflow is configured.
- https://github.com/pomerium/internal/issues/1584#issuecomment-1887663893
=> ci: switch to regular runners

pkg/contextutil/contextutil.go, pkg/httputil/serve.go
Turns out there's a `WithoutCancel` function in the `context` package that does the same thing as `contextutil.OnlyValues`.
=> core: use context.WithoutCancel

internal/handlers/device-enrolled.go, internal/handlers/signedout.go, internal/handlers/signout.go, internal/handlers/userinfo.go, internal/handlers/webauthn/webauthn.go, internal/httputil/errors.go, ui/dist/index.gohtml, ui/embed.go, ui/embed_ext.go
Set the page title for UI pages. For pages like the dashboard they are set to a title that makes sense for that page. For errors we set the title to something like `403 Forbidden`.
The `index.html` file was converted to a Go template.
- https://github.com/pomerium/internal/issues/1698
=> core/ui: fix page title

internal/zero/api/api.go, internal/zero/grpcconn/client.go, internal/zero/grpcconn/config.go
When running in Zero managed mode, Pomerium must maintain a streaming gRPC to the Connect signalling service in the cloud, in order to receive configuration updates from the cloud as they appear. 
It was noticed that sometimes the gRPC connection may be in the `READY` state while the end to end connection to the Connect gRPC server, is in fact, long time gone. 
This PR introduces a client-side keepalive with infrequent 1-minute interval for the Connect service, to ensure we are still maintain gRPC connection.
Fixes https://github.com/pomerium/pomerium-zero/issues/1711
=> connect: add gRPC keep-alive

authorize/log.go, authorize/log_test.go
Currently the `user` field of the authorize logs is empty for requests authenticated via a service account, as there is no associated User object. Instead, populate this log field directly from the the `sessionOrServiceAccount` value, to handle both types of user.
- pomerium/internal#1740
Populate the authorize logs `user` field for requests authenticated via a service account.
=> authorize: log service account user ID

.github/workflows/benchmark.yaml, .github/workflows/lint.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml, .tool-versions, Dockerfile, Dockerfile.debug, go.mod
Upgrades Go to 1.22
Related: https://github.com/pomerium/internal/issues/1731
=> ci: upgrade to Go 1.22

go.mod, go.sum
This includes a fix for CVE-2024-24786.
See https://pkg.go.dev/vuln/GO-2024-2611 for more details.
=> chore(deps): bump google.golang.org/protobuf from 1.32.0 to 1.33.0

.tool-versions, Dockerfile, Dockerfile.debug
Bump Go in Dockerfiles to 1.21.8 
The GitHub actions are supposed to pick up latest from 1.21 
https://groups.google.com/g/golang-announce/c/5pwGVUPoMbg
=> ci: bump Go to 1.21.8 in docker

config/envoyconfig/clusters.go, config/envoyconfig/clusters_test.go, config/envoyconfig/testdata/clusters.json
Envoy has an option `auto_host_rewrite` that rewrites the Host header of an incoming request to match the upstream domain that the proxied request is sent to. Pomerium sets the `auto_host_rewrite` option for all Pomerium routes that do not set one of the [Host Rewrite options](https://www.pomerium.com/docs/reference/routes/headers#host-rewrite-options).
When Envoy rewrites the Host header, it does not include the upstream port, even when it is a non-standard port for the scheme (i.e. a port other than 80 for http or a port other than 443 for https).
I think this behavior does not conform to RFC 9110. The nearest thing I can find in the text is this statement about http and https URIs:
> If the port is equal to the default port for a scheme, the normal form is to omit the port …
=> envoy: set explicit hostname on cluster endpoints

pkg/zero/cluster/models.gen.go, pkg/zero/cluster/openapi.yaml
Adds `shared_secret` to the cluster bootstrap API spec.
Related: https://github.com/pomerium/pomerium-zero/issues/1260
=> cluster api: add shared secret to the cluster bootstrap params

internal/zero/bootstrap/bootstrap.go, internal/zero/bootstrap/new.go, internal/zero/bootstrap/new_test.go, internal/zero/bootstrap/source_test.go, internal/zero/cmd/command.go, internal/zero/controller/config.go, internal/zero/controller/controller.go
When Pomerium starts in zero mode, it tries to write bootstrap parameters to a local cache file, 
so that it may start independently from the control plane, if necessary. 
This PR ensures the inability to create a cache file is just a warning in the log, and not a fatal 
error.
Related: https://github.com/pomerium/pomerium-zero/issues/2011
=> zero: fix bootstrap config path

authenticate/handlers.go, authenticate/handlers_test.go, internal/handlers/signedout.go, internal/handlers/signout.go
Add support for the Enterprise branding options to the `sign_out` and `signed_out` page handlers.
- https://github.com/pomerium/pomerium-console/issues/4103
Apply Enterprise branding options to the authenticate service sign out pages.
=> authenticate: apply branding to sign out pages

authorize/evaluator/headers_evaluator.go, authorize/evaluator/log.go, authorize/evaluator/log_test.go, authorize/evaluator/policy_evaluator.go
To make custom rego easier to debug add support for `print` statements.
Fixes https://github.com/pomerium/pomerium-console/issues/4095
=> core/authorize: add support for rego print statements

ui/package.json, ui/yarn.lock
This should resolve a security vulnerability alert on the transitive dependency @babel/traverse: https://github.com/pomerium/pomerium/security/dependabot/66.
- https://github.com/pomerium/internal/issues/1645
=> chore(deps): bump @trivago/prettier-plugin-sort-imports from 2.0.4 to 4.3.0

scripts/get-envoy.bash
Upgrades Envoy to v1.28.2 (Linux only).
Related: https://github.com/pomerium/internal/issues/1771
=> envoy: upgrade to v1.28.2

authenticate/handlers.go, authenticate/handlers_test.go
Currently if an IdP does not support the `SignOut` method, and a signout redirect URL is not defined, and a redirect URL is not passed on the query string, we default to redirecting to `/`. This PR updates the logic to redirect to the signed out URL instead (`/.pomerium/signed_out`).
- https://github.com/pomerium/internal/issues/1767
=> core/authenticate: redirect to /.pomerium/signed_out when no signout redirect url is defined

config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go, internal/databroker/config_source.go
Currently if the `grpc_address` is set to the empty string:
```yaml
grpc_address: ""
```
We will start the `grpc-ingress` on port `80`. With these changes we will instead disable the `grpc-ingress`. The databroker and authorize service will only listen on the gRPC port, which is randomly chosen on start, and only bound to the local ip.
- https://github.com/pomerium/pomerium-zero/issues/1987
=> core/config: disable gRPC ingress when address is the empty string

Dockerfile, Dockerfile.debug
This is in preparation for https://github.com/pomerium/pomerium/pull/5061:
- the dev Dockerfile and Dockerfile.debug files use a base Go image `golang:1.22.1-bookworm`
- the base Go images set `ENV GOTOOLCHAIN=local`, which disables automatic toolchain fetching
- this means they won't build if we set a `go 1.22.2` directive in the go.mod file
Let's update the dev docker images to use `golang:1.22.2-bookworm`.
I obtained the current digest for `golang:1.22.2-bookworm` from [Docker hub](https://hub.docker.com/layers/library/golang/1.22.2-bookworm/images/sha256-cac8fb1c85bf96316112f5dd2671c8da0c19d2dfce88af9551b3141499a59eaf?context=explore):
- https://github.com/pomerium/internal/issues/1773
=> update dev Dockerfiles to use Go 1.22.2

internal/zero/connect-mux/service.go, internal/zero/grpcconn/client.go, internal/zero/reconciler/sync.go
Reduce the log level for some zero messages.
- https://github.com/pomerium/pomerium-zero/issues/2043
=> core/zero: lower log level

config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go, config/envoyconfig/outbound.go, config/envoyconfig/testdata/metrics_http_connection_manager.json
On MacOS we see messages like:
```
{"level":"error","service":"envoy","name":"config","time":"2024-04-11T13:42:06-06:00","message":"reuse_port was configured for TCP listener \\'grpc-ingress\\' and is being force disabled because Envoy is not running on Linux. See the documentation for more information."}
```
This PR fixes that.
=> core/envoy: only enable port reuse on linux

README.md
Remove the inline integration test instructions in favor of a link to the Contributing page on the documentation site. Remove some unused link definitions and update the godoc.org link to use pkg.go.dev instead.
- https://github.com/pomerium/pomerium/issues/5069
=> update README: link to Contributing page

config/envoyconfig/http_connection_manager.go, config/envoyconfig/listeners.go, config/envoyconfig/testdata/main_http_connection_manager_filter.json, ui/embed.go
Update the local reply config to format errors returned from envoy. Instead of plain text messages you will see:
For https://github.com/pomerium/internal/issues/1735
=> core/envoy: format envoy local replies

internal/zero/grpcconn/config.go, internal/zero/reconciler/report_status.go, pkg/zero/cluster/client.go
Adds `User-Agent` header to requests to the control plane. 
Fixes https://github.com/pomerium/pomerium-zero/issues/2177
=> zero: add user-agent to requests

pkg/health/check.go, pkg/storage/inmemory/backend.go, pkg/storage/postgres/backend.go
This PR adds a periodic health check for storage backend health. 
Fixes https://github.com/pomerium/pomerium-zero/issues/2106
=> health-check: add storage health check

scripts/get-envoy.bash
Upgrade Envoy from v1.29.3 to v1.30.1.
Release notes:
- https://www.envoyproxy.io/docs/envoy/v1.30.1/version_history/v1.30/v1.30.0
- https://www.envoyproxy.io/docs/envoy/v1.30.1/version_history/v1.30/v1.30.1
Unblocks https://github.com/pomerium/pomerium/issues/4362.
=> envoy: upgrade to v1.30.1

config/envoyconfig/routes.go, config/envoyconfig/routes_test.go, config/policy.go, config/policy_test.go
Add a distinction between TCP routes depending on whether the To URL(s) have the scheme tcp://. For routes with a TCP upstream, configure Envoy to terminate CONNECT requests and open a TCP tunnel to the upstream service (this is the current behavior). For routes without a TCP upstream, configure Envoy to proxy CONNECT requests to the upstream.
This new mode can allow an upstream proxy server to terminate a CONNECT request and open its own TCP tunnel to the final destination server. (Note that this will typically require setting the [`preserve_host_header`](https://www.pomerium.com/docs/reference/routes/headers#1-preserve-host-header) option as well.)
Note that this requires Envoy 1.30 or later.
- #4362 
Adds a new TCP route mode, for use with upstream proxy servers.
=> config: add support for TCP proxy chaining

internal/zero/connect-mux/service.go, pkg/health/check.go
Adds health check for zero connect service.
Related: https://github.com/pomerium/pomerium-zero/issues/2105
=> connect: add health check

config/envoyconfig/acmetlsalpn.go, config/envoyconfig/clusters.go, config/envoyconfig/envoyconfig.go, pkg/envoy/misc.go
We recently enabled CodeQL scanning. This has flagged a few instances where we parse an integer using `strconv.Atoi()` and then convert to a `uint32`. Let's resolve these warnings by using `strconv.ParseUint()` instead, like @calebdoxsey did in https://github.com/pomerium/pomerium/pull/5066/commits/5b06b27ebbdc0401644e2b5ec22eb171724aac11.
One of this instances is in a function that appears to be unused ([GitHub search link](https://github.com/search?q=org%3Apomerium%20pkg%2Fenvoy%20ParseAddress&type=code)), so let's go ahead and delete that function.
- https://github.com/pomerium/pomerium/security/code-scanning/2
- https://github.com/pomerium/pomerium/security/code-scanning/3
- https://github.com/pomerium/pomerium/security/code-scanning/5
=> envoyconfig: address strconv.Atoi warnings

authorize/evaluator/headers_evaluator_test.go, authorize/evaluator/opa/policy/headers.rego
Remove the empty string from the `Impersonate-Group` header.
For #5089
=> core/kubernetes: fix impersonate group header

cmd/pomerium/main.go, internal/log/grpc.go, internal/log/log.go, internal/zero/cmd/command.go
Previously, gRPC used default global logger, that caused mismatch with levels and format options configured across Pomerium.
This PR: 
1. sets default gRPC logger to use Pomerium global logger
2. only log gRPC related messages if debug level is enabled. 
- By default, gRPC logs are rather verbose and have numerous transient errors as various Pomerium modules are initializing, that may be confusing to the user. 
- if user enables pomerium `log_level: debug`, they would also observe all the gRPC transport related errors, without need to specifically adjust gRPC verbosity via [special env variables](https://pkg.go.dev/google.golang.org/grpc/examples/features/debugging#section-readme) which should be handy when troubleshooting Pomerium installation.
3. set default level to `info` in main.go, …
=> log/grpc: use standard logger

internal/zero/controller/controller.go, internal/zero/healthcheck/check_routes.go, internal/zero/healthcheck/checks.go, pkg/health/check.go, pkg/zero/ping/ping.go
Adds periodic health check for all referenced hosts to correctly resolve to this particular instance. 
Moves cluster ping code to shared package. 
Fixes https://github.com/pomerium/pomerium-zero/issues/2110
=> health-checks: add route reachability

internal/databroker/config_source.go, pkg/health/check.go
Adds health check to report whether rebuilding config from the databroker source was successful.
Related: https://github.com/pomerium/pomerium-zero/issues/2318
=> health-check: building config from databroker source

config/envoyconfig/http_connection_manager.go, config/envoyconfig/testdata/main_http_connection_manager_filter.json
Exclude `ext_authz_denied` from the local reply handling so it retains the data returned by the authorize service.
I couldn't find a way of doing `NOT` with the filter, so I just took all the possible values and removed `UAEX`.
For https://github.com/pomerium/internal/issues/1783
=> core/envoy: exclude unauthorized access from local replies

ui/src/App.tsx, ui/src/components/UpstreamErrorPage.tsx, ui/src/types/index.ts
Adds a different error page for routes that have an issue with the upstream connection
Fixes https://github.com/pomerium/internal/issues/1782
Distinguishes between having an issue with your Pomerium config vs an error with an upstream provider
=> adds upstream error page

ui/src/components/ClaimRow.tsx, ui/src/components/ClaimValue.tsx, ui/src/components/SessionDetails.tsx
Improve the display of the user info dashboard when using hosted authenticate. In that case there will be no session object. Instead we will use the profile object which may have claims which aren't flattened.
- https://github.com/pomerium/hosted-authenticate/issues/58
=> core/ui: user info dashboard improvements

internal/telemetry/prometheus/convert.go, internal/telemetry/prometheus/convert_test.go, internal/telemetry/prometheus/stream.go, internal/telemetry/prometheus/stream_test.go, internal/telemetry/prometheus/testdata/counter.txt, internal/telemetry/prometheus/testdata/histogram.txt
Added initial support for converting Prometheus format metrics to OTLP format in a streaming manner. This is mainly for use with Envoy metrics output, where we want to focus on a small subset of specific metrics and ignore the rest. Standard Prometheus library loads everything in memory. 
Related: https://github.com/pomerium/pomerium-zero/issues/2454
=> telemetry: add prometheus streaming converter to OTLP

scripts/get-envoy.bash
Upgrade Envoy from v1.30.1 to v1.30.2.
Release notes:
- https://www.envoyproxy.io/docs/envoy/v1.30.2/version_history/v1.30/v1.30.2
- https://github.com/pomerium/internal/issues/1821
=> envoy: upgrade to v1.30.2

authorize/evaluator/headers_evaluator.go, authorize/evaluator/headers_evaluator_test.go, authorize/evaluator/opa/policy/headers.rego, integration/policy_test.go
Update JWT assertion generation:
1. `jti` is now a random UUID instead of the session id
2. `iat` is now the current time
3. `exp` is now the current time + 5 minutes
- https://github.com/pomerium/internal/issues/1834
=> core/authorize: use uuid for jti, current time for iat and exp

config/envoyconfig/listeners.go, internal/autocert/manager.go, internal/autocert/manager_test.go
Fix several issues with autocert:
1. Disable HTTP challenges when the redirect server is not enabled.
2. At some point the TLS ALPN filter was removed from envoy, so the autocert code was never being called. How it works at all is a mystery to me, but because of the missing envoy filter it was impossible for certificates to be provisioned via TLS ALPN challenges at runtime.
3. We weren't calling `Handshake` after accepting the TLS connection. This is necessary to complete the ACME protocol.
- https://github.com/pomerium/pomerium/issues/5138
=> core/autocert: fix filter chain, handshake

pkg/envoy/get-envoy/main.go
Upgrade Envoy from v1.30.2 to v1.30.3.
Release notes:
- https://www.envoyproxy.io/docs/envoy/v1.30.3/version_history/v1.30/v1.30.3
- https://github.com/pomerium/internal/issues/1821
=> envoy: upgrade to v1.30.3

internal/zero/telemetry/sessions/activeusers_test.go
Set a fixed start time in the TestActiveUsers unit test to avoid any unintended behavior if run just before midnight UTC.
- https://github.com/pomerium/pomerium/issues/5153
=> zero: set fixed start time for active users test

internal/controlplane/server.go
Tweak the cleanup logic in controlplane.NewServer(). Following the pattern of the other two `net.Listen` calls I think the intent was to call `MetricsListener.Close()` if the `DebugListener` fails to start, rather than `DebugListener.Close()`.
There was a nil panic from this line in a recent integration test run:
https://github.com/pomerium/pomerium/actions/runs/9688646705/job/26735594932?pr=5155#step:8:74
=> controlplane: avoid calling Close on nil listener

authorize/evaluator/headers_evaluator.go, authorize/evaluator/headers_evaluator_test.go, ui/src/components/Header.tsx
Add a user info link in the header dropdown that points to `/.pomerium/`.
For https://github.com/pomerium/internal/issues/1831
=> core/ui: add user info link

ui/src/components/UpstreamErrorPage.tsx
Add the request id to the upstream error page.
For https://github.com/pomerium/internal/issues/1842
=> core/ui: add request id to upstream error page

internal/handlers/userinfo.go, internal/handlers/userinfo_test.go
A typo in https://github.com/pomerium/pomerium/pull/5137 caused a cycle in the profile data on the userinfo page. This data is typically only used in the stateless flow in hosted authenticate.
- https://github.com/pomerium/hosted-authenticate/issues/66
=> core/ui: fix cycle in profile data

pkg/grpc/session/session.go, pkg/grpc/session/session_test.go
Per the OIDC spec, section 2:
> NOTE: The ID Token expiration time is unrelated [to] the lifetime of the authenticated session between the RP and the OP.
A Pomerium session should remain valid for as long as the underlying OAuth2 session.
- https://github.com/pomerium/pomerium/issues/5181
Fix an issue where Pomerium sessions might expire earlier than intended, in cases where the OIDC ID token expires before the OAuth access token.
=> session: do not invalidate based on ID token

pkg/identity/oidc/oidc.go, pkg/identity/oidc/oidc_test.go
Add tests for all of the oidc.Provider methods not currently covered. Remove the GetSubject() method as it appears to be unused.
Increases statement coverage for the oidc package from 42.7% to 84.1%.
n/a
=> oidc: add more unit tests

pkg/envoy/get-envoy/main.go
Upgrade Envoy from v1.30.3 to v1.31.0.
Release notes:
- https://www.envoyproxy.io/docs/envoy/v1.31.0/version_history/v1.31/v1.31.0
- https://github.com/pomerium/internal/issues/1862
=> envoy: upgrade to v1.31.0

internal/authenticateflow/authenticateflow.go, internal/authenticateflow/identityprofile.go, internal/authenticateflow/identityprofile_test.go, internal/authenticateflow/stateful.go, internal/authenticateflow/stateful_test.go, pkg/grpc/session/session.go, pkg/grpc/session/session_test.go, pkg/identity/legacymanager/data.go, pkg/identity/legacymanager/data_test.go, pkg/identity/manager/data.go, pkg/identity/manager/data_test.go
Currently, the Session proto [id_token](https://github.com/pomerium/pomerium/blob/e5e6558de6302898b558060b14eeb90e74ed9437/pkg/grpc/session/session.proto#L41) field is populated with Pomerium session data during initial login, but with IdP ID token data after an IdP session refresh.
Instead, only store IdP ID token data in this field.
Update the existing `SetRawIDToken()` method to populate the structured data fields based on the contents of the raw ID token. Remove the other code that sets these fields (in the authenticateflow package and in manager.sessionUnmarshaler).
Add a test for the identity manager, exercising the combined effect of session claims unmarshaling and SetRawIDToken(), to verify that the overall behavior is preserved before and after this change.
- …
=> authenticate: rework session ID token handling

config/config.go
=> config: allow overriding port numbers using environment variables

.github/workflows/benchmark.yaml, .github/workflows/test.yaml
Update the integration test and benchmark workflows to use Docker Compose v2.
- https://github.com/pomerium/internal/issues/1881
=> ci: switch to docker compose v2

pkg/grpc/databroker/leaser.go
We run numerous operations within a databroker Lease, which involves gRPC calls to the databroker service.
sometimes the databroker service may not be available and gRPC retry mechanism would try to reestablish the connection forever if there's no limit set for individual calls.
We always tried to `ReleaseLease` gracefully, but used background context for that. 
That could cause the `ReleaseLease` call be stuck. 
i.e. 
```
goroutine 131 gp=0x14000980540 m=nil [select, 3 minutes]:
runtime.gopark(0x14001158ed8?, 0x2?, 0x60?, 0x0?, 0x14001158e2c?)
/Users/pomerium/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.darwin-arm64/src/runtime/proc.go:402 +0xc8 fp=0x14001158ce0 sp=0x14001158cc0 pc=0x102a4c618
runtime.selectgo(0x14001158ed8, 0x14001158e28, 0xd0?, 0x0, 0xd0?, 0x1) …
```
=> databroker/leaser: set timeout on ReleaseLease

config/envoyconfig/listeners.go, internal/controlplane/grpc_accesslog.go, internal/log/access.go
Supersedes https://github.com/pomerium/pomerium/pull/5196
This implements limited listener-based access logging for downstream transport failures, only enabled when downstream_mtls.enforcement is set to 'reject_connection'. Client certificate details and the error message will be logged.
Additionally, the new key 'client-certificate' can be set in the access_log_fields list in the configuration, which will add peer certificate properties (issuer, subject, SANs) to the existing per-request http logs.
https://github.com/pomerium/pomerium/issues/5130
=> envoy: log mtls failures

config/envoyconfig/protocols.go, config/envoyconfig/protocols_int_test.go, config/envoyconfig/protocols_test.go
This allows using the scheme 'h2c' to indicate http2 prior knowledge for insecure upstream servers. This can be used to perform TLS termination for GRPC servers configured with insecure credentials.
As an example, this allows the following route configuration:
```
routes:
- from: https://grpc.localhost.pomerium.io
to: h2c://localhost:9090
```
Note: the custom "h2c" scheme is used by Traefik to implement this same feature. So while it is not an "official" scheme like http/https, it may still be familiar to many users.
https://github.com/pomerium/pomerium/issues/5213
We can have a similar explanation as in the Traefik docs: https://doc.traefik.io/traefik/user-guides/grpc/#with-http-h2c
=> envoy: support http2 prior knowledge for insecure upstream targets

.github/workflows/benchmark.yaml, .github/workflows/lint.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml, .tool-versions, Dockerfile, Dockerfile.debug, Makefile, authorize/grpc_test.go, go.mod, internal/httputil/client.go, internal/sessions/cookie/cookie_store_test.go, internal/telemetry/metrics/providers_test.go
This updates Go to 1.23 and golangci-lint to 1.60.1, which includes important Go 1.23 related bugfixes for some linters. 
A few new lint errors surfaced after the update, presumably due to regular updates to the linters that golangci-lint runs. These fixes are relatively minor, and have been included in this PR.
=> Update to Go 1.23

.golangci.yml
Disables the GCI linter temporarily due to a bug preventing it from working correctly with new Go 1.23 imports.
=> Temporarily disable gci linter

internal/zero/connect-mux/messages.go
When running in zero managed mode, cloud may send a message over the `connect.proto` channel that is not recognized and would cause an error and shutdown. This PR changes the behaviour to ignore such message. 
Fixes: https://github.com/pomerium/pomerium-zero/issues/2839
=> connect/client: ignore unknown message types

internal/zero/telemetry/sessions/sessions.go, pkg/grpc/databroker/generic.go, pkg/grpc/databroker/generic_test.go
Add an `IterateAll` method to the databroker that's like `InitialSync` but returns an iterator:
```go
for record, err := range databroker.IterateAll[session.Session](ctx, client) {
// record.Object is a session.Session
}
```
This avoids having to create a full slice of records and also handles unmarshaling the data automatically.
- https://github.com/pomerium/pomerium-zero/issues/2764
=> core/grpc: add IterateAll method

Makefile
Allow to specify `VERSION` as env to `make build`.
=> ci: allow to override VERSION in Makefile via env

config/config_source.go, config/options.go, config/options_test.go, databroker/cache.go, databroker/databroker.go
Add support for loading the `DataBrokerStorageConnectionString` from a file.
- https://github.com/pomerium/pomerium/issues/5228
=> core/config: add databroker_storage_connection_string_file

k8s/zero/deployment/base.yaml, k8s/zero/deployment/env.yaml, k8s/zero/deployment/image.yaml, k8s/zero/deployment/no-root.yaml, k8s/zero/deployment/ports.yaml, k8s/zero/deployment/readonly-root-fs.yaml, k8s/zero/deployment/resources.yaml, k8s/zero/deployment/volumes.yaml, k8s/zero/kustomization.yaml, k8s/zero/rbac/kustomization.yaml, k8s/zero/rbac/role.yaml, k8s/zero/rbac/role_binding.yaml, k8s/zero/rbac/service_account.yaml
Previously, Pomerium in Zero mode was deployed using `StatefulSet` and required a PVC to store the bootstrap piece.
Support to store the bootstrap piece in a kubernetes secret was added in #5114. 
This PR updates manifests accordingly to use stateless `Deployment` and configures the bootstrap writeback to the `pomerium-zero/pomerium` `Secret` that is already required to store `POMERIUM_ZERO_TOKEN`. 
Related: https://github.com/pomerium/pomerium-zero/issues/2405
=> zero/k8s: use deployments

internal/zero/api/api.go, internal/zero/api/download.go, internal/zero/token/cache.go, internal/zero/token/cache_test.go, pkg/zero/cluster/client.go, pkg/zero/cluster/client_test.go, pkg/zero/cluster/token_fetcher.go, pkg/zero/cluster/urlcache.go
When interacting with zero api, we currently cache the access token and download URLs for the period of time they've been issued for. 
However, those tokens may become invalid and that would cause 401 Unauthorized returned by the API. 
Currently, such response would be handled via a retry, similarly to any other error. The retry would therefore continue until the cache is expired.
This PR changes the behaviour - if 401 is returned by zero API or the blob download service, a cached token or download url would be invalidated, that would cause the operation to be retried requesting a new token or download url.
=> zero/api: reset token and url cache if 401 is received

config/runtime_flags.go, pkg/envoy/resource_monitor_linux.go, pkg/envoy/resource_monitor_test.go
Sort the runtime flag definitions alphabetically. Rename `envoy_resource_manager_enabled` to just `envoy_resource_manager` for consistency with the other flag names. (This flag hasn't been released yet, so it should be OK to rename it.) Add a doc comment for this flag.
- https://github.com/pomerium/internal/issues/1744
=> config: sort runtime flags, name consistency

k8s/zero/service/proxy.yaml
Allow preserving the original client IP address by default when deploying to Kubernetes in Zero managed mode. 
Related: https://github.com/pomerium/pomerium/issues/5265
=> zero/k8s: set externalTrafficPolicy: Local

config/envoyconfig/clusters.go, config/envoyconfig/clusters_test.go, config/envoyconfig/listeners.go, config/envoyconfig/listeners_test.go, config/envoyconfig/testdata/metrics_http_connection_manager.json, config/envoyconfig/tls.go
By default envoy only allows TLS v1.2 for upstream connections. This PR updates the cluster config in envoy to support TLS v1.3 as well.
- https://github.com/pomerium/pomerium/issues/5247
=> core/envoy: allow TLS 1.3

ui/embed.go, ui/src/components/SignOutConfirmPage.tsx
The UI HTML page should not be cached as it contains data that changes frequently. I don't think it was being cached, since we used `time.Now`, but now we explicitly set the `Cache-Control` header to make sure it doesn't get cached.
Also update the `history.back` so that it will reload the page if you cancel the logout.
- https://github.com/pomerium/pomerium-console/issues/3968
=> core/ui: no-cache html, force back

config/config.go
This reverts commit fdefcf9a16333b007058707f81cfbd1b97463c4f (https://github.com/pomerium/pomerium/pull/5194)
This was originally intended for a specific integration test use case, but it did not end up being needed. Additionally, the environment variable names can conflict with Kubernetes service environment variables.
Fixes https://github.com/pomerium/internal/issues/1900
=> Revert "config: allow overriding port numbers using environment variables (#5194)"

k8s/zero/deployment/image.yaml
Set image to `v0.27.0` for zero kubernetes manifests.
=> ci: update k8s manifests before v0.27.0 release

changelogs/v0.27.0.md
Add v0.27.0 changelog.
I removed a few items that appeared to affect only tests or CI checks (e.g. linter version update).
I tried to standardize and alphabetize the category tags, and update a few descriptions to provide additional detail.
=> add v0.27.0 changelog

config/config.go, internal/zero/bootstrap/source.go, internal/zero/bootstrap/writers/k8s/secret_test.go, pkg/zero/cluster/models.gen.go, pkg/zero/cluster/openapi.yaml
Add the organization id and the cluster id to the zero config.
- https://github.com/pomerium/pomerium-zero/issues/2964
=> core/zero: add organization id and cluster id to bootstrap config

.github/Dockerfile-cloudrun, .github/Dockerfile-release, .github/Dockerfile-release-debug, .github/Dockerfile-release-debug-nonroot, .github/Dockerfile-release-nonroot, Dockerfile, Dockerfile.debug, examples/mutual-tls/Dockerfile
Recently I've been seeing some new warnings from our automated Docker image builds, about "FROM" and "as" casing and the format of the "ENV" directive. Let's update all our Dockerfiles accordingly.
- https://github.com/pomerium/internal/issues/1908
=> ci: address Dockerfile warnings

internal/zero/bootstrap/source.go
In Zero-managed mode, log the organization ID and cluster ID on startup. (These are newly available in the bootstrap config, and surfacing this information should help when debugging problems.)
- pomerium/pomerium-zero#2848
=> zero: log organization and cluster IDs on startup

config/options.go, internal/log/authorize.go
Currently we log headers during authorization if the log level is set to debug. This PR changes it to never log headers by default. If a user wants headers logged they need to set the authorization header field to include headers explicitly.
- https://github.com/pomerium/internal/issues/1892
=> core/authorize: remove default header logging in debug

config/policy_ppl.go, config/policy_ppl_test.go
When converting a core route to a PPL policy, if an embedded policy object is present but none of the shorthand options that translate to PPL snippets (`allowed_users`, etc.) are present, omit the empty (no-op) allow block from the resulting policy.
This doesn't change any semantics of the policy, but it may be confusing for users if we display the converted yaml.
=> ppl: fix empty/no-op allow block added in some cases to converted PPL policies

pkg/grpc/config/config.go, proxy/data.go, proxy/data_test.go
Currently we look for a `dashboard` record to see if we have an enterprise install. This config was broken up into separate configs, one of which is `dashboard-settings`, so look for that instead.
- https://github.com/pomerium/internal/issues/1894
=> core/proxy: fix is-enterprise check

config/config.go, internal/zero/bootstrap/source.go, internal/zero/bootstrap/writers/k8s/secret_test.go, internal/zero/controller/controller.go, internal/zero/controller/usagereporter/usagereporter.go, internal/zero/controller/usagereporter/usagereporter_test.go, pkg/cryptutil/pseudonymize.go, pkg/zero/cluster/models.gen.go, pkg/zero/cluster/openapi.yaml
Add a dedicated psuedonymization key instead of just using the organization id.
- https://github.com/pomerium/pomerium-zero/issues/2964
=> core/zero: add pseudonymization key

Makefile
The build-dev-docker.sh script will run
env GOOS=linux make build
to build Pomerium for Linux (before copying this binary into a minimal Docker image).
However, now that the `get-envoy` target is implemented using a Go command, it too will be affected by `GOOS`. As a result running this step on macOS will result in an error when trying to execute a Linux `get-envoy` binary.
Instead, let's unset `GOOS` when running the `get-envoy` command, so that it defaults to building for the host OS.
- https://github.com/pomerium/pomerium/issues/5299
=> Makefile: unset GOOS for get-envoy target

k8s/zero/deployment/image.yaml
Bump Zero k8s manifest image tag to v0.27.1.
n/a
=> zero: update k8s manifest to prepare for v0.27.1

k8s/zero/deployment/image.yaml
Set the Pomerium Zero k8s deployment manifest to use the `latest` tag (in the `main` branch).
This way, users installing from the `main` branch will stay up to date as we make new releases, and we won't need to keep this tag in sync between `main` and the current release branch during patch releases.
n/a
=> zero: set k8s deployment to follow :latest tag

databroker/databroker.go, internal/databroker/config.go
The `databroker.serverConfig` struct has a few fields which are written to but never read. Let's remove these.
n/a
=> databroker: remove unused serverConfig fields

.github/PULL_REQUEST_TEMPLATE
Update the PR template to better reflect our current workflow:
- Do not suggest using the "Fixes" keyword, as this will close linked issues upon merge. (For most issues, the process is to let QA verify and then close the issue.)
- Remove the "updated docs" and "updated UPGRADING.md" checklist steps. As documentation lives in a separate repository, it is no longer possible to update docs in the same PR.
- Expand the list of labels, based on the changelog categories (omitting "security" because security issues should be reported separately)
=> github: update PR template

pkg/storage/inmemory/backend.go
Fixes a possible race condition in the usage of the maps.Keys iterator in the in-memory databroker storage backend's ListTypes method.
=> storage: fix possible race condition with maps.Keys iterator

internal/zero/controller/databroker_restart_test.go
The existing check was using NotEqual which was trying to compare internal grpc client structs recursively, including fields which should not be compared.
=> Fix race condition in databroker restart test

config/envoyconfig/routes.go, config/envoyconfig/routes_test.go, internal/httputil/reproxy/reproxy.go
Several `kubectl` commands use spdy, and in more recent versions websockets, so go ahead and enable those features if a kubernetes service account token is being used for a route.
Also update the reproxy handler to disable HTTP/2 when using websockets.
- https://github.com/pomerium/pomerium/issues/5293
=> core/config: allow websockets and spdy by default for k8s urls

config/options_check.go
Most fields in the [config.Options](https://github.com/pomerium/pomerium/blob/075ea01b0add1563da73461bb3e5d78896d6fb46/config/options.go#L59) struct are populated by the `mapstructure` package, but the [SetResponseHeaders](https://github.com/pomerium/pomerium/blob/075ea01b0add1563da73461bb3e5d78896d6fb46/config/options.go#L192) field is handled separately. As a result, when the `set_response_headers` key is present, it also shows up as an unknown config option.
Add this key to the [ignoreConfigFields](https://github.com/pomerium/pomerium/blob/075ea01b0add1563da73461bb3e5d78896d6fb46/config/options_check.go#L42) map, to avoid logging an incorrect "unknown config option" message when set.
- https://github.com/pomerium/pomerium-zero/issues/3093
=> config: set_response_headers is not unknown

pkg/storage/inmemory/backend_test.go
Add a test that interleaves calls to `Put()` (with different type strings) and `ListTypes()`. At least on my machine, this appears to reliably detect the data race fixed in commit 2f8743522d7b60a6b3773fff5a13d6b0b76924ae when run with the Go race detector. (The `make test` and `make cover` targets run with the Go race detector enabled.)
- #5319
=> inmemory: add a test for the ListTypes race fix

internal/controlplane/server_test.go, internal/handlers/well_known_pomerium.go, internal/handlers/well_known_pomerium_test.go
This adds an `issuer` field to the `/.well-known/pomerium` endpoint available on any route. The field contains the route's base uri, including the https:// scheme and ending with a trailing slash. 
For example, the route with hostname foo.example.com will have an endpoint `https://foo.example.com/.well-known/pomerium` which will contain (along with the existing fields) `"issuer":"https://foo.example.com/"`. 
This is part of Kubernetes structured authentication support, but could also be used by other compatible upstream services.
=> Add an 'issuer' field to the /.well-known/pomerium endpoint

authorize/evaluator/headers_evaluator_test.go, authorize/evaluator/opa/policy/headers.rego
This is a prerequisite for supporting k8s structured authentication config. Adds a new variable `${pomerium.jwt}` that will substitute the pomerium JWT into request headers.
https://github.com/pomerium/pomerium/issues/5342
=> Add new request header variable 'pomerium.jwt'

authorize/evaluator/headers_evaluator.go, authorize/evaluator/headers_evaluator_test.go, authorize/evaluator/opa/policy/headers.rego
Quick follow up to https://github.com/pomerium/pomerium/pull/5338 - the `aud` claim in the pomerium JWT was previously set to be identical to the `iss` claim. We now have the ability to change the issuer format, but the audience format should remain the same.
=> Decouple audience claim value from issuer format

pkg/policy/criteria/matchers.go, pkg/policy/criteria/matchers_test.go
For string and string list matchers rather than only supporting a string or object value on the right side, support any type.
Fixes #5347
=> ppl: support additional types for string matchers

config/envoyconfig/routes.go, config/envoyconfig/routes_test.go, config/policy.go, config/policy_test.go
The `response_code` [redirect option](https://www.pomerium.com/docs/reference/routes/redirect#redirect-options) does not behave as documented. It currently accepts an Envoy [RedirectResponseCode](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#enum-config-route-v3-redirectaction-redirectresponsecode) enum value (in the range 0 through 4) instead of an HTTP status code.
Fix this option to behave as documented, by adding a translation step from numerical HTTP status code to the appropriate Envoy RedirectResponseCode enum value.
Add validation logic to reject any redirect status code that Envoy does not support.
- https://github.com/pomerium/pomerium/issues/4903
=> config: fix redirect response code

.golangci.yml, config/envoyconfig/bootstrap.go, config/envoyconfig/bootstrap_test.go, config/envoyconfig/clusters_envoy_admin.go, config/envoyconfig/clusters_test.go, config/envoyconfig/protocols_int_test.go, config/envoyconfig/testdata/clusters.json, internal/autocert/manager.go, internal/benchmarks/config_bench_test.go, internal/benchmarks/latency_bench_test.go, internal/controlplane/server.go, internal/controlplane/server_test.go, internal/log/debug.go, internal/testenv/environment.go, internal/testenv/logs.go, internal/testenv/route.go, internal/testenv/scenarios/mock_idp.go, internal/testenv/scenarios/mtls.go, internal/testenv/snippets/routes.go, internal/testenv/snippets/wait.go, internal/testenv/types.go, internal/testenv/upstreams/grpc.go, internal/testenv/upstreams/http.go, internal/testenv/values/value.go, pkg/cmd/pomerium/pomerium.go, pkg/cryptutil/tls.go, pkg/envoy/envoy.go, pkg/envoy/envoy_linux.go, pkg/grpc/databroker/syncer.go
This adds a new integration test fixture in the style of controller-runtime's test environment which can be used for lightweight in-process integration tests. This is not intended to replace the existing integration test system, only to cover a different set of use cases.
Only a basic feature set is implemented, additional features will be added as needed. 
The first example test using this is in protocols_int_test.go. I left the previous implementation there for now (will delete it once this is moved out of draft) to compare against.
Possibly obsoletes https://github.com/pomerium/pomerium/pull/5195
=> New integration test fixtures

config/envoyconfig/routes_test.go, config/policy.go, config/policy_test.go
Small bug fix, follow up to https://github.com/pomerium/pomerium/pull/5346
- https://github.com/pomerium/pomerium/issues/4903
=> config: only validate redirect response code when non-nil

config/envoyconfig/route_configurations_test.go, config/envoyconfig/routes_test.go, config/policy.go, config/policy_test.go, internal/benchmarks/latency_bench_test.go, internal/hashutil/hashutil.go
This contains the RouteID changes from https://github.com/pomerium/pomerium/pull/5185, but not the changes to Checksum functions. This will speed up requests, but will not speed up config building.
=> Optimize Policy RouteID

internal/benchmarks/latency_bench_test.go, internal/testenv/snippets/pprof.go
This adds a new function `snippets.PauseProfiling()`, which allows stopping and restarting CPU and memory profiling if running via -cpuprofile=filename and -memprofile=filename during tests.
=> testenv: Add utility to pause/resume profiling

internal/testenv/environment.go
This adds configuration for `MetricsAddr` in the global pomerium options.
=> testenv: configure metrics address

internal/testenv/dns.go, internal/testenv/selftests/dns_test.go, internal/testenv/upstreams/grpc.go, internal/testenv/upstreams/http.go
This adds a custom dialer that prevents lookups for `localhost.pomerium.io` and any subdomains to avoid flooding DNS servers with requests during benchmarks (and influencing benchmark results)
=> testenv: avoid dns lookups for *.localhost.pomerium.io

internal/telemetry/metrics/providers.go, internal/telemetry/prometheus/convert.go, internal/telemetry/prometheus/export.go, internal/telemetry/prometheus/export_test.go, internal/telemetry/prometheus/relabel.go, internal/telemetry/prometheus/relabel_test.go, internal/telemetry/prometheus/stream.go, internal/telemetry/prometheus/testdata/large.txt
Improves memory usage when producing Prometheus metrics by performing streaming processing. Previously, the entire Envoy metrics dump was loaded into memory and parsed for relabeling purposes, which added GC pressure when a lot of routes were present. 
https://github.com/pomerium/internal/issues/2003
=> core/metrics: improve memory usage

authorize/evaluator/headers_evaluator_evaluation.go, authorize/evaluator/headers_evaluator_test.go
Make sure to serialize the JWT "groups" claim as an empty list rather than a JSON null. This matches the behavior of Pomerium v0.27.2 and earlier, and should provide better compatibility with some third-party libraries.
- https://github.com/pomerium/pomerium/issues/5393
=> authorize: change handling of empty groups claim

internal/registry/reporter.go
This allows the reporter to shut down cleanly if the underlying context is canceled. It was previously only shut down when restarting.
=> registry: fix reporter client context on config change

databroker/cache.go, internal/retry/config.go, pkg/cmd/pomerium/pomerium.go, pkg/identity/legacymanager/config.go, pkg/identity/legacymanager/manager.go, pkg/identity/manager/config.go, pkg/identity/manager/manager.go
This adds the ability to adjust two previously hard coded durations - databroker lease TTL, and retry (package internal/retry) initial interval.
Cherry-picked from https://github.com/pomerium/pomerium/pull/5388
=> add options to adjust databroker lease ttl, and retry initial interval

internal/telemetry/metrics/info_test.go
Currently there appears to be a test order dependency between a couple of the info_test.go test cases and the `Test_PrometheusHandler` test. This can be exposed by running:
go test -count 2 ./internal/telemetry/metrics
The test cases in info_test.go overwrite the global 'registry' variable, which seems to prevent `Test_PrometheusHandler` from being able to export the internal Go metrics. Add a helper method to restore the original registry after these test cases.
=> metrics: restore global registry in unit tests

authorize/check_response.go, authorize/check_response_grpc.go, authorize/check_response_test.go
Add support to the authorize service for gRPC requests. We already supported gRPC-Web, which uses the same headers `grpc-status` and `grpc-message`. 
Updated the code to use `http.Header` consistently. There was also a bug in the `okResponse` with sorting, and now it will just use the same `toEnvoyHeaders` function we were already using.
- https://linear.app/pomerium/issue/ENG-1750/core-respond-with-json-to-a-grpc
=> authorize: handle gRPC requests

config/options.go, config/options_test.go, pkg/grpc/config/config.go
Because of the way we set branding settings if there were multiple settings in the databroker the last one would always win, even if no branding settings were set in it. This updates the code to only update the branding settings if at least one of the branding settings in the protobuf are set.
- https://linear.app/pomerium/issue/ENG-1766/branding-not-applied-to-core-pages-when-using-ingress-controller
=> config: fix lost branding settings when there are multiple configuration sources

go.mod, go.sum, internal/autocert/manager.go
Fix the HTTP redirect server so that if the proxy protocol is being used it will also be used for this server.
A longer term fix would be to use envoy for this server. However this has complications because it interacts poorly with certmagic.
As it stands now certmagic is not compatible with `use_proxy_protocol` and appears never to have been, but at least we can fix this issue when autocert is not being used. (The challenge is that certmagic provides no mechanism to add proxy protocol capability, so it's not clear how we can fix this given the package we're using)
For https://github.com/pomerium/pomerium/issues/5403
=> fix redirect server proxy protocol

authorize/databroker.go, authorize/internal/store/store.go, go.mod, go.sum
(cherry picked from commit 1709a7b1f61d7b45c4a60d9374223d252260f576)
related: https://github.com/pomerium/pomerium/pull/5411
This adds `grpc.WaitForReady(true)` to databroker queries in the authorize service. 
Previously, this would fail fast with a 503 error; the policy/header evaluation logic ignores these errors (only considering the response, which would be empty/nil regardless of error), and would continue the auth process and start redirecting the user to sign in, since it was unable to retrieve a session for the user. This causes some confusion, both in cases where the databroker [client] is offline when the user is redirected back after the oauth flow, and when the databroker comes online between the time that the user is redirected to sign in and the time that the user is …
=> authorize: enable WaitForReady on databroker query requests

config/envoyconfig/listeners_main.go, config/envoyconfig/testdata/main_http_connection_manager_filter.json, config/options.go, config/trace.go, config/trace_test.go
The previous default sample rate of 0.0001 is very low, so traces are unlikely to be visible after enabling them until many thousands of requests have been sent. This could be confusing to users.
=> config: set default tracing sample rate to 1.0

config/policy.go, pkg/zero/importutil/namegen.go, pkg/zero/importutil/namegen_test.go
Make the `GenerateRouteNames` function generic so it can work with protobuf Routes or config Routes. This is done by adding some getters to `config.Policy`.
- https://github.com/pomerium/pomerium/pull/5424#discussion_r1915429150
=> importutil: refactor GenerateRouteNames to allow for protobuf or config routes

config/envoyconfig/filters.go, config/envoyconfig/http_connection_manager.go, config/envoyconfig/outbound.go, config/envoyconfig/testdata/main_http_connection_manager_filter.json, config/envoyconfig/testdata/metrics_http_connection_manager.json
See docs: https://www.envoyproxy.io/docs/envoy/v1.32.3/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-internal-address-config
=> envoy: add internal_address_config to address deprecation warning

config/options.go, config/options_test.go
When applying the settings proto, update the JWT groups filter option only if the filter set is non-empty.
This is important when Pomerium via the Ingress Controller in combination with Pomerium Enterprise. In this scenario there is a settings proto applied from both Ingress Controller and the Enterprise console, and we want to make sure the one from Ingress Controller does not overwrite the filter settings from Enterprise.
(This is the same kind of issue and the same kind of fix as in https://github.com/pomerium/pomerium/pull/5401.)
https://linear.app/pomerium/issue/ENG-1802/add-support-for-jwt-groups-filtering
=> config: fix JWT groups filter option

internal/telemetry/trace/debug_test.go
Fix test flake seen in https://github.com/pomerium/pomerium/actions/runs/12893427421/job/35949817188
=> Fix small timeout causing test flake

authorize/authorize.go, authorize/cache_warmer.go, authorize/cache_warmer_test.go, authorize/databroker_test.go, authorize/grpc.go, internal/testenv/selftests/tracing_test.go, pkg/storage/cache.go, pkg/storage/cache_test.go, pkg/storage/querier.go
Add a cache warmer that will sync records from the databroker and add them to the cache. These records are set with a TTL a year in the future so they won't expire. 
- https://linear.app/pomerium/issue/ENG-1915/authorize-improve-group-query-performance
=> authorize: cache warming

authorize/authorize.go, authorize/grpc.go
Removes `Authorize.stateLock` mutex as it's currently not guarding anything.
=> core/authz: remove unused mutex

config/envoyconfig/bootstrap.go, config/envoyconfig/bootstrap_test.go, internal/benchmarks/latency_bench_test.go, internal/telemetry/trace/global.go, internal/telemetry/trace/server.go, internal/testenv/scenarios/trace_receiver.go
Update envoy otel flush interval and span batch size parameters to match the same values from the go sdk. The go defaults are 5000ms and 512 spans respectively.
=> tracing: adjust envoy otel trace batching settings to match go sdk

authorize/evaluator/headers_evaluator_evaluation.go, authorize/evaluator/headers_evaluator_test.go
Change the JWT groups filtering behavior:
- to filter only by group ID (not group name)
- and only for groups sourced from directory sync (groups from a `"groups"` claim will not be filtered)
This avoids the need to fetch all group names up front, which should improve performance in specific circumstances.
https://linear.app/pomerium/issue/ENG-1802/add-support-for-jwt-groups-filtering
=> authorize: filter only by group ID

authorize/evaluator/evaluator.go, authorize/evaluator/headers_evaluator.go, authorize/evaluator/headers_evaluator_evaluation.go, authorize/evaluator/headers_evaluator_test.go, authorize/log.go, authorize/log_test.go, internal/log/authorize.go
Add a new mechanism for passing additional authorize log fields back from the authorize `Evaluator`. Use this mechanism to pass back the count of groups removed due to the JWT groups filter option as the new log field `removed-groups-count`.
Also add a separate debug-level log entry with the specific IDs of any removed groups.
https://linear.app/pomerium/issue/ENG-1802/add-support-for-jwt-groups-filtering
=> authorize: log JWT groups filtering

scripts/protoc
The script to generate protobuf downloaded several 3rd party repositories. It would skip this if the local directory already existed. Because of the way this was done it would not detect if the URL was updated. This PR updates the code to check the url and if it changes the zip is downloaded. To make this work the URLs also need to be pinned to a specific commit, so I updated the URLs accordingly.
=> proto: fix dependencies

.github/workflows/backport.yaml, .github/workflows/benchmark.yaml, .github/workflows/codeql.yaml, .github/workflows/docker-main.yaml, .github/workflows/docker-version-branches.yaml, .github/workflows/lint.yaml, .github/workflows/needs-data.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml
pending https://github.com/actions/runner-images/issues/11471 resolution, this moves us back to images that were working.
There is a recent issue with the image used to run github actions that results in odd errors and segmentation faults on arm64/aarch64 platforms.  
https://github.com/pomerium/pomerium/pull/new/rsmith/downgrade-22.04
=> roll back to using ubuntu-22.04 images

.golangci.yml, config/config_source.go, config/envoyconfig/clusters_test.go, config/envoyconfig/filemgr/filemgr_test.go, config/envoyconfig/filemgr/name.go, config/envoyconfig/listeners_test.go, config/envoyconfig/route_configurations_test.go, config/envoyconfig/routes_test.go, config/envoyconfig/testdata/metrics_http_connection_manager.json, config/envoyconfig/tls_test.go, config/policy.go, go.mod, internal/hashutil/hashutil.go, internal/hashutil/hashutil_test.go, internal/testutil/tracetest/buffer.go, pkg/zero/importutil/namegen.go, proxy/handlers_portal_test.go, proxy/portal/portal_test.go
Replace `xxhash` with `xxh3`. According to [the documentation](https://xxhash.com/doc/v0.8.3/index.html):
> Modern 64-bit and 128-bit hash function family which features improved strength and performance across the board, especially on smaller data. It benefits greatly from SIMD and 64-bit without requiring it.
This PR is mostly updating tests where the id has changed. I also updated the trace buffer test because it was relying on ordering of the base64 encoding of the hash. It will now use insertion order instead for deterministic results.
=> replace xxhash with xxh3

config/config_source.go, config/config_source_test.go
Add a `SIGHUP` handler to the `FileOrEnvironmentSource`. When this signal is received config will be reloaded.
Fixes #5458
=> config: handle SIGHUP

config/envoyconfig/tracing.go
https://linear.app/pomerium/issue/ENG-1960
=> tracing: add missing check for otel_exporter_otlp_endpoint in envoy trace config

internal/telemetry/trace/client.go, internal/telemetry/trace/client_test.go
Treat empty-string protocol the same way as nil/unset, and attempt to auto detect from the endpoint.
=> tracing: handle empty protocol

ui/src/components/RoutesPage.tsx
Fix the error message that is displayed when there are no routes available for the routes portal.
- [ENG-1980](https://linear.app/pomerium/issue/ENG-1980/the-routes-portal-page-lacks-message-no-accessible-routes-found-when)
=> proxy: fix routes portal error message

internal/telemetry/trace/client.go, pkg/cmd/pomerium/pomerium.go
This adds the necessary locking to calls to trace/SyncClient.Update on config change.
=> Fix trace client update

proxy/portal/portal.go, proxy/portal/portal_test.go, ui/src/components/RoutesPage.tsx
For extended TCP routes like `tcp+https://proxy.corp.example.com:8443/redis.internal.example.com:6379` the connect command was only showing `pomerium-cli tcp proxy.corp.example.com:8443`, but it should've used the whole URL.
- [ENG-1981](https://linear.app/pomerium/issue/ENG-1981/extended-tcp-routes-display-incorrectly-on-the-routes-portal-getting)
=> proxy: fix connect command in routes portal

config/envoyconfig/filemgr/config.go, config/envoyconfig/filemgr/filemgr.go, config/options.go, internal/fileutil/atomic.go, internal/fileutil/atomic_test.go, internal/fileutil/directories.go, internal/zero/cmd/env.go
We've been bitten in the past by `XDG_CACHE_HOME` not being set. This updates the code referencing these directories to log an error indicating what default was used.
There is a change here to what default is used. Previously the autocert default directory would default to `$HOME/.local/share/pomerium`, and then if `HOME` wasn't set, to `./.local/share/pomerium`. If `HOME` isn't set it will now default to `/tmp/pomerium/data`.
For the `envoyconfig` filemgr, we previously defaulted to `/tmp/{random uuid}`, when neither `XDG_CACHE_HOME` nor `HOME` was set. This could result in lots of redundant files. With this change it will always end up at `/tmp/pomerium/cache`. As a result we may end up having multiple file managers sharing a directory, which the random UUID was preventing at least some …
=> fileutil: add directory helpers, atomic file writing

pkg/netutil/netutil.go, pkg/netutil/netutil_test.go
Try to improve the way we allocate ports so we don't end up re-using a recently allocated port. Hopefully this will improve some test flakiness.
=> netutil: improve port allocation

proxy/data.go, proxy/data_test.go, proxy/handlers.go, proxy/handlers_portal.go, proxy/proxy.go, proxy/proxy_test.go, proxy/state.go
Creating sessions for IdP tokens was implemented in #5484 . This adds the same functionality to the proxy service.
- [ENG-2017](https://linear.app/pomerium/issue/ENG-2017/proxy-add-support-for-loading-sessions-via-idp-access-and-identity)
=> support loading idp token sessions in the proxy service

go.mod, go.sum
Upgrade the x/oauth2 module in response to CVE-2025-22869.
=> upgrade x/oauth2 from v0.24.0 to v0.27.0

pkg/envoy/get-envoy/main.go
=> get-envoy: allow downloading a specific os/arch

internal/fileutil/directories.go, internal/telemetry/trace/trace.go
Remove some noisy logs.
- [ENG-1982](https://linear.app/pomerium/issue/ENG-1982/core-version-command-output-includes-error-log-entry)
=> remove noisy logs

config/session.go, config/session_test.go
When we create a session for an IdP token we also create a `user.User` object. Currently if there is already a user object we would overwrite it. This PR instead merges the existing user record with claims from the access or identity token, so emails, names, etc should be preserved.
- [ENG-2062](https://linear.app/pomerium/issue/ENG-2062/core-users-created-from-idp-tokens-overwrite-existing-users)
=> config: preserve existing user when creating sessions from idp token

config/policy_ppl_test.go, pkg/policy/criteria/domain.go, pkg/policy/criteria/domain_test.go, pkg/policy/criteria/email.go, pkg/policy/criteria/email_test.go, pkg/policy/rules/rules.go
Update policy evaluation of `email` and `domain` to support retrieving a user's email address from the `DirectoryUser` in addition to the `User` record in the databroker.
We already do this when evaluating headers, so this seems like an oversight of the current implementation.
- #5503
=> policy: support emails from directory user

proxy/handlers_portal.go, proxy/portal/logo_provider_favicon.go, proxy/portal/logo_provider_test.go
Add a short `500ms` timeout on the logo discovery request for the routes portal to prevent the page from timing out on misbehaving upstream services.
- [ENG-2071](https://linear.app/pomerium/issue/ENG-2071/routes-portal-often-times-out-in-master-pgsql-env)
=> proxy: add short timeout for logo discovery

ui/src/components/RoutesPage.tsx
Adds a box around the route name to add word wrap and padding.
Also changes the height of the card to account for multiple lines.
ENG-2026
Handles long route names.
=> handle long names in the cards for route portal - ENG-2026

internal/testutil/testutil.go
use cmp.Diff in protojson comparisons that allows to see specifically which field doesn't match.
=> testutil: use cmp.Diff in protobuf json assertion

config/options_test.go, config/policy.go, config/policy_test.go
Fix a bug from https://github.com/pomerium/pomerium/pull/5508: remove the previous conversion logic in `NewPolicyFromProto()` for the `jwt_issuer_format` field. This would prevent the new "unset" state from working correctly. Add a unit test to verify that all three values (unset, "hostOnly" and "uri") will successfully round trip to the proto format and back again.
Also add a test case for the `Options.ApplySettings()` method to verify that an unset `jwt_issuer_format` will not overwrite the existing value (if any) in the settings.
https://linear.app/pomerium/issue/ENG-2072/config-jwt-issuer-format-should-also-be-support-at-the-global-level
=> config: fix jwt_issuer_format conversion

config/envoyconfig/listeners_main.go, config/envoyconfig/testdata/main_http_connection_manager_filter.json
Disable HTTP2/Connect that seems to break websocket protocol upgrade in #5387
Fix https://github.com/pomerium/pomerium/issues/5431
=> websockets: disable http2 connect

config/metrics.go, config/runtime_flags.go, go.mod, internal/telemetry/metrics/bench_test.go, internal/telemetry/metrics/providers.go, internal/telemetry/metrics/providers_test.go, internal/telemetry/prometheus/relabel_text_stream.go, internal/telemetry/prometheus/relabel_text_stream_test.go
We add extra labels (hostname and installation id) to the Prometheus metrics output.
Previously we were parsing the incoming streams (from Envoy and internal ones) with `expfmt` prometheus library, updated each entry with extra labels and encoded back.
Unfortunately in a large streams that creates a significant GC pressure as a lot of small objects are created and destroyed.
This PR tries to do metric label augmentation with minimal GC allocations. It also adds a runtime flag `add_extra_metrics_labels` that would disable adding extra labels entirely, if they are not explicitly used during queries. 
Ref: https://linear.app/pomerium/issue/ENG-2117
Ref: https://github.com/pomerium/pomerium/issues/5378
=> metrics: reduce gc pressure

config/options.go, config/options_test.go
The `bearer_token_format` and `idp_access_token_allowed_audiences` options are currently always being overwritten when applying protobuf config. When there are two sources of configuration (for example the ingress controller and the enterprise console), the last applied configuration should take precedence, but since these fields are optional, they should only overwrite the existing configuration option if they are set, otherwise the current value should be preserved.
- [ENG-2171](https://linear.app/pomerium/issue/ENG-2171/idp-token-configuration-issue)
=> config: fix layered bearer_token_format and idp_access_token_allowed_audiences

internal/telemetry/trace/debug_test.go
Should fix these test flakes:
```
--- FAIL: TestSpanObserver (0.12s)
--- FAIL: TestSpanObserver/new_references_observed_during_wait (0.08s)
debug_test.go:125: 
Error Trace:	/Users/runner/work/pomerium/pomerium/internal/telemetry/trace/debug_test.go:125
Error:      	Condition never satisfied
Test:       	TestSpanObserver/new_references_observed_during_wait
--- FAIL: TestSpanObserver/multiple_waiters (0.02s)
debug_test.go:148: 
Error Trace:	/Users/runner/work/pomerium/pomerium/internal/telemetry/trace/debug_test.go:148
Error:      	Condition never satisfied
Test:       	TestSpanObserver/multiple_waiters
```
=> Increase some test timeouts

authorize/authorize.go, authorize/databroker.go, authorize/databroker_test.go, authorize/grpc.go, pkg/grpc/databroker/databroker.go, pkg/storage/cache.go, pkg/storage/querier.go, pkg/storage/querier_test.go, proxy/data.go, proxy/data_test.go, proxy/proxy.go, proxy/state.go
Update the proxy service to use the same querier interface and cache as the authorize service. This should improve performance for redundant queries, like group information. In all-in-one mode it will also have the added benefit of using the same cached data that was used for authorization.
- [ENG-2160](https://linear.app/pomerium/issue/ENG-2160/core-inefficient-userinfo-groups)
=> proxy: use querier cache for user info

internal/telemetry/metrics/info.go
The IdentityManagerLastSessionRefreshErrorView appears to be a duplicate of IdentityManagerLastUserRefreshErrorView. Adjust it to use the matching identityManagerLastSessionRefreshError instead.
https://linear.app/pomerium/issue/ENG-2190/core-identitymanagerlastsessionrefresherrorview-appears-to-be
=> metrics: fix an apparent metric setup error

config/session.go, config/session_test.go, internal/httputil/headers.go, proxy/data_test.go, proxy/proxy_test.go
Instead of 
```
X-Pomerium-IDP-Access-Token: <TOKEN>
Authorization: Pomerium-IDP-Access-Token <TOKEN>
Authorization: Bearer Pomerium-IDP-Access-Token-<TOKEN>
X-Pomerium-IDP-Identity-Token: <TOKEN>
Authorization: Pomerium-IDP-Identity-Token <TOKEN>
Authorization: Bearer Pomerium-IDP-Identity-Token-<TOKEN>
```
Only support:
```
Authorization: Bearer Token
```
With the corresponding bearer token format option set.
=> only support loading idp tokens via bearer tokens

.github/workflows/release.yaml
Set NodeJS version to 22 in `goreleaser` action.
=> ci: set goreleaser Node version to 22

authenticate/handlers.go, authenticate/handlers_test.go, authenticate/middleware.go
Remove the `/.pomerium/callback` handler in the authenticate service. This appears to have been added to allow using webauthn devices in the authenticate service, but this is no longer allowed (the webauthn registration and creation options are only passed on the proxy service), so this code appears to be unnecessary.
Currently this function is called instead of the proxy service's `/.pomerium/callback` function. As a result the pomerium session cookie is not being written in a way that the authorize service can read. We are writing `_pomerium_authenticate` in the authenticate service, and `_pomerium` in the proxy service. Because the cookie isn't written properly, the next call to the authorize service fails, resulting in an infinite redirect loop.
By removing this function, the proxy …
=> authenticate: remove /.pomerium/callback handler

internal/fileutil/directories.go
This log message ends up getting printed very early (during init in some places), so is difficult to remove by configuring the global logger. I'm not sure it's actually useful anyway, so we can just remove it.
- https://github.com/pomerium/cli/issues/509#issuecomment-2771809348
=> remove debug log message for directories

authorize/check_response.go, authorize/state.go, config/options.go, config/policy.go, config/policy_test.go, internal/authenticateflow/authenticateflow_int_test.go, internal/authenticateflow/stateful.go, internal/authenticateflow/stateful_test.go, internal/authenticateflow/stateless.go, internal/urlutil/proxy.go, internal/urlutil/query_params.go, proxy/handlers.go, proxy/state.go
Add support for redirecting through multiple domains upon initial login to a Pomerium route. This may be useful for resolving CORS issues in certain circumstances (e.g. single-page applications that host resources on different sub-domains).
Add a new `depends_on` route setting that accepts a list of additional hosts to redirect through.
Add an integration test using the `testenv` framework.
Caveats:
- This feature is not available for Pomerium deployments using the Hosted Authenticate Service.
- This feature is not available for programmatic login.
- There is a limit of 5 additional hosts for a particular route.
- All of the additional hosts must resolve to the same Pomerium deployment.
https://linear.app/pomerium/issue/ENG-1710/better-support-for-cross-domain-requests
=> multi-domain login redirects

authorize/evaluator/evaluator.go, cmd/pomerium/main.go, config/config_source.go, config/metrics.go, config/options.go, internal/log/grpc.go, pkg/envoy/resource_monitor_linux.go, pkg/grpc/databroker/syncer.go
Cleanup some logs:
- remove the authorize signing key log message
- remove the `config_file_source` and `bootstrap` fields added to every log line. It's unclear what these fields were intended to mean, but they don't appear to be updated depending on the configuration source.
- change the file watcher underlying config change message to `debug`
- remove the message about metrics being disabled
- remove the `server will be using a self-signed certificate` message. The ask was to remove it only for zero, enterprise or the ingress controller, but the way pomerium works is by loading an initial config, and then the subsequent configs come in via the databroker, so it will start with a self-signed certificate regardless (in other words this log message is accurate)
- change default gRPC levels …
=> cleanup logs

authenticate/handlers.go, config/config_source.go, config/options.go, databroker/cache.go, internal/autocert/manager.go, internal/controlplane/server.go, internal/databroker/config_source.go, internal/log/log_test.go, internal/telemetry/metrics/info.go, internal/testenv/snippets/wait.go, internal/zero/api/download.go, internal/zero/reconciler/sync.go, pkg/cmd/pomerium/pomerium.go, pkg/grpc/databroker/leaser.go, pkg/grpc/databroker/syncer.go, pkg/identity/manager/manager.go, pkg/storage/inmemory/backend.go
We currently have a mix of hyphens and underscores in log event attribute names. Let's standardize on hyphens, as that seems to be more the more common of the two kinds.
https://linear.app/pomerium/issue/ENG-2326/consistent-naming-convention-for-log-message-attributes
=> logging: standardize on hyphens in attribute names

config/envoyconfig/http_connection_manager.go, config/envoyconfig/route_configurations.go, config/envoyconfig/route_configurations_test.go, config/envoyconfig/routes.go, config/envoyconfig/routes_test.go, config/options.go, config/options_test.go, internal/controlplane/http.go, internal/mcp/handler.go, internal/mcp/handler_metadata.go
For MCP routes, serve `/.well-known/oauth-authorization-server` according to OAuth 2.0 Authorization Server Metadata (RFC8414). 
Fixes: https://linear.app/pomerium/issue/ENG-2318/mcp-authorization-server-metadata
=> mcp: add oauth metadata endpoint

go.mod, pkg/storage/postgres/backend_test.go
@wasaga reports that there have been some recent test failures in `TestLookup` with the error message "i/o timeout". It looks like this test does a real DNS lookup, and so depends on a working DNS server and reliable network connectivity. Let's swap in a fake in-memory DNS server instead.
https://linear.app/pomerium/issue/ENG-2352/core-test-flake-in-pkgstoragepostgresbackend-testgo
=> storage: use a fake DNS server in TestLookup

internal/mcp/handler.go, internal/mcp/handler_authorization.go, internal/mcp/oauth_config.go, internal/mcp/oauth_config_test.go
If the mcp route has `upstream_oauth2` configured, redirect `/.pomerium/mcp/authorize` call to the auth URL of that server, with callback set to the internal route handler `/.pomerium/mcp/oauth/callback`. 
Ref: https://linear.app/pomerium/issue/ENG-2321/mcp-support-handling-external-oauth-servers
=> mcp: redirect to upstream oauth2 for authentication

pkg/identity/oauth/apple/apple.go, pkg/identity/oauth/apple/apple_test.go
Add support for IdP identity token authorization for Apple. Apple does not appear to support access token validation.
This allows a user to pass an identity token directly as a bearer token:
```
curl -H 'Authorization: Bearer Apple-Identity-Token' ...
```
- [ENG-2000](https://linear.app/pomerium/issue/ENG-2000/core-implement-token-validation-for-apple)
=> authenticate: add support for apple identity tokens

pkg/identity/oidc/azure/microsoft_test.go, pkg/identity/oidc/oidc.go, pkg/identity/oidc/oidc_test.go
For the generic `oidc` provider, used by `auth0`, `cognito`, `gitlab`, `google`, `oidc`, `okta`, `onelogin` and `ping`, add support for direct access and identity token verification. Because Keycloak uses `oidc` this also adds support for Keycloak.
Access tokens are verified by using the user info endpoint. If a call to this endpoint succeeds using the access token, that access token is considered valid and the user info claims will be returned.
Identity tokens are verified by using the jwks endpoint to retrieve the signing key, and verifying that the identity token was signed with that key. If the identity token is valid the claims in the JWT will be returned.
- [ENG-2312](https://linear.app/pomerium/issue/ENG-2312/core-implement-token-validation-for-keycloak)
=> identity: add IdP access and identity token verification for OIDC

pkg/identity/oauth/github/github.go, pkg/identity/oauth/github/github_test.go
Implement direct access token support for GitHub. GitHub doesn't have identity tokens, so that isn't supported. The "IdP Access Token Allowed Audiences" option is also not supported because GitHub doesn't populate an `aud` claim.
- [ENG-2137](https://linear.app/pomerium/issue/ENG-2137/core-implement-token-validation-for-github)
=> identity: add access token support for github

authorize/authorize_int_test.go, authorize/grpc.go, authorize/state.go
A customer reports high `ext_authz_error` rates when using the IdP token auth feature under heavy load. We have a `singleflight` group to avoid making duplicate verify requests to the authenticate service in this case, but it looks like it is not having the intended effect. Instead, move the `IncomingIDPTokenSessionCreator` initialization into the main authorize state object.
Add an integration test to assert that making a large number of requests with the same IdP token will result in only one token verification request to the authenticate service.
https://linear.app/pomerium/issue/ENG-2387/high-ext-authz-error-rates-with-idp-token-auth
=> authorize: move IdP token session creator initialization

config/envoyconfig/routes.go
- fix wording in routes.go comment referencing authenticate service
- `go vet ./...`
- `go test ./config/...` *(fails: connect: no route to host)*
=> Fix comment grammar

pkg/hpke/hpke.go
- fix a typo in `pkg/hpke/hpke.go` comment
- `go vet` *(fails: module download timed out)*
- `go test ./...` *(fails: module download timed out)*
[n.b. this was an experiment using codex]
=> Fix typo in Seal comment

authorize/evaluator/evaluator.go, authorize/grpc.go, authorize/grpc_test.go, authorize/log.go, authorize/log_test.go, config/envoyconfig/per_filter_config.go, config/envoyconfig/route_configurations_test.go, config/envoyconfig/routes.go, config/envoyconfig/routes_test.go, config/policy.go, config/policy_test.go, internal/controlplane/xdsmgr/xdsmgr.go, internal/controlplane/xdsmgr/xdsmgr_test.go, internal/databroker/config_source.go, internal/httputil/reproxy/reproxy.go, internal/log/authorize.go, proxy/portal/portal.go
Update the `RouteID` to use the `policy.ID` if it is set. This makes it so that updated routes use a stable identifier between updates so if the envoy control plane is updated before the authorize service's internal definitions (or vice-versa) the authorize service will still be able to match the route.
The current behavior results in a 404 if envoy passes the old route id. The new behavior will result in inconsistency, but it should be quickly remedied. To help with debugging 4 new fields were added to the authorize check log. The `route-id` and `route-checksum` as the authorize sees it and the `envoy-route-id` and `envoy-route-checksum` as envoy sees it.
I also updated the way we send updates to envoy to try and model their recommended approach:
> In general, to avoid traffic drop, …
=> config: use stable route ids for authorize matching and order xds responses

config/policy.go, config/policy_test.go
Currently in core we support weighted URLs like this in the config file:
```yaml
to: 
- https://a.example.com,1
- https://b.example.com,2
```
However in the protobuf we use a separate `load_balancing_weights` field:
```proto
message Route {
repeated string to                     = 3;
repeated uint32 load_balancing_weights = 37;
}
```
This PR updates the code to convert from protobuf so that it also supports weights directly in the `to` addresses. The existing `load_balancing_weights` behavior is preserved and will take precedence when provided.
- [ENG-2398](https://linear.app/pomerium/issue/ENG-2398/enterprise-api-upstream-weight-is-not-parsed)
=> config: support weighted URLs in To field

authorize/authorize.go, authorize/databroker.go, authorize/databroker_test.go, authorize/grpc.go, authorize/state.go, pkg/grpc/databroker/databroker.go, pkg/storage/cache.go, pkg/storage/querier.go, pkg/storage/querier_test.go, proxy/data.go, proxy/data_test.go, proxy/proxy.go, proxy/state.go
Backport #5532 to 0.29.
- [ENG-2160](https://linear.app/pomerium/issue/ENG-2160/core-inefficient-userinfo-groups)
=> proxy: use querier cache for user info (#5532)

internal/mcp/handler_register_client.go
Some clients may send RFC7591 Client Registration Request with extra fields that are not part of the spec, and we used too restrictive decoder for that. This PR ignores the unknown fields.
=> mcp: ignore unknown fields in the client registration request

pkg/cryptutil/pem.go, pkg/cryptutil/pem_test.go
Fix for an issue with #5642 . If a file didn't end in a newline it was possible for blocks to be concatenated like this:
```
-----END CERTIFICATE----------BEGIN CERTIFICATE-----
```
This would only happen if the last certificate was moved forward. (Technically the spec requires a newline, but a trimmed input would be missing it, so we should tolerate that)
#5642
=> fix pem normalization when file has no trailing newline

pkg/cryptutil/pem.go, pkg/cryptutil/pem_test.go
If a certificate was its own authority it would result in `NormalizePEM` going into an infinite loop. This PR updates the code to avoid cycles using a set.
- [ENG-2423](https://linear.app/pomerium/issue/ENG-2423/enterprise-console-updatekeypair-check-is-too-restrictive)
=> cryptutil: fix normalize pem with certificate cycles

config/envoyconfig/listeners_main.go, config/envoyconfig/local_reply.go, config/envoyconfig/local_reply_test.go
Add a test to ensure the local reply config results in errors in the right format.
- [ENG-2470](https://linear.app/pomerium/issue/ENG-2470/core-add-test-for-grpc-error-formatting)
=> envoyconfig: add test for local reply

pkg/policy/criteria/matchers.go, pkg/policy/criteria/matchers_test.go
Adds `in` string matcher to PPL, that matches a string with an array of strings. 
Related: https://linear.app/pomerium/issue/ENG-2393
=> ppl: add in string matcher

authorize/evaluator/evaluator.go, authorize/evaluator/evaluator_test.go, authorize/evaluator/policy_evaluator.go, authorize/grpc.go, pkg/policy/criteria/criteria_test.go, pkg/policy/criteria/mcp_tool.go, pkg/policy/criteria/mcp_tool_test.go, pkg/policy/criteria/reasons.go
Adds `mcp_tool` PPL criterion, that matches MCP tool names like 
```yaml
- from: https://db.localhost.pomerium.io
to: http://localhost:3000/mcp
policy:
allow:
and:
- email: 
in: ["user@pomerium.com"]
- mcp_tool:
in: ["list_tables", "read_table", "search_records"]
mcp: {}
```
Fix https://linear.app/pomerium/issue/ENG-2393/mcp-authorize-each-incoming-request-to-an-mcp-route
=> mcp: add mcp_tool to ppl

pkg/identity/mock_provider.go, pkg/identity/oauth/apple/apple.go, pkg/identity/oauth/github/github.go, pkg/identity/oidc/errors.go, pkg/identity/oidc/oidc.go, pkg/identity/providers.go
This adds the necessary logic needed for device auth flow in ssh. The code is not used currently; will follow up with testenv updates that can let us test this with the mock idp.
=> oauth: add minimal device auth support for ssh

internal/testenv/scenarios/mock_idp.go, internal/testenv/upstreams/http.go, internal/testutil/mockidp/mockidp.go
Refactor the testenv mock IdP implementation to split off the core functionality from the testenv environment setup. Add a Start() method to run the mock IdP as an httptest server, tied to a test lifecycle. This allows the mock IdP to be used also in tests that do not start a full Pomerium instance.
n/a
=> refactor testenv mock IdP to also work standalone

authorize/authorize.go, authorize/ssh_grpc.go, authorize/state.go, pkg/ssh/auth.go, pkg/ssh/auth_test.go, pkg/ssh/manager.go, pkg/ssh/manager_test.go, pkg/ssh/stream.go, pkg/ssh/stream_test.go
Re-evaluate ssh authorization decision on a fixed interval. If access is no longer allowed, log a new `authorize check` message and disconnect.
https://linear.app/pomerium/issue/ENG-2044/support-continuous-verification-with-ssh-proxying
=> ssh: continuous authorization

go.mod, pkg/ssh/ssh_int_test.go
Add a bare-bones integration test using the testenv framework to verify the basics of SSH proxying: configure an upstream ssh server and connect to it through Pomerium.
https://linear.app/pomerium/issue/ENG-2242/write-e2e-test-framework-for-pomerium-integration-with-ssh-network
=> ssh: add basic end-to-end test

config/envoyconfig/clusters.go, config/envoyconfig/clusters_test.go, config/envoyconfig/envoyconfig.go, config/envoyconfig/testdata/clusters.json, config/validate.go
Address the deprecation warnings for `respect_dns_ttl` by migrating to the newer CustomClusterType config proto.
https://linear.app/pomerium/issue/ENG-2503/address-envoy-deprecation-warning-for-respect-dns-ttl
=> config: migrate deprecated cluster DNS settings

.github/workflows/test.yaml
Set `fail-fast: false` so that if one of these jobs fails it will not cancel the other. These have have unfortunately become very flaky, and the current behavior is not helpful.
Remove 'go-version' from the matrix as it is currently unused and it does not match the actual Go version in use.
=> ci: update build job

authorize/evaluator/evaluator.go, authorize/grpc_test.go, authorize/log.go, authorize/log_test.go, internal/log/authorize.go
Adds an option to log request body for protocols that perform request inspection, such as MCP. 
Fix https://linear.app/pomerium/issue/ENG-2544/authorize-request-body-logging
=> authorize: add request body logging

config/runtime_flags.go, internal/testenv/scenarios/ssh.go, pkg/ssh/auth.go, pkg/ssh/auth_test.go, pkg/ssh/stream.go, pkg/ssh/stream_test.go, pkg/storage/querier_sync.go
Adds a new runtime flag `ssh_allow_direct_tcpip` (default false) which enables the "jump-host mode". This is disabled by default since we are missing related config options/policy criteria.
=> ssh: add runtime flag for jump host mode

.github/goreleaser-mac.yaml, .github/goreleaser.yaml
Instead, we'll generate Homebrew formula updates from a workflow triggered after the macOS builds finish. See https://github.com/pomerium/homebrew-tap/pull/26 and https://github.com/pomerium/mac-builds/pull/6.
https://linear.app/pomerium/issue/ENG-2546/core-release-fails-due-to-unsupported-goreleaser-homebrew-option
=> ci: remove 'brews' configuration from GoReleaser

config/envoyconfig/listeners_ssh.go
OpenSSH requires a trailing newline for private keys, which is easy to accidentally omit when configuring private keys as strings inline via copy/paste. This adds the missing newline if it is not present. Private keys read from files still require the trailing newline.
=> ssh: add trailing newline to key strings if missing

config/runtime_flags.go, pkg/envoy/envoy.go, pkg/envoy/resource_monitor_linux.go
Explicitly set the `concurrency` option for envoy to match `GOMAXPROCS`. In v1.25 the default behavior of `GOMAXPROCS` will change:
> On Linux, the runtime considers the CPU bandwidth limit of the cgroup containing the process, if any. If the CPU bandwidth limit is lower than the number of logical CPUs available, GOMAXPROCS will default to the lower limit. In container runtime systems like Kubernetes, cgroup CPU bandwidth limits generally correspond to the “CPU limit” option.
However we use [github.com/uber-go/automaxprocs](https://github.com/uber-go/automaxprocs) so we already have this behavior.
This behavior is enabled by default but can be disabled by setting the runtime flag `set_envoy_concurrency_to_go_max_procs` to false. 
This change will be backported to v0.30 and v0.29, though …
=> envoy: set concurrency to GOMAXPROCS

config/runtime_flags.go, pkg/envoy/envoy.go
Backport #5721 to v0.29. For v0.29 this runtime flag defaults to false rather than true.
=> envoy: set concurrency to GOMAXPROCS (#5721)

pkg/synccache/sync_cache.go, pkg/synccache/sync_cache_test.go
Move SyncCache from pkg/grpc/databroker to a new pkg/synccache package.
https://linear.app/pomerium/issue/ENG-2571/clicore-refactor-databroker-code-to-avoid-pebble-dependency
=> move SyncCache to a new pkg/synccache package

.github/workflows/lint.yaml, Makefile, pkg/identity/manager/schedulers_test.go
Rework the existing identity manager scheduler tests to use the new [testing/synctest](https://go.dev/blog/synctest) package. This should let us test the timing more precisely, and make it easier to exercise more complex scenarios.
Add a new test to exercise the session refresh scheduling behavior around the OAuth access token expiration time.
In preparation for https://linear.app/pomerium/issue/ENG-2588/support-configuring-earlier-token-refresh-and-id-token-expiration.
=> identity manager: use synctest for scheduler tests

config/envoyconfig/clusters.go, config/helpers.go, config/helpers_test.go, config/options.go, internal/telemetry/util.go, internal/telemetry/util_test.go
Currently you can either run a single service or all-in-one mode. This PR adds support for running any 2 or 3 services together. For example `services: authorize,proxy`.
I think I updated the conditions to make sense, but there's some risk here as there may have been some assumptions in places I'm overlooking.
- [ENG-2485](https://linear.app/pomerium/issue/ENG-2485/core-support-running-multiple-but-not-all-services)
=> config: support multiple running services in addition to all-in-one mode

internal/mcp/token.go
Upstream OAuth2 providers may not return the refresh token at every access token renewal request, 
this PR ensures we do not accidentally overwrite the refresh token at hand with an empty string. 
Fix https://linear.app/pomerium/issue/ENG-2619/mcp-upstream-oauth2-google-drive-did-not-return-refresh-token
=> mcp: if upstream oauth does not return a refresh token, keep previous

pkg/storage/postgres/option.go, pkg/storage/postgres/postgres.go, pkg/storage/postgres/postgres_test.go
When there are a large number of record changes and several databrokers, the query to delete those record changes can sometimes deadlock. If we use a CTE with `FOR UPDATE SKIP LOCKED` we can avoid this deadlock.
I also lowered the default expiry from 24 hours to 1 hour. The record changes table is used via `Sync` and any client using `Sync` should already account for missing records by switching to `SyncLatest` if its too far behind. An hour ought to be more than sufficient.
- [ENG-2635](https://linear.app/pomerium/issue/ENG-2635/core-postgres-deadlock-in-record-change-deletion)
=> postgres: fix delete deadlock

.github/workflows/test.yaml
I think the step to upload coverage to coveralls has been getting skipped since https://github.com/pomerium/pomerium/pull/5456.
=> ci: restore coverage step in test workflow

config/envoyconfig/clusters.go, config/envoyconfig/clusters_test.go
Do not automatically set an upstream source address if the freebind option is set. It looks like Envoy can apply the freebind option whether or not a source address is set, and if we set 0.0.0.0:0 as the default this will cause errors with IPv6 upstream connections.
https://linear.app/pomerium/issue/ENG-2606/core-applying-empty-settings-protobuf-should-not-modify-configuration
https://linear.app/pomerium/issue/ENG-2637/core-allow-freebind-and-source-address-settings-to-be-completely
Fixes a bug where the source address for upstream connections was explicitly bound to 0.0.0.0:0, even if no source address was configured, when using Pomerium Enterprise or the Pomerium Ingress Controller. This bug would result in errors like `failed_to_bind_to_0.0.0.0:0:_Address_family_not_supported_by_protoco …
=> envoyconfig: make source_address independent of freebind

authenticate/identity.go, config/identity.go, config/runtime_flags.go, databroker/cache.go, pkg/identity/manager/config.go, pkg/identity/manager/data.go, pkg/identity/manager/data_test.go, pkg/identity/manager/manager.go, pkg/identity/manager/schedulers.go, pkg/identity/manager/schedulers_test.go, pkg/identity/oauth/apple/apple.go, pkg/identity/oauth/apple/apple_test.go, pkg/identity/oauth/options.go, pkg/identity/oidc/oidc.go, pkg/identity/oidc/oidc_test.go, pkg/identity/providers.go, pkg/ssh/auth.go
Add a new runtime flag `refresh_session_at_id_token_expiration` to guard the two changes introduced by https://github.com/pomerium/pomerium/pull/5727, which are:
1. schedule session refresh based on ID token expiration (in addition to access token expiration and overall session lifetime)
2. always overwrite an existing ID token upon successful session refresh
This requires a bit of refactoring to make the runtime flag setting available in the identity manager and OIDC code:
- add a new `WithRefreshSessionAtIDTokenExpiration(bool)` option to the identity manager config
- add a new `OverwriteIDTokenOnRefresh bool` field to the oauth.Options struct
https://linear.app/pomerium/issue/ENG-2588/support-configuring-earlier-token-refresh-and-id-token-expiration
=> add runtime flag for session refresh change

config/envoyconfig/listeners.go, config/envoyconfig/listeners_envoy_admin.go, config/envoyconfig/listeners_grpc.go, config/envoyconfig/listeners_main.go, config/envoyconfig/listeners_metrics.go, config/envoyconfig/outbound.go, config/envoyconfig/testdata/metrics_http_connection_manager.json
This PR updates stats prefix for the listeners, so that it would be easier to distinguish between their statistics. 
See also https://github.com/pomerium/documentation/pull/1942 
Fix https://linear.app/pomerium/issue/ENG-2643/set-stats-prefix-to-listeners
=> metrics: add stats prefix to the listeners

internal/databroker/server.go, pkg/grpc/databroker/syncer.go, pkg/storage/inmemory/backend.go, pkg/storage/inmemory/backend_test.go, pkg/storage/inmemory/config.go, pkg/storage/postgres/backend.go, pkg/storage/postgres/backend_test.go, pkg/storage/postgres/option.go, pkg/storage/postgres/postgres.go, pkg/storage/storage.go, pkg/storage/storagetest/storagetest.go
The databroker maintains a list of record changes over time. Those changes are retrieved via the databroker `Sync` call. Both the in-memory and postgres storage backends periodically remove old changes.
Since this logic is necessary for any storage backend, add a `Clean` method to the public interface and start the background cleaner in the databroker server rather than the storage backend itself. This makes it easier to test.
Currently if a client attempts to `Sync` changes, but they've fallen too far behind, we would not detect this and the client would never receive the missing changes. The correct behavior is to abort the `Sync`, which signals the client to do a full re-sync via `SyncLatest`. This PR attempts to implement that behavior.
There is some risk with this change. If the …
=> databroker: move gc to public interface, abort sync calls with invalid record versions

authenticate/authenticate.go, authenticate/handlers.go, authenticate/handlers_verify.go, authenticate/identity.go, internal/testenv/selftests/tracing_test.go, pkg/identity/oidc/azure/microsoft.go
Currently we create a new authenticator on every request. When creating sessions from incoming IdP tokens this results in HTTP requests to the OIDC discovery document and JWKS keys every time. These are unnecessary HTTP requests and should be cached.
Update the `defaultGetIdentityProvider` so that it will cache authenticators and re-use them. We actually have very similar functionality in the identity manager, but I wanted to minimize the number of changes since this will need to be backported. Future improvements would be to unify this into a single authenticator cache and also handle frequent changes to IdP settings. (as of now they will just stay cached until restart)
A separate access token validator is now being used. This lets us properly trace the requests and adds a default 10 …
=> authenticate: cache authenticators

pkg/storage/postgres/backend.go
Postgres tests have been failing when the context is canceled. This appears to happen when health is reported. So we can just ignore that error and skip reporting health if it happens.
=> postgres: ignore canceled context when reporting health for flaky test

authorize/authorize.go, authorize/ssh_grpc.go, internal/testenv/environment.go, internal/testenv/selftests/tracing_test.go, internal/testutil/tracetest/tracing.go, pkg/ssh/auth.go, pkg/ssh/auth_test.go, pkg/ssh/channel.go, pkg/ssh/cli.go, pkg/ssh/manager.go, pkg/ssh/manager_test.go, pkg/ssh/mock/mock_auth_interface.go, pkg/ssh/ssh_export_test.go, pkg/ssh/ssh_int_test.go, pkg/ssh/stream.go, pkg/ssh/stream_test.go
If an SSH session record is deleted from the databroker, any active connections for that session will be closed.
=> ssh: terminate connection if corresponding session is revoked

cmd/pomerium/main.go, internal/zero/cmd/run.go, pkg/cmd/pomerium/pomerium.go, pkg/contextutil/signals.go, pkg/envoy/envoy.go
Right now we explicitly do not handle OS signals in pomerium - this has the side effect of not necessarily running shutdown phases of pomerium, e.g. things that are supposed to run after a context is done, for example `context.AfterFunc(ctx, ...)`.
It works mostly as expected right now since when container orchestration frameworks like Kubernetes pass a SIGTERM to the process, any sub-processes spawned with exec.Command will inherit those signals and get sent SIGTERM as well, which according to the envoy docs will result in draining listeners according to `--drain-time` which defaults to 600s.
However, right now the pomerium.Shutdown is a utility function explicitly used by our test environment, our current pomerium.Wait doesn't handle graceful shutdown correctly, it has been amended to: …
=> feat: handle signals to better gracefully drain/terminate envoy

internal/databroker/server_clustered_leader.go, internal/databroker/server_clustered_leader_test.go
Add the clustered leader server for the databroker. It just wraps a local server instance. See #5815.
- [ENG-2722](https://linear.app/pomerium/issue/ENG-2722/databroker-add-clustered-server)
=> databroker: add clustered leader server

cmd/pomerium/main.go, integration/clusters/multi-stateful/compose.yml, integration/clusters/multi-stateless/compose.yml, integration/clusters/single-stateful/compose.yml, integration/clusters/single-stateless/compose.yml, integration/tpl/backends/pomerium.libsonnet, internal/controlplane/server.go, pkg/health/cli.go, pkg/health/cli_test.go, pkg/health/http.go, pkg/health/http_test.go
Requires https://github.com/pomerium/pomerium/pull/5822
Adds a sub-command to the pomerium binary to provide health checking in container environments like docker compose or amazon ECS.
The command runs a http client against the http health check server and exits with 0 on success and 1 on failure.
[ENG-1895](https://linear.app/pomerium/issue/ENG-1895/feature-request-cli-health-command)
Users can now enable health checks in their docker compose environments using:
```yaml
services:
pomerium:
healthcheck:
test: ["CMD", "pomerium", "health"]
interval: 1m30s
timeout: 10s
retries: 3
start_period: 40s
start_interval: 5s
```
=> feat: health check CLI

proxy/handlers.go, proxy/proxy.go
mcp handler is not atomically set in the constructor so race condition can occur when a configuration is updated, trying to load the mcp handler.
If the mcp handler has not been set, while trying to serving traffic, it will serve a 503 Service Unavailable code.
<details>
<summary>Stack trace</summary>
<pre><code>
pomerium-1  | panic: runtime error: invalid memory address or nil pointer dereference
pomerium-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2868806]
pomerium-1  |
pomerium-1  | goroutine 213 [running]:
pomerium-1  | github.com/pomerium/pomerium/internal/atomicutil.(*Value[...]).Store(...)
pomerium-1  |   /go/src/github.com/pomerium/pomerium/internal/atomicutil/value.go:34
pomerium-1  | github.com/pomerium/pomerium/proxy.(*Proxy).OnConfigChange(0xc0009b9900, …
=> fix: race condition with mcp server handler loading

config/options.go, internal/controlplane/health_linux.go, internal/controlplane/health_other.go, internal/controlplane/server.go, pkg/health/deduplicate_test.go, pkg/health/manager.go, pkg/health/manager_test.go, pkg/health/systemd.go, pkg/health/systemd_test.go
This PR adds systemd as a valid integration for internal pomerium health checks.
When all expected checks have started, report READY to systemd. 
When any component enters the terminating state, report STOPPING to systemd.
When any component reports an error, the latest error reported gets surfaced to systemd's status so that `sudo systemctl status pomerium.service` reflects the last error
References (sd_notify & sd_watchdog_enabled man pages), convenient web links here:
- https://www.freedesktop.org/software/systemd/man/latest/sd_notify.html
- https://www.freedesktop.org/software/systemd/man/latest/sd_watchdog_enabled.html#
To have a startup probe based on the sd_notify protocol the systemd configuration should have:
```
[Service]
#...
Type=notify
```
The sd_notify health checker also …
=> feat: report pomerium health to systemd

internal/databroker/server_backend.go, pkg/storage/file/backend.go, pkg/storage/file/backend_test.go, pkg/storage/file/metrics.go, pkg/storage/file/pebble.go, pkg/storage/file/registry.go, pkg/storage/file/registry_test.go
Add additional tracing and metrics for the pebble storage backend.
- [ENG-2958](https://linear.app/pomerium/issue/ENG-2958/core-investigate-additional-telemetry-for-on-disk-databroker-storage)
=> pebble: add additional tracing and metrics

authenticate/authenticate.go, authenticate/handlers.go, authenticate/handlers_callback_test.go, authenticate/handlers_test.go, authenticate/handlers_verify_test.go, internal/controlplane/http.go, internal/handlers/well_known_pomerium.go, internal/handlers/well_known_pomerium_test.go
The authenticate callback path option wasn't being used in the authenticate service. To get this to work we needed to dynamically construct the `mux.Router` any time the config was updated. This is similar to what we do in the proxy service.
- [ENG-2951](https://linear.app/pomerium/issue/ENG-2951/core-fix-or-remove-the-authenticate-callback-path-setting)
=> authenticate: fix callback path

config/bearer_token_format.go, config/codec_type.go, config/constants.go, config/custom.go, config/custom_test.go, config/otelconfig/otelconfig.go, go.mod, go.sum
The `github.com/mitchellh/mapstructure` repo is archived, and `github.com/go-viper/mapstructure` is the blessed replacement according to https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc#the-list.
Update the remaining `mapstructure` imports to the new package.
The behavior of `StringToSliceHookFunc()` has changed slightly, in a way that breaks decoding of the `POLICY` environment variable. However we can use [StringToWeakSliceHookFunc()](https://pkg.go.dev/github.com/go-viper/mapstructure/v2#StringToWeakSliceHookFunc) instead, which provides the old behavior. Other than that, it looks like all the unit tests still pass.
- https://github.com/pomerium/pomerium/issues/5566
=> config: migrate remaining mapstructure imports
