cmd/pomerium/main.go

This PR adds the implementation of the SERVICES environment variable to only enable authentication or proxy or both.
I got this running successfully in a test Kubernetes cluster.
Open issues:
* I was forced to put in a "/ping" so that Kubernetes/load balancing liveness checks would work in authenticator mode even when the virtual hostname isn't provided. This is over and above the /ping in each of the authenticator and proxy. Perhaps there's a cleaner way of organizing the code.

Implement only running either authenticator or proxy

---

README.md
docs/guide/readme.md
env.example

docs: add build from source guide

---

proxy/authenticator/authenticator.go
proxy/authenticator/authenticator_test.go
proxy/authenticator/grpc.go
proxy/authenticator/grpc_test.go
proxy/authenticator/mock_authenticator.go
proxy/handlers.go
proxy/handlers_test.go
proxy/proxy.go

proxy: add tests

---

README.md
authenticate/handlers.go
authenticate/handlers_test.go
authenticate/providers/mock_provider.go
internal/templates/templates.go
proxy/authenticator/authenticator_test.go
proxy/authenticator/grpc_test.go
proxy/handlers.go
proxy/handlers_test.go

authenticate: add tests, fix sign-out

---

README.md
docs/.vuepress/config.js
docs/docs/config-reference.md
internal/cryptutil/sign.go
package.json

Closes #29
Live version can be found at https://www.pomerium.io/docs/config-reference.html
**Checklist**:

docs: add configuration variables

---

CHANGELOG.md
docs/docs/examples.md
docs/guide/helm.md
docs/guide/kubernetes.md
scripts/helm_gke.sh

Minor updates before tagging and releasing v0.0.3

docs: changelog++ v0.0.3

---

CHANGELOG.md
Dockerfile
docs/docs/config-reference.md
docs/docs/examples.md
docs/docs/examples/docker/nginx.docker-compose.yml
docs/docs/examples/kubernetes/proxy.deploy.yml
docs/guide/synology.md
proxy/handlers.go
proxy/proxy.go
proxy/proxy_test.go

proxy: remove unused setting AuthorizeInternalAddr

---

authenticate/handlers.go
cmd/pomerium/main.go
internal/middleware/middleware.go
proxy/handlers.go

Closes #90 
/cc @yegle 
**Checklist**:

cmd/pomerium: add http redirect and hsts

---

Dockerfile.arm64v8

Please let me know if any modification is needed, happy to help with that
Closes #125

deployment: add arm64v8 dockerfile

---

proxy/handlers.go
proxy/proxy.go

Fixes #132 
Follow the **Repro Steps** in #132. Ensured the behavior was as expected.

proxy: fix bug with incorrect addressing causing invalid route configs

---

CHANGELOG.md
docs/docs/upgrading.md

docs: update changelog and upgrading docs

---

docs/docs/examples.md
docs/docs/readme.md
docs/guide/binary.md
docs/guide/from-source.md
docs/guide/helm.md
docs/guide/readme.md
docs/readme.md
docs/reference/readme.md

docs: update docs for v0.0.5

---

.dockerignore

Fixes #171 for new builds.
**Checklist**:

deployment: remove docker ignore file

---

CHANGELOG.md
authenticate/handlers_test.go
proxy/handlers.go
proxy/handlers_test.go

Fixes #170 
**Checklist**:
/cc @victornoel

proxy: fix bug in sign_out handler

---

CHANGELOG.md
cmd/pomerium/main.go
docs/reference/readme.md
go.mod
go.sum
internal/config/options.go
internal/metrics/exporter.go
internal/metrics/exporter_test.go
internal/metrics/middleware.go
internal/metrics/middleware_test.go

Establish initial implementation of #35 
Subsequent PRs for authenticate, authorize, proxy client side, and misc values.
**Checklist**:

Add metrics implementation

---

docs/reference/readme.md
internal/metrics/middleware.go
internal/metrics/middleware_test.go
internal/tripper/chain.go
internal/tripper/chain_test.go
internal/tripper/roundtripper.go
proxy/proxy.go

Proxy client metrics implementation for #35 
**Checklist**:

Proxy Client Metrics

---

CHANGELOG.md
docs/reference/readme.md
internal/config/options.go
internal/config/options_test.go

Correctly parse HEADERS environment variable

---

cmd/pomerium/main.go
docs/reference/readme.md
go.sum
internal/metrics/helpers_test.go
internal/metrics/interceptors.go
internal/metrics/interceptors_test.go
internal/metrics/middleware.go
internal/metrics/middleware_test.go
internal/metrics/tags.go
internal/metrics/view.go
internal/metrics/view_test.go
proxy/clients/clients.go

GRPC client metrics for #35 
**Checklist**:

Add GRPC Client Metrics

---

CHANGELOG.md
proxy/handlers.go

Fixes #205
**Checklist**:
/cc @victornoel

proxy: add auth redirect to internal urls

---

CHANGELOG.md
docs/docs/examples/config/config.example.yaml
docs/docs/examples/config/config.minimal.yaml
docs/docs/examples/config/policy.example.yaml
docs/docs/examples/docker/basic.docker-compose.yml
docs/docs/examples/docker/nginx.docker-compose.yml
docs/docs/examples/kubernetes/proxy.deploy.yml
docs/docs/upgrading.md
docs/guide/binary.md
docs/guide/from-source.md
docs/guide/readme.md
docs/guide/synology.md
docs/readme.md
docs/reference/readme.md

Update docs related to v0.1.0 release.
See #214 
**Checklist**:

docs: update for v0.1.0 release

---

.gitignore
CODE_OF_CONDUCT.md

docs: add code of conduct

---

CHANGELOG.md
cmd/pomerium/main.go
docs/reference/readme.md
internal/metrics/helpers_test.go
internal/metrics/interceptors.go
internal/metrics/interceptors_test.go
internal/metrics/middleware_test.go
internal/metrics/tags.go
internal/metrics/view.go
internal/metrics/view_test.go
proxy/clients/clients.go

- Improves GRPC client instrumentation internals
- Adds GRPC server instrumentation
Related to #35 
**Checklist**:

GRPC Metrics Improvements

---

CHANGELOG.md
go.mod
go.sum

Upgrade GRPC to 1.22

---

CHANGELOG.md
docs/reference/readme.md
internal/metrics/helpers_test.go
internal/metrics/middleware.go
internal/metrics/middleware_test.go
internal/metrics/tags.go
internal/metrics/view.go
proxy/proxy.go

Related to #35 
- Switch to ochttp plugin
- Add HTTP request metrics
- Relabel for consistency
**Checklist**:

HTTP metrics improvements

---

CHANGELOG.md
internal/sessions/cookie_store.go
internal/sessions/cookie_store_test.go
internal/sessions/session_state.go
internal/sessions/session_state_test.go

internal/sessions: add (chocolate chip) cookie chunks

---

CHANGELOG.md
authorize/authorize.go
cmd/pomerium/main.go
docs/reference/readme.md
internal/metrics/helpers_test.go
internal/metrics/info.go
internal/metrics/info_test.go
internal/metrics/tags.go
internal/metrics/view.go
proxy/proxy.go

The last of the metrics in scope for #35 
**Checklist**:

internal/metrics: status metrics

---

.codecov.yml

deployment: make codecov more tolerable

---

CHANGELOG.md
internal/identity/google.go

identity/google: always prompt for user selection.

---

Makefile
docs/docs/identity-providers.md
docs/reference/readme.md

deployment: add docs spellcheck to pipeline

---

internal/telemetry/metrics/grpc.go
internal/telemetry/metrics/http.go
internal/telemetry/metrics/info.go
internal/telemetry/metrics/providers.go

Mostly cleanup. 
**Checklist**:

telemetry: fix package name in messages

---

CHANGELOG.md
authorize/authorize.go
authorize/authorize_test.go
proxy/proxy.go
proxy/proxy_test.go

Prevent nil pointer when reloading in single service mode

---

authorize/authorize.go
cmd/pomerium/main.go
internal/config/options.go
internal/telemetry/metrics/const.go
proxy/proxy.go

Fixes regression in info metrics
**Checklist**:

Fix info metrics registration

---

authenticate/authenticate.go
authenticate/authenticate_test.go
cmd/pomerium/main_test.go
internal/config/options.go
internal/config/options_test.go
internal/identity/providers.go
internal/urlutil/url.go
internal/urlutil/url_test.go
proxy/handlers.go
proxy/handlers_test.go
proxy/proxy.go
proxy/proxy_test.go

Fixes #253 . Thank you @yegle for reporting
**Checklist**:

config: fix url type regression (#253)

---

docs/.vuepress/config.js

Please confirm with preview for sanity. :) 
**Checklist**:

docs: readd programmatic-access

---

docs/community/readme.md

docs: add mailing list and twitter

---

proxy/clients/clients_test.go

Attempt to fix test errors on dockerhub.

Fix dockerhub tests

---

docs/.vuepress/config.js
docs/.vuepress/theme/components/AlgoliaSearchBox.vue

Much improved search. Previously search only used headers, now full text is indexed by Algolia.
**Checklist**:

docs: use algolia for search

---

.travis.yml

dev: add code climate

---

proxy/clients/clients.go

Disable GRPC ServiceConfig

---

.travis.yml

🤦‍♂ https://docs.travis-ci.com/user/conditions-v1#integration
**Checklist**:

Fix image build conditions

---

docs/docs/readme.md

Text seems repeated, removing.
**Checklist**:

Remove duplicated text

---

docs/docs/reference/examples/config/config.example.env
docs/docs/reference/examples/config/config.example.yaml
docs/docs/reference/examples/config/config.minimal.env
docs/docs/reference/examples/config/config.minimal.yaml
docs/docs/reference/examples/config/config.visual-studio-code.yaml
docs/docs/reference/examples/config/policy.example.yaml
docs/docs/reference/examples/docker/basic.docker-compose.yml
docs/docs/reference/examples/docker/nginx.docker-compose.yml
docs/docs/reference/examples/kubernetes/kubernetes-config.yaml

These changes fix some broken links in the example configurations.
**Checklist**:

docs: fix example configuration urls

---

docs/.vuepress/public/_redirects
docs/docs/quick-start/synology.md

These changes add redirects to past-permalinks that are now showing 404 😭 
**Checklist**:

docs: fix existing links

---

proxy/handlers.go

These changes fix a bug introduced by #300 in which the csrf middleware was accidentally being applied to proxied routes causing unexpected CSRF failures in downstream apps when making `PUT/POST/` calls. 
Thank you Constantinos for [reporting the issue](https://pomerium-io.slack.com/archives/CK6SVMPU0/p1568831007054300). 
(httpbin is helpful here because we can replicate a post). 
1. Go to `https://httpbin.corp.example.com/forms`
2. Fill out the form
3. Click submit
4. See CSRF failure from pomerium. 
```
12:52PM ERR http-error error="403 Forbidden: CSRF Failure: CSRF token invalid"
```
**Checklist**:

proxy: remove accidental csrf checks from proxied routes

---

docs/.vuepress/config.js
docs/docs/reference/production-deployment.md

Add production configuration documentation.
**Checklist**:

docs: production configuration

---

docs/docs/CHANGELOG.md
proxy/handlers.go

proxy: fix group impersonation bug

---

cmd/pomerium/main.go
docs/docs/CHANGELOG.md
proxy/handlers.go
proxy/proxy.go

Fixes #262 
\cc @alagendijk-minddistrict 
**Checklist**:

proxy: handle double slash in paths

---

cmd/pomerium/main.go
docs/docs/CHANGELOG.md

cmd/pomerium: add host to main logging handler

---

docs/docs/CHANGELOG.md
internal/middleware/middleware.go
internal/middleware/middleware_test.go

Fixes #319 
/cc @xbglowx 
**Checklist**:

middleware: health-check return 405 for non-get

---

scripts/helm_gke.sh

Fixes an issue found while trying to run the GKE script against https://github.com/helm/charts/pull/17347. 
**Checklist**:

scripts: fix helm gke script

---

internal/log/example_test.go
internal/log/middleware_test.go

Adds more unit tests to logs package. 
**Checklist**:

internal/log: add unit tests

---

authenticate/authenticate_test.go
cmd/pomerium/main_test.go
docs/docs/CHANGELOG.md
internal/config/options.go
internal/config/options_test.go
proxy/proxy_test.go

internal/config: Switch to using struct scoped viper instance

---

docs/docs/reference/examples/docker/basic.docker-compose.yml
docs/docs/reference/examples/docker/nginx.docker-compose.yml
docs/docs/reference/examples/kubernetes/pomerium-authenticate.yml
docs/docs/reference/examples/kubernetes/pomerium-authorize.yml
docs/docs/reference/examples/kubernetes/pomerium-proxy.yml

Related to #330 
**Checklist**:

docs: use updated build in examples (v0.3.X branch)

---

docs/docs/background.md

What it says on the tin
**Checklist**:

docs: add nist publication to background

---

docs/.vuepress/config.js

docs: use dev for current master branch

---

docs/docs/CHANGELOG.md
docs/docs/reference/reference.md
internal/config/policy.go
internal/middleware/middleware.go
proxy/middleware.go
proxy/middleware_test.go
proxy/proxy.go

Fixes #338 
\cc @mleklund 
**Checklist**:

proxy: add per-route request headers setting

---

docs/.vuepress/config.js
docs/docs/FAQ.md
docs/docs/reference/reference.md

Started a guide to cover some of the issues we commonly see pop up in chat, and elsewhere. It's a start 🤷‍♂ 
Fixes #318 
**Checklist**:

docs: add faq / troubleshooting guide

---

docs/.vuepress/config.js
docs/.vuepress/theme/components/Home.vue
docs/enterprise/readme.md

Add contact us page for enterprise inquiries uses netlify forms. 
**Checklist**:

docs: add enterprise contact form

---

internal/sessions/cookie_store.go
proxy/middleware.go

Previously, only the exact session cookie (including matches on `Path` and `Domain` values would be cleared when doing a session clear. Because version `v0.5.0` is moving from a global session cookie whose domain is defaulted to be the parent subdomain, on an error on the new `v0.5.0` branch, the session cookie would not be cleared because `MaxAge` and `Expiry` would be set on a _new_ session which a differently scoped `Domain`.
<s>These changes change the behavior of `ClearSession` generate new, clearing session cookies for both the route-domain (e.g. no domain set, `Host-Only`) and the previous default cookie session domain scope, which was the immediate parent domain. 
This should solve the [infinite …

internal/sessions: fix upgrade path for new sessions

---

config/options.go
config/policy.go
docs/docs/CHANGELOG.md

- add `yaml` tags to options struct
- add `omitempty` to all yaml tags on `Options` and `Policy` structs
**Checklist**:

config: Update yaml tags

---

cmd/pomerium/main.go
docs/docs/CHANGELOG.md
proxy/proxy.go
proxy/proxy_test.go

proxy: Fix policy reload regression

---

config/options.go
config/policy.go
docs/docs/CHANGELOG.md

Add yaml tags to hydrated data structures.
Completes #394 
**Checklist**:

config: additional yaml tags

---

test.txt

Test release!

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Adds release drafter github action to help automate away the tedium of drafting and updating our release changelog.
**Checklist**:

deployment: add release drafter

---

docs/docs/upgrading.md

N/A
- Fixes #372
- https://github.com/pomerium/pomerium/issues/388
https://www.pomerium.io/docs/faq.html#certificate-signed-by-unknown-authority
**Checklist**:

docs: update v0.3.0 regarding all service mode

---

authenticate/authenticate.go
authorize/authorize.go
config/options.go
config/policy.go
internal/cryptutil/certificates.go
internal/cryptutil/encrypt.go
internal/encoding/ecjson/ecjson.go
internal/identity/google.go
internal/telemetry/metrics/providers.go
proxy/clients/clients.go
proxy/proxy.go

Wrap and fix Go errors with the new %w [verb directive introduced in 1.13](https://golang.org/doc/go1.13#error_wrapping)
- https://github.com/fatih/errwrap
**Checklist**:

errors: use %w verb directive

---

renovate.json

Tells renovate to only check for updates weekly. 
- #403 
**Checklist**:

dependency: have renovate-bot check weekly

---

config/options.go
config/options_test.go
docs/docs/CHANGELOG.md

Do sanity checking on `shared_secret` whitespace.
Closes #420 
**Checklist**:

config: Validate that `shared_key` does not contain whitespace

---

config/options.go
config/options_test.go

Remove CookieRefresh which seems not to use anywhere.
Fixes #428 
**Checklist**:
nothing to change cause it’ not written about it
I could not find it

config: Remove CookieRefresh (#428)

---

docs/configuration/readme.md
docs/docs/upgrading.md
docs/recipes/kubernetes.md
docs/recipes/yml/dashboard-forwardauth.ingress.yaml
docs/recipes/yml/dashboard-fwdauth.ingress.yaml
docs/recipes/yml/pomerium.ingress.yaml

To be consistent with https://github.com/travisgroth/charts/tree/pomerium/fwd_auth
**Checklist**:

docs: s/fwdauth/forwardauth/

---

.travis.yml

Fix conflict between `matrix` and `jobs` sections in .travis.yml.  This recently broke docker image builds.
**Checklist**:

Fix docker image builds

---

config/options.go

Add correct `yaml` tag to `Options.Policies` to (Un)Marshal as `[]policy`.
**Checklist**:

config: Add proper yaml tag to Options.Policies

---

scripts/helm_gke.sh

Updates the helm-quickstart guide to use helm v3. Yay no more tiller. 
Closes https://github.com/pomerium/pomerium/issues/455
**Checklist**:

docs: update helm for v3

---

cache/cache.go
cache/cache_test.go
cache/grpc_test.go

Add option validation to the cache service.
Fixes #467 
**Checklist**:

cache: add option validations

---

docs/readme.md
docs/recipes/ad-guard.md
docs/recipes/readme.md

These changes fix several typos, and add some additional context to the recipes section.
**Checklist**:

docs: various fixes

---

docs/docs/background.md

docs: update background

---

docs/recipes/kubernetes.md

docs: fix kubernetes dashboard recipe docs

---

renovate.json

Streamline Renovate PR process.
**Checklist**:

deps: enable automerge and set labels on renovate PRs

---

go.mod
go.sum
internal/identity/google.go
internal/identity/microsoft.go
internal/identity/oidc.go
internal/identity/okta.go
internal/identity/onelogin.go
internal/identity/providers.go
internal/sessions/state.go

identity: support oidc UserInfo Response
- switch back to main oidc repo
Attempt to gather more info especially useful if initial request did not an contain email, or subject. 
https://openid.net/specs/openid-connect-core-1_0.html#UserInfo
- fixes #526 
**Checklist**:

identity: support oidc UserInfo Response

---

internal/sessions/state.go

To be cherrypicked to v0.6.X
Fixes #530 
**Checklist**:

sessions: signout bug , fixes #530

---

docs/docs/quick-start/binary.md
docs/docs/reference/programmatic-access.md
internal/kv/autocache/autocache.go

Fixed some typo.
**Checklist**:

fix `the` typo

---

.github/workflows/test.yaml
.travis.yml

Switch testing to GH Workflow
https://github.com/pomerium/pomerium/pull/405
**Checklist**:

deployment: Add testing workflow

---

internal/grpcutil/doc.go

Remove unused grpcutil package.  🙃 
**Checklist**:

grpcutil: remove unused pkg

---

cmd/pomerium-cli/cli.go

Fixes some confusing comments in the CLI package. 
- #552 
**Checklist**:

cli: fix confusing comments

---

docs/docs/identity-providers/cognito.md
docs/docs/identity-providers/github.md
docs/docs/identity-providers/gitlab.md

Just trying to improve the readability of our identity provider documentation.
**Checklist**:

docs: improve identity providers documentation

---

.github/workflows/test.yaml
scripts/build-dev-docker.bash

Hopefully alleviate random CI failures starting minikube
🤖 
**Checklist**:

ci: Switch integration tests from minikube to kind

---

go.sum

deps: go mod tidy

---

renovate.json

This should run `go mod tidy` after updating dependencies.
**Checklist**:

renovate: Update Renovate to run go mod tidy

---

renovate.json

:sigh: figures as soon as I merge it, it tells me I did something wrong

renovate: Update Renovate option should be a list

---

internal/controlplane/xds_routes.go

This implements websocket support with envoy.
**Checklist**:

proxy: add websocket support

---

config/options.go
docs/configuration/readme.md
internal/controlplane/grpc_accesslog.go
internal/controlplane/grpc_xds.go
internal/controlplane/server.go
internal/controlplane/xds.go
internal/controlplane/xds_listeners.go

This change adds a separate proxy log level option.
- closes pomerium/internal#19
**Checklist**:

envoy: add separate proxy log level option

---

.github/goreleaser.yaml
internal/envoy/envoy_linux.go
internal/envoy/envoy_notlinux.go
scripts/embed-envoy.bash

- Ensure we bundle the correct envoy binary with goreleaser
- Fix process group assignment to share signals on all platforms 
**Checklist**:

deployment: Envoy cross platform improvements

---

docs/configuration/readme.md

Clarifies documentation on `jwt_claims_headers`
Closes #700 
**Checklist**:

Update jwt_claims_headers docs

---

go.mod
integration/backends/httpdetails/main.go
integration/internal/cluster/certs.go
integration/internal/cluster/cluster.go
integration/internal/cluster/cmd.go
integration/internal/cluster/setup.go
integration/manifests/lib/backends.libsonnet
integration/manifests/lib/pomerium.libsonnet
integration/manifests/lib/reference-openid-provider.libsonnet
integration/manifests/lib/tls.libsonnet
integration/policy_test.go

These change add tests for the various TLS policy configuration options.
**Checklist**:

integration-tests: TLS policy configuration options

---

docs/configuration/examples.md
docs/configuration/examples/kubernetes/istio/gateway.yml
docs/configuration/examples/kubernetes/istio/grafana.ini.yml
docs/configuration/examples/kubernetes/istio/pomerium-helm-values.yml
docs/configuration/examples/kubernetes/istio/service-entry.yml
docs/configuration/examples/kubernetes/istio/virtual-services.yml

I'm not sure if I put this in the right place but I wanted to add an example of how to get Pomerium to play nicely with Istio within the context of adding authentication to Grafana.
Let me know what you think, I'm happy to make changes.
**Checklist**:

Documentation around Pomerium/Istio/Grafana

---

cmd/pomerium/main.go
config/options.go
docs/configuration/readme.md
docs/docs/upgrading.md
go.mod
go.sum
internal/telemetry/trace/trace.go

Add Zipkin tracing support to pomerium.  There will be a follow up for pushing configuration to envoy.
**Checklist**:

telemetry/tracing: Add Zipkin tracing support

---

authorize/grpc.go
authorize/grpc_test.go

To be cherrypicked onto 0.8.1
Fixes #704
**Checklist**:

authorize: fix nil reference (#704)

---

internal/envoy/envoy.go

Envoy sometimes doesn't return logs in the format we asked for (particularly when there are unexpected errors), so I updated the format to prefix it with `[LOG_FORMAT]` and used a regular expression to find it.
I also changed the default log level to debug, and disabled hot-restart because we're not using it.
**Checklist**:

envoy: improvements to logging

---

config/options.go
config/options_test.go
config/trace.go
config/trace_test.go
docs/configuration/readme.md
docs/docs/upgrading.md
internal/cmd/pomerium/pomerium.go
internal/controlplane/xds_listeners.go
internal/envoy/envoy.go
internal/telemetry/metrics/providers.go
internal/telemetry/metrics/providers_test.go
internal/telemetry/trace/trace.go
internal/telemetry/trace/trace_test.go

* Enables setting up zipkin tracing in bootstrap config
**Checklist**:

envoy: Enable zipkin tracing

---

authorize/check_response.go
authorize/evaluator/evaluator.go
authorize/grpc.go
authorize/grpc_test.go

This refactors the `grpc.go` file to make it easier to understand and adds additional unit tests.
**Checklist**:

authorize: refactor and add additional unit tests

---

config/options_test.go

Add some additional tests to config. 
**Checklist**:

config: add some cert tests

---

authorize/authorize.go
authorize/authorize_test.go
authorize/grpc_test.go

Adds additional tests to authorize to ensure that AuthN is set, and to the check function. 
**Checklist**:

authorize: add authN validation, additional tests

---

internal/controlplane/xds.go

This PR converts the initialization of the root CA bundle into a lazily-loaded value the first time its used via a `sync.Once` function. By doing it this way we avoid calling the code when merely importing the library, which in turn fixes the early log line that happens when `pomerium -version` is used.
Fixes #774 
**Checklist**:

xds: lazy-load root ca bundle to avoid log in version command

---

docs/docs/reference/getting-users-identity.md

The docs are wrong regarding what the headers are called.
I haven't raised an issue. If you want to, please go ahead and we will link it to this PR.
**Checklist**:

fix: docs regarding claim headers

---

docs/docs/upgrading.md

This adds a note to the upgrading docs about limited platform support.
- #798 
**Checklist**:

docs: add note about unsupported platforms

---

docs/configuration/readme.md

- Show the list of config parameters in the nav bar for easier discovery
- Sort parameters alphabetically
**Checklist**:

docs: Expose config parameters in sidebar

---

docs/configuration/readme.md

Correct minor typo regarding memcached designation

Fix typo on configuration doc

---

docs/configuration/examples/docker/autocert.docker-compose.yml
docs/configuration/examples/docker/basic.docker-compose.yml
docs/configuration/examples/docker/nginx.docker-compose.yml

This updates the dockerfiles for v0.9.0.
- #798 
**Checklist**:

docs: update dockerfiles for v0.9.0

---

.github/workflows/backport.yaml

Add an action to automate backporting PRs to release branches.
add `backport BRANCHNAME` label to PRs that should be backported.
Eg, `backport 0-9-0`
- I'm very lazy
**Checklist**:

ci: Add backport action

---

.github/Dockerfile-release

Backport #810 to v0.9
**Checklist**:

envoy: Switch to distroless/base for releases (#810)

---

go.sum
internal/controlplane/xds.go

xds: use ipv4 address when ipv6 is disabled

---

docs/docs/readme.md

I noticed a small typo while reading the website.

Fix small typo

---

go.sum

Remove merge conflict blocks accidentally introduced in #830 
**Checklist**:

deps: Fix merge conflict markers

---

.gitignore

Add a few more file types to ignore when doing local testing.
**Checklist**:

git: ignore additional test file types

---

docs/docs/CHANGELOG.md

Update changelog for release.
**Checklist**:

Add 0.9.1 changelog

---

authorize/grpc.go

authorize: only log headers if debug set

---

authenticate/handlers.go

Fixes a typo, and uses the parent span context. 
- #926 
**Checklist**:

autenticate: fix some typos

---

docs/docs/upgrading.md

docs/docs: remove extra text when resolve conflict

---

docs/docs/CHANGELOG.md

Update v0.9.2 Changelog

---

authorize/grpc.go
authorize/run.go
cache/session.go
cache/user.go
internal/databroker/memory/server.go

Add tracing into cache and databroker code paths
Closes #986 
**Checklist**:

telemetry: add tracing spans to cache and databroker

---

authenticate/authenticate.go
authenticate/authenticate_test.go
authenticate/handlers.go
docs/docs/CHANGELOG.md
internal/cmd/pomerium/pomerium.go

By implementing OptionsUpdater interface.
Fixes #982
**Checklist**:

authenticate: support hot reloaded config

---

internal/directory/onelogin/onelogin.go
internal/directory/onelogin/onelogin_test.go

We need to use the user id for the directory information so that it is queried properly by the OPA policy.
Same as #988
**Checklist**:

internal/directory/onelogin: store directory information by user id

---

internal/directory/okta/okta.go

We need to use the user id for the directory information so that it is queried properly by the OPA policy.
Same as #988
**Checklist**:

internal/directory/okta: store directory information by user id

---

authenticate/authenticate.go
config/options.go
docs/configuration/readme.md
internal/identity/oauth/options.go
internal/identity/oidc/azure/microsoft.go
internal/identity/oidc/google/google.go
internal/identity/oidc/oidc.go

identity: support custom code flow request params

---

cache/memberlist.go

Fix build error introduced in previous PR.
#1004 
**Checklist**:

cache: fix missing parameter

---

docs/configuration/examples/config/config.example.env
docs/configuration/examples/config/config.example.yaml
docs/configuration/examples/kubernetes/kubernetes-config.yaml
docs/configuration/examples/kubernetes/values.yaml
docs/configuration/readme.md
docs/docs/identity-providers/readme.md

Add documentation about IdP service accounts for group data.
**Checklist**:

docs: Add warnings cones around requiring IdP Service Accounts

---

Makefile

Allow specify go executable in Makefile

---

cache/memberlist_test.go

Adding test for c.runMemberList
**Checklist**:

cache: add test for runMemberList

---

go.sum
internal/controlplane/xds_listeners.go
internal/controlplane/xds_listeners_test.go

internal/controlplane: enable envoy use remote address

---

config/policy.go
docs/docs/upgrading.md

docs: document preserve_host_header with policy routes to static ip

---

.github/workflows/release.yaml

Avoid tagging `rc` releases as `latest` docker images
**Checklist**:

ci: support rc releases

---

authorize/grpc.go
authorize/grpc_test.go
proxy/forward_auth.go
proxy/middleware.go

Backport 1030 to 0 9 0

---

authenticate/handlers.go

authenticate: fix wrong SignIn telemetry name

---

docs/recipes/local-oidc.md
docs/recipes/readme.md

Add example configuration with local OIDC server.
Closes #1042
**Checklist**:

docs/recipes: add local oidc example

---

authorize/evaluator/evaluator.go
authorize/evaluator/evaluator_test.go
docs/docs/CHANGELOG.md

authorize: include "kid" in JWT header

---

authorize/grpc.go

When user signin to 2 sites "a.example.com" and "b.example.com", we're
using the same session for user when accessing those sites. When user
singout from "a.example.com", that session is marked as deleted, thus
user now can not access "b.example.com" nor re-signin to get new access.
User must wait the cookie is expired, or delete the cookie manually to
re-signin to "b.example.com".
This is also affected if user signout from authenticate service
dashboard page directly.
To fix this, we will clear the session state if the session was deleted,
authorize service will return unauthorized, so the user will be
redirected to re-authenticate.
Updates #1014
Updates #858
**Checklist**:

authorize: clear session state if session was deleted in databroker

---

.github/workflows/release.yaml

Backport 98831aeb59402b4e925d17a63809bc3828be7c31 to 0-9-0

Backport #1011

---

pkg/storage/inmemory/inmemory.go
pkg/storage/storage.go

pkg/storage: add package docs

---

docs/docs/CHANGELOG.md

Add docs for changes in #1055
**Checklist**:

docs/docs: add changelog for #1055

---

config/config_source.go
go.mod
go.sum

`copystructure` doesn't handle unexported fields.

fix deep copy of config

---

proxy/handlers.go

Backport 979 to 0 9 0

---

.github/workflows/release.yaml

Prevent GCP login from creating dirty git state
**Checklist**:

ci: Prevent dirty git state

---

authorize/grpc.go
authorize/grpc_test.go

authorize,proxy: allow traefik forward auth without uri query (#1103)

---

scripts/embed-envoy.bash

Updates Envoy to the latest version 1.14.4 which contains several bug fixes and security patches. 
See
- https://groups.google.com/g/envoy-announce/c/yxFpI54NeWg
- https://groups.google.com/g/envoy-announce/c/qrrF8klFl-I
**Checklist**:

deps: update envoy to 1.14.4

---

authorize/evaluator/custom.go
authorize/evaluator/custom_test.go
authorize/evaluator/evaluator.go
go.sum

This PR adds support for custom rego policies. A subsequent PR will query these from the data broker.
**Checklist**:

authorize: custom rego policies

---

internal/databroker/server.go
internal/databroker/server_test.go

PR #1121 was merged without proper amended commit.

internal/databroker: fix wrong server version init

---

examples/traefik/docker-compose.yaml

Fix forward auth middleware in traefik example
https://github.com/pomerium/pomerium/pull/324
**Checklist**:

docs: Fix incorrect example middleware

---

cache/cache.go
cache/databroker.go
config/options.go
config/options_test.go
docs/configuration/readme.md
internal/databroker/config.go
internal/databroker/server.go
pkg/storage/inmemory/inmemory.go
pkg/storage/redis/redis.go

Allow configuring backend storage types that databroker will use.
**Checklist**:

databroker server backend config

---

authenticate/handlers.go
authenticate/handlers_test.go
go.sum

The code checks session client not nil, but using databroker client in
the body instead.
**Checklist**:

authenticate: fix wrong condition checking in VerifySession

---

docs/docs/CHANGELOG.md

Update changelog for `v0.9.6` release
Also included `v0.9.5` notes.
Closes #983 
**Checklist**:

Update changelog for 0.9.6

---

docs/.vuepress/config.js
docs/recipes/readme.md
docs/recipes/tiddlywiki.md
examples/tiddlywiki/REAME.md
examples/tiddlywiki/config.yaml
examples/tiddlywiki/docker-compose.yaml

Add the recipe documentation for using Pomerium with TiddlyWiki Node.js version.
**Checklist**:

docs: Add recipe for TiddlyWiki on Node.js

---

config/helpers.go
config/options.go
docs/reference/readme.md
internal/databroker/server.go
internal/telemetry/metrics/const.go
internal/telemetry/metrics/kv.go
internal/telemetry/metrics/kv_test.go
internal/telemetry/metrics/registry.go
internal/telemetry/metrics/storage.go
internal/telemetry/metrics/storage_test.go
pkg/storage/inmemory/inmemory.go
pkg/storage/redis/redis.go
pkg/storage/storage.go

Add metrics and tracing to redis storage backend
**Checklist**:

telmetry: add databroker storage metrics and tracing

---

config/helpers.go
pkg/storage/redis/redis.go

Fix lint checks
**Checklist**:

fix lint errors

---

docs/.vuepress/config.js
docs/docs/reference/data-storage.md

Provide background and recommendations around storage backends.
**Checklist**:

docs: Redis and stateful storage docs

---

.github/goreleaser.yaml

Add brew tap at  pomerium/homebrew-tap to goreleaser process
**Checklist**:

deploy: Add homebrew tap publishing

---

.github/workflows/release.yaml

- make cross-repo token available to goreleaser
**Checklist**:

ci: release fixes

---

internal/urlutil/url_test.go

Add tests for GetDomainsForURL
Updates #959
**Checklist**:

internal/urlutil: add tests for GetDomainsForURL

---

docs/docs/upgrading.md

Add redis to upgrading docs.
**Checklist**:

docs/docs: update upgrading to mention redis storage backend

---

.github/goreleaser.yaml

Fix brew for pomerium-cli
**Checklist**:

deployment: fix brew creation for pomerium-cli

---

authorize/check_response.go
authorize/check_response_test.go
go.sum

Deriving check response message from reply message
While at it, add tests for ok response related functions.
**Checklist**:

authorize: derive check response message from reply message

---

authorize/check_response_test.go
go.sum

Add test for denied response
**Checklist**:

authorize: add test for denied response

---

authorize/evaluator/evaluator_test.go

More test cases for authorize evaluator
**Checklist**:

authorize/evaluator: add more test cases

---

config/policy.go
docs/guides/kubernetes.md
docs/reference/readme.md
internal/controlplane/xds_routes.go
internal/controlplane/xds_routes_test.go

Add spdy 3.1 as a protocol that can be enabled.  
Closes #1202 
**Checklist**:

proxy: add support for spdy upgrades

---

pkg/storage/redis/redis.go

- pkg/storage/redis: add metric to subscribe
- pkg/storage/redis: fix pool stats nil pointer
**Checklist**:

pkg/storage/redis: metrics updates

---

pkg/storage/redis/redis.go

There are two data race in current code:
- Call to close pub sub conn and renew pub sub conn
- Call to close notify channel and send data to it
Fixing them by:
- Moving pub sub conn creation/renew in the doNotifyLoop
- Add a lock to guard before close/send data to channel, and also add
another check for context was done at the beginning of notify loop.
Verifying by running:
```
for _ in {1..100}; do
go test -race -count=1 ./pkg/storage/redis/...
done
```
with no failure.
**Checklist**:

pkg/storage/redis: fix multiple data race

---

docs/guides/kubernetes.md
docs/reference/readme.md

Fix typo in docs
**Checklist**:

docs: fix minor errors

---

authenticate/handlers.go

The session expiry was never being set, which caused the pomerium-cli kubernetes exec credentials provider to always timeout after an hour.
- https://github.com/pomerium/pomerium/issues/1201
**Checklist**:

set session state expiry

---

docs/.vuepress/config.js
docs/_posts/2020-05-11-release-0-8.md
docs/docs/CHANGELOG.md
docs/docs/background.md
docs/docs/community/contributing.md
docs/docs/identity-providers/azure.md
docs/docs/identity-providers/gitlab.md
docs/docs/identity-providers/google.md
docs/docs/identity-providers/okta.md
docs/docs/identity-providers/one-login.md
docs/docs/identity-providers/readme.md
docs/docs/quick-start/binary.md
docs/docs/quick-start/from-source.md
docs/docs/quick-start/helm.md
docs/docs/quick-start/kubernetes.md
docs/docs/quick-start/readme.md
docs/docs/quick-start/synology.md
docs/docs/topics/certificates.md
docs/docs/topics/getting-users-identity.md
docs/docs/topics/impersonation.md
docs/docs/topics/production-deployment.md
docs/docs/topics/programmatic-access.md
docs/docs/upgrading.md
docs/guides/ad-guard.md
docs/guides/cloud-run.md
docs/guides/kubernetes-dashboard.md
docs/guides/vs-code-server.md
docs/reference/readme.md
package.json

- Fixes a bunch of broken links in the docs. 
- Cleaned up some of the upgrade-guide for v0.10 hopefully
- add a script to check for broken links `docs:check-md`
**Checklist**:

docs: fix links, clarify upgrade guide for v0.10

---

authorize/check_response_test.go
authorize/evaluator/store_test.go
authorize/google_cloud_serverless.go
authorize/google_cloud_serverless_test.go
authorize/grpc.go
authorize/grpc_test.go
authorize/session_test.go

Increasing authorize test coverage.
**Checklist**:

Increasing authorize coverage

---

docs/docs/installation.md
docs/docs/readme.md
docs/docs/releases.md
docs/docs/topics/kubernetes-integration.md
docs/docs/topics/production-deployment.md

- Add section for installation
- Move installation related information from `Releases` to `Installation`
- Fix incorrect links
**Checklist**:

docs: add installation section

---

cache/cache.go

Avoid starting memberlist for configuration warnings unless we are running `memory` databroker storage type.  
**Checklist**:

cache: only run memberlist for in-memory databroker

---

authenticate/authenticate.go
authorize/authorize.go
authorize/authorize_test.go
cache/cache_test.go

Check that authorize service is given a valid databroker url. 
**Checklist**:

authorize: add databroker url check

---

config/policy.go

Set json/yaml `omitempty` for Options.SubPolicies
**Checklist**:

config: omit empty subpolicies in yaml/json

---

docs/.vuepress/config.js
docs/readme.md

Makes `/` and `/enterprise` redirect to the enterprise site.
**Checklist**:

docs: add / redirect

---

authorize/authorize.go
authorize/authorize_test.go
authorize/check_response_test.go
authorize/grpc.go
authorize/grpc_test.go
authorize/run.go
authorize/session.go
authorize/session_test.go
authorize/state.go
internal/cmd/pomerium/pomerium.go

Same as #1280 but for the authorize service. 
- #1254 
**Checklist**:

authorize: use atomic state for properties

---

.github/workflows/test.yaml

Add precommit action to run checks during CI.
#666 
**Checklist**:

ci: add precommit to test workflow

---

pkg/storage/redis/redis_test.go

- Update docker interaction to mount certs locally
- Change to using the upstream redis image
Fixes #1304
**Checklist**:

pkg/storage/redis: update tests to use local certs + upstream image

---

docs/docs/CHANGELOG.md

Update CHANGELOG.md for v0.10.1
**Checklist**:

docs: v0.10.1 changelog

---

internal/autocert/manager.go

Use an atomic value for the acme manager instead of taking the lock. This was blocking because the update method doesn't complete until all the certificates are acquired, which mean the call to `RLock` could never complete.
- fixes #1305 
**Checklist**:

autocert: fix locking issue

---

internal/autocert/manager.go

autocert: fix locking issue (#1310)

---

integration/forward_auth_test.go
integration/internal/flows/flows.go

This PR adds integration tests for forward auth. It's in the progress of refactoring how pomerium handles forward auth requests flow.
**Checklist**:

integration: add forward auth test

---

internal/urlutil/query_params.go

internal/urlutil: remove un-used constants

---

.golangci.yml
docs/docs/identity-providers/cognito.md
docs/docs/topics/data-storage.md
docs/docs/topics/kubernetes-integration.md
docs/docs/topics/programmatic-access.md
integration/main_test.go
internal/middleware/middleware_test.go
internal/telemetry/metrics/http.go
internal/telemetry/metrics/http_test.go
internal/telemetry/metrics/storage.go
pkg/storage/encrypted.go
pkg/storage/encrypted_test.go
pkg/storage/redis/redis_test.go

These changes add go import with local package awareness which is constantly being broken for those of us who are using vscode and gopls. 
Fixes https://github.com/pomerium/internal/issues/120
**Checklist**:

deployment: add goimports with path awareness

---

docs/docs/CHANGELOG.md

Update change log for v0.10.2
**Checklist**:

docs: update change log for 0.10.2

---

docs/guides/nginx.md

@desimone suggested changes

---

pkg/logutil/logutil.go
pkg/logutil/scrub.go
pkg/logutil/scrub_test.go

This adds a new log scrubber which can be used to sanitize protobuf messages.
**Checklist**:

logs: add new log scrubber

---

docs/reference/readme.md

Remove typo on remove_request_headers docs
**Checklist**:

Remove typo on remove_request_headers docs

---

.github/workflows/release.yaml
docs/guides/cloud-run.md
examples/cloudrun/deploy.sh

Ensure we publish a `latest` tag for cloudrun images and update references to the gcr image.
**Checklist**:

ci: publish cloudrun latest tag

---

docs/docs/community/readme.md

Small grammar changes.
**Checklist**:

docs: fix grammar

---

examples/config/policy.example.yaml

Correct a typo
N/A
**Checklist**:
- N/A add related issues
- N/A updated docs
- N/A updated unit tests
- N/A updated UPGRADING.md

chore(docs): Fix typo in example policy

---

docs/docs/CHANGELOG.md

Add v0.10.4 changelog entry
**Checklist**:

Add v0.10.4 changelog entry

---

docs/docs/CHANGELOG.md

Add new entry to v0.10.4 changelog
**Checklist**:

docs: update 0.10.4 changelog

---

internal/databroker/server.go
pkg/storage/redis/redis.go
pkg/storage/redis/redis_test.go

cherry-pick https://github.com/pomerium/pomerium/pull/1450

redis: use pubsub instead of keyspace events

---

docs/docs/CHANGELOG.md

Update changelog for v0.10.5
**Checklist**:

docs: Update changelog for v0.10.5

---

scripts/embed-envoy.bash

Update `arm64` to latest envoy.
Follow-up to #1473 
**Checklist**:

deps: update envoy arm64 to v1.15.1

---

docs/docs/CHANGELOG.md

Update changelog for v0.10.6
**Checklist**:

docs: Update changelog for v0.10.6

---

examples/nginx/httpbin.conf
examples/nginx/pomerium.conf
examples/nginx/proxy.conf

Fixes a few issues in the nginx example. 
#1459 
**Checklist**:

examples: fix nginx example

---

go.sum

Runs go mod. 
- #1510 
- #1506 
- #1507 
- #1508 
- #1509
**Checklist**:

deployment: run go mod tidy

---

authorize/check_response.go

Fixed an issue caused by #1521 where the redirect uri was not getting added to the debug endpoint making it impossible for authN to know how to complete the flow to save the updated session token. 
Fixes #1532 
Caused by #1521 
**Checklist**:

authorize: add redirect url to debug page

---

docs/reference/readme.md
docs/reference/settings.yaml
scripts/generate-settings-docs.py

This changes the markdown readme.md file to be generated from a YAML file which can be used for other purposes.
**Checklist**:

add settings.yaml file

---

.github/workflows/docker-master.yaml

- Publish git hash tagged docker images from master
- Commit latest image tag to internal test environment deployment
**Checklist**:

ci: automatically update test environment with master

---

go.sum
internal/identity/manager/manager.go

Updates the user info when refreshing a session.
Closes #1571 
**Checklist**:

update user info in addition to refreshing the token

---

docs/reference/settings.yaml
scripts/generate-settings-docs.py

Moving the new any authenticated user setting into the settings.yaml.
#1515 
**Checklist**:

move docs to settings.yaml

---

docs/reference/readme.md
examples/config/config.example.env
examples/config/config.example.yaml

These changes attempt to standardize the language in how we describe lists of settings.
https://pomerium-io.slack.com/archives/CK6SVMPU0/p1605219526115500?thread_ts=1605045822.106300&cid=CK6SVMPU0
**Checklist**:

docs: use standard language for lists

---

.github/workflows/release.yaml

Fix action syntax error in release workflow
**Checklist**:

ci: fix release workflow syntax

---

scripts/embed-envoy.bash

Updates Envoy to 1.16.1 
- https://www.envoyproxy.io/docs/envoy/v1.16.1/version_history/current
- https://groups.google.com/g/envoy-announce/c/FIwkINkxF5A
**Checklist**:

chore(deps): update envoy 1.16.1

---

.github/workflows/release.yaml

Remove unmaintained github action for getting the current tag
n/a
**Checklist**:

ci: update tag parsing step

---

.github/workflows/docker-master.yaml

Fix error in publish workflow.
**Checklist**:

ci: remove bad quoting in publish steps

---

.github/workflows/release.yaml

Begin pushing RPMs to bintray
N/A
**Checklist**:

ci: add bintray publishing

---

docs/docs/upgrading.md

Update upgrade notes for `cache_service_url` removal
n/a
**Checklist**:

docs: add cache_service_url upgrade notice

---

README.md

Switch build badge to point at GitHub Actions
- My OCD
**Checklist**:

docs: update build badge

---

docs/reference/readme.md
docs/reference/settings.yaml

These docs need to be in the `settings.yaml` file so they can be consumed by other projects.
**Checklist**:

move signing key algorithm documentation into yaml file

---

internal/identity/oidc/azure/microsoft.go

Fix imports on `microsoft.go`
n/a
**Checklist**:

identity/oidc/azure: goimports

---

internal/identity/manager/manager.go

Previously when receiving a session update, if no user existed for that session we'd create a new one. Because `Sync` streams records it's possible for the local user record to not exist when the session is updated. When this happens, the user record was being replaced with an empty claim set (and names, etc).
I was able to reproduce the problem by adding a sleep before doing the user sync, and sure enough I got an empty user record. The problem would resolve itself when the user record was refreshed, but it would be empty until then.
This change simply removes the creation of the user record, since it's now created during authentication anyway, so it's not necessary:
```go
// if no user exists yet, create a new one
currentUser, _ := user.Get(ctx, state.dataBrokerClient, s.GetUserId())
if …
```

don't create users when updating sessions

---

pkg/storage/inmemory/inmemory.go
pkg/storage/inmemory/inmemory_test.go

We weren't locking the mutex when iterating over the btree. This wasn't safe.
Fixes #1673 
**Checklist**:

fix concurrency race

---

.github/goreleaser.yaml
.github/workflows/release.yaml

Backport d1194ef6e8f0d5fbdbbc8f21b0a9e8b6dc6a7580 from #1687

[Backport 0-11-0] deployment: Fix docker and rpm workflows

---

docs/reference/readme.md
go.mod
go.sum
internal/telemetry/metrics/kv.go
internal/telemetry/metrics/kv_test.go
pkg/storage/redis/redis.go

Adjust redis connection stats for new client package.
#1649 
**Checklist**:

internal/telemetry/metrics: update redis metrics for go-redis

---

config/options.go

Backport 5f6e11623f75555e2dc4884e9940679b6f13d5ad from #1698

[Backport 0-11-0] config: fix ignored yaml fields

---

docs/.vuepress/config.js
docs/docs/topics/tcp-support.md
docs/reference/readme.md
docs/reference/settings.yaml
scripts/generate-settings-docs.py

Add docs around TCP tunneling support
n/a
**Checklist**:

docs: tcp support

---

internal/cliutil/jwtcache.go
internal/tcptunnel/tcptunnel.go

This PR updates the TCP tunnel code to handle non-200 HTTP response codes. We will retry-authentication once for any redirect codes, but otherwise we will delete the saved JWT to make sure we can restart the login process.
I also noticed that we were attempting to do programmatic login against the authenticate service URL, but AFAIK the programmatic login is only available on the proxy URL, so I updated the URL that's used in this case.
**Checklist**:

tcptunnel: handle invalid http response codes

---

internal/controlplane/xds_cluster_test.go
internal/controlplane/xds_clusters.go
internal/controlplane/xds_listeners.go
internal/controlplane/xds_listeners_test.go

Set recommended defaults for envoy.
**Checklist**:

set recommended defaults

---

Makefile
authorize/evaluator/evaluator.go
config/options_test.go
internal/tcptunnel/tcptunnel.go
pkg/grpc/client_test.go

Fix the coverage makefile command so that it errors properly.
**Checklist**:

fix coverage

---

.github/workflows/docker-master.yaml

Update workflow syntax for breaking changes in yq v4.
https://github.com/pomerium/pomerium/pull/1711
**Checklist**:

ci: upgrade yq syntax for v4

---

.github/workflows/docker-master.yaml

Fix typo.
- https://github.com/pomerium/pomerium/pull/1745
- 🤦 
**Checklist**:

ci: fix typo in yq image

---

docs/docs/CHANGELOG.md
docs/docs/upgrading.md

Update release information for `v0.12`
n/a
**Checklist**:

docs: v0.12 upgrade notes and changelog

---

docs/.vuepress/config.js

Add v0.12 link to docs menu
#1753 
**Checklist**:

docs: update menu for v0.12

---

internal/autocert/manager.go
internal/autocert/manager_test.go
internal/cmd/pomerium/pomerium.go
internal/log/log.go

Backport changes from #1767 to v0.12.
- cherry-picked preliminary changes from #1765 
- #1749 
**Checklist**:

[Backport 0-12-0] autocert: improve logging

---

.github/workflows/test.yaml
lichen.yaml

Add a CI step to check dependency licenses
n/a
**Checklist**:

ci: license check action

---

docs/docs/topics/getting-users-identity.md

Adds reference to our go-sdk! 
- https://github.com/pomerium/sdk-go
**Checklist**:

docs: add reference to the go-sdk

---

.github/workflows/release.yaml

address incomplete change from #1763 
#1763 
**Checklist**:

ci: fix usage of env variable in latest tag

---

.github/PULL_REQUEST_TEMPLATE

Adds an entry to the checklist so we don't forget to tag. :) 
**Checklist**:

github: add tag suggestion to checklist

---

config/config_source.go
config/config_source_test.go
go.sum

Change detection was only bubbling up if one of the TLS certs changed. This should fix it.
Fixes #1818

config: fix hot-reloading

---

internal/controlplane/xds.go
internal/controlplane/xds_cluster_test.go
internal/controlplane/xds_clusters.go
internal/controlplane/xds_listeners.go
internal/controlplane/xds_listeners_test.go
internal/controlplane/xds_routes.go
internal/controlplane/xds_routes_test.go

This PR updates the XDS code to return optional errors. This was requested in #1798 but given the number of changes I didn't want to confuse these changes with the ones related to the actual change.

controlplane: return errors in xds build methods

---

docs/reference/readme.md
docs/reference/settings.yaml

Fixes user confusion around Host Rewrite Headers in the console. The related PR on the console is 440.
**Checklist**:

updated host rewrite docs

---

config/policy.go
config/policy_test.go
docs/reference/readme.md
docs/reference/settings.yaml
internal/controlplane/xds_routes.go
internal/controlplane/xds_routes_test.go

provides a human readable cluster name, useful for metrics.

cluster name

---

internal/controlplane/xdsmgr/xdsmgr_test.go

Apparently this test fails sometimes? I was unable to reproduce locally, but maybe this will make it more reliable.

controlplane: maybe fix flaky test

---

internal/controlplane/xds_routes.go
internal/controlplane/xds_routes_test.go

Currently its not possible to use the Pomerium proxy in front of the authenticate service. To support a single network ingress proxy, these changes implement pass-through to the authenticate backend. There are 3 changes:
1. `.pomerium` routes are not added
2. `ext_authz` is disabled
3. The cookie is not stripped
This should allow support for routes like:
```yaml
policy:
- name: authenticate
from: https://authenticate.localhost.pomerium.io
to: https://pomerium-authenticate
allow_public_unauthenticated_access: true
host_rewrite: "authenticate.localhost.pomerium.io"
tls_skip_verify: true
```

proxy: implement pass-through for authenticate backend

---

docs/docs/topics/load-balancing.md
docs/docs/upgrading.md
docs/reference/readme.md
docs/reference/settings.yaml

- Add some more context links and examples for the health checking and load balancing options
- Add the load balancing feature set to `UPGRADING`
https://github.com/pomerium/pomerium/pull/1804
https://github.com/pomerium/pomerium/pull/1796

docs: additional load balancing documentation

---

docs/docs/community/security.md

Updates security policy for more details on disclosure process, removes keybase, and some things NOT to do.

docs: update security policy

---

docs/docs/CHANGELOG.md
docs/docs/upgrading.md

Small upgrade notes and changelog for v0.13
n/a

docs: misc upgrade notes and changelog

---

docs/docs/topics/load-balancing.md
docs/docs/upgrading.md
docs/reference/readme.md
docs/reference/settings.yaml

Update docs for load balancing weight configuration.
#1882
#1830

docs: add load balancing weight documentation

---

docs/docs/upgrading.md

Further clarifies some of the upgrade notes. Alpha-bet-tize-er-s some of the changelog.

docs: update changelog for v0.13.0

---

internal/registry/server_test.go

fix registry test

---

docs/.vuepress/config.js

Update docs site for v0.13
n/a

docs: add v0.13 to docs site menu

---

.github/workflows/docker-master.yaml
.github/workflows/release.yaml

Backport 3c84004c1d436f3891331b8e02fd4f25c8892c89 from https://github.com/pomerium/pomerium/pull/1916

ci: deploy releases to test environment (#1916)

---

internal/identity/manager/manager.go
internal/telemetry/metrics/info.go

Add a metric for the last refresh time.

identity: record metric for last refresh

---

docs/.vuepress/config.js
docs/guides/jwt-verification.md
docs/guides/readme.md

Add an example for how to verify the JWT header using Envoy.
Fixes #1925

docs: add JWT Verification w/Envoy guide

---

go.sum
internal/testutil/redis.go
pkg/storage/redis/client.go
pkg/storage/redis/client_test.go
pkg/storage/redis/redis.go
pkg/storage/redis/redis_test.go

Add support for redis-sentinel URLs.

redis: add support for redis-sentinel

---

authorize/log.go
pkg/protoutil/crypt_test.go

Add additional tracing for the audit log message. Also add a benchmark for the encryptor. The overhead for a protobuf object with ~100 fields is:
```text
goos: linux
goarch: amd64
pkg: github.com/pomerium/pomerium/pkg/protoutil
cpu: AMD Ryzen 7 5800X 8-Core Processor             
BenchmarkEncrypt
BenchmarkEncrypt-16    	   12732	     95750 ns/op
```

authorize: additional tracing, add benchmark for encryptor

---

internal/registry/constants.go
internal/registry/reporter.go

`metrics_address` should be optional parameter.

metrics_address should be optional parameter

---

internal/controlplane/xdsmgr/xdsmgr.go

Just the error handling from https://github.com/pomerium/pomerium/pull/2090

xdsmgr: update resource versions on NACK

---

docs/docs/community/security.md

This PR adds a section to our docs discussing what is and what is not in our threat model. This is a living document, and will be updated from time to time. 
- Closes #296

docs: add threat model to security page

---

authorize/evaluator/evaluator.go

This log wasn't intended. I had removed it locally but forgot to push.

authorize: remove log

---

config/envoyconfig/clusters_test.go
config/envoyconfig/envoyconfig.go
config/envoyconfig/listeners.go
config/envoyconfig/listeners_test.go
config/envoyconfig/protocols.go

Update the envoy configuration with the recommended defaults: https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge. This is a rehash of https://github.com/pomerium/pomerium/pull/1735.
Fixes #2085

envoy: re-implement recommended defaults

---

docs/docs/upgrading.md

Add upgrade notes for the changes to our user ID format.
#2068

docs: upgrade notes on `allowed_users` by ID

---

.github/workflows/test.yaml
README.md

Remove codecov action from CI.  
n/a

ci: remove codecov

---

internal/controlplane/xdsmgr/xdsmgr.go

Report instance hostname in xds events

report instance hostname in xds events

---

docs/docs/community/readme.md

Update slack community link.
n/a

docs: update slack link to vanity url

---

docs/docs/topics/data-storage.md
docs/docs/upgrading.md

Add headline features to upgrade docs.
n/a

docs: add v0.14 feature highlights

---

config/envoyconfig/routes.go

A common use case for `kubectl` is to tail logs. Since we have a default timeout of 30 seconds for routes this will cause log tailing to stop. Currently we disable the default timeout for websockets and tcp connections. This PR also adds excludes kubernetes routes from the default timeout.
Fixes #2182

envoy: disable timeouts for kubernetes

---

scripts/get-envoy.bash

deps: bump envoy to v1.17.3

---

docs/docs/readme.md

The ordered list at the end changed from simple present tense to present progressive tense, which can break reader flow.## Related issues
~reference any related issues~
~updated unit tests~
~updated UPGRADING.md~

docs: Match Tenses

---

go.mod
go.sum

Details to follow release. 
Fixes https://github.com/pomerium/internal/issues/415

depedency: update /x/net

---

authorize/evaluator/custom.go

These functions were accidentally left out of custom policy evaluation.

authorize: add rego functions to custom evaluator

---

examples/helm/helm_gke.sh
examples/kubernetes/values.yaml

Update examples for new service type values.
https://github.com/pomerium/pomerium-helm/pull/196

docs: update helm values for chart v20.0.0

---

internal/controlplane/events.go

Retry storing configuration events if the databroker is unavailable.
FWIW I didn't figure out a way to trigger the underlying problem because we use `WaitForReady`, so gRPC is already handling this internally.
Fixes https://github.com/pomerium/internal/issues/421

xds: retry storing configuration events

---

pkg/storage/redis/redis.go

Changes the way we enforce capacity in redis. There were 3 issues previously:
1. Because we used `uint64`s, the check `removeCnt <= 0` didn't make sense. It often resulted in a very large number.
2. If two databrokers simultaneously enforced options, there was a race on `ZCARD` vs `ZPOPMIN`. 
3. We were adding the removed record back to the same list of records.
By using `ZREVRANGE` we can find the excess records and remove them one at a time. If two databrokers attempt to enforce the options simultaneously we may end up removing the same record twice, but that should be ok.
Fixes https://github.com/pomerium/internal/issues/428

redis: enforce capacity via ZREVRANGE to avoid race

---

.github/workflows/test.yaml
Makefile

Add [coveralls](https://coveralls.io/) to CI.
n/a

ci: add coveralls

---

pkg/storage/redis/redis_test.go

Coverage detection for this test was non-deterministic because parts of the `Put` operation wouldn't necessarily complete before the test exited. I updated the test so that the `Put` doesn't trigger until after the first backend binds `onChange`. This should allow the `Put` to fully complete before completing the test.
Fixes https://github.com/pomerium/internal/issues/460

redis: refactor change signal test to be more deterministic

---

.github/workflows/test.yaml

Fix integration tests timing out.
https://github.com/helm/kind-action/issues/42

chore(deps): upgrade kind action to v1.2.0

---

authorize/grpc.go
authorize/log.go
authorize/sync.go

Log service account and impersonation details.
- https://github.com/pomerium/pomerium-console/issues/1541

authorize: log service account and impersonation details

---

.github/workflows/test.yaml

Backport 937f1cc83f4e2615649ecfc039046eabdaaf25c7 from #2281

chore(deps): upgrade kind action to v1.2.0 (#2281)

---

internal/databroker/config_source_test.go
internal/databroker/server_test.go

Add tests to the databroker server.
Fixes https://github.com/pomerium/internal/issues/459

databroker: tests

---

cmd/pomerium-cli/cache.go
cmd/pomerium-cli/kubernetes.go

Add subcommand to flush credentials.
Fixes #2378

k8s: add flush-credentials command

---

docs/docs/quick-start/helm.md
examples/helm/helm_gke.sh
examples/kubernetes/values.yaml

- Removed or fixed redundant or incorrect config options. 
- Some small copy edits

Helm Quickstart Update

---

authorize/evaluator/evaluator.go
authorize/evaluator/headers_evaluator.go
authorize/evaluator/policy_evaluator.go

Add additional tracing for rego evaluation:

authorize: add additional tracing for rego evaluation

---

.github/workflows/release.yaml

The gcloud action we used has been moved. Update workflow files to fix.
n/a

ci: update gcloud action

---

config/policy_ppl.go
pkg/policy/criteria/accept.go
pkg/policy/criteria/authenticated_user.go
pkg/policy/criteria/claims.go
pkg/policy/criteria/cors_preflight.go
pkg/policy/criteria/domains.go
pkg/policy/criteria/emails.go
pkg/policy/criteria/groups.go
pkg/policy/criteria/invalid_client_certificate.go
pkg/policy/criteria/pomerium_routes.go
pkg/policy/criteria/reject.go
pkg/policy/criteria/users.go
pkg/policy/generator/criterion.go
pkg/policy/generator/generator.go
pkg/policy/generator/generator_test.go

Remove support for criteria aliases.
- https://github.com/pomerium/internal/issues/471

ppl: remove support for aliases

---

config/envoyconfig/clusters.go
config/envoyconfig/clusters_test.go
config/envoyconfig/protocols.go

Requested improvements to envoy config.
- #2399

envoyconfig: improvements

---

docs/enterprise/console-settings.yaml

Add docs about PPL.
Fixes https://github.com/pomerium/internal/issues/484

add docs about PPL

---

scripts/get-envoy.bash

envoy: bump to 1.19

---

Makefile

Add the embedded envoy files to `make clean`.
n/a

build: add envoy files to `make clean`

---

authorize/log.go

Log additional session details when impersonating:
```json
{
"level":"info",
"service":"authorize",
"request-id":"3c6cd224-986b-4717-8579-275a6e697f7d",
"check-request-id":"dc54800a-cb8d-497b-8d5c-4bdea534d5db",
"method":"GET",
"path":"/static/js/2.chunk.js.map",
"host":"console.localhost.pomerium.io:20443",
"query":"",
"session-id":"1bd04cc5-39ef-48d5-980e-651499978214",
"impersonate-session-id":"f8f827a9-b6bd-4bae-bdb6-5157e5f29395",
"impersonate-user-id":"143879211",
"impersonate-email":"cdoxsey+test@pomerium.com",
"allow":true,
"deny":null,
"user":"81199643",
"email":"cdoxsey@pomerium.com",
"databroker_server_version":10971234588439785608,
"databroker_record_version":15,
"time":"2021-08-02T11:38:47-06:00",
"message":"authorize check"
}
```
Fixes #2418

authorize: log additional session details

---

RELEASING.md
docs/docs/CHANGELOG.md
docs/docs/upgrading.md
scripts/changelog.sh

Update changelog and release notes for v0.15.
Also:
- add a brief writeup of our release process so it doesn't live in my head
- tweak changelog script so it doesn't cache in the repo directory
n/a

v0.15 release notes

---

docs/docs/topics/getting-users-identity.md
docs/docs/topics/tcp-support.md
docs/guides/jwt-verification.md
docs/guides/kubernetes.md
docs/guides/local-oidc.md
docs/guides/mtls.md
docs/guides/transmission.md
docs/reference/readme.md
docs/reference/settings.yaml
examples/config/config.example.yaml
examples/config/route.example.yaml

Various doc updates. In PPL the `groups` criterion supports a single string value, not an array. I think I updated all of them.

doc updates

---

docs/enterprise/install/helm.md
docs/enterprise/install/quickstart.md

These docs updates are required, should https://github.com/pomerium/pomerium-console/pull/1783 be merged.

Update Console installs to match signing_key

---

docs/docs/CHANGELOG.md

Additions to v0.15 changelog.
n/a

update v0.15 changelog

---

docs/docs/install/helm.md
docs/enterprise/about.md
docs/enterprise/concepts.md
docs/enterprise/console-settings.yaml
docs/enterprise/install/helm.md
docs/enterprise/install/quickstart.md
docs/enterprise/install/readme.md
docs/enterprise/prometheus.md
docs/enterprise/reference/config.md
docs/enterprise/reference/configure.md
docs/enterprise/reference/manage.md
docs/enterprise/reference/reports.md

docs: update branding, concepts

---

docs/docs/install/binary.md
docs/guides/local-oidc.md
examples/config/config.minimal.yaml

- Fixes the route block in the minimal config example file.
- Updates the Binary installation doc to include our OS packages.

Update binary install doc

---

.github/CODEOWNERS

Add dev and docs teams to /docs directory
n/a

docs: update codeowners

---

docs/.vuepress/config.js
docs/enterprise/changelog.md
docs/enterprise/console-settings.yaml
docs/enterprise/reference/configure.md
docs/enterprise/reference/manage.md
docs/enterprise/upgrading.md
scripts/generate-console-pages.js

Closes https://github.com/pomerium/pomerium-console/issues/1831
- Creates an Upgrade and a Changelog page for Enterprise docs.
- Updates reference docs for a removed setting and updated branding.

Enterprise Upgrade & Changelog Pages

---

docs/reference/readme.md
docs/reference/settings.yaml

Copy edit for docs update pushed without it.
#2471

wrap header example values as inline code.

---

authorize/session.go
authorize/session_test.go
config/custom.go
config/custom_test.go
internal/log/middleware.go
internal/log/middleware_test.go
internal/middleware/middleware.go
internal/middleware/middleware_test.go

Remove a bit of unused code we've had laying around for quite a while. Post v0.15.

all: remove unused handler code

---

docs/.vuepress/config.js
docs/docs/install/helm.md
docs/docs/install/readme.md
docs/docs/topics/certificates.md
docs/partials/install-mkcert.md
examples/config/config.docker.yaml
examples/docker/basic.docker-compose.yml
package.json

Manual Backport of #2482 to `0.15.0`.

Update Docker Quickstart (#2482)

---

examples/config/config.docker.yaml

Fixes blocking in example config comments.
#2482

adjust comment blocking

---

docs/docs/identity-providers/dex-freeipa.md
docs/docs/identity-providers/readme.md

- Removes Dex/FreeIPA content (saved in non-indexed page, for posterity and/or to be revived later).
- Updates the IdP Overview page to prepare users for what to expect when following the IdP-specific docs
Closes https://github.com/pomerium/docs/issues/9
Closes https://github.com/pomerium/docs/issues/16
~updated unit tests~
~updated UPGRADING.md~

Update IdP Overview Page

---

docs/enterprise/install/helm.md
docs/enterprise/upgrading.md

Updates Helm instructions for new config requirements.

Update Helm Instructions

---

.github/goreleaser.yaml
.github/workflows/release.yaml

Backport e3770e29eccdf18c12a52ebe19a1440d34837c57 from #2473

ci: support darwn/arm64 aka m1 for cli

---

scripts/get-envoy.bash

deps: update envoy to 1.19.1

---

config/envoyconfig/bootstrap.go

Remove the deprecated envoy bootstrap admin `access_log_path` option in favor of `access_log`.
Fixes https://github.com/pomerium/internal/issues/481
- [x reference any related issues

envoy: remove deprecated access_log_path

---

docs/enterprise/changelog.md

Update enterprise changelog for v0.15.1.
n/a

docs: enterprise v0.15.1 changelog

---

docs/enterprise/changelog.md

Release notes for v0.15.2.
n/a

docs: enterprise console v0.15.2 changelog

---

cmd/pomerium-cli/main.go
internal/authclient/config.go
internal/tcptunnel/config.go
internal/tcptunnel/tcptunnel_test.go

Backport #2593 and #2594 to 0.15

backport 2593 and 2594 to 0.15

---

docs/.vuepress/public/_redirects

Adds redirect for old path to installation doc.

Add redirect for installation

---

docs/enterprise/pomerium-console_serve.yaml
docs/enterprise/reference/config.md
docs/enterprise/reference/configure.md
docs/enterprise/reference/manage.md

- Updated console reference for the `audience` key.
- Imported clarifications `tracing_sample_rate` and `set_request_headers`.

DOCS: Update Enterprise Reference Docs

---

docs/docs/identity-providers/okta.md

Correction flagged by @acidDrain, re-created since the CLA was never accepted.
Closes #2507

DOC: Copy edits to Okta IdP doc.

---

docs/docs/releases.md
docs/docs/topics/certificates.md
docs/docs/topics/data-storage.md
docs/enterprise/about.md

- Reduce sidebar depth for several docs
- Add Desktop Clients to releases page.
https://github.com/pomerium/docs/issues/40

adjust sidebarDepths and document Desktop Client releases

---

docs/enterprise/api.md
docs/enterprise/console-settings.yaml
docs/enterprise/reference/configure.md
docs/reference/readme.md
docs/reference/settings.yaml

Manual backport of #2651 
* standardize relative links
* make img refs very relative
#2651

DOCS: Standardize Relative Links (#2651)

---

docs/.vuepress/components/Newsletter.vue
docs/.vuepress/config.js
docs/docs/community/readme.md
package.json

Added LinkedIn link
Added Discourse link
Added copy for newsletter sign-up, but someone will need to add a redirect link or a form.

Docs: Update Community Page

---

docs/reference/readme.md
docs/reference/settings.yaml

Updates the traefik docker-compose file to use current claim naming convention.
Closes #2728

Docs: Update Traefik Example Headers

---

.github/workflows/release.yaml

Update goreleaser to latest.
https://github.com/goreleaser/goreleaser/issues/2595
Fixes https://github.com/pomerium/pomerium/issues/2708

deps: update goreleaser

---

docs/docs/upgrading.md

Copy Edit for #2782, merged before I could review it.
#2782

Copy edit to changelog entry

---

docs/.vuepress/config.js
docs/docs/topics/ppl.md

Creates new topic page on PPL.
Closes https://github.com/pomerium/docs/issues/15
Closes https://github.com/pomerium/docs/issues/39
Closes https://github.com/pomerium/docs/issues/58

Document Pomerium Policy Language

---

docs/guides/readme.md

Addition to Guides index was skipped when the new guide was added.

DOCS: add Grafana to Guides index

---

docs/docs/identity-providers/okta.md

fix typo in docs

---

docs/docs/k8s/ingress.md

add docs for ingress regex path

---

config/options.go
internal/envoy/envoy.go

Fixed return description error

fix: Fixed return description error

---

docs/reference/readme.md
internal/identity/manager/manager.go
internal/telemetry/metrics/info.go
pkg/metrics/constants.go

Adds more fine-grained identity provider metrics. 
Implements https://github.com/pomerium/internal/issues/699

more idp metrics

---

docs/docs/community/readme.md

Better titles and describes our forum and its desired use compared to Slack and GitHub

Rephrase Discussion around Discuss

---

docs/guides/kubernetes-dashboard.md

Remove duplicate configuration items of route
This is the commit from #2867 that improves docs, without the additional changes to the source code.
#2867

DOCS: Cherry-Pick from #2867

---

docs/docs/identity-providers/okta.md
docs/docs/topics/device-identity.md
docs/docs/upgrading.md
docs/enterprise/changelog.md
docs/guides/grafana.md
docs/guides/kubernetes-dashboard.md
docs/guides/kubernetes.md
docs/reference/readme.md

- Fixed some malformed links
- Adjusted copy to prevent (some of the) false positives in the Vuepress link checker.

DOCS: Link Cleanup & Checker Workaround

---

docs/docs/topics/mutual-auth.md

Replaces a placeholder link with a good source for info on zero-trust
#2820

DOCS: Crosslink Mutual Auth and Background pages

---

docs/reference/readme.md
docs/reference/settings.yaml

Minor updates and alignment to settings reference, which had been modified at the markdown level and no longer consistent with the source YAML.

Docs: Update and align reference settings

---

docs/reference/readme.md
docs/reference/settings.yaml

Docs: Manual Backport: update and align reference settings (#2905)

---

docs/guides/upstream-mtls.md

Adds a "More Resources" section with relevant links.

Docs: Crosslinks on Upstream mTLS

---

internal/directory/provider.go

Persist and return a root cause when IDP directory sync is disabled. 
Fixes https://github.com/pomerium/internal/issues/722

return explicit error when directory sync is disabled

---

docs/guides/code-server.md

Updates the guide for code-server with adjusted formatting and small copy edits.
Resolves https://github.com/pomerium/docs/issues/3

Docs: code-server guide refresh

---

internal/frontend/assets/html/userInfo.html

fix: frontend html tag mismatch

---

docs/.vuepress/config.js
docs/docs/glossary.md

Creates a Glossary page with common terminology used throughout the docs.
Resolves https://github.com/pomerium/docs/issues/65

DOCS: New page: Glossary

---

docs/docs/glossary.md
docs/guides/istio.md
examples/kubernetes/istio/grafana.ini.yml

Rewrites our Istio Guide to work with our Ingress Controller's upcoming enhancements.
Resolves https://github.com/pomerium/docs/issues/5

Docs: Rewrite Istio Guide for Ingress Controller

---

docs/reference/readme.md
docs/reference/settings.yaml

Docs - Backport of: clarify base path for idp_provider_url (#2956)

---

docs/enterprise/changelog.md
docs/enterprise/upgrading.md

Add changelog summary for the enterprise product. 
Related to https://github.com/pomerium/internal/issues/744

Update enterprise changelog for v0.16.0

---

examples/nginx/config.yaml
examples/nginx/docker-compose.yaml
examples/nginx/verify.conf

Backport 2995 to 0-16-0

---

.github/Dockerfile-release
.github/Dockerfile-release-debug
.github/Dockerfile-release-debug-nonroot
.github/goreleaser.yaml
.github/workflows/release.yaml
docs/docs/releases.md

Add a debug image for each official release.
Closes https://github.com/pomerium/pomerium/issues/584

deployment: add debug image for all releases

---

docs/guides/kubernetes.md

DOCS: Fix metadata description

---

docs/guides/local-oidc.md
examples/config/config.docker.yaml

Updates examples using the Verify app with the port `8000`.
Fixes #2930

update verify port

---

.github/workflows/release.yaml

Backport 393ae660de8cd65fe99ca4a9e1a9ef5f5087b516 from #3042 
#3042

ci: use default branch name for helmfile repo 

---

ui/src/components/Header.tsx

Hot fix for broken link in avatar picture

fix link for picture in avatar

---

docs/reference/readme.md
docs/reference/settings.yaml

This PR has three changes, sorted by commit:
- 89fa0f2f346a04ffadce10ed63b0c4cc5ab25c6a sorts the Routes section alphabetically. See the commit notes for details on how I confirmed no data was lost.
- 22d3a36da46e0e84fef3cbb62fc480f3954227c8 provides minor copy edits to the Host Rewrite section.
- 5f8e3ded5f88584a9b0787ce46d2b9d44073e047 documents the per-route `idp_client` and `idp_secret` keys introduced in #3030.
Documents #3030

DOCS: Reference Updates

---

docs/reference/readme.md
docs/reference/settings.yaml

Copy edits for reference docs added in #3047

DOCS: Auth Passthrough Edits

---

scripts/get-envoy.bash

deps: bump envoy to v1.20.2

---

scripts/get-envoy.bash

Update the v0.16 release to latest envoy v1.19.
Also lint fixes to the embed script.
https://github.com/pomerium/pomerium/pull/3082

deps: update envoy to v1.19.3

---

docs/reference/readme.md
docs/reference/settings.yaml

Manual backport of several commits from #3059 
- https://github.com/pomerium/pomerium/commit/89fa0f2f346a04ffadce10ed63b0c4cc5ab25c6a
- https://github.com/pomerium/pomerium/commit/22d3a36da46e0e84fef3cbb62fc480f3954227c8

DOCS: Backport Reference Updates

---

docs/.vuepress/config.js

Update dev branch to reflect master -> main.
#3045

docs: update dev branch name

---

docs/docs/CHANGELOG.md
docs/docs/upgrading.md

Upgrade notes and changelog for v0.17.
n/a

docs: Update release notes and changelog for v0.17

---

docs/docs/identity-providers/okta.md

Small updates to Okta IDP guide:
- new meta keywords
- new Intro paragraph on what Okta provides, and how we work with them.

Docs: Update Okta Copy

---

docs/guides/istio.md

typo correction

---

docs/docs/identity-providers/auth0.md

Documents the required JWT signature algorithm.
Fixes #3124

DOCS: Auth0 JWT signature algorithm

---

docs/enterprise/console-settings.yaml
docs/enterprise/reference/manage.md

Documents the Metric Name Field in Routes

DOCS: Metrics Name

---

docs/.vuepress/config.js
docs/docs/security.md

New doc page: Securing Pomerium - an index of security-related docs and guides, organized to match a typical user journey.
Closes https://github.com/pomerium/docs/issues/45

DOCS: Securing Pomerium

---

.github/workflows/release.yaml

ci: update setup-gcloud to use v0

---

authenticate/handlers.go
authenticate/handlers/userinfo.go
internal/httputil/errors.go
ui/src/App.tsx
ui/src/components/Footer.tsx
ui/src/types/index.ts

Remove the version from the UI.
Fixes https://github.com/pomerium/pomerium/issues/3159

ui: remove version

---

.github/workflows/backport.yaml
.github/workflows/docker-main.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml

Pin github actions. This is considered a best practice by [ossf/scorecard](https://github.com/ossf/scorecard).
Fixes https://github.com/pomerium/internal/issues/478

github: pin github actions

---

docs/docs/troubleshooting.md

Expands the Troubleshooting [section](https://www.pomerium.com/docs/troubleshooting.html#redirect-loop-with-redis-databroker) on the Redis redirect loop to cover all shared_secret mismatch cases.
Fixes https://github.com/pomerium/internal/issues/809
Relates to #3187

DOCS: Expand shared_secret troubleshooting

---

.github/workflows/release.yaml

Update deployment workflow to reflect new repo/layout.
n/a

ci: update release deployment location

---

.github/workflows/backport.yaml

Bump backport action to latest `retain_labels`, which now includes the built typescript.
#3223

deps: bump backport action version

---

docs/guides/grafana.md
docs/reference/readme.md
docs/reference/settings.yaml

- Updates reference documentation for `jwt_claims_headers`
- Updates Grafana guide to provide more seamless user creation and login
- Includes community contributions from #3218

Docs: Grafana JWT & jwt_claims_headers updates

---

.github/CODEOWNERS

Removes Dev approval requirement for docs updates.

remove dev ownership of docs.

---

docs/docs/glossary.md
docs/docs/production-deployment.md

- Adds a glossary entry for "Stateless"
- Link to new entry from Production Deployment doc.
Fixes https://github.com/pomerium/internal/issues/814

DOCS: Define stateless

---

.github/CODEOWNERS

With a single docs team member who cannot review their own PRs, this allows for hotfixes to be merged more quickly.

Allow docs changes without review

---

docs/guides/cockpit.md

Fixes a config value, and adjusts the syntax highlighting

DOCS: hotfix cockpit config

---

Makefile
docs/enterprise/console-settings.yaml
docs/enterprise/reference/configure.md
docs/reference/settings.yaml
scripts/generate-settings-docs.py

BACKPORT: Add UUID to docs yaml blocks (#3251)

---

integration/flows/flows.go

integration: fix memory leakage

---

examples/kubernetes/pomerium-values.yaml

Updates example values file.
Fixes #3213

DOCS: update helm values file

---

authorize/sync.go

This may cause a high CPU usage on each call.
Signed-off-by: Seena Fallah <seenafallah@gmail.com>
~~Maybe~~ Fixes #3319

fix: close the ticker after opened

---

examples/traefik-ingress/values/pomerium.yaml

replace policy by routes in pomerium values file

fixing pomerium traefik example

---

docs/docs/k8s/helm.md

References the Ingress Controller documentation at the beginning and end of the Helm installation doc.
Fixes https://github.com/pomerium/internal/issues/834

DOCS: Crosslink Helm to Ingress Controller

---

docs/docs/k8s/ingress.md

- Documents the annotations to create a TCP route.
- Includes an example route
- Documents https://github.com/pomerium/ingress-controller/pull/196
- Resolves https://github.com/pomerium/internal/issues/840
- Depends on https://github.com/pomerium/pomerium/pull/3340 to avoid merge conflicts.

Docs: Document TCP routes in Kubernetes

---

.github/workflows/docker-main.yaml

We tore down the mysql test environment

github-actions: remove mysql bump

---

config/envoyconfig/listeners.go

replace fmt.Sprintf with net.JoinHostPort

replace fmt.Sprintf with net.JoinHostPort

---

README.md

Add instructions for how to run the integration tests locally.
Fixes https://github.com/pomerium/pomerium/issues/3398

integration: update readme with instructions for how to run the tests locally

---

scripts/get-envoy.bash

security upgrade https://groups.google.com/g/envoy-announce/c/QxI6z6wdL7M/m/0zPrdTLAAQAJ

bump envoy to 1.21.3

---

.github/workflows/docker-main.yaml
.github/workflows/docker.yaml

Break up the docker publish so it can run faster.

github-actions: faster docker publish

---

.github/workflows/docker.yaml

Breaking these up broke our docker images.

github-actions: build docker platforms together

---

.github/workflows/docker-main.yaml
.github/workflows/docker.yaml

Revert changes from yesterday
Fixes #3428

revert docker changes

---

.github/PULL_REQUEST_TEMPLATE

Updates the PR template. The hope here is to get an explanation of changes from the Devs on the changes in a PR written for a less technical reader. This also serves to alert the docs team that docs need to be updated for a new change.
If approved, this should be replicated in other repos.

Expand PR template

---

.github/workflows/benchmark.yaml
.github/workflows/test.yaml
integration/benchmark_test.go

Add a performance benchmark for integration tests.
Fixes https://github.com/pomerium/internal/issues/871
Not user facing.

add benchmark

---

internal/databroker/registry.go
internal/sets/hash.go
pkg/storage/postgres/backend.go
pkg/storage/postgres/migrate.go
pkg/storage/postgres/option.go
pkg/storage/postgres/postgres.go
pkg/storage/postgres/registry.go
pkg/storage/postgres/registry_test.go
pkg/storage/postgres/stream.go

Implements a registry postgres backend.
Fixes https://github.com/pomerium/internal/issues/861
Not user facing.

postgres: registry support

---

authorize/access_tracker.go
config/envoyconfig/listeners.go
config/options.go
go.mod
go.sum
internal/redisutil/client.go
internal/sets/hash.go
internal/sets/size_limited.go
internal/sets/sorted.go

Use generics for the set types.
Fixes https://github.com/pomerium/internal/issues/934
Not user facing.

sets: convert set types to generics

---

RELEASING.md

Updates the releasing guide to the new procedure, and docs site.

deployment: update RELEASING.md

---

config/envoyconfig/clusters_test.go
config/envoyconfig/envoyconfig.go
config/envoyconfig/filters.go
config/envoyconfig/listeners.go
config/envoyconfig/listeners_test.go
config/envoyconfig/outbound.go
go.mod
go.sum
scripts/get-envoy.bash

Upgrade to envoy 1.23.0. Several filters needed to be updated so I pulled them into a separate file.
- https://github.com/pomerium/internal/issues/931
Upgrade to envoy 1.23.0.

envoy: upgrade to 1.23.0

---

authenticate/handlers.go
authenticate/handlers/webauthn/webauthn.go

Fix branding for webauthn device registration page.
Fixes https://github.com/pomerium/pomerium-console/issues/2738

authenticate: fix branding for webauthn device registration page

---

scripts/get-envoy.bash

Upgrade to envoy v1.23.1
- #3598

upgrade envoy to v1.23.1

---

authorize/evaluator/policy_evaluator_test.go
authorize/internal/store/store.go

When retrieving a record from the databroker check the `ExpiresAt` timestamp to make sure its still a valid record.
Fixes https://github.com/pomerium/pomerium-console/issues/2712

authorize: enforce service account expiration

---

go.mod
go.sum
internal/chanutil/batch.go
internal/chanutil/batch_test.go
internal/chanutil/chanutil.go
internal/chanutil/merge.go
internal/chanutil/merge_test.go
internal/fileutil/watcher.go
internal/fileutil/watcher_test.go

Backport https://github.com/pomerium/pomerium/pull/3663

fileutil: update watcher to use fsnotify and polling (#3663)

---

config/envoyconfig/clusters.go

Fix the databroker health checks for envoy.
Fixes https://github.com/pomerium/pomerium/issues/3665

envoyconfig: fix databroker health checks

---

scripts/get-envoy.bash

Upgrades Envoy to 1.23.2
Related https://github.com/pomerium/internal/issues/1039

bump Envoy to 1.23.2

---

.github/workflows/release.yaml

Fix `setup-gcloud`.
https://github.com/pomerium/internal/issues/1041

ci: fix google

---

pkg/storage/postgres/backend_test.go
pkg/storage/postgres/postgres.go

Backport https://github.com/pomerium/pomerium/pull/3876

postgres: return unknown records instead of skipping them (#3876)

---

authenticate/handlers.go
internal/httputil/errors.go
ui/src/components/ErrorPage.tsx
ui/src/types/index.ts

Add additional error details for hmac errors
Fixes #3859

authenticate: add additional error details for hmac errors

---

.github/workflows/release.yaml

bump goreleaser to v4.1.1

---

internal/handlers/jwks_test.go

It doesn't make any sense why this would fail but 🤷 .
Fixes https://github.com/pomerium/internal/issues/1258

maybe fix flaky test

---

authorize/check_response.go

Fix the webauthn URL so that it's attached to the route, not the authenticate service.
Fix https://github.com/pomerium/pomerium/issues/3982

fix webauthn url

---

internal/handlers/jwks_test.go

Fix test
Fixes https://github.com/pomerium/internal/issues/1287

use deterministicecdsa to fix test

---

authorize/evaluator/evaluator.go
authorize/grpc.go
config/envoyconfig/listeners.go

authorize: fix IsInternal check

---

.github/dependabot.yaml

- https://github.com/pomerium/internal/issues/1432

dependabot: improvements

---

config/envoyconfig/listeners.go

Pomerium configures a gRPC listener in Envoy, for internal communication between the various Pomerium services. Currently this listener shares much of the same configuration as the main HTTP listener, based on the main Pomerium configuration options.
However, some configuration options don't make sense for the gRPC listener. Specifically, the `codec_type` option should not be applied to the gRPC listener, as gRPC requires HTTP/2. Also, any client certificate settings should not apply to the gRPC listener. (This is not currently a problem, but it will interfere with https://github.com/pomerium/pomerium/issues/4353.)
Separate the gRPC listener configuration from the main HTTP listener configuration, so we can avoid applying these configuration options. Instead set AlpnProtocols to just "h2" …

envoy: separate gRPC listener configuration

---

config/options.go
config/options_test.go

Update bindEnvs() to add support for binding nested fields of the Options struct to environment variables. The variable names are formed by joining the nested fields' mapstructure tags with underscores (after first converting to uppercase).
This is in preparation for adding a new nested struct for downstream mTLS settings that will look something like this:
downstream_mtls:
ca_file: /path/to/CA/cert.pem
enforcement: reject_connection
With this change, these fields would be bound to the variables `DOWNSTREAM_MTLS_CA_FILE` and `DOWNSTREAM_MTLS_ENFORCEMENT`.
(We need to be careful not to bind `downstream_mtls` itself, or else the behavior of viper's `Unmarshal()` method becomes non-deterministic when combining settings between a config file and environment variables — nested field …

config: support arbitrary nested config structs

---

scripts/get-envoy.bash

Upgrade Envoy to [v1.28.0](https://github.com/envoyproxy/envoy/releases/tag/v1.28.0).
https://github.com/pomerium/pomerium/issues/4624

upgrade envoy to v1.28.0

---

internal/identity/manager/manager.go
internal/identity/manager/manager_test.go

Currently, if a temporary error occurs while attempting to refresh an OAuth2 token, the identity manager won't schedule another attempt.
Instead, update the session refresh logic so that it will retry after temporary errors. Extract the bulk of this logic into a separate method that returns a boolean indicating whether to schedule another refresh.
Update the unit test to simulate a temporary error during OAuth2 token refresh.
https://github.com/pomerium/internal/issues/1558
Improve reliability of session refresh.

identity: rework session refresh error handling

---

internal/zero/cmd/env_release.go

Fix the zero URLs.
https://github.com/pomerium/pomerium-zero/issues/602

core/zero: fix urls

---

internal/zero/reconciler/restart.go

Currently the `RunWithRestart()` loop may not exit when `execFn` returns an error unrelated to its context cancellation. Add an additional check for this case.
- https://github.com/pomerium/internal/issues/1604

zero/reconciler: fix restart behavior

---

.tool-versions
Dockerfile
Dockerfile.debug

Update dev Dockerfiles to Go 1.21.4.
- https://github.com/pomerium/internal/issues/1519#issuecomment-1828479546

update to Go 1.21.4

---

internal/zero/analytics/sessions.go
internal/zero/apierror/request_id.go
internal/zero/apierror/terminal.go

Fix the lint task.
- https://github.com/pomerium/internal/issues/1633

core/ci: fix linting issues

---

.github/workflows/test.yaml
Dockerfile
Dockerfile.debug
scripts/check-docker-images

Add a script to check docker images to make sure they are multi-platform images.
For https://github.com/pomerium/internal/issues/1629

core/ci: check docker base images

---

authorize/check_response.go
authorize/check_response_test.go

Currently the Authorize service will handle denied requests by returning an HTML page with the error message. If the user is `unauthenticated` it will also return a `302` with a `Location` header set to the authenticate service.
These responses only make sense for standard HTML requests. For non-HTML requests the current redirect or error page won't make sense.
We already have code to avoid the redirect in these cases. This PR also updates the error page so that its returned in a format that makes more sense for `application/json` or `application/grpc-web-text`.
- https://github.com/pomerium/pomerium-console/issues/3975

core/authorize: return non-html errors on denied

---

authenticate/handlers.go
authorize/check_response.go
config/envoyconfig/route_configurations_test.go
config/envoyconfig/routes.go
config/envoyconfig/routes_test.go
proxy/handlers.go
proxy/handlers_test.go
proxy/proxy.go

Fix the access denied error page. Handle robots.txt in the authorize service.
- #4951 
- #4912

core/authorize: result denied improvements

---

internal/urlutil/url.go

validate: fix typo

---

changelogs/v0.25.1.md

changelog: v0.25.1

---

scripts/get-envoy.bash

Upgrades Envoy to v1.29.2
For https://github.com/pomerium/pomerium/issues/5041

envoy: set to v1.29.2

---

authorize/evaluator/evaluator.go
cmd/pomerium/main.go
internal/autocert/certmagic_logger.go
internal/controlplane/server.go
internal/controlplane/xds.go
internal/controlplane/xdsmgr/xdsmgr.go
internal/databroker/config_source.go
internal/databroker/server.go
internal/identity/manager/manager.go
internal/zero/connect-mux/service.go
internal/zero/controller/controller.go
internal/zero/controller/mux_log.go
internal/zero/grpcconn/client.go
internal/zero/reconciler/sync.go
pkg/cmd/pomerium/pomerium.go
pkg/envoy/envoy.go
pkg/grpc/client.go
pkg/grpc/databroker/syncer.go

Turn a bunch of `Info` logs into `Debug` logs.
For https://github.com/pomerium/pomerium-zero/issues/2046

core/logging: less verbose logs

---

scripts/get-envoy.bash

Upgrades Envoy to v1.29.3
Related: https://github.com/pomerium/internal/issues/1771

envoy: upgrade to v1.29.3

---

config/envoyconfig/bootstrap.go
config/envoyconfig/bootstrap_test.go

Migrate from `overload.global_downstream_max_connections` to the suggested `envoy.resource_monitors.global_downstream_max_connections` replacement.
Note that the deprecation warning mentions `envoy.resource_monitors.downstream_connections`, but this appears to be incorrect, as attempting to use this name results in an error message:
error initializing config '  envoy-config.yaml': Didn't find a registered implementation for 'envoy.resource_monitors.downstream_connections' with type URL: 'envoy.extensions.resource_monitors.downstream_connections.v3.DownstreamConnectionsConfig'
See https://github.com/envoyproxy/envoy/issues/31429#issuecomment-1871511999.
- https://github.com/pomerium/internal/issues/1672

envoy: migrate deprecated overload setting

---

ui/yarn.lock

Run `yarn upgrade-interactive` to update UI dependencies:
```
dependencies
name                              range     from        to
@babel/core                       ^7.0.0    7.17.0   ❯  7.24.4
@emotion/react                    ^11.7.1   11.7.1   ❯  11.11.4
@emotion/styled                   ^11.11.0  11.11.0  ❯  11.11.5
@fontsource/dm-mono               ^5.0.14   5.0.14   ❯  5.0.20
@fontsource/dm-sans               ^5.0.13   5.0.13   ❯  5.0.21
@mui/icons-material               ^5.14.9   5.14.9   ❯  5.15.15
@mui/material                     ^5.4.0    5.4.0    ❯  5.15.15
markdown-to-jsx                   ^7.2.1    7.2.1    ❯  7.4.7
devDependencies
name                              range     from        to
@types/luxon                      ^2.0.9    2.0.9    ❯  2.4.0
@types/node …
```

chore(deps): update UI dependencies

---

authorize/evaluator/headers_evaluator_test.go
authorize/evaluator/opa/policy/headers.rego

backport #5090

---

pkg/envoy/envoy.go

Go raises the "max open files" soft limit to match the hard limit for itself, but has special logic to reset the original soft limit before forking a child process. This logic does not apply if the file limit is set explicitly. Add a pair of Getrlimit / Setrlimit calls so that we
1. preserve the default Go limit behavior for ourselves, and
2. keep these same limits when launching Envoy.
- https://github.com/pomerium/pomerium-zero/issues/1724
Ensure that Envoy inherits the same max open files limit that Pomerium has. This should improve stability under heavy load.

envoy: preserve Go's max file limit for Envoy

---

ui/src/components/ErrorPage.tsx

Add "Policy ID" to the explanation text when error details are displayed.
- https://github.com/pomerium/pomerium-zero/issues/2456

core/ui: add policy id

---

pkg/envoy/get-envoy/main.go

Update the get-envoy script to add an extra mode to download only the current `GOOS`/`GOARCH` binary as just `envoy` and `chmod +x` it.
- https://github.com/pomerium/pomerium-zero/pull/2631#pullrequestreview-2139684207

core/envoy: add mode to download only the current binary

---

scripts/get-envoy.bash

Backport https://github.com/pomerium/pomerium/commit/6ee9e5238ce5a635d4db2817128f9c9f67b3801f from https://github.com/pomerium/pomerium/pull/5152

envoy: upgrade to v1.30.3

---

.github/goreleaser.yaml

Fixes the URL in goreleaser.yaml

ci: fix url typo in goreleaser

---

internal/zero/cmd/command.go
internal/zero/controller/controller.go

Adds an explicit log when shutdown is initiated in Zero mode, so that it would be evident from logs what caused it. 
i.e. it could be a top-level signal received, or cluster deletion detected.

zero/cmd: make it more evident what caused shutdown

---

SECURITY.md

Fix `SECURITY.md` treated as symlink.

Fix SECURITY.md treated as symlink

---

.github/workflows/lint.yaml

Forgot to change this when I updated the other versions (in Makefile/.tool-versions) to use the latest tagged release.

Update golangci-lint version in lint workflow

---

.github/workflows/benchmark.yaml
.github/workflows/test.yaml

Backport https://github.com/pomerium/pomerium/commit/41f1e61911519d2057861e59a6d6723a90a04199 from #5206

ci: switch to docker compose v2 (#5206)

---

.github/workflows/codeql.yaml

core/ci: codeql

---

authorize/grpc.go

Adds `request-id` to some authorize service error log messages to enable cross-correlation to the incoming request.  
Fixes: https://github.com/pomerium/internal/issues/1896

authorize: add request-id to error messages

---

pkg/grpcutil/options.go
pkg/grpcutil/options_test.go

Add additional validation to the `grpcutil.RequireSignedJWT` method. Log any validation error, instead of returning error details in the gRPC status message.
https://github.com/pomerium/internal/issues/1907

grpcutil: additional JWT validation

---

authorize/grpc.go

When the databroker is temporarily unavailable, do not clear sessions during authorization, instead return the 500 error so it can be detected and retried.
https://github.com/pomerium/pomerium/issues/5316

authorize: fix transient errors from databroker causing redirect loop

---

config/options_check.go

These fields are actually set when decoding, but for some reason they still show up in the unpopulated list. This adds all the fields in the embedded envoy opts message to the list of fields we will not warn as unknown fields.
Fixes https://github.com/pomerium/pomerium-zero/issues/3110

config: suppress unused warnings for all fields in embedded route envoy options

---

config/policy_ppl_test.go
pkg/policy/criteria/claim.go
pkg/policy/criteria/claim_test.go
pkg/policy/criteria/matchers.go
pkg/policy/criteria/matchers_test.go

Add support for more flexible PPL matchers.
For #5335

ppl: more flexible matchers

---

authorize/check_response.go
authorize/check_response_test.go

When responding to a Kubernetes api request with a (pomerium) auth error, serialize the error in the format expected by the Kubernetes rest client. 
Kubernetes client requests are detected by the presence of the string "kubernetes/" in the user-agent, as set in client-go: https://github.com/kubernetes/kubernetes/blob/9b56413d56a9805ce37207b940b0e566f30db785/staging/src/k8s.io/client-go/rest/config.go#L495-L498. This covers kubectl, standard client-go sdk, and the controller-runtime client.
#5328

authorize: serialize errors in metav1.Status format when kubernetes user-agent is detected

---

authorize/evaluator/headers_evaluator_test.go
pkg/storage/querier.go

In preparation for #5362 add some additional unit tests and a benchmark.
- #5357

authorize: additional header evaluator tests

---

config/from_test.go
config/identity.go
config/policy.go
internal/urlutil/known_test.go
internal/urlutil/url.go

change Policy.Matches to accept a URL pointer

---

internal/testenv/environment.go

Adds a function `Pause()` that can be used to stop the running test and wait for ctrl+c, very useful for debugging or interacting with the test environment externally.

testenv: add Pause() method

---

config/envoyconfig/listeners_main.go
config/envoyconfig/listeners_test.go
config/envoyconfig/protocols.go
config/envoyconfig/testdata/main_http_connection_manager_filter.json

Extended connect support.
- #5386

envoy: enable extended connect

---

config/envoyconfig/routes.go
config/envoyconfig/routes_test.go
config/policy.go
config/policy_test.go
internal/urlutil/url.go

Add support for UDP routes. UDP routes using `CONNECT-UDP` tunneling.
Fixes #5389

UDP support

---

.github/workflows/benchmark.yaml

Run all the benchmarks in the project.

ci: run all benchmarks

---

internal/telemetry/metrics/providers.go

The [writeMetricsMux()](https://github.com/pomerium/pomerium/blob/3d53f26d181ce7cc7165b4416ff783c9040cfdfd/internal/telemetry/metrics/providers.go#L125) method instantiates a buffered writer but does not call `Flush()` after it is done writing. As a result the metrics output may be incomplete.
I noticed this when the following test invocation failed reliably on my machine:
```
go test -count 2 -run Test_PrometheusHandler  ./internal/telemetry/metrics
```

metrics: make sure to flush buffered writer

---

config/envoyconfig/tls.go
config/envoyconfig/tls_test.go

Currently Pomerium will always generate a wildcard certificate for use as a fallback certificate.
If any other certificate is configured, this fallback certificate will not normally be presented, except in the case of a TLS connection where the client does not include the Server Name Indication (SNI) extension. All modern browsers support SNI, so in practice this certificate should never be presented to end users.
However, some network scanning tools will probe connections by IP addresses (without SNI), and so this fallback certificate may be presented. The presence of this certificate may be flagged as a problem in some automated vulnerability scans (see e.g. https://github.com/pomerium/pomerium/issues/3735).
Let's avoid generating this fallback certificate if Pomerium has any other …

config: generate fallback cert only as last resort

---

config/options_test.go

Remove some test code that was probably not intended to be kept :smile:

remove test code from config/options_test.go

---

authorize/databroker.go
authorize/grpc.go
pkg/storage/querier.go
pkg/storage/storage.go

Adds more tracing around authz code for troubleshooting.
Related: https://linear.app/pomerium/issue/ENG-1904

authz: add more tracing

---

authorize/authorize.go
authorize/cache_warmer.go
authorize/cache_warmer_test.go
authorize/databroker_test.go
authorize/grpc.go
pkg/storage/cache.go
pkg/storage/cache_test.go
pkg/storage/querier.go

backport: authorize: cache warming (#5439)

---

internal/telemetry/trace/client.go
internal/testutil/minio.go
internal/testutil/postgres.go

This is necessary for (but kinda unrelated to) https://github.com/pomerium/pomerium/pull/5438

fix testcontainers docker client using the global tracer provider

---

.github/workflows/docker-version-branches.yaml

ci: more flex version branch regex

---

authorize/evaluator/evaluator.go
authorize/evaluator/headers_evaluator.go
authorize/evaluator/headers_evaluator_evaluation.go
authorize/evaluator/headers_evaluator_test.go
authorize/log.go
authorize/log_test.go
internal/log/authorize.go

Backport b0f89fc688c084f52bc7b454d1b28929122c7784 from https://github.com/pomerium/pomerium/pull/5432

authorize: log JWT groups filtering (#5432)

---

.github/workflows/docker-version-branches.yaml

Also build docker images for any branches with the `experimental/` prefix.

ci: build docker images for experimental/* branches

---

changelogs/v0.29.0.md

Draft v0.29.0 release notes.
Ref: https://linear.app/pomerium/issue/ENG-2090/draft-0290-repository-changelogs

add v0.29.0 release notes

---

.github/CONTRIBUTING.md

Add a `CONTRIBUTING.md` file. 
- [ENG-1804](https://linear.app/pomerium/issue/ENG-1804/add-contributing-page-back-to-pomeriumpomerium-github)

add CONTRIBUTING

---

internal/log/middleware.go

Update the log unary interceptor to log calls to the authorization check method:
```json
{
"level":"info",
"server-name":"all",
"grpc.service":"envoy.service.auth.v3.Authorization",
"grpc.method":"Check",
"grpc.code":"OK",
"grpc.duration":1.008165,
"time":"2025-05-01T10:15:47-06:00",
"message":"finished call"
}
```
- [ENG-2364](https://linear.app/pomerium/issue/ENG-2364/generate-a-log-entry-when-check-returns-an-error)

add additional authorization check logs

---

config/envoyconfig/clusters.go

Modify the behavior of the `tmp_unlimited_connections` runtime flag so that it applies also to internal clusters (not just to clusters for upstream services).
https://linear.app/pomerium/issue/ENG-2310/add-cirquit-breaker-settings-per-route

config: apply unlimited conns setting to internal clusters

---

authenticate/authenticate.go
authenticate/handlers_verify.go
authorize/authorize.go
authorize/evaluator/evaluator.go
authorize/evaluator/headers_evaluator.go
authorize/log.go
config/session.go
internal/telemetry/metrics/otel.go

core: more metrics (#5629)

---

config/envoyconfig/http_connection_manager.go
config/envoyconfig/listeners_main.go
config/envoyconfig/listeners_test.go
config/envoyconfig/local_reply.go
config/envoyconfig/local_reply_test.go
config/envoyconfig/lua.go
config/envoyconfig/lua_test.go
config/envoyconfig/luascripts/local-reply-type.lua
config/envoyconfig/matchers.go
config/envoyconfig/testdata/main_http_connection_manager_filter.json

envoyconfig: add additional local reply mappers for gRPC (#5644)

---

pkg/storage/postgres/backend.go

Enables metrics for the `pgxpool` that is used by the PostgreSQL databroker backend. 
Metrics are updated at 1s interval. 
Will add the following metric output in the regular Prometheus `/metrics` endpoint:
```
pomerium_pgxpool_acquire_duration_nanoseconds_total{db_client_connection_pool_name="localhost:5432/pomerium",db_system="postgresql",otel_scope_name="github.com/exaring/otelpgx",otel_scope_version="v0.9.1",hostname="MacBookPro"} 5.1058702e+07
pomerium_pgxpool_acquired_connections{db_client_connection_pool_name="localhost:5432/pomerium",db_system="postgresql",otel_scope_name="github.com/exaring/otelpgx",otel_scope_version="v0.9.1",hostname="MacBookPro"} 0
pomerium_pgxpool_acquires_total{db_client_connection_pool_name="localhost:5432/pomerium",db_system="postgresql",otel_scope_name="gi …
```

pgxpool: enable metrics

---

internal/testenv/environment.go

This should fix some test flakes. If (*Pomerium).Start() fails, we should not attempt to call (*Pomerium).Shutdown().

testenv: do not attempt to shutdown pomerium if it fails to start

---

changelogs/v0.30.0.md

changelog for v0.30.0

---

config/envoyconfig/listeners_test.go
config/envoyconfig/testdata/main_http_connection_manager_filter.json
config/envoyconfig/tracing.go

Fixes https://github.com/pomerium/pomerium/issues/5652

tracing: fix incorrect proto conversion logic for otel timeouts

---

internal/telemetry/metrics/otel.go

metrics: don't add units and scope tags to prometheus metrics (#5749)

---

internal/databroker/server_clustered_follower.go

When switching from leader to follower in clustered mode can lead to a race condition in health checks.
Health checks may continue reporting errors, despite not being unhealthy.
Changes:
- Follower sync health checks now ignore stopped servers
- Stop  in cluster followers  now blocks until the main loop of `run()` exists
N/A
N/A

fix: tweak stop logic in cluster follower
